### ISSUE TITLE
Upvotes

### ISSUE THREAD

**Issue by GeneralPutPut** [citizenfx/fivem#1025]
I bought upvotes over ZapHosting but i cant use it. What can i do? in the Settings its says loading and if i want to boost my server only this text will show up:

You have performed this action too much recently. Try again in 5 Minutes. 

After Waiting for 20 minutes it says the same think. My Problem is i bought upvotes burst vor 3 hours and know i only got 2h left to use it.

**Comment by GeneralPutPut** [comment]
![Screenshot 2021-09-22 215707](https://user-images.githubusercontent.com/88453022/134413137-16ee8f9c-93fd-464c-a69f-b115a8ce4932.png)

**Comment by duck-37** [comment]
I see you've posted this on the forums as well, so please wait for a response there. GitHub issues are strictly for technical problems related to the core modification. This seems more like an uptime issue with one of the backend services, which is out of scope here.
