### ISSUE TITLE
newline has no effect in lua on strings inside adaptive cards

### ISSUE THREAD

**Issue by Minn1337** [citizenfx/fivem#1037]
Displaying an adaptive card within the playerConnecting event in lua and creating a newline using 
\n within the cards displayed text has no effect. Noticed this today (9/24/21) on canary, issue did not occur on canary previous to 9/24. Switched to release and issue no longer occurs. I know the post date is not 9/24. Late post, sorry.

![image](https://user-images.githubusercontent.com/91351467/134803214-4a6d11e8-5906-402c-a9e4-6f037df31f0c.png)

![image](https://user-images.githubusercontent.com/91351467/134803220-2176e32b-a553-4524-a790-d94401c4d710.png)

**Comment by blattersturm** [comment]
I see newlines just fine, however. 🤔

**Comment by Minn1337** [comment]
Sorry, I wasn't thinking, I should've specified double newlines, not single. Here is the card:

`local card = {
    ["type"] = "AdaptiveCard",
    ["body"] = {
        {
            ["type"] = "TextBlock",
            ["size"] = "Medium",
            ["weight"] = "Bolder",
            ["text"] = "Welcome!",
            ["horizontalAlignment"] = "Center",
            ["fontType"] = "Default"
        },
        {
            ["type"] = "Image",
            ["horizontalAlignment"] = "Center"
        },
        {
            ["type"] = "TextBlock",
            ["wrap"] = true,
            ["horizontalAlignment"] = "Center",
            ["text"] = "Before joining, please be sure to join our discord and read the official server rules.\n\nTo join the server, click the \"Play\" button below. \n\nHave fun!"
        },
        {
            ["type"] = "ColumnSet",
            ["columns"] = {
                {
                    ["type"] = "Column",
                    ["width"] = "stretch",
                    ["items"] = {
                        {
                            ["type"] = "ActionSet",
                            ["actions"] = {
                                {
                                    ["type"] = "Action.OpenUrl",
                                    ["title"] = "Discord",
                                    ["url"] = "https://discord.com",
                                    ["iconUrl"] = "https://i.imgur.com/QesBJvm.png",
                                    ["id"] = "discord"
                                }
                            }
                        }
                    }
                },
                {
                    ["type"] = "Column",
                    ["width"] = "stretch",
                    ["items"] = {
                        {
                            ["type"] = "ActionSet",
                            ["actions"] = {
                                {
                                    ["type"] = "Action.OpenUrl",
                                    ["title"] = "Store",
                                    ["url"] = "https://store.mrz.gg/",
                                    ["id"] = "store",
                                    ["iconUrl"] = "https://i.imgur.com/ojhjHgW.png"
                                }
                            }
                        }
                    }
                }
            }
        },
        {
            ["type"] = "ActionSet",
            ["actions"] = {
                {
                    ["type"] = "Action.Submit",
                    ["title"] = "Play",
                    ["id"] = "play",
                }
            }
        }
    },
    ["$schema"] = "http://adaptivecards.io/schemas/adaptive-card.json",
    ["version"] = "1.3"
}`

**Comment by blattersturm** [comment]
![image](https://user-images.githubusercontent.com/24576130/134805671-6a5cafc9-3379-4433-9506-c08586f8ee81.png)

Outcome is slightly different but it's at least back.
