### ISSUE TITLE
False ban

### ISSUE THREAD

**Issue by RedIvyy** [citizenfx/fivem#1047]
I was globally banned it seems even though I am 100% sure it is a false ban. I do not have any programs or mods that would interfere with FiveM at all. I have been playing on it for months without any issues and suddenly I get banned for 300+ days for no reason. I assure you that it is not because of third party software. I have heard of similar things happening with other people recently as well.

**Comment by duckhunter392** [comment]
This is not the correct use of GitHub issues. The ban message includes information on what to do if you believe there was a "false ban".

**Comment by blattersturm** [comment]
A '300 day ban' has a _zero_ chance of being 'a false ban'. However, you've not provided your ban ID so I can't give you what the kids call a ' 🤢🔥'.
