### ISSUE TITLE
False ban

### ISSUE THREAD

**Issue by RedIvyy** [citizenfx/fivem#1048]
I was banned from FiveM and was given the code 1508e157-6335-4698-9acb-05cb1dcbd6e2_01. I do not understand why as I have never used any 3rd part programs or mods with FiveM.  I was having issues with FiveM before where it seemed to delete itself and this happened on more than 1 occasion. I don't know if it had gotten corrupted or what as I don't use any mods or 3rd party software with FiveM, I run it as itself vanilla. Could it have detected corrupted files and been flagged for that?

**Comment by blattersturm** [comment]
Didn't I tell you to _not_ in #1047?
