### ISSUE TITLE
Fivem Ban

### ISSUE THREAD

**Issue by Zlomus** [citizenfx/fivem#1049]
Hello i got account with cheats from my friend. Im lua developer and i do my anticheat for my server. I only check anti inject to script and blocking props. Im sorry and I am so sorry for that. My ban id: 6f014685-66eb-430a-8d5a-614aea657a5_01 

I promise that it will not happen again and next time I will ask my friend to check it so as not to risk getting banned and can i get unban?

**Comment by agusdarma22** [comment]
![image](https://user-images.githubusercontent.com/59126763/142736237-e2aee427-8d93-46b7-b5ed-46fb524b62c5.png)
help me, i'm not using illegal programs but i'm getting banned please i don't do anything very suspicious let alone use cheats, can i get unban pleaseee
