### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by teo-zountsas2002** [citizenfx/fivem#1051]
Hello Fivem Team, i am teo and i am a server owner with a  platinum patreon key. Yesterday i was on my test server working on some updates for my server and when i relog i have got a ban from fivem. I am asking for an unban from fivem i we can do something. And btw this is my first ever ban from fivem. Here is a screenshot from my ba
![Screenshot_1](https://user-images.githubusercontent.com/54405244/135267525-846d09c6-7189-455a-98df-e957d987d59a.png)
n.

**Comment by technetium-cfx** [comment]
Whoever is sending people here, it won't help.
