### ISSUE TITLE
Fivem Global Ban

### ISSUE THREAD

**Issue by Matczyk** [citizenfx/fivem#1053]
I have been banned globally for using the Red Engine program. Yes, it's true that I used this program to help my colleague in creating the server. I helped him make the Anty Cheat. Please unban me now my computer is 100% clean.
![image](https://user-images.githubusercontent.com/91725718/135643754-f1640efb-e4e1-4d70-ba7b-d767245f6764.png)
Your ban ID is 049f4c3f-ca6e-414b-97dd-aa97c2f2cef1.

**Comment by blattersturm** [comment]
How is this an 'issue'? It seems the anticheat works as it should.
