### ISSUE TITLE
crash ink-dakota-mountain

### ISSUE THREAD

**Issue by Luk3St1rrup** [citizenfx/fivem#1054]
when ever i load into any fivem server i keep on getting the crash stated above. ive literally tried every fix under the sun and nothings helped at all.

**Comment by blattersturm** [comment]
Hi,

Our GitHub issues are only for actionable tasks, such as work items, bugs that have clear reproduction steps and crashes/traces with actual information.

Your report provided neither, yet asked to have 'help'.

Try asking in the technical support section on the forums: https://forum.cfx.re/c/technical-support/27

Thanks!
