### ISSUE TITLE
show who destroyed an entity

### ISSUE THREAD

**Issue by MarqSolucoes** [citizenfx/fivem#1056]
show who destroyed an entity in the event "entityRemoved".

with this antihack developers could detect possible abuses with hacks.
Today we have no way to automatically detect hackers who are deleting vehicles or other entities.

**Comment by MRV6** [comment]
Don't you need to be the owner of an entity to delete it ? If yes, you could just check the owner ?

**Comment by LegendProjects** [comment]
If we could see who is requesting entity control we could manage to do something -> Cause ApplyEntityForce need to request entity control first - Obviously entity lockdown is not a option cause need a lot of changes and spawn veh, peds from serverside.

**Comment by blattersturm** [comment]
> Obviously entity lockdown is not a option

What?
