### ISSUE TITLE
Tint not being applied correctly to penthouse ipl on 4714

### ISSUE THREAD

**Issue by GAccountFivem** [citizenfx/fivem#1057]
On the current stable version (4685) the penthouse calling the SetInteriorEntitySetColor method to color "Set_Pent_Tint_Shell" doesn't work at all. Testing on the 4714 version I see this was partially fixed but the patterns are still all messed up.

**Comment by blattersturm** [comment]
So this was 'fixed', and you're not providing any info or repro, so.. what?
