### ISSUE TITLE
rbind (client command) not working for resources that haven't used REGISTER_KEY_MAPPING

### ISSUE THREAD

**Issue by Rasinzz** [citizenfx/fivem#1066]
I have ensured that:

- The resource is running
- The mapper, input & command are all valid
- My command format is valid (`rbind test keyboard i "test"`)

I have tried:

- Switching between `Release` & `Canary` versions
- Unbinding and rebinding multiple times

**Comment by blattersturm** [comment]
Right - it seems this doesn't work for any resources that haven't used REGISTER_KEY_MAPPING yet.

For example:

- Works: `rbind chat keyboard i quit`
- Doesn't work: `rbind mapmanager keyboard i quit`

It makes sense for it to not work that way given the implementation, but it's somewhat unexpected.
