### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by NOLAcOLLINS** [citizenfx/fivem#1069]
https://github.com/citizenfx/fivem/blob/34b50cc445b20d2e8bec63c3242ce4817045a4db/code/components/gta-core-five/src/GameSkeleton.cpp#L214

**Comment by blattersturm** [comment]
Hi,

Our GitHub issues are only for actionable tasks, such as work items, bugs that have clear reproduction steps and crashes/traces with actual information.

Your report provided neither, yet asked to have 'help'.

Try asking in the technical support section on the forums: https://forum.cfx.re/c/technical-support/27

Thanks!
