### ISSUE TITLE
Game crashes (in utf8cpp) when reading User Music files with 'broken' UTF16 sequence in their name

### ISSUE THREAD

**Issue by Deivunis123** [citizenfx/fivem#1077]
Getting this crash when i try join a any server, any ideas how to fix?
![Screenshot_1](https://user-images.githubusercontent.com/91023674/137197145-a16724e9-1b3d-43a8-8d93-68cac5e03c66.png)
x?

**Comment by blattersturm** [comment]
`x?`

Can you upload the crash dump file from the 'save information' option in a comment?

**Comment by blattersturm** [comment]
Do you have any Self Radio tracks in your GTA V with 'weird' file names?

**Comment by Deivunis123** [comment]
> Do you have any Self Radio tracks in your GTA V with 'weird' file names?

thank you, i fixed
