### ISSUE TITLE
fivem crashing when trying to join server

### ISSUE THREAD

**Issue by matehun00** [citizenfx/fivem#1078]
[Window Title]
Error GTA5+17AF9CF

[Main Instruction]
GTA5+17AF9CF

[Content]
An error at GTA5+17AF9CF caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: sodium-failed-minnesota

[Expanded Information]
Crash signature: fivem.exe+17AF9CF
Error uploading: HTTP 0

**Comment by duck-37** [comment]
(note for anyone looking at this: we know and we're looking into it)
