### ISSUE TITLE
FiveM Main Menu Settings not saving. 

### ISSUE THREAD

**Issue by zGato** [citizenfx/fivem#1084]
Randomly these settings doesn't save if you don't join a server upon clicking on them. 

If you need to restart FiveM to change version some of these settings will randomly deselect themselves if you haven't joined any server and saved the settings (seems that joining a server forces a settings save)

![image](https://user-images.githubusercontent.com/88756568/137718278-09600db4-2a6a-41dc-8e25-17efe76599e3.png)

**Comment by zGato** [comment]
Hello,

Sorry for the late response, here's a video to show you https://youtu.be/s-m4OaLZWTI

**Comment by zGato** [comment]
Hello,

Sorry for the late response, after some time looking into it, seems that it only happens the first time you run FiveM (or, the first time you launch FiveM without the "CitizenFX" folder on the Roaming folder of AppData

If you have this folder, and you modified any option before, you won't have any issue at all, they'll apply correctly.

**Comment by blattersturm** [comment]
This directory should get created on startup, however. How does one end up with multiple launches without it existing? :/

**Comment by blattersturm** [comment]
Yeah, I can't replicate this still - I renamed the `%appdata%\CitizenFX` directory, opened the game, changed a setting, quit the game, and the setting still remains. :/

**Comment by zGato** [comment]
The only thing is that it happens only if I activate the 'fix UI lag' and some other options, if I check the others without the 'fix UI lag' it doesn't happen.

**Comment by Collaze** [comment]
I'm currently getting this issue and can't seem to fix it, can't connect to servers either.

**Comment by blattersturm** [comment]
Old/not reproducible.
