### ISSUE TITLE
Issues with the Connection to the Servers 

### ISSUE THREAD

**Issue by JustHsky** [citizenfx/fivem#1091]
Since the last update i´m no longer abled to connect / load the Files of my Server.
With the last version i was abled to... what can i do to fix this?

**Comment by duck-37** [comment]
Hi,

We need more information than just "it doesn't work." 
Some examples would be error screenshots, crash dumps, and most importantly **steps we can use to reproduce the bug**. 

Until we get something actionable, we can't do anything.

**Comment by JustHsky** [comment]
This is all what  i can give you so far, i can make a Video to show you what exactly happens there.

[Expanded Information]
[Crashlog.zip.zip](https://github.com/citizenfx/fivem/files/7393687/Crashlog.zip.zip)
Report ID: si-

**Comment by duck-37** [comment]
Again, we need more information than just "it doesn't work."

If you have steps to reproduce, open a different issue with those.
If you don't, try a clean game install.
