### ISSUE TITLE
Crash in CloneDebug.cpp when writing SyncTree nodes

### ISSUE THREAD

**Issue by snoobdogg** [citizenfx/fivem#1099]
Hello, a few friends and I are working on a server which is supposed to be at least 128 slots, thus we are using onesync infinity. While we were developing and testing, we have ran into one issue - a crash (see the image) https://cdn.discordapp.com/attachments/791438750076239882/900101505456177162/Screenshot_6.png
We have tried disabling each script, the crash still occured. So we decided to run the server without onesync and nobody has crashed from this so called "lambda operator crash". We suppose it has to do with onesync infinity, because usually the crash occurs when people are on the same grid.

**Comment by snoobdogg** [comment]
Hello, here's a full dump https://mega.nz/file/molWgIZR#M6lwaC4WOJpH0diBPZ66DBsnsAyfwM9dqqVh7t8_tbM

**Comment by blattersturm** [comment]
Are you sure that full dump is of _this_ crash? It doesn't look like there's any `CloneDebug.cpp` entry in there at all.
