### ISSUE TITLE
SDK: unable to join server that requires an identifier.

### ISSUE THREAD

**Issue by Pesoen** [citizenfx/fivem#1110]
i am trying to create some scripts for a server that is already setup and running. my issue is that i cannot join the server due to some of the things on it requiring a steam id, which is not present. disabled the allowlist to try and fix this problem, but since it's an rp server, it requires some form of identification, and it seems nothing is sent, no license or steam identifier.

a possible solution is if there is a way to temporarily just set an identifier for the game to send(i know my steam identifier, and can easily get it from the database, which would fix the issue) and cheat my way in that way? its a test server for now anyway, and i am messing with a job system i want to rewrite for easier adding of jobs later and overall simpler coding of new jobs, as well as some extra features we want in there, that currently does not exist.

another possible solution is to add some way to login to steam, and get the identifier that way, less hacky/cheaty way, but possibly more complicated.

Version: 1.61.2-cfx
Commit: unknown
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.48 Safari/537.36
Embedder: unknown

**Comment by nihonium-cfx** [comment]
You can not currently get identifiers in FxDK environment. You can however check for this environment to tweak your logic accordingly using `GetConvarInt('sv_fxdkMode', 0) == 1`.

**Comment by Pesoen** [comment]
well i guess any esx scripts will have to be done the old way then, a server locally to mess with scripts and just the game running normally.. since ESX actively kicks you without an identifier of any kind since it requires some sort of identifier.. doubt a convar can fix that. thanks for the quick reply though, just wish it was possible(maybe not now but in the future) to send some identifier along somehow.

**Comment by nihonium-cfx** [comment]
Well, yeah, I guess it's better to ask esx developers to add support for FxDK environment. Other than that there will be at least `fivem:` identifier eventually: https://github.com/citizenfx/fivem/issues/865

**Comment by Pesoen** [comment]
that should work i think... as long as SOME identifier gets sent, i should be able to add it to the database and use it, even if it's local, just hope it will then be a permanent fivem identifier pr project or pr install so i don't have to change it once its in there.

**Comment by thelindat** [comment]
> 
> 
> well i guess any esx scripts will have to be done the old way then, a server locally to mess with scripts and just the game running normally.. since ESX actively kicks you without an identifier of any kind since it requires some sort of identifier.. doubt a convar can fix that. thanks for the quick reply though, just wish it was possible(maybe not now but in the future) to send some identifier along somehow.


You just need to modify ESX to support the identifier you want to use - to keep this simple, modify ESX's `config.lua` with the following (setting a convar for primary_identifier would actually be the _best_ way to handle this overall).

```lua
Config.Identifier = GetConvar('sv_lan', '') == 'true' and 'ip' or 'steam'
```

You should also add the following function (either to the ESX table, or as an export); since you use steam I'm assuming you're on 1.1.
```lua
ESX.GetIdentifier = function(playerId)
	for _, v in pairs(GetPlayerIdentifiers(playerId)) do
		if string.match(v, Config.Identifier) then
			local identifier = string.gsub(v, identifier, '')
			return identifier
		end
	end
end
```

You can now simply call the function whenever you need an identifier check
```lua
local identifier = ESX.GetIdentifier(source)
```

Connecting through FxDK or having your server use sv_lan will result in your identifier being `ip:127.0.0.1`.
