### ISSUE TITLE
F8 Console causes mouse cursor to disappear

### ISSUE THREAD

**Issue by Xseba360** [citizenfx/fivem#1114]
https://forum.cfx.re/t/cursor-invisible-after-opening-f8-console/4768705

https://streamable.com/oxbx0h
https://streamable.com/656kjm
https://streamable.com/234y90

When the console is opened, the NUI mouse cursor disappears until it hovers on an element that causes the cursor to change.

**Comment by blattersturm** [comment]
Resolved as of 3f8a1d129426b551cc9c9c8a7b0d5e11b9182dee.
