### ISSUE TITLE
Scaleform API call SET_FORMATTED_TEXT_WITH_ICONS doesn't return the movieClip layer with icons.

### ISSUE THREAD

**Issue by manups4e** [citizenfx/fivem#1118]
The API call  `SET_FORMATTED_TEXT_WITH_ICONS` (present in `com.rockstargames.ui.utils.Text`) is the only one that asks for the movieClip to be sent as a parameter and doesn't have a callback function to be called.
The strings are actually formatted and shown but no icons are displayed in the movieClip in parameters. it feels like it doesn't want to work with custom Scaleforms as it works with stock ones 
basically the strings are correctly formatted so the textfields are actually working... but the blip movieClip passed as parameters is not handled and so no blips are shown. 
As the same code without the INT parameters works flawlessly with the TEXTFIELD scaleform that uses the same ActionScript code that i'm using in my custom scaleforms.

Example taken using my custom PauseMenuScaleform script and scaleform:
```cs
BeginScaleformMovieMethod(_pause.Handle, "ADD_RIGHT_LIST_ITEM");
ScaleformMovieMethodAddParamInt(1);
ScaleformMovieMethodAddParamInt(0);
ScaleformMovieMethodAddParamInt(0);
BeginTextCommandScaleformString("TOOLTIPS_72");
EndTextCommandScaleformString_2();
EndScaleformMovieMethod();
```

should return this:
![image](https://user-images.githubusercontent.com/4005518/140377589-2a2404e3-a159-4c8a-a433-247208d4808e.png)

instead i get this:
![image](https://user-images.githubusercontent.com/4005518/140379100-47e02a93-565d-4d64-be91-897c3345fddb.png)

seems like that the API Call ignores the movieClip

Scaleform Code used:
```as
function BasicTabItem(mc, label, param2, param3, param4)
{
	this.itemMC = mc.attachMovie("basicListItem", "basic_item_" + mc.getNextHighestDepth(), mc.getNextHighestDepth());
	this.itemMC.bgMC._visible = false;
	com.rockstargames.ui.utils.Colour.ApplyHudColour(this.itemMC.labelMC,com.rockstargames.ui.utils.HudColour.HUD_COLOUR_WHITE);

	var _loc3_ = new com.rockstargames.ui.utils.Text();
	this.blipLayer = this.itemMC.labelMC.createEmptyMovieClip("blipLayer", this.itemMC.labelMC.getNextHighestDepth());
	_loc3_.setTextWithIcons(label,this.blipLayer,this.itemMC.labelMC.titleTF,0,13,3,false);
	this.itemMC.labelMC.titleTF.autoSize = "left";
	this.itemMC.labelMC.titleTF.multiline = true;
	this.itemMC.labelMC.titleTF.wordWrap = true;
	/*
	this.itemMC.labelMC.titleTF.html = true;
	*/
	this.snapBGGrid(this.itemMC.bgMC);
}
```
where `setTextWithIcons` is basically the `SET_FORMATTED_TEXT_WITH_ICONS` API call.
The AS code is basically a copy of the FEED scaleform so i'm sure it should work as it's the same from the creator.
Sadly i am not able to debug further as there aren't tools or natives to debug scaleforms code and parameters.. and surely no API calls documentation 😅 

In my opinion the problem might be the fact that custom scaleforms are not in the same folder as the game and so the blipLayer cannot be returned correctly.. or something like this anyway.

As requested i'll add an example scaleform built upon the TEXTFIELD scaleform:

to run it for an example just use this code after having it loaded.

```lua
BeginScaleformMovieMethod(scaleform, "SET_TEXT")
BeginTextCommandScaleformString("TOOLTIPS_88")
EndTextCommandScaleformString_2()
EndScaleformMovieMethod()
```

TEXTFIELD SCALEFORM 
![image](https://user-images.githubusercontent.com/4005518/140624325-c9407b24-47ee-483d-9ae6-ccc57dc7e84c.png)

EXAMPLE SCALEFORM
![image](https://user-images.githubusercontent.com/4005518/140624343-20b3dfe5-f763-41f0-a65a-8324a5e5f15a.png)

[example.zip](https://github.com/citizenfx/fivem/files/7491284/example.zip)

**Comment by blattersturm** [comment]
> In my opinion the problem might be the fact that custom scaleforms are not in the same folder as the game and so the blipLayer cannot be returned correctly.. or something like this anyway.

Have you tried this with just a copy of an existing GFx file? I can't find anything obviously wrong in the function implementing this call from a quick glance.

**Comment by manups4e** [comment]
yes trying with a streamed copy of the TEXTFIELD scaleform it seems to be working.. so it must be surely some sort of dependency  missing 🤔 the code is the exact same in my custom ones and the textfield one.

**Comment by blattersturm** [comment]
Right, so this is not directly a bug/work item here, then. Will close it as it's not a work item, though will keep it open for discussion.

---

Are you inheriting from font_lib etc. like the original GFx files are?

**Comment by manups4e** [comment]
no as if i try inheriting from font_lib and font_efigs all the text disappear.. this is a lot to dig up for an old tech.. but i'll keep trying!
Thanks!!

**Comment by blattersturm** [comment]
Looking through ffdec for some differences may help.

**Comment by manups4e** [comment]
i'm using both ffdec and trillix but some dependencies are lost when opening the gfxs

**Comment by manups4e** [comment]
after lots of trials and errors.. i managed to make it work for streamed gfx too
![image](https://user-images.githubusercontent.com/4005518/151343096-c4dd255e-d7ad-4ccb-ab7d-4854c85786e1.png)

**Comment by blattersturm** [comment]
'nvm fixed it' without any info, nice :P

**Comment by manups4e** [comment]
i was actually gonna write that.. it just needs a couple of mins to write ahahahah

**Comment by manups4e** [comment]
besically i had to import all the font_lib_efigs.gfx button sprites into my project specifying the font_lib_efigs.swf as import url
![image](https://user-images.githubusercontent.com/4005518/151344994-bbea537a-cf09-4721-b461-d2b41b96daa0.png)

then i added (like in the textfield scaleform) all the TXTBTN movieclips setting them as exported in actioscript adding my scaleform as url
![image](https://user-images.githubusercontent.com/4005518/151345292-43825541-cb25-46d0-aaf5-5ad68e241ecb.png)

last but not least i had an idea... it's not visible in the reverse engineered swfs as they don't show imported movieclips... i tried to add for each TXTBTN_ its corresponding imported movieclip.. so i'm exporting the imported movieclip in few words..

plus there's a SHARE_ME empty movieclip in the efigs gfx that i imported and added to my CONTENT movieclip
