### ISSUE TITLE
SDK: Project settings 'channel' section has non-selectable tab/buttons options

### ISSUE THREAD

**Issue by itschip** [citizenfx/fivem#1126]
The 'Recommended' and 'Optional' button/tab option in the 'project settings' window is not selectable, it seems. 

It does not get selected by the look of it. If its intended that they shouldn't be, then they should perhaps have a disabled state, or removed?

**Comment by itschip** [comment]
Alright, did a quick test, and it does reload after you reload fxdk. Should be some sort of a feedback when selecting.

**Comment by nihonium-cfx** [comment]
Thank you for spotting this bug! We're in the middle of big refactoring that will address internal extensibility and how things are organized in general, this bug will be fixed during that. Closed #1127 as it's not how it is supposed to work (read followup comment there for details).

**Comment by nihonium-cfx** [comment]
Fixed in e7b8480
