### ISSUE TITLE
Tuner DLC Sandy Shores Textures! #Client

### ISSUE THREAD

**Issue by Matetv** [citizenfx/fivem#1131]
Hello! I wanted to switch to the current GameBuild version! Everything worked out so far! The casino works and the island is there too! Without mistakes! But when I go to Sandy Shores, the map disappears completely! See screen! I use the Cayo Perico & Casino DLC IPL Loader Cayo Perico & Casino DLC IPL Loader 1 as well as bob74_ipl and the iplLoader! Even if I switch off all IPL loaders, the map (floor, water) disappears in Sandy Shores! What could be the reason? I also turned off all MLOs! But I can’t find a mistake!
Data:
Server Build: 4947
Client build: +set sv_enforceGameBuild 2372

![20211111200257_1](https://user-images.githubusercontent.com/35634379/141453317-beb3786d-0abf-449f-b04b-5e0400d4f8ee.jpg)

**Comment by blattersturm** [comment]
... another 'bug report' without info that seems to be the user asking for something they broke themselves.
