### ISSUE TITLE
... another 'bug report' without info that seems to be the user asking for something they broke themselves.

### ISSUE THREAD

**Issue by Matetv** [citizenfx/fivem#1132]
... another 'bug report' without info that seems to be the user asking for something they broke themselves.

_Originally posted by @blattersturm in https://github.com/citizenfx/fivem/issues/1131#issuecomment-967002498_
Are you kidding me?
I didn't change anything, installed everything as normal and brought the ServerBuild up to date! No MLOs on it! It works on the Linux server, but not on the Windows server! I wonder why such stupid statements come from you! For what do I pay 50 euros a month to Patreon (FiveM Element Club Platinum 🌟) if you don't even get a lot of help from you! What's the crap? And again: Sandy Shores is faulty on Windows Server (WinServerBuild)! Even Linux (LinuxServerBuild) works with SandyShores! And that's why I ask again! Where is the error!

**Comment by blattersturm** [comment]
... what?

Server platforms have **nothing** to do with in-game things, and you didn't provide **any sort of reproduction steps** to cause whatever issue. We aren't psychic, we do not have access to your server files, and your tone is **very, very hostile**.

**Comment by Disquse** [comment]
Why people can't understand that the GitHub issues section in this repo is not for their issues but for project related tasks. If you don't have reproduction steps or clear explanation why and how this happens - report it **on forum**.
