### ISSUE TITLE
Weird Return Types For `IsVehicleExtraTurnedOn`

### ISSUE THREAD

**Issue by MiddleSkillz** [citizenfx/fivem#1143]
[isextraenabled.zip](https://github.com/citizenfx/fivem/files/7578538/isextraenabled.zip)

Attached you will find a sample resource to demonstrate the odd behavior caused by this natives return values

When using the `IsVehicleExtraTurnedOn` native the return values aren't consistent, when the extra is enabled, it returns 1 with the type of number, whereas when the extra is disabled it returns false as a boolean. Not sure if this is intentional or something that just slipped through the cracks. As you can see with the below screenshots with the same extras setup you get 2 different return types.

![Screenshot_219](https://user-images.githubusercontent.com/57847649/142808921-428fe131-1ef1-4fd1-baf6-4c832ead1039.png)
![Screenshot_218](https://user-images.githubusercontent.com/57847649/142808923-b7753900-daa9-4d8b-9f4a-fbaa0cf8bfc8.png)

**Suggested/Expected Result:** The return value always being a boolean, true when enabled, false when disabled.

**Comment by blattersturm** [comment]
https://forum.cfx.re/t/ismodelincdimage-and-ismodelavehicle-return-an-integer-1-or-a-boolean-false-value-in-lua-scripts/2731483/2

Not a bug, also not actionable at all so doesn't belong here.
