### ISSUE TITLE
Fivem Request

### ISSUE THREAD

**Issue by Zydsonek** [citizenfx/fivem#1147]
Hello, Im developer of AntiCheat which one prevent cheaters from doing shit things. For testing it I need to use executor (checking non-isolated injection and blocking it, also I used it to spawn objects and other few things), all tests are performed on my own server, Im think you can easily check this. I know that I shoudn't use any software like executor, but there is no other way to test it. Im sorry for that, I promise that it will not happen again because I already done test injection. Also I dont need to use It anymore becausue test 
block injection is succesful, I can use Lua Menus by client side script. Waiting for reply. There is my banID: "4f11c6c3-5f15-4616-a03f-4d1eb3edee0c" 
Best Regards mr. Zydsonek

**Comment by blattersturm** [comment]
Also:

> 'developer of AntiCheat'

![image](https://user-images.githubusercontent.com/24576130/142913061-a8c7ca51-668d-42ba-b301-9fefc5cf100e.png)

Looks more like 'developer of cheat'?
