### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by xCzn** [citizenfx/fivem#1148]
Yo, when I try to change full-screen to borderless window It doesn't save, I need to open normal GTA V and change setting here and then it work on fivem. Any solution for this because every time when I click alt+enter this freakin shit changing to full-screen and I again need to open GTA V

**Comment by xCzn** [comment]
also I can add that I have the same issue on my old PC

**Comment by blattersturm** [comment]
This is not a support section _unless_ you have reproduction steps. Post on the forums: https://forum.cfx.re/
