### ISSUE TITLE
linux support through wine?

### ISSUE THREAD

**Issue by cicada7772** [citizenfx/fivem#1151]
i was wondering if it would be to much trouble to make fivem work with wine for linux support
gtav works perfectly under wine, and when trying to run fivem under wine i got an error having to do with rockstar authentication. please look into it, it would be great for us linux users, and would add support for the steam deck

**Comment by blattersturm** [comment]
**We** can't 'look into it'. See all the past discussions including #1125: this depends on DXVK developers adding shared resource support.

**Comment by fbievan** [comment]
Bumping this, shared resourcres has been implemented in dxvk, while seemingly pretty beta  this has been merged in dxvk
https://github.com/doitsujin/dxvk/pull/2516

**Comment by fbievan** [comment]
I have not been able to get pass installation (but i mean I really didnt expect to). Would like to know if i should make an updated issue on this.
