### ISSUE TITLE
Converter doesn't work for .wdr

### ISSUE THREAD

**Issue by userMacieG** [citizenfx/fivem#1155]
For some reason, **FiveM.com** converting tool doesn't work on **.wrd**.
I tried to use that tool to create own conversion of Liberty City map to FiveM but only way to convert **.wrd** is this tool or **GIMS Evo**.
[One of the tutorials how to do that](https://youtu.be/ZbuWWL-dmCs) is from 2015 and as we can see it works fine but right now after doing same thing file is not converting and no error appears.

**Comment by blattersturm** [comment]
Do you have an example file that isn't working- and have you extracted the game shaders?

**Comment by blattersturm** [comment]
(closed as this is not a work item yet, if it does turn out to be an actual issue I can reopen, note: not locked: you can still reply)

**Comment by userMacieG** [comment]
Currently, I tried to convert all files from **GTA 4** base folder (pc) with no success.
![image](https://user-images.githubusercontent.com/24211405/143511648-e8e0bbc9-bfed-4770-b9a6-0c986dd1fdf4.png)
As you can see, any of **.wdr** files doesn't convert.
I have fresh installation of **GTA 5** and **FiveM** also **GTA 4** files are fully working.
![image](https://user-images.githubusercontent.com/24211405/143512026-f7a111a8-26df-4470-a2fa-08be8b825b5e.png)
Also, this is not a new issue. (dunno why didn't they report that before)
[click](https://gtaforums.com/topic/970979-wdr-iv-to-ydr-v-conversion/)
[click](https://gtaforums.com/topic/960412-wdr-to-ydr-conversion-doesnt-work/)
[click](https://gtaforums.com/topic/849372-how-do-i-get-wdr-to-ydr-on-the-latest-version-of-gta-v/)

**Comment by userMacieG** [comment]
I checked shaders to make sure that everything is as it should be and for me all looks fine.
**.wdr** is the only file type that doesn't convert.

**Comment by Vinipux322** [comment]
> 

![изображение](https://user-images.githubusercontent.com/36007766/143537670-702fca5a-bd72-4ade-b861-b96597615777.png)

It's working for me, check your shaders

**Comment by userMacieG** [comment]
> 

Can you show exactly how you installed shaders? Maybe I'm missing something.
