### ISSUE TITLE
RedM: Clarify error messages for IPFS

### ISSUE THREAD

**Issue by roentgenium-cfx** [citizenfx/fivem#1158]
When downloading a new game build for RedM using IPFS, the error messages are somewhat cryptic when something has gone wrong. While I don't have all examples yet, the attached image is an example from when a user no longer had disk space as the build was being downloaded.

When/where possible, we should (to the best of our ability) try to explain what actually went wrong during the download process. There are probably a **ton** of cases one could hit here, but I also imagine the most common one to be hit is 'out of disk space'.

![image](https://user-images.githubusercontent.com/87940610/143660706-28c2847d-d33c-4a4f-8901-4503afbe2cde.png)

**Comment by EagleNaativa** [comment]
![imagem_2022-12-26_180958608](https://user-images.githubusercontent.com/106751994/209583516-e4be65f0-c4d3-4bf4-ad94-e8ee23833afd.png)
Here, another example. 
I cant play RedM because of this

**Comment by gottfriedleibniz** [comment]
IPFS is no more! Closing as fixed.
