### ISSUE TITLE
Restarting resources while connecting to a server in a loading screen causes a crash

### ISSUE THREAD

**Issue by freedy69** [citizenfx/fivem#1164]
Haven't seen this occur until today. Attached a crash dump below in case it has any use.

[CfxCrashDump_2021_11_30_19_05_56.zip](https://github.com/citizenfx/fivem/files/7628180/CfxCrashDump_2021_11_30_19_05_56.zip)
.

**Comment by blattersturm** [comment]
This .zip file seems to be empty. Do you have _any_ more info, like a repro step or so?

**Comment by FlawwsX** [comment]
**Repro steps:**

1. Use canary
2. Load into a server on 2189 (idk if it needs to be or not)
3. Whilst loading in, stop a Lua resource.
4. Crash

Crash DMP file: https://cdn.discordapp.com/attachments/914251027149099098/915337371032092712/511ff9b9-6ae4-496a-a6c8-2d4fc56567e7.dmp

Log: https://cdn.discordapp.com/attachments/914251027149099098/915337455559925900/CitizenFX_log_2021-11-30T202237.log

**Comment by blattersturm** [comment]
Right, appears IScriptRuntime::Destroy gets called _unconditionally_ even if Create has never been called. Will fix on both sides _and_ hopefully the .zip saving hang too.
