### ISSUE TITLE
Resource CPU time spikes (canary)

### ISSUE THREAD

**Issue by Profex1999** [citizenfx/fivem#1171]
I'm using canary and I noticed some random spikes in resmon.
It seems that whenever ther's some sort of loop inside a thread, even after that loop finishes, random CPU time spikes appear regularly in resmon (like every 1 sec). Here's the code I used for testing
`fxmanifest.lua`
```lua
fx_version 'bodacious'
game 'gta5'
client_script 'client.lua'
```
`client.lua`
```lua
CreateThread(function()
    for i =1, 10000 do
        print(i)
    end
end)
```
Here's a clip https://streamable.com/o68mf1
As you can see, every 1 sec there's a spike in resmon (even if the code has  finished).
If i put the for loop outside the CreateThread this does not happen.

**Comment by blattersturm** [comment]
Historical resmon data is only cleared when code actually runs for performance reasons, and I'm not sure what a clean way would be to fix this wraparound for a one-off execution without having to clear every resource's historical tick data _constantly_ or introducing other new edge cases.

Anyone else have any idea?

**Comment by Fortahr** [comment]
Unknown with the current implementation; maybe store the last update time and check against those when drawing the graph?
