### ISSUE TITLE
SetVehicleWheelPower not working

### ISSUE THREAD

**Issue by kasuganosoras** [citizenfx/fivem#1174]
| Game Info | |
| ---- | ---- |
| **Client** | FiveM Canary (1182520) |
| **Server** | FXServer-master v1.0.0.4947 linux |
| **Game** | Build 1604 |

### Description
I'm trying to make a script to simulate the diff-lock system, I tried `SetVehicleWheelRotationSpeed` native, but it doesn't work, the wheel only rotation when it is floating, it will stop immediately if it touches the road. I guess it is because the wheels has no power, so I try to set the wheel power, but looks like this native doesn't set the power correctly.

### Example
```lua
local wheelPower
Citizen.CreateThread(function()
    local vehicle = nil
    while true do
        Wait(0)
        vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
        SetVehicleWheelRotationSpeed(vehicle, 0, -30.0)
        SetVehicleWheelPower(vehicle, 0, 1.0)
        wheelPower = GetVehicleWheelPower(vehicle, 0)
    end
end)
RegisterCommand("test", function(source, args, rawCmd)
    print(wheelPower)
end, false)
```

### Result
When I type the `/test` command, it will always print `0`.

**Comment by JGabT** [comment]
Have you tried changing the order of the natives?
```lua
local wheelPower
Citizen.CreateThread(function()
    local vehicle = nil
    while true do
        Wait(0)
        vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
        SetVehicleWheelPower(vehicle, 0, 1.0)
        SetVehicleWheelRotationSpeed(vehicle, 0, -30.0)
        wheelPower = GetVehicleWheelPower(vehicle, 0)
    end
end)
RegisterCommand("test", function(source, args, rawCmd)
    print(wheelPower)
end, false)
```

Have you also tried changing the wheel index?
Try this executing this native `SetVehicleWheelIsPowered()` in your function

**Comment by gottfriedleibniz** [comment]
Marking as stale. If still an issue, please reopen.

**Comment by YXNGFU** [comment]
hello i have been trying the last couple of days to get a welded diff in fivem and i just need some help since ive been trying everying and i dont know what to do so is there a step by step guide or something to go off
