### ISSUE TITLE
Native CreateMissionTrain doesn't work

### ISSUE THREAD

**Issue by badfantomas** [citizenfx/fivem#1177]
Hi, I found native that doesn't work in the latest linux builds. They still work on linux builds 36xx or latest windows builds. 
Native: **CreateMissionTrain**
Errors: 
**Error executing native 0x63c6cca8e68ae8c8**
![image](https://user-images.githubusercontent.com/95302580/144747039-d7575c31-fe7d-4a37-9b78-429e717850c5.png)
Thank you in advance for the fix <3

**Comment by titanium-cfx** [comment]
Hello,

This is a client-side native, FXServer version is not related.
If you believe this native is not working as intended in FiveM, please provide us with a reproduction resource. :)

**Comment by Disquse** [comment]
Read native description **very carefully**.
```
Train models must be requested before use. See trains.xml for freight and metro variations.
```

**Comment by badfantomas** [comment]
Yes, in the resource I tested trains requested berfore spawn/use. 
Reproduction resource: https://github.com/VenomXNL/XNL-FiveM-Trains-U3/blob/master/XNL-FiveM-Trains-U3/client.lua

**Comment by Samnick86** [comment]
Any resource that use the native **CreateMissionTrain** function not working on latest or recomended **linux** build. 

On latest or recomended windows build native fce working...

**Comment by blattersturm** [comment]
The server platform or version has _zero_ relation to whether this native 'working or not working', (by the way, the English language has a word 'is', you can't just say 'any resource not working', it's 'any resources are not working').

You likely didn't request the new train models used in the mptuner update despite having mptuner enabled. This is still not _our_ bug, or a bug at all, or even related to server platforms: you probably don't have the tuner build set on your Windows machine so your older resource with the older train model list works fine.

**Comment by Samnick86** [comment]
Dear Fivem CEO, 

using "is" is easy...I did it. If there is no dependency between operating system and build version and native function, please explain why native function "CreateMissionTrain" works on windows but not on linux. 

The fivem server setup is completely identical, the only difference is in the OS and build. I don't use any DLC packs.

Yes, you're right. "you can't just say 'any resource that use the function not working". I have tested 5 different resourcers with native function **CreateMissionTrain**. The result was always the same. The client crashed.

Can you please try the resource(which was mentioned in this thread) on latest or recomended linux build? Only with the CFX Default template. -> to exclude that another resources causing the issue.

Thank you

**Comment by blattersturm** [comment]
Instead of somehow trying to prove yourself as being right, can you at least read what is being written here?

You are missing some train models. These resources including the one you linked are from 2020. Your selected game build is newer than that. Rockstar added new trains since then.

Being stubborn isn't going to help you.

I'm closing this issue now. You really are a pestilence.
