### ISSUE TITLE
Creating new c# resources in FXDK loose inteli-sense

### ISSUE THREAD

**Issue by RJMGames** [citizenfx/fivem#1184]
After the first c# resource is created every resources created after looses inteli-sense... Creating more then one resource you lose access to using CitizenFX and can not access any internal fx code.

Version: 1.62.3-cfx
Commit: unknown
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.48 Safari/537.36
Embedder: unknown

**Comment by RJMGames** [comment]
<img width="704" alt="Screenshot (15)" src="https://user-images.githubusercontent.com/95596423/145501896-8b6f3f18-4238-4b32-818f-67045354bb5c.png">

you can see i no longer have access to the CitizenFX using... this only occurs if you have mroe then one resource

**Comment by RJMGames** [comment]
So i can confirm that this is just an issue with FXDK because i can open the project in visual studio code and intelli-sense works fine... so something weird is going on just with the FXDK

**Comment by nihonium-cfx** [comment]
If you have more than one C# resource in project - OmniSharp (that is providing, among other things, intellisense) will only load one of them, however, this is the same behavior as normal VSCode have. You can, however, select what C# project to load in OmniSharp, by clicking on solution name on the bottom (`csrp-core.sln` in your case):

![image](https://user-images.githubusercontent.com/77746579/145523239-a6d93982-dda8-420f-8464-0914dd1c15bf.png)
