### ISSUE TITLE
FiveM: Deferrals Issue

### ISSUE THREAD

**Issue by NotScar** [citizenfx/fivem#1191]
When using deferrals and closing connection with a string that includes "steam" it prints out the reason included in deferrals.done but also "This is a Steam authentication failure, but you are running Steam and it is signed in. The server owner can find more information in their server console."

**Comment by blattersturm** [comment]
Can you explain how this is an _issue_? It seems you are reporting a feature, rather.

**Comment by NotScar** [comment]
Could be deceiving but i do get your point.

**Comment by blattersturm** [comment]
'Deceiving' how? This is meant to indicate to users that random resources rejecting for reasons like 'Could not find SteamID' or 'Your FiveM is not connected with Steam', when a server is misconfigured or can not reach Steam, are an issue with the server, and not their client setup.

**Comment by NotScar** [comment]
Atleast in my occasion, which was deferring the steam identifier it was deceiving but now that you've explained it's something wanted as feature for multiple reasons i guess it's fine
