### ISSUE TITLE
Some files can break GetWeaponComponent.. natives

### ISSUE THREAD

**Issue by MatinHQ** [citizenfx/fivem#1192]
![image](https://user-images.githubusercontent.com/22664859/146195886-62fefb93-403f-43ca-a21a-c77fc16b78bd.png)

Steps to reproduce:
1. Open FiveM application data
2 .Head to \citizen\common\data
3. [Download](https://mega.nz/file/4vIXBSqb#6ucPujA4JEm5wLm-LVugf4guGsOSANiinPExrUrgM8A) and put this folder there
4. Open your FiveM and try to call one of `GetWeaponComponent` natives and it doesn't work

video for repro =>
https://user-images.githubusercontent.com/22664859/146195811-82efed78-3993-4b6e-9faa-2dde9714c10a.mp4
video of how it modfies weapon =>
https://user-images.githubusercontent.com/22664859/146196234-70418434-82b7-4535-91c5-24318749c00f.mp4

this file modifies fire rate, weapon damage and range

**Comment by PichotM** [comment]
Did you try on canary? I thought I fixed it

**Comment by MatinDark** [comment]
yeap that was on canary

**Comment by PichotM** [comment]
Can you tell me which component is giving this error

**Comment by gottfriedleibniz** [comment]
`g_weaponComponentCount` is an int and it would probably be better to copy the inlined binsearch from gamecode. And is that pattern offset correct?

**Comment by MatinDark** [comment]
> Can you tell me which component is giving you this error

I can't exactly tell as I just put all weapon components and their default values in a object and iterate over them as player connects
