### ISSUE TITLE
FiveM GetDistanceBetweenCoords

### ISSUE THREAD

**Issue by bCzxm** [citizenfx/fivem#1200]
Hello, can you add GetDistanceBetweenCoords native to work in server side?

**Comment by PsychoShock** [comment]
First, don't post a issue for this. 
Second, use lua math instead of `GetDistanceBetweenCoords`.

Example:
#(coords1 - coords2)
It will return the distance between two vec3.

**Comment by PsychoShock** [comment]
Also we don't ask "can you add GetDistanceBetweenCoords native to work in server side". That doesn't make any sens.
