### ISSUE TITLE
Game crashed: citizen-devtools.dll!tbb

### ISSUE THREAD

**Issue by RadinPirouz** [citizenfx/fivem#1209]
**I crash when I open the resource monitor**

**Comment by blattersturm** [comment]
**You provide no info**

**Comment by RadinPirouz** [comment]
[CfxCrashDump_2021_12_31_11_55_38.zip](https://github.com/citizenfx/fivem/files/7796117/CfxCrashDump_2021_12_31_11_55_38.zip)
![Crash Message](https://user-images.githubusercontent.com/75082987/147822275-079dd5d8-f94e-4938-af61-24135a2c3bc1.PNG)

**Comment by blattersturm** [comment]
... and repro steps? What did you do to cause this (i.e. any code to reproduce?) and how?
