### ISSUE TITLE
Newer artifacts breaking giving items for whole server !

### ISSUE THREAD

**Issue by Knowgood93** [citizenfx/fivem#1211]
Running any artifacts newer then 4394 on es extended 1.1 breaks giving items for me every time. This is huge because every script made now has the dependency of the newer artifacts like my anti cheat.

**Comment by blattersturm** [comment]
Seems more like an issue with 'es extended 1.1'.

Ask their maintainers..?

**Comment by blattersturm** [comment]
Also,

1. barely any actionable info provided. no repro steps, no saying what 'breaks', no saying what 'your' anticheat is either
2. I doubt 'any' newer break since from 4394 to the release after there have been _zero_ server side changes.

**Comment by Knowgood93** [comment]
What does 4394 have that the current builds don't?

**Comment by blattersturm** [comment]
Nothing? Less features? More bugs?

Are you expecting us to be psychic?

**Comment by blattersturm** [comment]
Closing this as the user seems to be expecting a magical fix to an unspecified concern.
