### ISSUE TITLE
high tick time

### ISSUE THREAD

**Issue by ipittyxx** [citizenfx/fivem#1213]
well weve got the problem that
158.9 ms90.8 % | thread citizen:/scripting/lua/scheduler.lua[505..517]

and in the same file at line 205-207 haste a tick time of 147ms wich is causing massive problems and so far we dont know hot to fix it

wich is CLEARLY an bug on YOUR script so go ahead and close it again but its typicalfor you and go ahead ban people with the reason dont waste staff time

**Comment by blattersturm** [comment]
If this is 'an bug on OUR script' (sic), you still haven't provided a repro or any info, including where you've copy-pasted this stuff from.

I'm rather suspecting this is a reference call in _your_ code taking time, but you're not using the 'detailed' profiler mode, so the only 'bug' here is the standard profiler is not showing the actual ref chunk origin.

There's no reason for you to spam here or make other random blame-placing assumptions, so I'm closing this yet again.
