### ISSUE TITLE
Could not load assembly

### ISSUE THREAD

**Issue by PrexCoder** [citizenfx/fivem#1222]
Hello,

I'm trying to make library, but I do neet some nuget packages for it one of them is Microsoft.Extension.Configurations.Abstractions, for some reasons I get the console log some errors related to loading the assembly file
![image](https://user-images.githubusercontent.com/72302739/149064912-b1cc745d-6034-46dc-a1fb-0caa7cb32364.png)

Is there any way to make this work?

**Comment by blattersturm** [comment]
This is not the place for support questions like yours.
