### ISSUE TITLE
Build 2545 - Spawning PEDS via vMenu causing client crash

### ISSUE THREAD

**Issue by djmetla** [citizenfx/fivem#1224]
Hey, we are issue with latest game build 2545. After we spawn some saved ped from vMenu, all our players got error described on screenshot. I try latest server artifact (linux 5208), latest vMenu update (v3.5.0) and still same error.

![Snimek_obrazovky_122](https://user-images.githubusercontent.com/2371031/149302472-5b731fca-7512-45fe-a08b-066f60badbbb.png)

**Comment by blattersturm** [comment]
Do you have any more precise repro steps than 'some' saved ped?

**Comment by Disquse** [comment]
Looks like it's caused by cloth #MT files limit.

**Comment by blattersturm** [comment]
So basically user error yet again/user not bothering to provide the full story. Seriously?

**Comment by djmetla** [comment]
There is no story, vMenu persist our character PED with clothes in KVP Storage. When we join server, and select load your stored PED, client just crashed with this error. 250 clients got same error. What story you need? Step by step?

1) joined to server
2) open vMenu
3) select stored ped character with clothes (EUP included)
4) ENTER
5) Freeze, Windows desktop with this error

**Comment by blattersturm** [comment]
> select stored ped character with clothes (EUP included)

Again, we don't have _your_ setup of 'stored ped character' or 'EUP' or such.

**Comment by djmetla** [comment]
When i used +set sv_enforceGameBuild 2372 everything works fine.

**Comment by blattersturm** [comment]
1. See @Disquse's message. You're probably hitting the .#mt limit.
2. Cool, but 'everything works fine' with 2545 for us. We don't have **your** server, not we do we have **your** saved ped characters nor **your** EUP files.

**Comment by djmetla** [comment]
How can i know about .#mt limit?, Is a client crash correct reaction about reaching this limit? Where is the limit described?

**Comment by blattersturm** [comment]
I don't know, I don't know about this 'limit' either. @Disquse does and maybe whoever made your addon '.#mt files' would know, but it seems to be a common thing for people to mention and is apparently not possible to fix at all other than merging .#mt files which we don't have any means to do _for you_ as these are _your_ files made with tools _you_ used.

**Comment by blattersturm** [comment]
Locking this thread as it's really getting out of hand. No, 'client crash' is not 'correct reaction about' anything. But this is a Rockstar thing and we can't add safeguards to anything we don't have repro steps for.

**Comment by Disquse** [comment]
> How can i know about .#mt limit?

If you were researching the subject, you would know. The modding factor.

> Is a client crash correct reaction about reaching this limit?

No, but if you want this limit to be increased go and vote for it on the forum (there was a topic). That's not our decision to crash client when limit is reached. The crash caused by the fact that the game can't handle overflow.

> Where is the limit described?

In the game's code that can't be easily edited/fixed at this point.
