### ISSUE TITLE
game files missing

### ISSUE THREAD

**Issue by LOLKills** [citizenfx/fivem#1228]
i cant download fivem says game files are missing and idk what to do ive went on youtube nothing helped  
![unknown](https://user-images.githubusercontent.com/97712256/149432921-cb48d6f8-d23f-4d22-9615-4d8d6a5ee616.png)
![unknown](https://user-images.githubusercontent.com/97712256/149432937-d5c60116-d20f-4103-9def-a1475a6b7e0a.png)

**Comment by titanium-cfx** [comment]
GitHub issues are not for support requests. Please use our Discord server or forums for that.

As for your issue, do what's said in the error message: update your GTA.

**Comment by LOLKills** [comment]
thx for the help
