### ISSUE TITLE
game data out dated

### ISSUE THREAD

**Issue by LOLKills** [citizenfx/fivem#1229]
it says my game is outdated and game files missing ive updated it i got backup files for gta and it wont work nothing will how do i fix this fivem wont even load ive been trying all day and it says same thing over and over even youtube wont help

**Comment by LOLKills** [comment]
![image](https://user-images.githubusercontent.com/97712256/149448329-1c346f01-5cc2-48e4-9909-1733f9a4df85.png)

**Comment by duk-37** [comment]
this is the second time you've asked about this, so I'll just paste what @titanium-cfx said last time

```
GitHub issues are not for support requests. Please use our Discord server or forums for that.

As for your issue, do what's said in the error message: update your GTA.
```
