### ISSUE TITLE
nvidia shadowplay gets completely disabled when playing FiveM

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#1239]
I've been aware of FiveM disabling the embedded game capture, but recently that has effected shadowplay as a whole and completely turns it off for EVERYTHING when launched, requiring it be manually turned on each time.

Previously, you could utilize desktop capture as an alternative to it being embedded in it, however this is made practically impossible.

DisableNVSP=0 in CitizenFX.ini does not seem to work either.

**Comment by blattersturm** [comment]
> DisableNVSP=0 in CitizenFX.ini does not seem to work either.

I suspect this is the only 'bug' here. Maybe that feature has been removed once - no idea, maybe people were using it and complaining about crashes.

Contact NVIDIA or use any open-source alternative like OBS, or built-in Windows tools like Xbox Game Bar.
