### ISSUE TITLE
Make it possible to turn off BGM in menu

### ISSUE THREAD

**Issue by jacob-hougaard** [citizenfx/fivem#1249]
As a user i would like to be able to enable/disable music inside the application, either through the settings menu or as an icon in the top right corner of the application. 
![Capture](https://user-images.githubusercontent.com/8928540/151214585-16c8282d-9ff8-4316-a0f4-aecd2cb1c49e.PNG)

**Comment by Xinerki** [comment]
![image](https://user-images.githubusercontent.com/17089404/151214824-0121f1f5-28e5-42fe-bb42-9ba46b372731.png)

**Comment by blattersturm** [comment]
As above, this is already a thing.
