### ISSUE TITLE
Runtime Dictionary & Textures Issue

### ISSUE THREAD

**Issue by rdelian** [citizenfx/fivem#1252]
## Issue
If I create multiple RuntimeTextures inside the same Runtime Dictionary only _some_ of them are available

## Observations
- Noticed that if I change `dict_name` the order of "good/bad textures" doesn't change, but if I change the `texture_name` the order will change.
- If I create a dictionary each time I create a texture is fine (unless I create too many and the game crash - I can provide the crash report if needed)
- Is there any way to delete/create a RuntimeTexture or RuntimeDictionary?
    - Textures are kept in memory even if I restart the resource (probably intendent)

## Repro code
<details>
<summary>Click to expand</summary>

```lua
local dict_name = "DICT_A"
local texture_name = "IMAGE_A_"
local steam_avatars = {
    'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/f3/f334aaaba2f6edc91dd561f63723d779ca051505_full.jpg',
    'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/fc/fccbd10e71aead5b73a591dc8bd6fe8cd2e125eb_full.jpg',
    'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/af/af42d2489409ab0fdad97213b09d24586c46d7c4_full.jpg',
    'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/b6/b6fd72bb0a861cbd35fd0b18a1bb2b85d3d2d952_full.jpg',
    'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/68/6828f1c6bc12c05364a350d918104b1aaddf5e9b_full.jpg'
}

function Init()
    -- Texture Dictionary
    local dict_handle = CreateRuntimeTxd(dict_name)

    -- Multiple Textures inside the Texture Dictionary
    for i = 1, #steam_avatars do

        -- DUI from the image
        local dui_object = CreateDui(steam_avatars[i], 64, 64)
        local dui_handle = GetDuiHandle(dui_object)

        -- Create the texture into our dictionary from DUI
        CreateRuntimeTextureFromDuiHandle(dict_handle, texture_name .. i, dui_handle)
    end
end

Citizen.CreateThread(function()
    Init()

    -- Test Draw textures on vertical row
    while true do Wait(0)
        for i = 1, #steam_avatars do
            DrawSprite(dict_name, texture_name .. i, 0.3, 0.1 + i / 16, 0.03, 0.05, 0.0, 255, 255, 255, 255)
        end
    end
end)
```

</details>

**Comment by blattersturm** [comment]
I'm guessing the hash/pointer list isn't sorted correctly and binary search is failing. Should be an easy fix.

**Comment by blattersturm** [comment]
![image](https://user-images.githubusercontent.com/24576130/151695420-8ec3b9ea-f52f-4044-bbe7-22e68b5cb966.png)

I guess as GH was down when I was pushing my fix it didn't apply the issue-closing commit.
