### ISSUE TITLE
NPC (Peds) not shooting first

### ISSUE THREAD

**Issue by sangyoo91** [citizenfx/fivem#1259]
Spawned peds wont shoot players first unless they are shot at. They will only aim at the ped while moving backwards until they find cover. 

Natives I've tried using to force them to shoot are

```lua
TaskCombatPed
TaskCombatHatedTargetsAroundPed
```

I'm on server artifact build 5181, mptuners and canary enabled.

**Comment by blattersturm** [comment]
Can you post the _actual_ code you're using here?

**Comment by sangyoo91** [comment]
Yes I can, sorry about that.

```lua
local function createEnemy (modelHash, pos, heading)
  AddRelationshipGroup(`ENEMY`)

  if not HasModelLoaded(modelHash) then
    RequestModel(modelHash)
    Citizen.Wait(100)
  end

  local ped = CreatePed(26, modelHash, pos, heading, true, true)
  NetworkRegisterEntityAsNetworked(ped)
  SetPedAsEnemy(ped, true)
  SetPedRelationshipGroupHash(ped, `ENEMY`)
  SetEntityOnlyDamagedByPlayer(ped, true)
  SetNetworkIdCanMigrate(networkId, true)
  SetNetworkIdExistsOnAllMachines(networkId, true)
  SetEntityAsMissionEntity(ped)

  SetPedAccuracy(ped, 100)
  SetPedArmour(ped, 100)
  SetPedCanSwitchWeapon(ped, true)
  SetPedDropsWeaponsWhenDead(ped, false)
  GiveWeaponToPed(ped, `WEAPON_PISTOL`, 255, false, false)
  TaskCombatPed(ped, PlayerPedId())
end
```

**Comment by blattersturm** [comment]
I can't check right now, but your code is calling a lot of redundant natives setting defaults _again_, and you're not switching the weapon as current either.

What ped model are you spawning, and where?

Also, are you testing with more than one player in an area? If so, you need to handle task reassignment as well.

**Comment by sangyoo91** [comment]
I'm testing alone, right now  but with 2 ~ 3 players around it was the same.  I did try task reassignment as well a few days ago and wasn't different.

I was calling redundant natives to see if I was missing anything but with the below code, testing by myself, the results were not any different.

```lua
local function createEnemy (modelHash, pos, heading)
  local playerPed = PlayerPedId()
  while not HasModelLoaded(modelHash) do
    RequestModel(modelHash)
    Citizen.Wait(100)
  end
  local ped = CreatePed(26, modelHash, pos, heading, true, true)
  SetPedCanSwitchWeapon(ped, true)
  SetPedDropsWeaponsWhenDead(ped, false)
  GiveWeaponToPed(ped, `WEAPON_PISTOL`, 255, false, false)
  SetCurrentPedWeapon(ped, `WEAPON_PISTOL`, true)
  TaskCombatPed(ped, PlayerPedId())
end
```

**Comment by blattersturm** [comment]
> What ped model are you spawning, and where?

**Comment by sangyoo91** [comment]
Right now I'm using `s_m_m_chemsec_01`. I can try other peds and see if it helps. 

As for the where part, I've been trying here and there around the vespucci and vinewood area but results are the same.

**Comment by CritteRo** [comment]
I think you might be missing combat attributes, that can make the ped aggressive from the start. This is the code that I use for my enemies, in an arena script (all client-side):
```lua
function spawnEnemy(model)
    local ped = PlayerPedId()
    local coords = GetEntityCoords(ped)
    local head = GetEntityHeading(ped)

    RequestModel(model)
    while not HasModelLoaded(model) do
        RequestModel(model)
        Wait(0)
    end
    local sLoc = math.random(1,5)
    local enemy = CreatePed(1, model, spawnLocs[sLoc].x, spawnLocs[sLoc].y, spawnLocs[sLoc].z, spawnLocs[sLoc].heading, true, true)
    SetPedCombatAttributes(enemy, 0, true)
    SetPedCombatAttributes(enemy, 46, true)
    SetPedCombatAttributes(enemy, 5, true)
    SetPedCombatRange(enemy, 2)
    SetPedCombatAbility(enemy, 2)
    SetPedCombatMovement(enemy, 3)
    SetPedConfigFlag(enemy, 183, true)
    SetPedConfigFlag(enemy, 4, true)
    SetPedFiringPattern(emeny, GetHashKey("FIRING_PATTERN_FULL_AUTO "))
    SetPedRelationshipGroupHash(enemy, GetHashKey("GROUP_LSLD_ARENA_NPC")) --custom group hash, set to hate the "PLAYER" group.
    SetModelAsNoLongerNeeded(model)

    GiveWeaponToPed(enemy, GetHashKey("weapon_carbinerifle"), 9999, false, true)
    SetPedInfiniteAmmo(enemy, true, "weapon_carbinerifle")
    TaskCombatPed(enemy, ped, 0, 16)
    --TaskCombatHatedTargetsAroundPed(enemy, 600.0, 0) --don't 
end
```

With this script, no matter which ped I choose, they will all act like like a zancudo soldier, after being agitated (angered).

**Comment by Fortahr** [comment]
Maybe there are other settings that are being applied to peds on your server?

the example given works fine on my end, I died...

**Comment by sangyoo91** [comment]
I had a trainer that had `SetEveryoneIgnorePlayer` to true. Thanks guys :D
