### ISSUE TITLE
SP: 'The Big Score' mission has a hanging flow

### ISSUE THREAD

**Issue by roentgenium-cfx** [citizenfx/fivem#1262]
Hello i am having a issue with five m single player when i get to this point in the union depository mission it just does not do anything it does not freeze but nothing happens Pic below

![image](https://user-images.githubusercontent.com/87940610/152136546-15a49965-4308-46be-81c2-98f3804b2fe4.png)

**Comment by blattersturm** [comment]
Fixed in #977, thanks for the report!
