### ISSUE TITLE
Unloading crash masked by earlier fix: FiveM_GTAProcess.exe!sub_1415A572C (0x4c) (maine-venus-neptune)

### ISSUE THREAD

**Issue by roentgenium-cfx** [citizenfx/fivem#1267]
Internal link: https://sentry.fivem.net/organizations/citizenfx/issues/687/

```EXCEPTION_ACCESS_VIOLATION_READ at FiveM_GTAProcess.exe!sub_1415A572C (0x4c) (maine-venus-neptune)```

**Comment by gottfriedleibniz** [comment]
Issue is no longer on sentry. While there does exist a similar crash within the same function `2802: 0x14162D0D8 + 0x54` it is quite insignificant.

Closing issue as stale.
