### ISSUE TITLE
Update Chromium to M99 or newer

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#1276]
With M91 we're a bit behind again.

An Apple user has [updated the public patch set](https://bitbucket.org/chromiumembedded/cef/pull-requests/285#comment-255373881) to M96, our repository (https://github.com/citizenfx/cef and https://github.com/citizenfx/chromium) has a patch set as well which needs to be retained, and ideally we'd again convert the CEF .patch files into a rebase commit atop the relevant tag so it's easier to track patches in Git again.

Skia renderer changes are still on some local tree, but I'd _hope_ the old renderer is still left in somewhere as the Skia changes had some buffer flip concerns.

**Comment by Lop0q** [comment]
Hey, more than 10 people have been falsely hardware banned. While I am one of them, I have been banned for 200 days without doing anything. I tried contacting support but there was no reply. So I think there is a problem with the anti cheat system. You can check it out, here is the banned Id:
ID: c6a80403-e512-4d97-814a-acf777b43594_01

**Comment by Lop0q** [comment]
Hey, more than 10 people have been falsely hardware banned. While I am one of them, I have been banned for 200 days without doing anything. I tried contacting support but there was no reply. So I think there is a problem with the anti cheat system. You can check it out, here is the banned Id:
ID: c6a80403-e512-4d97-814a-acf777b43594_01
