### ISSUE TITLE
Remove unsafe libraries from server-side lua libraries (or make them safe)

### ISSUE THREAD

**Issue by fjuton** [citizenfx/fivem#1284]
# What?
- os library
- io library

# Why?
Since FiveM has published their own "Anti-Escrow System", I discovered some issues that can cause big problems!!!!!!!

For example:
Someone sells his random script on Tebex and uses the "Anti-Escrow System" but he adds dangerous code that gives him access to the customers's machine.

**Comment by titanium-cfx** [comment]
We will not remove these from FXServer Lua ScRT. 

First: we cannot break the compatibility of all the resources that have legitimate use of those libraries.
Second: It would be very stupid for any seller on Tebex to include any malicious code in their resources, as they would get permanently suspended from Tebex and our forums by doing so. 

It's also the due diligence of any server owners to make sure the resources they're using, free or paid, come from trustworthy parties.
