### ISSUE TITLE
CEventNetworkEntityDamage issue

### ISSUE THREAD

**Issue by BuddiesTV** [citizenfx/fivem#1286]
CEventNetworkEntityDamage is not triggered on fall damage in the latest build 2545, I tested it with older builds (2060) and it works with older builds.

**Comment by gottfriedleibniz** [comment]
Also https://github.com/citizenfx/fivem/blob/master/code/components/gta-streaming-five/src/GameEventHooks.cpp#L301 : needs to be updated for 2545 (130)
