### ISSUE TITLE
[Suggestion] make Serverside CreateVehicle able to spawn when no one is on the server.

### ISSUE THREAD

**Issue by BuddiesTV** [citizenfx/fivem#1297]
Currently, if you spawn a vehicle Serverside with CreateVehicle and no one is on the server, the vehicle will not spawn.

Why is this a good idea to implement?
People like me, working on an RP server, if you want the vehicles to be saved when the server stops and spawn again when the server starts, this is currently not possible because vehicles spawned at server startup do not spawn.

**Comment by AvarianKnight** [comment]
Github is for actionable issues, please use the [forums](https://forum.cfx.re/c/general-discussion/feature-requests/33) for suggestions.

What you requested is already a thing too, search for CREATE_AUTOMOBILE in the Cfx discord.

**Comment by BuddiesTV** [comment]
> Github is for actionable issues, please use the [forums](https://forum.cfx.re/c/general-discussion/feature-requests/33) for suggestions.

Oh, okay. i guess i'll close the issue.
But thx!
