### ISSUE TITLE
[Question] Tools and methods for hooks

### ISSUE THREAD

**Issue by mcmonkey4eva** [citizenfx/fivem#13]
Spread across the code base is things like this:
```cpp
static hook::thiscall_stub<rage::fiCollection*(rage::fiCollection*)> packfileCtor([] ()
{
	return hook::pattern("44 89 41 28 4C 89 41 38 4C 89 41 50 48 8D").count(1).get(0).get<void>(-0x1E);
});
```

Which, even to an experienced programmer, would be utter nonsense: it's just a hex string that somehow connects to actual data.

So my question is:
How is this written? What tools and methods are used to create lines of code like this and bring FiveM to life?

**Comment by blattersturm** [comment]
Disassembly of the GTA5 EXE in IDA. You can look up the hex string using binary search and should end up finding the referenced address.

**Comment by mcmonkey4eva** [comment]
Ah. Thanks for the information! :)
