### ISSUE TITLE
Error with scenario file (.ymt) won't give an error message on crash

### ISSUE THREAD

**Issue by TheKronoss** [citizenfx/fivem#1303]
When you stream an .ymt file (the correct way, as seen in the cookbook) that is broken in some way I think. Your game will crash, but won't give an crash / error message. It will just close (at the same way as F8 > quit). 

I've checked this when having no streaming, .ymt file it won't happen. And when editing and deleting a lot of scenario's in an .ymt with for example codewalker in the downtown.ymt for example and streaming it, your game will close. The crash isn't happening every time you log in, I assume it happens when a scenario inside the .ymt is active, so only at specific moments when a corrupt scenario is loaded in. As most of the scenario's are only loaded / active at certain ingame clock hours it won't happen every time you pass the location of the edited corrupt .ymt.

When checking the fxlog's etc. nothing is shown. It also won't give you a crash message. 

If something is unclear or information is missing, let me know!

**Comment by blattersturm** [comment]
... I'm missing an actual example of a broken file to test with.

**Comment by TheKronoss** [comment]
[downtown.zip](https://github.com/citizenfx/fivem/files/8100092/downtown.zip)
When streaming this file, with the ingame clock at around 15:30 when you come close to legion square your game will crash / close.

**Comment by AvaN0x** [comment]
Hello, I started streaming a scenario file two days ago and I had the same issue of game closing without any informations sometimes. Seeing this issue I investigated it on my side and I can say that it is related to the scenario file in some ways.
I made a repro :
[fivem_issue_1303.zip](https://github.com/citizenfx/fivem/files/8100422/fivem_issue_1303.zip)
Simple `ensure fivem_issue_1303`, go to the mission row police departement (in my case I was I was in front of the garages) and set the clock to 7am.
You should have the instant game closing around this time.

This streamed scenario file removes some peds and some vehicles scenario in the parking lot and in front of the MRPD.

**Comment by TayMcKenzieNZ** [comment]
To be fair, everyone seems to be streaming one Scenario file and misunderstanding the whole overriding thing. If you only stream one scenario, cool, you have one scenario, but you disable all others. 

I made a resource that has all the scenarios up to the Cayo Perico DLC, and then I modified them to remove the triathlon, paparazzi, clapping, cheering related scenarios. The only time it crashes for me is when I attempt to delete chains, nodes or clusters.

**Comment by mickeygeecom** [comment]
Out of curiosity, which version of CodeWalker are you using?
I have *very* recently edited exactly missionrow.ymt scenario, and have no crashes on b2372.

Older versions of CW have .ymt errors.

**Comment by blattersturm** [comment]
FWIW, the issue report here is about the crash itself not being caught by the crash handler and failing _silently_, not about the scenario files themselves.

**Comment by AvaN0x** [comment]
> Out of curiosity, which version of CodeWalker are you using?
As said by blattersturm, it's more about the game closing without any informations,  but to answer your question I used the last version for these edits of the mission_row.ymt file (R30_dev42).

**Comment by blattersturm** [comment]
I just tried this again and I seem to correctly crash:

```
[Window Title]
Error GTA5_b2545.exe!sub_140C38934 (0x2b)

[Main Instruction]
GTA5_b2545.exe!sub_140C38934 (0x2b)

[Content]
An error at GTA5_b2545.exe!sub_140C38934 (0x2b) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: summer-virginia-earth
Stack trace:
  GTA5_b2545.exe!sub_140C38934 (0x2b)
  GTA5_b2545.exe!sub_140C38AC8 (0xb6)
  GTA5_b2545.exe!sub_140C5598C (0x33d)
  GTA5_b2545.exe!sub_140C3C2B4 (0xab)
  GTA5_b2545.exe!sub_140C26A90 (0x4f5)
  GTA5_b2545.exe!sub_140EF4BE8 (0xa4)
  GTA5_b2545.exe!sub_140EF3FE8 (0xa1)


[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b2545.exe+C3895F
Report ID: si-5cf44f254145409cbeff19e49de4134b
You can press Ctrl-C to copy this message and paste it elsewhere.
```

Might be this got fixed in some recent crash handler changes?

**Comment by TheKronoss** [comment]
> [downtown.zip](https://github.com/citizenfx/fivem/files/8100092/downtown.zip) When streaming this file, with the ingame clock at around 15:30 when you come close to legion square your game will crash / close.

Hey, sorry for reopening the issue. I've just retested this in my local server but when I do this above my game crashed, tested it twice and it keeps crashing without giving an crash message. I'm on Latest (Unstable) with Ver. 5444/canary being in orange in the right bottom corner.

**Comment by blattersturm** [comment]
Do you have any more concrete repro steps - maybe a script to set time+coords?

**Comment by TheKronoss** [comment]
I think that it's crashing when loading in a broken scenario. The problem is that scenario's aren't spawned at specific coords / time. As they are meant to be spawn randomly. 
So when I set the time to be exactly 15:32, it will spawn sometimes. What I do is setting the time on 15:00 and then it progresses like ingame, then I noclip around legion square (where the downtown.ymt is located) and keep looking to the scenario's and then looking away and repeat that. After like one minute of doing that I'm crashing.

**Comment by blattersturm** [comment]
@TheKronoss 

> my game crashed

Wait, do you mean your game _crashed_ with an error message, or it _closed without error message_?

Crashing with broken files like this is _intended_ (CodeWalker bug fixed in dexyfex/CodeWalker@70ebdd8360e18e18f172ea0b138b283fa3780fa8), the only thing not supposed to happen is the game closing without a crash dialog.

As with the repro attempt above, I couldn't get this to lead to the game closing without crash dialog.

**Comment by TheKronoss** [comment]
Sorry for my bad explanation, the game closes without error message. On both my and my friends pc when testing.

I've made a full resource to test it: 
[fivem_issue_1303_downtown.zip](https://github.com/citizenfx/fivem/files/8402696/fivem_issue_1303_downtown.zip)

With the resource above it happens around legion square with the clock around 15:30

**Comment by TheKronoss** [comment]
I am really confused right now, I've tried it right now and my game is still closing without crash message.
My Windows version: Windows 11 Insider Preview 22593.1 
My FiveM Client Version: 5466 / Canary
FxServer build: 5461

Reproduction:
- Start an almost clean FxServer (mapmanager, spawnmanager etc. are loaded)
- Start the resource as zipped above with the name 'fivem_issue_1303_downtown'
- Join the server and set the time on 15:00 (without freeze so the time keeps ticking slowly)
- Use Noclip to fly around legion square in downtown 
- Within a couple of minutes my game closes without any crash message. 

If this isn't enough I could also zip my fxserver and send that to see if the problem is within the server build or even record a video if you think this is a user error (even if me and my friends' games are closing without a crash message.)

**Comment by TheKronoss** [comment]
I've tested it again now and now I'm getting also the summer-virginia-earth crash error. I think it was an error with my fivem.
