### ISSUE TITLE
Error building "could not get a repository handle"

### ISSUE THREAD

**Issue by Stay1444** [citizenfx/fivem#1308]
Im trying to build the server using the guide provided in the docs folder. I'm getting this error when downloading the git submodules
`fatal: could not get a repository handle for submodule 'ext/sdk/resources/sdk-root/fxcode'` 
How can i fix this?

**Comment by thorium-cfx** [comment]
Did you manage to fix this already?

**Comment by FuseWasTaken** [comment]
i have the same issue, did u find a fix?

**Comment by blattersturm** [comment]
No info was provided.
