### ISSUE TITLE
Changing game build with second FiveM instance

### ISSUE THREAD

**Issue by freedy69** [citizenfx/fivem#1310]
Hi, my server used to be on the mptuner (2372) game build and I recently enforced mpsecurity (2545). Everything is fine with the normal FiveM instance, but not with the second instance. So far i've found two issues, which i can provide repros for:

Issue 1: Second instance not opening while normal instance is running
step 1: have normal FiveM instance open (the current build this instance is running is 2545)
step 2: open the second instance
step 3: try to connect to a server with higher build (it should prompt you the game build change dialogue)
step 3: hit OK
after this, your cursor will have the loading sprite until the normal instance is closed.
after you close the normal instance, you will get the 'Transitioning To Game Build' screen.
after this screen, you will connect to the server, but it opens the normal FiveM instance instead of the second one. Game build is not saved for the second instance either, which leads to continuous game build change prompts on second instance.

Issue 2: Second instance not changing build if normal FiveM instance is opened
step 1: open FiveM with second instance
step 2: connect to the server with higher build
step 3: hit OK on the changing build prompt
after this, FiveM will close and open the 'Transitioning To Game Build' screen. After this screen closes, normal FiveM instance opens and game build doesn't get saved on the second instance, which also leads to continuous change prompts.

**Comment by blattersturm** [comment]
For the time being, a valid workaround would be manually passing the target build number command line argument (e.g. -b2545) to the cl2 launch.

Issue here is probably that 'switchcl' launching isn't passing through the -cl2 switch.

**Comment by jaymo1011** [comment]
Yep, no args from the initial launch are passed to the new process when switching builds.
https://github.com/citizenfx/fivem/blob/d2311cceb0f45b48f3eb298891f2de2455e8d5e7/code/components/glue/src/ConnectToNative.cpp#L104-L107
