### ISSUE TITLE
Last server try to connect to final endpoints instead to the domain provide by sv_listingHostOverride

### ISSUE THREAD

**Issue by MrSentex** [citizenfx/fivem#1314]
When you connect to a server who has sv_listingHostOverride setted and disconnect or quit sometimes you connect directly to the IP instead using the domain who could have a different IP address. I tryed to search the code who get the last server address but I didn't find it.

**Comment by blattersturm** [comment]
'sometimes' seems very not actionable.

**Comment by MrSentex** [comment]
I think is a time based thing. Like if you successfully connect to a server the server is automaticaly added to your last server entry on the menu and if you try to reconnect 1 minute after you quit the game you will try to connect with server endpoint directly not throw the domain.
