### ISSUE TITLE
GetOffsetFromEntityInWorldCoords is not a function in javascript error

### ISSUE THREAD

**Issue by utkuali** [citizenfx/fivem#1317]
This native works fine in lua but does not work in javascript.

I tried with fx_version bodacious and cerulean.

My usage in lua:
```lua
local behindCoords = GetOffsetFromEntityInWorldCoords(ped, vector3(-0.6, -1.8, 0.3))
```

My usage in js:
```js
let behindCoords = GetOffsetFromEntityInWorldCoords(ped, [-0.6, -1.8, 0.3])
```

![image](https://user-images.githubusercontent.com/57073765/157832116-97e70827-8051-49f2-87af-31438824c9cb.png)

**Comment by blattersturm** [comment]
Can you upload a full repro resource just in case?

**Comment by AvarianKnight** [comment]
Isn't
```js
let behindCoords = GetOffsetFromEntityInWorldCoords(ped, [-0.6, -1.8, 0.3])
```
Supposed to be
```js
let behindCoords = GetOffsetFromEntityInWorldCoords(ped, -0.6, -1.8, 0.3)
```

**Comment by utkuali** [comment]
@AvarianKnight tried before posting it, same error
@blattersturm Here is the example command both in js and lua

[examples.zip](https://github.com/citizenfx/fivem/files/8230522/examples.zip)

**Comment by utkuali** [comment]
And also I don't know if it matters but I am enforcing game build 2372.

**Comment by Disquse** [comment]
As @AvarianKnight said, you shouldn't use arrays in arguments when calling natives. Your example works fine (no exceptions) after removing array brackets.

**Comment by utkuali** [comment]
I tried it, still the same error.

**Comment by utkuali** [comment]
Okay, my bad. I was trying to use IIFE. Function worked after I removed it.
