### ISSUE TITLE
fivem slow download speed & map buildings not loading

### ISSUE THREAD

**Issue by iAboodx** [citizenfx/fivem#1322]
i was playing fivem 2 months ago and none of these issues happen but yesterday i downloaded fivem again and everything is normal since i start joining servers so the first server i joined the download speed was very slow which it was downloading in kilobyte so i noticed the download speed is slow when ever fivem request to restart to switch the version and stuff, so when i join any server after that restart it gives me slow download speed, even if the download finished the map buildings is not loading & character is invisible & settings not open keep loading for ever, even if i stay for more than 2 hours in the server nothing happen, the game settings is normal, my pc is good enough i5 10gen & 1650 super & 16gb ram and all drivers is up to date 
and these issues is on all servers happen

solutions i tried :
disabled start up apps
disabled background apps
stop unnecessary services 
disabled task scheduler apps
cleared cache & temp files 
redownloaded fivem

**Comment by blattersturm** [comment]
The GitHub issues section is for _actionable work items_ only. None of your report is actionable to anyone but yourself.
