### ISSUE TITLE
Invalid ref call attempt: 9 REDM

### ISSUE THREAD

**Issue by Royalstick** [citizenfx/fivem#1327]
(Sorry about my english) Hello, since January artifacts update, i dont remember what is the right day, but is between 1 and 16 January, , because i was thinking that was the core and not artifacts, that i have this error. I cant solve it, and no one at our framework know what is it. But i really think its update from cfx. Can u help me with that?

- This error como from nohere.
- I tryed everyscript, and nothing to do about the scripts.
- Sometimes happens 2 in 12h, and for like 3/4 days no error. 
- Crash my server.
- Tryed roleback the artfacts, and still doesnt work. 
Its always the same error. 

Gonna send u prints. 
https://i.imgur.com/02Zst4h.jpg

**Comment by blattersturm** [comment]
The GitHub issues section is for _actionable reports_ only. 'prints' of a script error without repro, sadly, are not such.

**Comment by Royalstick** [comment]
the error is very simple

[    script:vorp_core] Invalid ref call attempt: 9
[script:vorp_inventor] Cannot perform runtime binding on a null reference
[    script:vorp_core] Invalid ref call attempt: 9
[script:vorp_inventor] Cannot perform runtime binding on a null reference
[    script:vorp_core] Invalid ref call attempt: 9

like that, but on a loop repeat, till restart of the server.
