### ISSUE TITLE
Link redirects to cfx.re

### ISSUE THREAD

**Issue by someone0002** [citizenfx/fivem#1328]
https://github.com/citizenfx/fivem/commit/ee1490e5a871d3c82112ea09ffa462cfb4ba974f

```
FatalError("Invalid native call in resource '%s'. Please see https://aka.cfx.re/scrstring-mitigation for more information.", luaRuntime->GetResourceName());
}
```

Link here just redirects to cfx.re, not sure if bubble noticed. Just pointing it out.

_unless im stupid and it just doesn't work for me_

**Comment by blattersturm** [comment]
This is intentional for now, as this code is only on pre-release versions and the page it's meant to lead to hasn't been written yet.
