### ISSUE TITLE
WHY IS MY FIVEM KEEP CRASHING

### ISSUE THREAD

**Issue by bababrrld** [citizenfx/fivem#1331]
https://github.com/citizenfx/fivem/blob/80cd44722e3ee94ffc32b29b1d12b0aadcfa788d/code/components/gta-core-five/src/CrashFixes.cpp#L266

**Comment by PsychoShock** [comment]
Do you have any more information? Any dump? Something that can help us providing a fix please. Thanks

**Comment by Sindrum** [comment]
Hey I'm getting the same issue IDK if you guys are even still around but if so heres the dump from my crash
[CitizenFX_log_2023-06-02T230656.log](https://github.com/citizenfx/fivem/files/11639905/CitizenFX_log_2023-06-02T230656.log)
