### ISSUE TITLE
Crash - GTA5_b2372.exe+A99F50

### ISSUE THREAD

**Issue by LilWhit3ADG** [citizenfx/fivem#1332]
![Screenshot_1](https://user-images.githubusercontent.com/101927580/159117443-052ed5c8-4391-485b-89aa-d074039a779a.png)

**Comment by blattersturm** [comment]
This isn't a place for non-actionable support questions, where you also somehow seem to have avoided providing any context, info, and have for whatever reason even cropped out the crash ID.

Try the forums: https://forum.cfx.re/
