### ISSUE TITLE
Entity state bag doesn't get replicated when set by client

### ISSUE THREAD

**Issue by BlackFlash5** [citizenfx/fivem#1335]
When I try to set a state bag key on an entity (vehicle) and set `replicated` to `true`, the key won't get replicated to the server or other clients.
I've created a [sample resource](https://github.com/BlackFlash5/StateBagRepro) to replicate this issue:
- get in any vehicle (as driver)
- run command `bagclient` / `bagserver` to verify the key `TestBag` is not set
- run `setbagclient test test` to save a dictionary with kvp `{ test, test }` to replicated key `TestBag`
- key `TestBag` is now set on the client, but not on the server or other clients (verify with `bagclient` / `bagserver`)

```
> bagclient
Bag is empty!
> setbagclient test test
OnSetBagClient | Args: test, test
- StateBagChangeHandler -
BagName: entity:124 | Key: TestBag | Replicated: True
Key: test | Value: test
> bagclient
Key: test | Value: test
> bagserver
OnBagServer | Player: Black Flash
Bag is empty!
```

Server: 5412
Client update branch: Latest (Unstable)

**Comment by jxckUK** [comment]
> When I try to set a state bag key on an entity (vehicle) and set `replicated` to `true`, the key won't get replicated to the server or other clients. I've created a [sample resource](https://github.com/BlackFlash5/StateBagRepro) to replicate this issue:
> 
> * get in any vehicle (as driver)
> * run command `bagclient` / `bagserver` to verify the key `TestBag` is not set
> * run `setbagclient test test` to save a dictionary with kvp `{ test, test }` to replicated key `TestBag`
> * key `TestBag` is now set on the client, but not on the server or other clients (verify with `bagclient` / `bagserver`)
> 
> ```
> > bagclient
> Bag is empty!
> > setbagclient test test
> OnSetBagClient | Args: test, test
> - StateBagChangeHandler -
> BagName: entity:124 | Key: TestBag | Replicated: True
> Key: test | Value: test
> > bagclient
> Key: test | Value: test
> > bagserver
> OnBagServer | Player: Black Flash
> Bag is empty!
> ```
> 
> Server: 5412 Client update branch: Latest (Unstable)

I've ran into this issue also and although its not in official documents it has been clarified:

> State bags can be initialized on the client, but they cannot replicate data to the server unless it's created on the server.

Ref: https://forum.cfx.re/t/how-to-use-state-bags/2093206

You can get around this by using an event such as entity creating to define the state bags for entities on the client side. You can then replicate data to those created bags.

For players you could use an event such as playerConnecting to add the state bags server side.

Hope this helps.

**Comment by blattersturm** [comment]
That's still not _intended_, it's a workaround at best.

**Comment by jxckUK** [comment]
> That's still not _intended_, it's a workaround at best.

I see - Is there a better solution?

**Comment by blattersturm** [comment]
I believe the need for 'a better solution' is the point of this issue report, in fact.
