### ISSUE TITLE
SDK: cannot open world editor

### ISSUE THREAD

**Issue by 0xLuca** [citizenfx/fivem#1337]
After trying to open the world editor on a newly created project, i got the following errors:
`Failed to download "latest" server artifact: Artifact server responded with status code: 404`
and
`Failed to start server: Error: ENOENT: no such file or directory, open 'C:\Users\XXX\AppData\Local\citizenfx\sdk-storage\server\latest\components.json'`

After restarting the Development Kit, the first error appeared again instantly, the second one after opening world editor.

**Comment by blattersturm** [comment]
Try setting the project to not use 'latest' version.

**Comment by 0xLuca** [comment]
> Try setting the project to not use 'latest' version.

I already tried, with recommended and optional. Instantly after starting the Kit, on the bottom left i get the first error.

**Comment by blattersturm** [comment]
>  it crashes everytime i want to open it

Unrelated concern, might be some process didn't exit.

**Comment by 0xLuca** [comment]
> > it crashes everytime i want to open it
> 
> Unrelated concern, might be some process didn't exit.

I restarted my pc, it no longer crashes. Still the two errors as stated in the first message.

**Comment by blattersturm** [comment]
Right.

Similarly, this server shouldn't ever return a 404-ing URL. I've pinged people who can look into this when you first posted, and I've just done so again as I've not heard _any_ response.

**Comment by titanium-cfx** [comment]
This issue should be resolved now. Could you please try again and confirm?
