### ISSUE TITLE
FiveM either shows the error code below or crashes and shows the crash report below when trying to join a server

### ISSUE THREAD

**Issue by vzixx** [citizenfx/fivem#1341]
[CfxCrashDump_2022_03_23_01_38_03.zip](https://github.com/citizenfx/fivem/files/8328939/CfxCrashDump_2022_03_23_01_38_03.zip)

![image](https://user-images.githubusercontent.com/101080564/159604975-9d33a18b-27d0-45d3-84f5-01e2f409ea62.png)

**Comment by PsychoShock** [comment]
Please stay alert for a CFX message in Discord, seems to be a major issue for some so will have to wait.
