### ISSUE TITLE
AddTextComponentSubstringPlayerName nil value

### ISSUE THREAD

**Issue by flnyla** [citizenfx/fivem#1342]
Hello, 

In the past few days AddTextComponentSubstringPlayerName attempts to call a nil value. I have made no changes to scripts or the environment in the past 45 days, and this error started happening on the live server right away. I am unable to get any prompts/texts or help notifications to show up either, almost about 50% of all my scripts are erroring with this.
![err](https://user-images.githubusercontent.com/50728497/159722889-f6c3fc27-cff1-4575-9f93-5b232c233c27.png)
 That is one example of the error

**Comment by blattersturm** [comment]
This should've been fixed as of 97c2abf4c1d703610462fbfc38e6bcecd49e1ec5, but you didn't provide any info or reproduction steps, so one can't be sure.
