### ISSUE TITLE
Game doesn't trigger CEventNetworkEntityDamage

### ISSUE THREAD

**Issue by Ultra-Meloncrafter** [citizenfx/fivem#1347]
With the newest game build(2545) i don't have any Falldamage anymore, even gas station explosives won't work anymore.

**Comment by thorium-cfx** [comment]
I'm unable to reproduce this in build 2545, `CEventNetworkEntityDamage` triggers fine over here (with expected data) when falling to my death or driving into exploding gas pumps. You are using the `gameEventTriggered` event right?

**Comment by Ultra-Meloncrafter** [comment]
> I'm unable to reproduce this in build 2545, `CEventNetworkEntityDamage` triggers fine over here (with expected data) when falling to my death or driving into exploding gas pumps. You are using the `gameEventTriggered` event right?

how do you mean this, i have a script running which shows me all of the game events, right when they are triggering

**Comment by manups4e** [comment]
definitely something on your side as for me using latest build (2545) everything works fine

![image](https://user-images.githubusercontent.com/4005518/161399667-ff8196ff-f0e8-4dfd-b65c-b405cc14e37c.png)

**Comment by Ultra-Meloncrafter** [comment]
> I'm unable to reproduce this in build 2545, `CEventNetworkEntityDamage` triggers fine over here (with expected data) when falling to my death or driving into exploding gas pumps. You are using the `gameEventTriggered` event right?

or is it because of onesync legacy

**Comment by thorium-cfx** [comment]
> or is it because of onesync legacy

Hmm tried it, didn't make a difference. Seems like this is only on your side, unless others are having issues as well.

From my observation: `CEventNetworkEntityDamage` goes through the same channels as any other `CEventNetwork*` event, so if you get other network events then you should also get this one, unless of course you don't get damage ;)

For now we would need more information and a repro to investigate this further.

**Comment by Ultra-Meloncrafter** [comment]
> > or is it because of onesync legacy
> 
> Hmm tried it, didn't make a difference. Seems like this is only on your side, unless others are having issues as well.
> 
> From my observation: `CEventNetworkEntityDamage` goes through the same channels as any other `CEventNetwork*` event, so if you get other network events then you should also get this one, unless of course you don't get damage ;)
> 
> For now we would need more information and a repro to investigate this further.

i have read much about the damage not working on onesync, like you can't damage any other person, it's triggered randomly and other stuff like explosions. But i don't know how to reproduce this.

**Comment by Ultra-Meloncrafter** [comment]
> Just to make sure; can you post your script/code that's handling this event? (preferably a minimal example)

i found the issue it was an admin duty script which couldn't differentiate between aduty and non aduty

**Comment by thorium-cfx** [comment]
Haha okay. Happy to hear you got it solved!
