### ISSUE TITLE
Issue with replay editor (can't load clip)

### ISSUE THREAD

**Issue by AlexLeGamer** [citizenfx/fivem#1348]
Hi, l'm actually having issues its been 3 days, when l'm trying to load a clip on replay editor here's what i get https://prnt.sc/ua-1QRxyHUzZ while the server bought the mapping and it's all functionnal ingame, i tried everything, from removing my cache and record a new clip to changing my game build, and nothing works, do you have any solution to fix this issue?

**Comment by blattersturm** [comment]
The error message says exactly what is the case: 'you are using the replay editor, which is currently unsupported'.

**Comment by AlexLeGamer** [comment]
i able to read but is there any solution to make it supported or do you know when is gonna be supported?

**Comment by blattersturm** [comment]
No, there isn't any 'solution to make it supported', and if there would be any ETA it would say so in the message.
