### ISSUE TITLE
Erreur 1008

### ISSUE THREAD

**Issue by WGDionysos** [citizenfx/fivem#1361]
Bonjour, 
Quand je lance mon application un message d'erreur apparait.
Il s'agit de l'erreur 1008 
AppData/Local/FiveM/FiveM.app./bin/mono-2.0-sgen.dll 
Check your system for any conflicting software.

Pouvez vous m'aider s'il vous plait ??? 
Merci !

**Comment by blattersturm** [comment]
Le what?
