### ISSUE TITLE
Discord Rich Presence local player function problem 

### ISSUE THREAD

**Issue by Will1022** [citizenfx/fivem#1362]
**In the update that just came in, it basically tells discord rich presence how many players are "near you" that I don't necessarily want to use and some people may not want to use. Is it possible to somehow turn this feature off, or how could it be fixed so that it doesn't write out "nearby players?"**

This is the change I am talking about:
https://github.com/citizenfx/fivem/commit/ce4d89e1a9770ab0810560f3bfdb0a2d161ac218#diff-0160e06fb910fb302e7cc731be8f4f7bb43429369ddaba462eea9e3689607922

This is something that cannot be changed:
Picture: [https://i.imgur.com/MAtzWLc.png](url)

Looking forward to your reply, Will

**Comment by mickeygeecom** [comment]
This is correct. We're also already doing this ourself, by sending the 'total amount of players' to each client:
![image](https://user-images.githubusercontent.com/5321009/161373488-8b8228de-e577-47e9-af3f-e389201d86ab.png)
But the new implementation only shows known players in the 'infinity bubble' by the client.

**Comment by blattersturm** [comment]
There's no 'new implementation' for a player count, though... this is rather a bug, I'd presume related to the handling of `line1` and `line2` stuff, and would be a side effect of a fix for a bug where it would show the same line twice:

https://github.com/citizenfx/fivem/blob/ce4d89e1a9770ab0810560f3bfdb0a2d161ac218/code/components/discord/src/DiscordPresence.cpp#L75-L86

Do you have any example code for how you're overriding presence data?

**Comment by mickeygeecom** [comment]
This is how we're doing it:
```lua
local appid = 'app_id' -- Make an application @ https://discordapp.com/developers/applications/ ID can be found there.
local asset = 'discord-asset' -- Go to https://discordapp.com/developers/applications/APPID/rich-presence/assets
local RPname = ''
local user_id = 0
local onlinePlayers = 0

function SetRP() -- rich presence, not roleplay ;)
  SetDiscordAppId(appid)
  SetDiscordRichPresenceAsset(asset)
  SetDiscordRichPresenceAction(0, "Join server", "fivem://connect/socialrp.dk")
  SetDiscordRichPresenceAction(1, "Se hjemmeside", "https://socialrp.dk")
end

Citizen.CreateThread(function()
  SetRP()

  while true do
      local presence = onlinePlayers.." i byen -- "..RPname.. " ("..user_id..")"

      if RPname ~= "" and user_id ~= 0 then
        SetRichPresence(presence)
      end

    Citizen.Wait(1000)
  end
end)
```
Have stripped event updating the variables, as I suggest these are irrelevant.

**Comment by itismejoey** [comment]
I believe that line, showing 4 players in the photo, used to show the `sv_hostname` that you defined.
