### ISSUE TITLE
hackers using PlaySound at -1 sound_id 

### ISSUE THREAD

**Issue by xTalal4** [citizenfx/fivem#1368]
there is new hackers using PlaySound native and using -1 as sound id this will make the sound play for all players without stopping.

i hope you fix this

this is the code they are using:
PlaySound(-1, 'Checkpoint_Hit', 'GTAO_FM_Events_Soundset', true)
PlaySound(-1, 'Boss_Blipped', 'GTAO_Magnate_Hunt_Boss_SoundSet', true)
PlaySound(-1, 'Bomb_Disarmed', 'GTAO_Speed_Convoy_Soundset', true)
PlaySound(-1, 'All', 'SHORT_PLAYER_SWITCH_SOUND_SET', true)
PlaySound(-1, 'SELECT', 'HUD_MINI_GAME_SOUNDSET', true)
PlaySound(-1, 'Beep_Green', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', true)

**Comment by donkras** [comment]
well this can't be "fixed" as nothing is broken - legit scripts may use this native like this as well
