### ISSUE TITLE
Game crash on launching single player

### ISSUE THREAD

**Issue by ali-exacute** [citizenfx/fivem#1372]
NOTE : I am using Natural Vision Evolved on Fivem and nothing else

[Window Title]
Error GTA5_b2372.exe!sub_1405CB070 (0x104)

[Main Instruction]
GTA5_b2372.exe!sub_1405CB070 (0x104)

[Content]
An error at GTA5_b2372.exe!sub_1405CB070 (0x104) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: burger-potato-washington
Stack trace:
  GTA5_b2372.exe!sub_1405CB070 (0x104)
  GTA5_b2372.exe!sub_1405C24AC (0x5f)
  GTA5_b2372.exe!sub_1405BFFC0 (0x7c)
  GTA5_b2372.exe!sub_1415C71E0 (0x4bc)
  GTA5_b2372.exe!sub_1415C82C8 (0x9a)
  GTA5_b2372.exe!sub_140A417F8 (0x4f)
  rage-scripting-five.dll!JustNoScript (0x24b) (scrEngine.cpp:533)

[Expanded Information]
Crash signature: GTA5_b2372.exe+5CB174

[CfxCrashDump_2022_04_04_09_17_59.zip](https://github.com/citizenfx/fivem/files/8408379/CfxCrashDump_2022_04_04_09_17_59.zip)

**Comment by blattersturm** [comment]
> NOTE : I am using Natural Vision Evolved

Does it work fine _without_ 'Natural Vision Evolved'?

**Comment by ali-exacute** [comment]
Just tried , and still crashes even if i dont have ANY mods at all

**Comment by Disquse** [comment]
Works fine on my end, would need more details and preferably clear reproduction steps.

**Comment by ali-exacute** [comment]
I just launch my FiveM, let it update and go to main menu, then i will select STORY from main menu (i dont think it differ from F8 anyway)
Game start loading  and shows the default Fivem loading screen
then as soon as it goes to GTA loading screen , it crashes..
