### ISSUE TITLE
[Question] Load people and vehicles only in 80 radius

### ISSUE THREAD

**Issue by xrtw** [citizenfx/fivem#1377]
Hey, is it possible to load players and vehicles only 80 radius range? Like Alt:V has that feature?

**Comment by technetium-cfx** [comment]
Feature requests and other questions should go to the forums, we try to keep Github issues to actionable items. There is no need to compare against different mods without understanding your underlying problem first.

**Comment by blattersturm** [comment]
[SET_PLAYER_CULLING_RADIUS](https://docs.fivem.net/natives/?_0x8A2FBAD4), though still not sure why, or why you need to add a weird comparison.
