### ISSUE TITLE
People using the integrated http-server to ddos

### ISSUE THREAD

**Issue by Keyinator** [citizenfx/fivem#1378]
As above mentioned people use this part to ddos server.

When the ddos is executed you see:
``
[      net-tcp-server] error on connection: too many open files
[      net-tcp-server] Listening on socket failed - libuv error EMFILE.
``
Looking at some internal logs we get this information:
https://i.imgur.com/vniX0Nd.png

Basically the perpetrators are opening a connection and then continuously requesting "GET /".
(They are also occasionally requesting other paths so hard-coding is not a solution)
I would suggest implementing some rate-limiting into the instance (1/sec maybe?).

**Comment by blattersturm** [comment]
There is 'rate limiting into the instance' but that won't help if you don't have your OS set up correctly.
