### ISSUE TITLE
Recent FiveM Canary Update cause issues with blocking NUI DevTools (on Latest Unstable)

### ISSUE THREAD

**Issue by gewrutv** [citizenfx/fivem#1383]
Recent FiveM client updates have causes issues when using latest (Unstable) and blocking access to NUI DevTools. When a player using Latest Unstable connects to the server and loads in they are kicked by our DevTools blocking script. We are using a RegisterNUICallback(GetCurrentResourceName() as the callback to see if they are attempting to open NUI dev tools. Our script is based off of this resource https://github.com/QamarQ/nui_blocker. We are using this for a multitude of reasons but one is to protect the UI itself. I Believe this issue is caused by https://github.com/citizenfx/fivem/commit/0323e827defd9a656f2f3de9321fb3d1d09d5340.

**Comment by blattersturm** [comment]
This is intentional.
