### ISSUE TITLE
GlobalState initialization on server startup

### ISSUE THREAD

**Issue by fkk-cz** [citizenfx/fivem#1384]
1. Create a resource with a server script that only contains the following:
```lua
GlobalState.TestKey = 0
print("TestKey: " .. GlobalState.TestKey)
```
2. Add the resource to server.cfg
3. Start FXServer
```
[    c-scripting-core] Creating script environments for test
[         script:test] Error loading script server.lua in resource test: @test/server.lua:2: attempt to concatenate a nil value (field 'TestKey')
[         script:test] stack traceback:
[         script:test]  @test/server.lua:2: in main chunk
[    c-scripting-core] Failed to load script server.lua.
[ citizen-server-impl] Started resource test
```

Restarting the resource will 'fix' the problem.

```
cfx> ensure test
[ citizen-server-impl] Stopping resource test
[    c-scripting-core] Creating script environments for test
[         script:test] TestKey: 0
[ citizen-server-impl] Started resource test
```

I started running into this issue after updating to latest artifacts. Test was done on 5461.

**Comment by fkk-cz** [comment]
Seems like it's related to resource ordering - starting the `test` resource after a resource with a lot of globbed server scripts and GlobalState initializations will produce this error.

Starting the resource before that particular resource will yield no errors.

**Comment by thorium-cfx** [comment]
I managed to reproduce this, with and without setting a state in `GlobalState` in a previous resource.
Until further investigated and potentially fixed, delaying the initialization of these global states (e.g.: with `CreateThread`) works fine.
