### ISSUE TITLE
NUI pages incorrectly replaced with `gameconfig.xml` placeholder

### ISSUE THREAD

**Issue by ianfd** [citizenfx/fivem#1385]
Hey everyone,

since 10:00AM today we're facing a small issue. 
This text started to appear. We haven't changed anything in the last 18 hours. Until 3:00AM it worked perfectly fine, now we're facing this issue. It seems to be related to a UI. 

![Screenshot_2022-04-08_135109](https://user-images.githubusercontent.com/17109144/162430600-a96652cc-e50f-4966-b877-fd4d2009dd86.png)

**Comment by blattersturm** [comment]
This isn't 'completely random', and _please_ provide a repro.

**Comment by NecronomiconCoding** [comment]
> This isn't 'completely random' (rather some edge case as of [202dfc2](https://github.com/citizenfx/fivem/commit/202dfc2ff1110c615f49fb85ba3587b118fd1246)), and _please_ provide a repro, as with you providing no info at all this isn't actionable.

Hi,
I have attached the ressource that is causing the issue. (Me and @ianfd are working together on this)

https://drive.google.com/drive/folders/1_GIjwY8rtsTGFgoR1Q9xYbfm6_6s_93c?usp=sharing

**Comment by blattersturm** [comment]
Right, you need to add your .html/.css/.js files to `file` too. This seems like user error, instead.

**Comment by NecronomiconCoding** [comment]
Thanks @blattersturm 

Fixed by adding them as file
