### ISSUE TITLE
Weird OAL behavior

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/fivem#1386]
I can't really explain what the behaviour is but I can give examples

When not using OAL
```lua
local coords = GetEntityCoords(PlayerPedId())
local ped = CreatePed(0, `a_m_m_indian_01`, coords, 100, false, false)
```
This works fine and the ped spawns, but when I use OAL (OAL as in `use_fxv2_oal 'yes'` in the manifest) with that code, then it doesn't work anymore, the ped won't spawn

It would only spawn with OAL was enabled when I defined each variable that it requires instead of letting the native unpack
```lua
local coords = GetEntityCoords(PlayerPedId())
local ped = CreatePed(0, `a_m_m_indian_01`, coords.x, coords.y, coords.z, 100, false, false)
```
Now it'll spawn when using OAL

**Comment by AvarianKnight** [comment]
Isn't this expected behavior? OAL doesn't do automatic vector expansion according to an [older thread](https://forum.cfx.re/t/lua-5-4-performance-issues-or-just-potato/4755067/3)

**Comment by nikez** [comment]
Yeah, what Avarian said. It's working as designed.

**Comment by blattersturm** [comment]
Explicit vector expansion is planned for a potential future API set change. At the time being, however, there indeed isn't (and can't be) any vector expansion here.

**Comment by BerkieBb** [comment]
Got it, thanks for the information!
