### ISSUE TITLE
Server randomly stops responding (HB Failed)

### ISSUE THREAD

**Issue by lilmonkeylv** [citizenfx/fivem#1390]
My server randomly crashes with the error in the txAdmin Log: **HB:16|HC:1) FXServer is not responding. (HB Failed)**
RAM is never over 70% and in the log file it says this right before the restart:
```
terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc
```
![image](https://user-images.githubusercontent.com/62300189/162619748-217cc241-28de-4399-b9e6-d80d11d81783.png)

This has been happening for about 5 days now and I can't seem to fix it.

**Comment by blattersturm** [comment]
This isn't a support section. Non-actionable reports **don't go here.** This isn't actionable, as the requirement is to have '_your_ server', which nobody but _you_ does.

Closing and locking.
