### ISSUE TITLE
SmashVehicleWindow, RemoveVehicleWindow not being able to target windshields

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1391]
WINDSCREEN IDs: 0-1 can't be smashed or removed by script for some reason.
Just doesn't work. Would be nice to have that fixed or documented.

**Comment by 4mmonium** [comment]
I could destroy `0, 1, 2, 3` on a (Dundreary) Landstalker, could you please provide some way to repro this? Thanks!

Here's my code sample:
```
RegisterCommand("sw", function(source, args, rawCommand)
    SmashVehicleWindow(GetVehiclePedIsIn(GetPlayerPed(-1), false), tonumber(args[1]))
end, false)
```

**Comment by Disquse** [comment]
@gottfriedleibniz notes are correct. Previous fix was incorrect and was leading to a described issue.
