### ISSUE TITLE
Cancelling game storage update allows for exceeding 100% and gives unknown error.

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#1392]
Summary:

If you cancel the game data download mid download and then start it again without closing FiveM it will display >100% download status due to the fact that the target download size decreases the second time.

Additionally it will say "Changing game build failed: An unknown error occurred" when you cancel it instead of something more descriptive.

Repro steps:

1. Clear game-storage or identify a version of the game you do not have downloaded already.
2. Connect to a server with a non 2545/version you already have downloaded (i am using the b2372 test server)
3. Let the game cache download proceed
4. Cancel during, past halfway to make effect easily noticeable.
5. Try and join the server again
6. Let the download finish and observe it go past 100%

https://user-images.githubusercontent.com/28872095/162640027-efa2c52c-5ac0-4ee8-8cdf-7f1e33b32ac1.mp4

**Comment by blattersturm** [comment]
Yeah, I can confirm this occurs.

However, after investigation,

> will display >100% download status due to the fact that the target download size decreases the second time.

is actually not the underlying reason, instead, the reason is the remaining file being in the download queue twice. A bit more difficult to fix as such, but should be done soon.
