### ISSUE TITLE
Faim et soif

### ISSUE THREAD

**Issue by ExoKalork** [citizenfx/fivem#14]
Faim et soif qui diminue graduellement, avec des items qui permettent de régénérer ces valeurs

Hey @WeAreFailure, ca fais quoi quand on tombe a 0

**Comment by ExoKalork** [comment]
Oh shit, wrong github, I'm so sorry xD Can you remove this please ?

**Comment by ifarbod** [comment]
@ExoKalork Just close it yourself.
