### ISSUE TITLE
feat: add pedaccuracy getter natives

### ISSUE THREAD

**Issue by mindiw01** [citizenfx/fivem#1402]
A lot of people are modifying their game files to increase the clip size, damage, accuracy, recoil, scope type of the weapon game components. It is not possible to 'override' the base components nor detect it so these natives will be useful to kick the players with modified game files.

pedaccuracy.meta
```
<?xml version="1.0" encoding="UTF-8"?>

<sPedAccuracyModifiers>
  <PLAYER_RECOIL_MODIFIER_MIN value="0.800000" />
  <PLAYER_RECOIL_MODIFIER_MAX value="1.000000" />
  <PLAYER_RECOIL_CROUCHED_MODIFIER value="0.500000" />
  <PLAYER_BLIND_FIRE_MODIFIER_MIN value="2.00000" />
  <PLAYER_BLIND_FIRE_MODIFIER_MAX value="4.000000" />
  <PLAYER_RECENTLY_DAMAGED_MODIFIER value="0.300000" />
  <AI_GLOBAL_MODIFIER value="2.000000" />
  <AI_TARGET_IN_COMBAT_ROLL_MODIFIER value="0.200000" />
  <AI_TARGET_COMING_OUT_OF_COVER_MODIFIER value="0.400000" />
  <AI_TARGET_IN_COVER_MODIFIER value="0.400000" />
  <AI_TARGET_WALKING_MODIFIER value="0.6" />
  <AI_TARGET_RUNNING_MODIFIER value="0.3" />
  <AI_TARGET_IN_AIR_MODIFIER value="0.3" />
  <AI_TARGET_DRIVING_AT_SPEED_MODIFIER value="0.3" />
  <AI_BLIND_FIRE_MODIFIER value="0.3" />
  <AI_DISTANCE_FOR_MAX_ACCURACY_BOOST value="5.000000" />
  <AI_DISTANCE_FOR_MIN_ACCURACY_BOOST value="15.000000" />
  <AI_HURT_ON_GROUND_MODIFIER value="0.10000" />
  <AI_HURT_MODIFIER value="0.5" />
  <AI_PROFESSIONAL_PISTOL_VS_AI_MODIFIER value="2.500000" />
</sPedAccuracyModifiers>
```

**Comment by blattersturm** [comment]
Nope. This was requested even and I already said at those points that adding a plethora of 'getter natives' is not a substitute or any proper alternative for a 'pure mode' which is what you are actually requesting.

Implementing a spam of getters as a PR with the main use case being 'anti abuse' (which has better ways to fix it) still won't get it accepted.

**Comment by blattersturm** [comment]
.. oh this is an issue and not a PR even, making it even more weird as to _why are you ignoring the past responses to this kind of request???_

**Comment by blattersturm** [comment]
Hell. **You** already posted an issue about this (#1375) that got a reply saying this place is not for feature requests. 

Yet, you are again posting a feature request.. right here.. the same one even.
