### ISSUE TITLE
NUI files get corrupted when combined with data files in one resource

### ISSUE THREAD

**Issue by tens0rfl0w** [citizenfx/fivem#1405]
## Description:
In the past days we experienced some issues related to one of our NUIs rendering completely broken for all users on some join events to our servers:

![html-mount](https://user-images.githubusercontent.com/57523343/163467624-1c3ac65d-1c9d-43e2-accb-1ec4b1c43f94.png)

As I checked the affected NUI in devtools I found out that when the NUI renders incorrectly either the HTML, CSS, or JS file gets loaded corrupted as seen below:

![js-mount](https://user-images.githubusercontent.com/57523343/163467949-9d44d980-5e5b-4b58-b1fd-cf6fbdbe59f3.png)

The only NUI that is affected by this is included in a resource where we also mount data_files and stream game files, so after some tries to isolate the issue further it appears to be related to having NUI and data files in one resource combined. Sometimes data files appear to get mounted as actual HTML, CSS, or JS files instead of the correct ones.

## Reproduction:
I created a repro including some data files we use on our server, if everything loads correctly the text should render centered saying 'THIS TEXT SHOULD SHOW IN WHITE...' and in white color, otherwise something got mounted improperly.
As this issue isn't triggered every time, if everything appears right after joining, try to 'ensure' the resource for some time or re-join and after some tries, it should break as shown above.
[Resource for reproduction](https://github.com/citizenfx/fivem/files/8492024/reproNUI.zip)
___
#### Additional info:
It appears like the frequency of this issue is heavily influenced by the order of the files in the 'files' tag in the fxmanifest and also by how many resources you have and when this resource is loaded on join.
Tested on both Canary and Stable channel, no difference.

**Comment by blattersturm** [comment]
I think one of these reports was somewhere before but it might've either gotten lost or it didn't reproduce by the time I got around to checking - mentioning if it differs based on the used server platform could be helpful.

Might also be another case of NUI scheme handler race conditions, I'd hope not though :(

**Comment by tens0rfl0w** [comment]
> mentioning if it differs based on the used server platform could be helpful.

This issue was originally discovered on an instance running Windows Server 2019 on bare metal, also tested on a VM with Windows Server 2022.

Additionally, I just tested this on a Linux VM running Ubuntu and the issue seems to be consistent over all server platforms.

**Comment by gottfriedleibniz** [comment]
I remember looking at this way-back-when and what I had noted seems to be corroborated by the 'mount data_files and stream game files' statement in initial issue (never verified, so ymmv):

There is some weird lock usage, or lack thereof, in VFSRagePackfile that may lead to potential race conditions between Chrome_IOThread and MainThrd. This issue may exist in the other Packfile implementations.

**Comment by blattersturm** [comment]
In reply to @gottfriedleibniz:
> I remember looking at this way-back-when and what I had noted seems to be corroborated by the 'mount data_files and stream game files' statement in initial issue (never verified, so ymmv):
> 
> There is some weird lock usage, or lack thereof, in VFSRagePackfile that may lead to potential race conditions between Chrome_IOThread and MainThrd. This issue may exist in the other Packfile implementations.

Right, that would make sense as to why this _didn't_ improve with added locking in scheme handlers, if it's rather a case of handle allocation in the VFS implementations. That also does make me wonder if the game's device implementations are even thread-safe when it comes to allocating handles. :/

**Comment by gottfriedleibniz** [comment]
> game's device implementations are even thread-safe

Seems to be. Well, at least from a cursory glance at IV/V/RDR's impls. 

This issue looks more typo-ish than anything else.

**Comment by blattersturm** [comment]
A quick fix removing the _blatant_ race condition in VFSRagePackfile didn't seem to improve this, so back to investigation it goes.

**Comment by blattersturm** [comment]
The handle indeed seems to reference the correct entry, with both offset _and_ length matching. That implies some lower-level Read call fails.

**Comment by blattersturm** [comment]
Successfully deduced the underlying issue.
