### ISSUE TITLE
Serverside created vehicles spawn in the routing bucket of the last serverside spawned vehicle, sometimes do not even spawn

### ISSUE THREAD

**Issue by 0xLuca** [citizenfx/fivem#1407]
When i spawn an vehicle serverside and then set it to the routing bucket of the player who issues the command (assuming that the routing bucket of the player is not 0):

```lua
RegisterCommand('testspawn1', function(source, args)
    local ped = GetPlayerPed(source)
    CreateVehicle(args[1], GetEntityCoords(ped), GetEntityHeading(ped), true, false)
    SetEntityRoutingBucket(vehicle, GetPlayerRoutingBucket(s))
end)
```

the vehicle gets created, and its in the right bucket. 
When i create another vehicle directly after the first one, without setting its bucket:

```lua
RegisterCommand('testspawn2', function(source, args)
    local ped = GetPlayerPed(source)
    CreateVehicle(args[1], GetEntityCoords(ped), GetEntityHeading(ped), true, false)
end)
```

it is visible to the player! This means, that **the vehicle is in fact being spawned in the routing bucket of the last vehicle i spawned**.

---

In my garage script, in a loop of e.g. 20 vehicles, i spawn the vehicle, then set its routing bucket, then do the same process for the next vehicle. Sometimes, the vehicle does exist on the server side (`DoesEntityExist` returns `true`), has the right routing bucket but the clients in the same bucket do **NOT** see the vehicle.
This issue appears randomly, i think onesync does not do its job correctly.

I already had onesync issues in another script, when trying to spawn props (they get created, some clients see them, some do not. Sometimes the server creates a prop, only one client sees them and for the client they only exist locally (isNetworked returns false)). Would be nice if these issues could be fixed.

**Comment by blattersturm** [comment]
Do you have a _full_ repro for this? So far I only see code snippets, no steps, and a lot of complaining and blaming.

This looks like something that was already reported before and at that time there also was no repro: https://forum.cfx.re/t/onesync-ghost-vehicle/4783063

**Comment by blattersturm** [comment]
Also, does this occur with CreateAutomobile? CreateVehicle at this time is inherently flawed and should not be used, however it can't be compatibly reimplemented to not be broken, and with no repro for issues that occur these issues can't be fixed either.

**Comment by blattersturm** [comment]
Also, why are you 'reporting' three unrelated issues in one report, of which only one states a repro (which is also wrong as it references a nonexistent variable?!), the other two have progressively less info, and the connection between them seems even more vague???

Closing this as it is very much not actionable.

**Comment by 0xLuca** [comment]
> Do you have a _full_ repro for this? So far I only see code snippets, no steps, and a lot of complaining and blaming: without any repro or other info (correlations, hints, logs, _anything_) such issues - especially if as you say 'the issue appears randomly' - can not be fixed, no matter how much you complain and try to place blame like 'onesync does not do its job correctly' or 'I already had onesync issues'... if it appears 'randomly', at least providing a repro involving, say, doing the same operation 50, or 100, or however many times to try to get it to occur would be needed.
> 
> This looks like something that was already reported before and at that time there also was no repro: https://forum.cfx.re/t/onesync-ghost-vehicle/4783063

I fully understand your concern about reproduction and me seemingly just blaming onesync.

The first issue (vehicles getting created in the routing bucket of the last one) is fully reproducable, just put these two commands into one serverside script, set your own routing bucket to something other than 0 and execute the first one, then the second one, the second vehicle will be in the routing bucket of the first one too.

**Comment by blattersturm** [comment]
The design of CreateVehicle is inherently incompatible with routing buckets, so just don't use RPC creation functions if you use any routing buckets.

Just another nail in the coffin of RPC creation natives tbh.

**Comment by blattersturm** [comment]
Will reopen or make a duplicate issue for the specific concern when I can and am not hurting like hell from toothache being worsened by the stress induced by yet another fucking confusing issue report causing more fear of response or random blame/comparison/threats regarding Russian abuse mods.

**Comment by 0xLuca** [comment]
> Will reopen or make a duplicate issue for the specific concern when I can and am not hurting like hell from toothache being worsened by the stress induced by yet another fucking confusing issue report causing more fear of response or random blame/comparison/threats regarding Russian abuse mods.

I totally understand you. (or at least i try)

I will create new issues for my problems, one for each, after i have a full reproduction.

I searched for `CreateAutomobile` in the native documentation, but cannot find any information about this native, can you provide some?

**Comment by blattersturm** [comment]
I think it was unfinished and never got a definition as eventually it had to replace CreateVehicle, look on the forums or so for snippets.

**Comment by cm8263** [comment]
For anyone searching for how to use `CREATE_AUTOMOBILE`.
***
LUA
```lua
local createAutomobile = GetHashKey("CREATE_AUTOMOBILE")

function CreateAutomobile(vehicleHash, position, heading)
  local vehicle = Citizen.InvokeNative(createAutomobile, vehicleHash, position, heading)
end

local vehicle = CreateVehicle(`bison`, vector3(1, 2, 3), 180.0)
```
***
C#
```csharp
Hash CREATE_AUTOMOBILE = (Hash)API.GetHashKey("CREATE_AUTOMOBILE");

Entity CreateAutomobile(string model, Vector3 position, float heading) => new Vehicle(Function.Call<int>(CREATE_AUTOMOBILE, API.GetHashKey(model), position.X, position.Y, position.Z, heading));

Entity vehicle = CreateAutomobile("bison", new Vector3(1f, 2f, 3f), 180f);
```
