### ISSUE TITLE
StartFindExternalKvp Issue

### ISSUE THREAD

**Issue by freedy69** [citizenfx/fivem#1409]
I seem to have an issue where StartFindExternalKvp key results are cut off when used in scripts. I've currently only tried this with the handling-editor resource. This is the outcome: https://i.imgur.com/3gChyVj.png, It's supposed to be handling_s13 1, handling_supra 1 etc, but the text seems cut off in my current resource. What seems weirder is that when i tried the same code with the runcode resource, i got this result: https://i.imgur.com/EhVWxm8.png

This is the code i currently use, If i'm doing something wrong then I apologise
```lua
function LoadExternalHandlingPresets()
    local currentResult = ''
    local searchHandle = StartFindExternalKvp('handling-editor', 'handling_')
    if searchHandle == -1 then
        print('invalid handle')

        return
    end

    while currentResult do
        currentResult = FindKvp(searchHandle)

        if currentResult ~= '' and currentResult then
            print('Found external preset')
            print(currentResult)
        end
    end

    EndFindKvp(searchHandle)
end```

**Comment by blattersturm** [comment]
Do you happen to have an affected `kvs/` dir for this repro?

**Comment by freedy69** [comment]
> 

what do you mean, do you want me to send my kvs folder?

**Comment by blattersturm** [comment]
Either that, or provide a repro for writing values from scratch that replicate this issue, yes.

**Comment by freedy69** [comment]
> Either that, or provide a repro for writing values from scratch that replicate this issue, yes.

try this: https://drive.google.com/drive/folders/1PQHAIlLE4nB0NFjBb-VA_ueThiGy9wHt?usp=sharing
