### ISSUE TITLE
Broken natives

### ISSUE THREAD

**Issue by MatinDark** [citizenfx/fivem#1412]
Since new update  on release channel `CreateMpGamerTagWithCrewColor` and `IsMpGamerTagFree(PlayerId())` always return false

also `CreateMpGamerTagWithCrewColor`  does not create gamer tags anymore

**Comment by blattersturm** [comment]
Do these have the correct definition in citizenfx/natives? If not, fix them there.

**Comment by stephanembl** [comment]
Hello,

I can confirm some natives are not working for us either. First bug reports from our users came in about 8 hours ago.

For example `0x74C0E2A57EC66760` (`GetShopPedComponent`) and `0x5D5CAFF661DDF6FC` (`GetShopPedProp`).

> Do these have the correct definition in citizenfx/natives?

They're documented in the natives docs if that's what you mean.

Those were working fine before the latest release, and their definition didn't change or at least it was not documented, so I don't think an example would help you.

> Also, why did you nor anyone else report this for the weeks this fix has been in canary/beta?

Why does this matter? People are reporting it now. It shouldn't be a surprise that once something hits production, it'll get tested by more people, and unreported stuff will show up. 

Just throwing it out there, I see this in the changelog:
> Reduce memory usage by ~30 MB by not loading natives.zip multiple times.

And now some natives seem broken, so maybe there's a link? Maybe not, but still we're having some issues with some natives.

**Comment by gottfriedleibniz** [comment]
> ... Example code would also help

Three (of four) natives referenced have void return types and I *suspect* (example required, see quote above) these scripts have been relying on the incorrect behaviour in the Lua native call handler.

**Comment by stephanembl** [comment]
> Three (of four) natives referenced have void return types and I _suspect_ (example required, see quote above) these scripts have been relying on incorrect behaviour in the Lua native call handler.

That's actually correct. Although the docs for `GetShopPedComponent` references a return value, digging in the typings definition the native actually have a void return type, and we missed that.

Thanks for the pointers!

**Comment by MatinDark** [comment]
```
local tagsCache = {}


Citizen.CreateThread(function()
    while true do

        for _, player in ipairs(GetActivePlayers) do
            local id = GetPlayerServerId(player)
            local data = tagsCache[id]

            if not data then
                tagsCache[id] = {
                    id = id,
                    name = GetPlayerName(player),
                    talking = NetworkIsPlayerTalking(player)
                }

                data = tagsCache[id]
            else
                data.talking = NetworkIsPlayerTalking(player)
            end

            if data.tag and not IsMpGamerTagActive(data.tag) then
                RemoveMpGamerTag(data.tag)
                data.tag = CreateMpGamerTagWithCrewColor(player, ('[%s] %s'):format(data.id, data.name), false, false, "", 0)
            elseif not data.tag then
                data.tag = CreateMpGamerTagWithCrewColor(player, ('[%s] %s'):format(data.id, data.name), false, false, "", 0)
            end

            -- Player Gamer Tag
            SetMpGamerTagVisibility(data.tag, 0, true)
            SetMpGamerTagAlpha(data.tag, 0, 200)
            -- Tallking
            SetMpGamerTagAlpha(data.tag, 4, 255)
            SetMpGamerTagColour(data.tag, 4, 18)
            SetMpGamerTagVisibility(data.tag, 4, data.taling)

        end
    
        Citizen.Wait(1000)
    end
end)
```

It's an example code for ` CreateMpGamerTagWithCrewColor` I have been using for almost a year since the last update on the production channel and it was working fine

**Comment by blattersturm** [comment]
> Those were working fine before the latest release, and their definition didn't change or at least it was not documented, so I don't think an example would help you.

An example would still help as it would show what the expected behavior is.

> Why does this matter? People are reporting it now. It shouldn't be a surprise that once something hits production, it'll get tested by more people, and unreported stuff will show up.

It matters because if this were caught at any point before, it wouldn't have broken in production. As a server owner, you're _expected_ to use canary/beta in order to catch unintended changes early. In fact, with 15% of people for _whatever_ reason using canary/beta, I'm rather surprised that only now people start noticing and asking.

> Just throwing it out there, I see this in the changelog:
> 
> > Reduce memory usage by ~30 MB by not loading natives.zip multiple times.
> 
> And now some natives seem broken, so maybe there's a link? Maybe not, but still we're having some issues with some natives.

Unrelated entirely.

This is rather an effect of a security fix \+ relying on incorrect/unintended behavior.

Then, from the comment below:
```lua
                data.tag = CreateMpGamerTagWithCrewColor(player, ('[%s] %s'):format(data.id, data.name), false, false, "", 0)
```

`CREATE_MP_GAMER_TAG_WITH_CREW_COLOR` is actually not meant to return anything at all, this code is as such wrong. Sadly, returning the old behavior would also return the old security vulnerability.

This call _incorrectly_ would return the first argument in the result field originally, so replacing use of `data.tag` with `player` would be the same.

**Comment by MatinDark** [comment]
I have been using this  to create gamer tags for a long time because it was more reliable and stable because `CreateFakeMpGamerTag` would create a tag on the ped, not the player and the tag disappear on ped change and we had to recreate it,  I don't have any idea what those changes are, but they broke a working native which was [documented](https://docs.fivem.net/natives/?_0x6DD05E9D83EFA4C9)

And it was returning the handle of created tag, since yesterday so we could delete/modify the tag, it doesn't make sense it was not supposed to return anything, so how people should modify that tag e.g hide or modify the tag label?

But the problem is not that that native does not work at all and does not create the tag at all

**Comment by mythicalbro** [comment]
> I have been using `CreateMpGamerTagWithCrewColor` to create gamer tags for a long time because it was more reliable and stable
> 
> `CreateFakeMpGamerTag` would create a tag on the ped, not the player and the tag disappear on ped change and we had to recreate it, I don't have any idea what those changes are, but they broke a working native which was [documented](https://docs.fivem.net/natives/?_0x6DD05E9D83EFA4C9)
> 
> And it was returning the handle of created tag, since yesterday so we could delete/modify the tag, it doesn't make sense if it was not supposed to return anything, so how people should modify that tag e.g hide or modify the tag label?

You can still use `CreateMpGamerTagWithCrewColor`. The created gamer tag will have the same ID as the player, so use the player ID as the gamer tag ID instead of the return value of `CreateMpGamerTagWithCrewColor`. It's also written in the documentation.

**Comment by blattersturm** [comment]
> but they broke a working native which was [documented](https://docs.fivem.net/natives/?_0x6DD05E9D83EFA4C9)

The native was documented as not having a return value. Both assuming it had one, but also how it did have one, is incorrect.

> And it was returning the handle of created tag

It wasn't. It was returning the first argument passed, which was the player ID, which is also the 'handle of the tag' for these non-'fake' entries.

**Comment by MatinDark** [comment]
Now it makes sense, let me try it out but last I checked it didn't create tag

**Comment by MatinDark** [comment]
It's working fine if use the player id as the handle of the tag, and the reason I thought that native is not working at all is, I was using the wrong handle to add components to that tag and make it visible, I owe an apology to you all for this miss understanding and wasting your time

**Comment by manups4e** [comment]
well.. on GetShopPedComponent i'm getting 
`SCRIPT ERROR in task continuation: System.Security.VerificationException: Error verifying TheLastPlanet.Client.Core.Utility.ShopPed:_GetShopPedComponent (uint): Invalid type (Complex) at stack for conversion operation. Numeric type expected at 0x001f`

using C# 


        [StructLayout(LayoutKind.Explicit, Size = 0x88)]
        private unsafe struct UnsafePedComponentData
        {
            [FieldOffset(0x00)] private int lockHash;

            [FieldOffset(0x08)] private int hash; // componentHash

            [FieldOffset(0x10)] private int locate;

            [FieldOffset(0x18)] private int drawable;

            [FieldOffset(0x20)] private int texture;

            [FieldOffset(0x28)] private int f_5; // price

            [FieldOffset(0x30)] private int componentType;

            [FieldOffset(0x38)] private int f_7;

            [FieldOffset(0x40)] private int f_8;

            [FieldOffset(0x48)] private unsafe fixed sbyte gxt[0x40];

            public PedComponentData GetData()
            {
                /*string label;
				fixed (sbyte* ptr = gxt)
				{
						label = new string(ptr);
				}
				return new PedComponentData(lockHash, hash, locate, drawable, texture, f_5, componentType, f_7, f_8, label);*/
                string label;
                fixed (sbyte* ptr = gxt)
                {
                    byte[] bytes = new byte[64];
                    int index = 0;
                    for (sbyte* counter = ptr; *counter != 0; counter++)
                    {
                        bytes[index++] = (byte)*counter;
                    }
                    label = System.Text.Encoding.UTF8.GetString(bytes, 0, index);
                }
                return new PedComponentData(lockHash, hash, locate, drawable, texture, f_5, componentType, f_7, f_8, label);
            }

        }

        //Global_4267002[Global_4267254] 
        //Global_4267368 = current category? check line 157959
        private static PedComponentData _GetShopPedComponent(uint componentHash)
        {
            UnsafePedComponentData data;
            unsafe
            {
                Function.Call(Hash.GET_SHOP_PED_COMPONENT, componentHash, new IntPtr(&data).ToInt64());
            }
            return data.GetData();
        }

        public static PedComponentData GetShopPedComponent(uint componentHash)
        {
            return _GetShopPedComponent(componentHash);
        }

**Comment by blattersturm** [comment]
@manups4e 

> `private unsafe struct`

I _did_ tell you when you mentioned this worked this wasn't intended and was on the chopping block. 😉

**Comment by blattersturm** [comment]
I'll close/lock this issue as any actionable tasks will likely have to be split up in multiple issues.

For continued discussion, use the forums.
