### ISSUE TITLE
AttachEntityToEntity,  NetworkGetEntityOwner

### ISSUE THREAD

**Issue by KiLaF** [citizenfx/fivem#1413]
So when you attach a entity to another player, and you try to get the owner of that attached entity, its gives the id of the other player that didn't even created it

**Comment by MRV6** [comment]
The owner is not always the client who created the entity, looks like a normal behaviour.

**Comment by KiLaF** [comment]
why does infect that, like why doesn't it just give to the one who run the code to create the entity

**Comment by blattersturm** [comment]
I'm not sure what makes this an actionable code issue so I'm closing it. 

Did someone miss out on https://docs.fivem.net/natives/?_0x1E546224 or so?
