### ISSUE TITLE
script deadloop

### ISSUE THREAD

**Issue by kFxDaKing** [citizenfx/fivem#1415]
Hello, probably after last client update (2 days ago) like 20% of your please are crashing while loading into our server with this error.
Mostly players with slower computers.

![image](https://user-images.githubusercontent.com/52855882/164496683-248f4229-6edb-4d80-b9d9-b3f28649f9fb.png)

There was nothing changed on server side past 7 days, we are using default chat resource provided by fivem.

Looks like last client update added some timer, and if players is loading longer then it gives the crash. (Could be problem for players with slower PC)
We have 200+ online, but like 30 players cant connected, 2 days ago they connected without any problems.

Windows: v4.14.0 atop FXServer 5504, tried more versions without luck.

Here is crash dump
[CfxCrashDump_2022_04_21_15_01_47.zip](https://github.com/citizenfx/fivem/files/8532402/CfxCrashDump_2022_04_21_15_01_47.zip)

**Comment by blattersturm** [comment]
... huh? Nothing in this regard was touched at all recently, no idea what 'some timer' would be - do you happen to have any repro case or a server to join that breaks like this?

**Comment by blattersturm** [comment]
Right, a server IP/ID to try to join might help instead so we can at least try to see what may lead to this (likely some unrelated changes may have slowed down a code path used with many commands and/or resources) worsening on slow PCs.

**Comment by kFxDaKing** [comment]
Here is ETW trace of player that have problem with connecting to the server:

- He started FiveM
- Started trace
- Connected to the server
- Was recording untill he crashed in loading screen.

Link: https://drive.google.com/file/d/1AKxRkX0MxZZE7LlFFZsx8m4eGAwyDDnY/view?usp=sharing

**Comment by kFxDaKing** [comment]
So we were debuging it whole day, and we found that there must be something like "time limit" for connection.

When loading takes too long, it crashes.

We disabled all cars, which we havent touch like month, and they are okay and those players with problems can now connect, because loading is faster.

Also the error say that:
![image](https://user-images.githubusercontent.com/52855882/164541076-7b4d379a-17ad-49a7-9467-adac40a2cc08.png)

**Comment by blattersturm** [comment]
> We have a lot of resources, but most of them are cars, that arent all in one pack

Each of these 'car' resources does seem to include a _giant_ Lua script that seems to affect load performance a lot.

**Comment by kFxDaKing** [comment]
Those cars doenst include any Lua scripts, only __resource.lua, that have 1kb, we are trying to put them today al in one pack.

**Comment by kFxDaKing** [comment]
ETW trace is from beggining of loading untill crash in loading, which can be halfway.

**Comment by kFxDaKing** [comment]
It seems we fixed it with putting cars in a pack, and your commit helped some players too.
