### ISSUE TITLE
Crash on drawing an outline on peds

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/fivem#1425]
So whenever you use `SetEntityDrawOutline` on a ped (player, spawned or npc doesn't matter) it crashes you.

This is the code I used to produce this crash, the ped spawns, then about 1-2 seconds after that it crashes me.
```lua
CreateThread(function()
    local model = `a_m_m_indian_01`
    RequestModel(model)
    while not HasModelLoaded(model) do
        Wait(10)
    end
    local newPed = CreatePed(0, model, GetEntityCoords(PlayerPedId()), GetEntityHeading(PlayerPedId()), false, false)
    FreezeEntityPosition(newPed, true)
    SetEntityDrawOutline(newPed, true)
end)
```

Here is the crash log I got if that is of any help, my server is on artifact 5503 and game build 2545
![image](https://user-images.githubusercontent.com/82737367/165151271-d7fddad3-e7fd-4a2b-9b1e-0cb265944259.png)

**Comment by ItsANoBrainer** [comment]
Can confirm this issue. Tested on client version 5503 and server build 5531.

My reproduction:
```lua
RegisterCommand('outline', function()
    SetEntityDrawOutline(PlayerPedId(), true)
end)
```

Crash Dump:
[CfxCrashDump_2022_04_25_18_47_06.zip](https://github.com/citizenfx/fivem/files/8557168/CfxCrashDump_2022_04_25_18_47_06.zip)

**Comment by gottfriedleibniz** [comment]
Can also confirm:

```lua
print([[
The documentation states:

"Draws an outline around a given entity. This function supports SDK infrastructure and is not intended to be used directly from your code."
]])
```

**Comment by blattersturm** [comment]
This native is not intended to be used directly from your code, see the docs: https://docs.fivem.net/natives/?_0x76180407

Ped draw handler is not supported because it requires additional setup and the original use of the function doesn't need it to work for vehicles/peds.

**Comment by BerkieBb** [comment]
That makes sense, what is the original use of the function? If you don't mind me asking.
