### ISSUE TITLE
Difference in hashes between Lua and JS

### ISSUE THREAD

**Issue by nikez** [citizenfx/fivem#1427]
I encountered this ~~"issue"~~ yesterday.. Thought I'd at least inform that this exists, perhaps it's already known or working as designed. I've yet to try C#, but I suspect that it'll behave the same as JS (?).

```js
on('populationPedCreating', (x, y, z, model, setters) => {
    console.log('JS', model, model & 0xffffffff, GetHashKey('a_c_seagull'), GetHashKey('a_c_seagull') & 0xffffffff);
    // JS 3549666813 -745300483 -745300483 -745300483
});
```
```lua
AddEventHandler('populationPedCreating', function(x, y, z, model, setters)
    print('LUA', model, model & 0xffffffff, GetHashKey('a_c_seagull'), GetHashKey('a_c_seagull') & 0xffffffff)
    -- Lua    3549666813    3549666813    -745300483    3549666813
end)
```

I could be doing something fundamentally wrong but in JS I'd have to check for `model & 0xffffffff == GetHashKey('a_c_seagull')` and in Lua I'd have to do `model == GetHashKey('a_c_seagull') 0xffffffff` to get a match.

**Comment by blattersturm** [comment]
Both languages handle integers and bitwise operations differently, even outside of 'our' runtime.

In Lua, integers are signed 64-bit and bitwise operations are also 64-bit.

In JS, there are no integers*, only 64-bit floating point values (of which 53 bits of effective integer precision exists), and bitwise operations are on 32-bit _signed_ integers.

Effectively, this means that in Lua, truncating the lowest 32 bits will result in an unsigned 32-bit integer (as there is no sign extension as such), but in JS, truncating the lowest 32 bits will result in a sign-extended value.

*) BigInt exists but it's unrelated in this context.

**Comment by nikez** [comment]
Thank you very much for the explanation! I assumed it was something similar, but didn't really have an explanation for it.
