### ISSUE TITLE
Rockstar Editor freezes on first frame of export

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#1438]
Reproduction steps:
1. Add script to server
2. Join server
3. Capture a rockstar editor clip
4. Open rockstar editor (either via game or from main menu)
5. Add clip to project
6. Save project and attempt to export
7. Observe crash

Tested on: 
Unstable/Canary: 2612, 2545, 2372, 1604
Beta: 2612
Stable: 2545

- Unstable/Canary:
2612:
Report ID (Opened via native): si-ae45c11a721b4e898c767612a7d4e0b7
(Opened via main menu): si-a8ec86d6dc3149a28e38288d53e5be1e
2372:
si-c051d29f6cc64757b3b362a162fee8cb
1604:
si-8dd9ec2dd2c74eb5a5355201a6db894d

- Stable:
2545: 
Report ID: si-d89196b084224a318988bcb2852d9895

This occurs both when accessed via ActivateRockstarEditor() and using the shortcut in the main menu.

Resource used to control rockstar editor in game:
https://gist.github.com/Lucas7yoshi/233accc00ff2ebab1aadf11c02386524

Video (2612 Canary):

https://user-images.githubusercontent.com/28872095/165877605-44bdbbb2-93d9-4423-bfe1-076feb8f69b1.mp4

Additional note: 

Editor itself appears to operate fine, you can preview and prepare clips without issue
it is ONLY exports.

**Comment by cm8263** [comment]
Unsure if this is related, but I did see [this post](https://forum.cfx.re/t/how-to-fix-rockstar-editor-export-carsh-in-fivem-fixed-fivem-rockstar-editor/4848064) on the forums today. I'd be curious to see if this fixes the issue for you.

**Comment by Lucas7yoshi** [comment]
> Unsure if this is related, but I did see [this post](https://forum.cfx.re/t/how-to-fix-rockstar-editor-export-carsh-in-fivem-fixed-fivem-rockstar-editor/4848064) on the forums today. I'd be curious to see if this fixes the issue for you.

This resolves it

Im opening a new issue and closing this as that i think is the right thing to do
