### ISSUE TITLE
Ban 255 jour pour cheats

### ISSUE THREAD

**Issue by Sarah57050** [citizenfx/fivem#1439]
Bonjour, j'ai un gros soucis mon fils avait mis son compte five m sur l'ordinateur d'un copain qui utilisé un cheat en rentrant a la laison il va sur son ordinateur il vois qu'il est ban pour cheat jusque la pas de soucis c'est bien fais pour lui mais étant donné que moi et son papa on a son compte sur nos pc pour surveiller se qu'il fait on est ban aussi comment peut-on faire car c'est quand même 260 jours aillant rien fais sa mets la colère
![20220428_154741](https://user-images.githubusercontent.com/104628536/165934258-691df7a1-1a05-40c3-9a35-4c3d05ea7934.jpg)

**Comment by SpeedyThePaster** [comment]
brain issue
