### ISSUE TITLE
Client options set by server persist beyond server session

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#1440]
Servers appear able to set client options for longer than just the session within the server

Spotted on Mega's Games with streaming progress

before join, streaming progress is enabled
upon join, streaming progress is turned off by the server
upon exit, streaming progress remains turned off

I believe I recall at some point that this is _not_ how the behaviour should be, and that it should only remain while in the server.
(If this is intended, then feel free to close as this wasn't a very long issue to write :p)

Repro steps:
1. Enable streaming progress
2. Connect to cfx.re/join/45yo89
3. Once loaded, disconnect
4. Go to client settings and observe streaming progress is still disabled.
5. fully quit, reopen, and observe this is still the case.

Quick video:

https://user-images.githubusercontent.com/28872095/166064822-86842ad0-311d-4a50-9920-710afd58fc53.mp4

**Comment by blattersturm** [comment]
Should be fixed by 65ce263079db6e572cb508235c662537c65784a4.
