### ISSUE TITLE
Minor CTextInputBox issues

### ISSUE THREAD

**Issue by freedy69** [citizenfx/fivem#1444]
Input Box button prompts:
- Safe zone for input box buttons doesn't seem to update if you change the setting in pause menu
- After the text input box is closed, buttons are not unloaded, which means that if you place the cursor above the 'Cancel' button (Even if the box is closed) and hit left click, pause menu will open (Since the cancel button uses INPUT_FRONTEND_PAUSE_ALTERNATE when mouse is clicked). This issue doesn't occur until DisplayOnscreenKeyboard is called.
- When you exit the box with right-click and re-open it, you cannot click on the buttons

I tested these in GTA Online and everything was fine, which is why I think this could be FiveM's fault. These issues are not at all major but still thought it would be nice to report them. Also, is it possible to have a native command to call scaleform movie methods on the text_input_box like CallMinimapScaleformFunction? I think it would be nice, since using RequestScaleformMovie on it could be buggy

**Comment by blattersturm** [comment]
... is this completed? Does it not reproduce anymore?

**Comment by freedy69** [comment]
> ... is this completed? Does it not reproduce anymore?

I closed it since I thought it wasn't that big of a deal anymore because it's mostly just visual stuff
