### ISSUE TITLE
Fivem crashes that only affect female mp model. Legacy crash hash: pizza florida speeker

### ISSUE THREAD

**Issue by Sypsaa** [citizenfx/fivem#1445]
Hello. We have been having this problem for almost a month now. All female mp models aka characters gets the same crash every couple of minutes and it doesn't matter what you do. You can just load in and get it, you can stand, drive you name it.
Females of the server can't play at all. We looked for an answer but couldn't find one.

I attached the the crash file.rar bellow
[CfxCrashDump_2022_05_01_16_51_36.zip](https://github.com/citizenfx/fivem/files/8599342/CfxCrashDump_2022_05_01_16_51_36.zip)
![crashh](https://user-images.githubusercontent.com/104730106/166156015-7785941a-bd90-491e-bc2d-489d5a2405a9.png)

**Comment by blattersturm** [comment]
Missing repro steps, also 'the server' without further info provided... really?
