### ISSUE TITLE
AMD/NVIDIA crash on requesting model

### ISSUE THREAD

**Issue by Korioz** [citizenfx/fivem#1447]
I'm not sure if this crash is the one the message below is originally talking about but i've found a repro for a crash in `nvwgf2umx.dll` (nvidia) & `atidxx64.dll` (amd).

![image](https://user-images.githubusercontent.com/45950144/167052558-9dec8ddc-2fc9-4489-bcc3-9555d4f0ac03.png)

Tested on : 1604 & 2545 gamebuild / beta update branch

[Repro resource](https://dropmefiles.com/JxLfl)

It happens when requesting the model of a specific car, interestingly there is no issue if the model is requested at an early stage like on resource start, also it's not related specificly to the `REQUEST_MODEL` native, for example if the car is created from server-side (`CREATE_AUTOMOBILE`) and you connect after the creation of the car in it's culling radius then the model will be requested by the game but it will not make any crash as the request is done at an early stage but if you connect at a position out of it's culling radius and then go in it it will crash.

If it cannot be fixed at least showing what ydd files are corrupted in server console would be a great help for server owners.

**Comment by blattersturm** [comment]
Was this asset passed through some 'ToolkitV' thing? There's been another report recently where people used this tool and it caused this error as well.

**Comment by Korioz** [comment]
After some research i can confirm the issue appeared after passing the asset in ToolKitV, this was used to *optimize* textures in vehicles .ytd files without doing it manually.

So the issue is related to .ytd files and not .ydd as i suggested.

I can share a copy of the .ytd file in the repro before it was passed to ToolKitV if needed.

**Comment by Vinipux322** [comment]
> After some research i can confirm the issue appeared after passing the asset in ToolKitV, this was used to _optimize_ textures in vehicles .ytd files without doing it manually.
> 
> So the issue is related to .ytd files and not .ydd as i suggested.
> 
> I can share a copy of the .ytd file in the repro before it was passed to ToolKitV if needed.

Hi, can you share original .ytd file to me, i'm will try to fix that

**Comment by blattersturm** [comment]
This is indeed a bad asset, the buffer passed for `script_rt` texture is _way too small_ as somehow it's stored as DXT when any `script_rt` texture will be forcibly read as RGBA.

There's some other hardcoded name prefixes too, but these assets are yet again plain wrong, but of course people just use these tools without a care in the world and 'eh just blame FiveM, right?' when some edge case breaks.

I'm trying to add mitigation for this case, but this'd need me to implement DXT _decompression_ myself just to uncorrupt this trash, may lead to memory leaks too, and there's probably even weirder stuff people do that leads to the same 'incomplete buffer' GPU driver crashes so this won't even fix all of them... sigh.
