### ISSUE TITLE
Gasstations Duplication Crash 

### ISSUE THREAD

**Issue by BuddiesTV** [citizenfx/fivem#1452]
Player A = Me
Player B = Another User

If player B is standing next to a gas station and player A shoots at the gas station so that it explodes, the gas station reappears after the explosion and explodes again. After some time, the game crashes. Sometimes player A crashes and player B doesn't, but when that happens, player B has to deal with some weird bugs, like green hair and so on.

Video:
https://streamable.com/buhrnp

crashdump Player A: 
[CfxCrashDump_2022_05_12_13_26_05.zip](https://github.com/citizenfx/fivem/files/8679470/CfxCrashDump_2022_05_12_13_26_05.zip)

crashdump Player B: 
[CfxCrashDump_2022_05_12_13_26_10.zip](https://github.com/citizenfx/fivem/files/8679469/CfxCrashDump_2022_05_12_13_26_10.zip)

**Comment by mickeygeecom** [comment]
Can you replicate this bug on a clean FXServer? I'd suspect you have a script running causing this.
If so you should share the code for repro, at least.

**Comment by Lucas7yoshi** [comment]
In relation to some discussion about this topic, do you have any scripts that interact with said gas station? like a gas pump script for fueling cars

**Comment by BuddiesTV** [comment]
> In relation to some discussion about this topic, do you have any scripts that interact with said gas station? like a gas pump script for fueling cars

No, its just a basic server with default esx & vMenu.

**Comment by duckhunter392** [comment]
This happens when you have entity lockdown enabled. What is your entity lockdown set to?

**Comment by BuddiesTV** [comment]
> This happens when you have entity lockdown enabled. What is your entity lockdown set to?

I haven't enabled entity lockdown.

**Comment by blattersturm** [comment]
Surprisingly, for a change, this does correctly repro, to _some_ extent in this setup. Of note is that is the player who is shooting is much closer than in this example, the gas pump appears to be invulnerable, and in this setup (shooting with an AK), I didn't manage to get the gas station fires to blow themselves up for too long.

![image](https://user-images.githubusercontent.com/24576130/168375723-55de6cfc-b027-4704-832f-994bba9aefcd.png)

**Comment by Lucas7yoshi** [comment]
the number of explosions seems to be from how many players in the area. video I got had it blow up like 6 times and the video stopped before it had finished and there was atleast a dozen people within culling radius. I've had it blow up twice in my server when I was able to recreate it but I was manually forcing the pump objects to network

**Comment by blattersturm** [comment]
This _looks_ like a good case of dummy objects failing to be created (or, rather, getting cleaned up way early), perhaps as one of the clients thinks they shouldn't create dummy objects:

```
[ 136752872] RegisterNetworkObject: registering [netObj:98:OBJECT] (uniqifier: 20676)
[ 136752880] uncompressed clone sync for [obj:98]: 69 bytes
[ 136752880] sync: got 1 creates, 1 syncs, 0 removes and 0 migrates
[ 136752880] compressed 89 bytes to 76 bytes
[ 136752890] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752890] received frame 3205086:1
[ 136752900] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752900] ProcessTimestampAck: ts ack 136752839
[ 136752900] ProcessSyncAck: sync ack 22
[ 136752910] uncompressed clone sync for [obj:1]: 9 bytes
[ 136752910] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752910] compressed 24 bytes to 26 bytes
[ 136752911] ProcessTimestampAck: ts ack 136752851
[ 136752911] ProcessSyncAck: sync ack 94
[ 136752911] received frame 3205087:1
[ 136752921] operator (): no early resend of object [obj:1]
[ 136752921] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752921] ProcessTimestampAck: ts ack 136752862
[ 136752921] ProcessCreateAck: create ack 98
[ 136752930] operator (): no early resend of object [obj:1]
[ 136752930] uncompressed clone sync for [obj:98]: 73 bytes
[ 136752930] sync: got 0 creates, 2 syncs, 0 removes and 0 migrates
[ 136752930] compressed 88 bytes to 76 bytes
[ 136752944] operator (): no early resend of object [obj:1]
[ 136752944] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752944] received frame 3205088:1
[ 136752954] operator (): no early resend of object [obj:1]
[ 136752954] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752955] ProcessTimestampAck: ts ack 136752891
[ 136752955] ProcessSyncAck: sync ack 1
[ 136752964] sync: got 0 creates, 1 syncs, 0 removes and 0 migrates
[ 136752965] received frame 3205089:1
[ 136752965] HandleCloneCreate: id 5 obj [obj:9] ts 136752950
[ 136752965] RegisterNetworkObject: registering [netObj:9:OBJECT] (uniqifier: 20771)
[ 136752974] DestroyNetworkObject: unregistering [netObj:98:OBJECT]
[ 136752974] ReturnObjectId: id 98
```

```
[ 136752951] RegisterNetworkObject: registering [netObj:98:OBJECT] (uniqifier: 20676)
[ 136752959] uncompressed clone sync for [obj:5]: 16 bytes
[ 136752959] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136752959] compressed 36 bytes to 38 bytes
[ 136752968] sync: got 0 creates, 2 syncs, 0 removes and 0 migrates
[ 136752968] ProcessTimestampAck: ts ack 136752905
[ 136752968] ProcessCreateAck: invalid uniqifier for 9
[ 136752968] received frame 3205089:1
[ 136752968] HandleCloneUpdate: id 4 obj [obj:1] ts 136752891
[ 136752968] dependent frame is 3205085 (our last frame 3205085) for object 1
[ 136752968] HandleCloneUpdate: id 4 obj [obj:98] ts 136752862
[ 136752968] dependent frame is 0 (our last frame 0) for object 98
[ 136752976] operator (): no early resend of object [obj:5]
[ 136752976] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136752985] operator (): no early resend of object [obj:5]
[ 136752985] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136752986] received frame 3205090:1
[ 136752986] HandleCloneUpdate: id 4 obj [obj:98] ts 136752911
[ 136752986] dependent frame is 3205088 (our last frame 3205089) for object 98
[ 136752994] uncompressed clone sync for [obj:5]: 16 bytes
[ 136752994] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136752994] compressed 31 bytes to 33 bytes
[ 136752994] ProcessTimestampAck: ts ack 136752934
[ 136752994] ProcessSyncAck: sync ack 5
[ 136752994] ProcessTimestampAck: ts ack 136752934
[ 136752994] ObjectIds_ConfirmObjectId: id 9
[ 136753002] sync: got 0 creates, 2 syncs, 0 removes and 0 migrates
[ 136753011] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136753019] sync: got 0 creates, 3 syncs, 0 removes and 0 migrates
[ 136753019] received frame 3205091:1
[ 136753019] Trying to remove entity 98 (sent uniq: 20676, local uniq: 20676, should steal: no)
[ 136753019] DestroyNetworkObject: unregistering [netObj:98:OBJECT]
[ 136753019] DeleteObjectId: object ID [obj:98]
```

**Comment by blattersturm** [comment]
0fa9425436b32308fecdfb7b3d50e1c13b9f3f64 indeed seems to be the culprit here - there's two little mistakes that which make it so that instead of fixing issues with dummy object creation, it _worsens_ them instead. Yay, another 7-month regression report delay... 😕

**Comment by duckhunter392** [comment]
> 0fa9425436b32308fecdfb7b3d50e1c13b9f3f64 indeed seems to be the culprit here - there's two little mistakes that which make it so that instead of fixing issues with dummy object creation, it _worsens_ them instead. Yay, another 7-month regression report delay, as the initial issue wasn't reproducible and the fix apparently caused another issue not in the initial repro suite... 😕 

I think it was about 7 months ago when I noticed this issue again ironically.

Back in the day I noticed this issue only occurred in entity lockdown. At some point it was "fixed" (I don't think anyone intentionally fixed it tbh), but then it stopped working again probably about 7 months ago. Presumably at that point it had nothing to do with entity lockdown?

**Comment by blattersturm** [comment]
Details from 08a79e546a8a2e3b363aa460c6d70a0613dbe2d1:

>This broke as of 0fa9425436b32308fecdfb7b3d50e1c13b9f3f64, as reported only recently in #1452 as a *reproducible* case of 'blowing up a gas pump leads to the pump instantly being recreated'.
>
>It turns out that the initial fix made a few mistakes in the ASM stub:
>
>1. `al` was overwritten with the post-restore `al`, and
>2. `rax` was saved in the scratch space for the callee, so it would often contain nonsense, causing 'Player Wants Control' to always be true.
>
> Fixes #1452 - at least for the reproducible regression case, hopefully for all cases however.

**Comment by GamingMakingDave** [comment]
have the same problem :/

**Comment by BuddiesTV** [comment]
> have the same problem :/

It is fixxed already. Just switch your Client Version to the Latest (Unstable) version.
