### ISSUE TITLE
The Mitigation of tools compressing "script_rt" doesn't show the resource name correctly

### ISSUE THREAD

**Issue by TheKronoss** [citizenfx/fivem#1455]
Since the new canary build (5592). I'm getting the console log that images are set to a compressed texture format etc.
That I'm getting the error could be correct, there's what I can see nothing wrong with that.
But in the source code I'm seeing that between "script:"  and ":stream"  there should be a resource name. As seen in the screenshot below that isn't the case, instead it's showing an underscore ( _ ). 

Than it is saying that in the texture file ( vehicles_muscle_n_w_interior.ytd ) there's set something wrong. But I am not streaming this file, could it be that it's saying the wrong texture dictionary and with the wrong texture?

Screenshot: 
![IHhdyxL](https://user-images.githubusercontent.com/42589271/168922441-5f41b9ee-9ea4-4913-ac01-a274c46eecab.png)

**Comment by Lucas7yoshi** [comment]
script_rt_dials_race in vehicles_muscle_n_w_interior.ytd appears to be using DXT1, and while i am not exactly an expert on texture formats it seems that one would indeed be compressed.

and this is straight from game files, perhaps this is a weird edge case where rockstar incorrectly compressed it?

**Comment by blattersturm** [comment]
> script_rt_dials_race in vehicles_muscle_n_w_interior.ytd appears to be using DXT1

Correct. The difference here seems to be that the buffer in the file, as well as the stride, allocates enough data for an ARGB texture anyway, and the initialized data is empty/weird/black for most of 'em.

It could be that R*'s offline resource compiler may correct for this mistake as well in case _artists_ make it, but do so by only updating the buffer size but not the format, especially as most stuff in the list @gottfriedleibniz sent seems to be newer content:

> > Checked another script_rt_ ...
> 
> Here are the other script_rt textures w/ inconsistent/compressed formats:
> 
> ```
> prop_muster_b1.ytd, script_rt_planning, D3DFMT_A1R5G5B5
> vehicles_biker_shared.ytd, script_rt_dials_race, D3DFMT_DXT1
> volatol.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> vehicles_itali_w_interior.ytd, script_rt_dials_itali, D3DFMT_DXT1
> vehicles_racecar.ytd, script_rt_dials_race, D3DFMT_DXT1
> h4_prop_battle_club_screen.ytd, script_rt_club_tv, D3DFMT_DXT1
> vehicles_gendials.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> vehicles_gendials.ytd, script_rt_dials_race, D3DFMT_DXT1
> sf_prop_sf_handler_01a.ytd, script_rt_dials_truck, D3DFMT_DXT1
> bombushka.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> howard.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> molotok.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> nokota.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> starling.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> tula.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> vehicles_race_generic.ytd, script_rt_dials_race, D3DFMT_DXT1
> tr_prop_scriptrt_table01a.ytd, script_rt_table, D3DFMT_DXT5
> vehicles_jugular_race_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_jugular_w_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_pfister_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_jugular_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_muscle_n_w_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_s80_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_sup1_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_sup1_w_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_sup2_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_sup2_w_interior.ytd, script_rt_dials_race, D3DFMT_DXT1
> vehicles_biker_shared.ytd, script_rt_dials_race, D3DFMT_DXT1
> molotok.ytd, script_rt_dials_lazer_vintage, D3DFMT_DXT1
> ```
> 
> Unfortunately, ran out of time stepping through the affected code-paths (and this will likely be fixed by the time I see this again).

A likely course of action would be checking if the stride at least fits width * 4, and if so, not doing anything.
