### ISSUE TITLE
Siren not working

### ISSUE THREAD

**Issue by Aburke150** [citizenfx/fivem#1457]
I want to know why my siren isn't working. I put in the file into my gta main directory and then nothing

**Comment by billymitchelljr** [comment]
To add a custom siren, copy RESIDENT.rpf and go to your main directory>x64>audio>sfx>paste. If it asks to replace you hit yes. Once that happens boom new siren. If you've done that but it ios not working then it could be the file itself having an issue.

**Comment by Disquse** [comment]
This is not a place for modding related questions. Use https://forum.cfx.re
