### ISSUE TITLE
FiveM for ARM

### ISSUE THREAD

**Issue by akxks** [citizenfx/fivem#1458]
Will there ever be FiveM available for Windows 10 ARM?

**Comment by donkras** [comment]
wrong place to ask stuff but since im already responding:
https://github.com/citizenfx/fivem/issues/1125#issuecomment-963101735

**Comment by blattersturm** [comment]
1. Windows 10 on ARM doesn't even support x64 apps, support for this was added only in Windows 11.
2. FiveM already runs on Windows 11 on ARM.
3. As to anticheat stuff working there, see the other issue and this still is the wrong place to even ask as this is *not a support place*.
