### ISSUE TITLE
[Onesync Feature] playerAttaching event for server-side

### ISSUE THREAD

**Issue by BugCode1** [citizenfx/fivem#1461]
Hello,

i'm searching for this event but can't found something useful, because some of cheaters can attach spawned vehicles by other players to another peds

so with this event we can find who attach entity to others in server-side

**Comment by cyneptic** [comment]
I'd love this aswell, it'll be quite useful to have such an event for anti cheats and other preventive measures.

**Comment by WrenchRB** [comment]
for this cheat you can change your scripts and use sv_filterRequestControl

**Comment by blattersturm** [comment]
This isn't a place for feature requests.
