### ISSUE TITLE
IsControlPressed

### ISSUE THREAD

**Issue by KiLaF** [citizenfx/fivem#1464]
so when use IsControlPressed and the in game console is opened, it doesn't work, i don't know if this a bug, i suggest adding it because its helps a lot, i personally wanna use it for anti-cheat detections.

**Comment by Lucas7yoshi** [comment]
https://github.com/citizenfx/fivem/pull/1450#issuecomment-1122224462 save someones breath here and link that as its likely relevant.

**Comment by Disquse** [comment]
This "anti cheat measure" makes absolutely no sense anyway.
