### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by MoskalykA** [citizenfx/fivem#1466]
When I run this command `fxd gen -game five`, I get this `Error: E:/fivem/code/vendor/mojo.lua:28: attempt to index a nil value (local 'r') in token: gen_typemap_args(file.abspath)`

**Comment by thorium-cfx** [comment]
Taking a quick peek into the file; did you install python 3? And if so is it present in your PATH environment variable?

**Comment by MoskalykA** [comment]
> Taking a quick peek into the file; did you install python 3? And if so is it present in your PATH environment variable?

![image](https://user-images.githubusercontent.com/100430077/171225026-846918b7-b098-4e72-a0fb-744aa4a10058.png)

**Comment by thorium-cfx** [comment]
hmm then I would `print(e, prj_root, path)`. Check for the error and/or if the pathing is correct.

**Comment by thorium-cfx** [comment]
Closing as of staleness
