### ISSUE TITLE
Fivem Deadloop

### ISSUE THREAD

**Issue by meibelleal** [citizenfx/fivem#1472]
Hi guys, I've had this problem for a month, it only happens in one FIVEM city, and that's where I have my whole life. I've done everything, formatted my computer, changed parts, I don't know what else to do if anyone can help me
![unknown](https://user-images.githubusercontent.com/106632243/171293994-ef7cee4c-a88a-4dd9-8773-a81a257753e2.jpg)
me.

**Comment by Zydson** [comment]
The problem is not on your end, changing parts/format won't help you. As you can see you got crash caused by dead loop in vrp_admin script, to solve this you should concact with server owner. This is not fivem related issue.

**Comment by blattersturm** [comment]
I suspect this server's 'admin script' has a function that kicks users by making their game crash. Clearly such a feature is just hostile as it leads to these users reporting it as an issue to _us_ instead. :/
