### ISSUE TITLE
Console input box?

### ISSUE THREAD

**Issue by waddle1010** [citizenfx/fivem#1473]
**Description:**

Upon pressing `F8` to open the in-game console, on player load in, it doesn't focus on the 'input box' to allow you to type. *i.e* If you would like to stop / restart a resource, you are unable to type until pressing the input box. This is *only* happening upon *first* player load in. Once you drag your mouse and press the input box, it will then allow you to use the `F8` console freely, for your remainder of your time in the server.

**Reproduction Steps:**
- Load into your server.
- Press F8.
- Drag your mouse cursor to the input box, and click the empty space to then begin typing.

**Expected Behavior:**

- The ability to use the in-game `F8` console.

**Additional Context**
- **Game Version:** 5562
- **Build:** 2189

**Comment by blattersturm** [comment]
This was resolved in 13f38d6afac3c45243ba00a9657f182ec1051a94.
