### ISSUE TITLE
RedM client - Can't change to other language than English for Steam and Epic players

### ISSUE THREAD

**Issue by xrb936** [citizenfx/fivem#1475]
For RGL players, they can use -rglLanguage=XX argument to switch language, but not for Steam and Epic players. I did some research and looked at the FiveM repo earlier but couldn't find any idea. Any suggestion or idea will be appreciated.

**Comment by xrb936** [comment]
Update: Tried different build, for 1311, -rglLanguage=XX is working for all platforms, for both 1355 and 1436, only RGL works.

**Comment by blattersturm** [comment]
This is likely related to 1355 and above using a different entitlement validation function so we run in _partial_ Steam/Epic mode so the game will accept licenses from these platforms.

I guess, however, that in those cases, the game also expects the language to be provided by their platforms - would likely need an additional patch somewhere to use this argument for all cases.

**Comment by xrb936** [comment]
> 

Thank you for your reply. Upon checking Steam game library file, looks like the RedM is changing the language back to English when it’s starting. It keeps adding language=English in mountedconfig part in the acf file.

**Comment by blattersturm** [comment]
Are you sure this doesn't work for Epic versions? It seems the game only overrides the language for Steam.

**Comment by FGouveia13** [comment]
is this still a thing? I have redm with steam. Steam is in ENG, RedM Settings in ENG, RDR2 game in ENG, however , when i join a redM server it comes back as half PT and half ENG... My system is in PT. Can I force RedM to be in ENG 100%???
