### ISSUE TITLE
Server granting control over already owned vehicles

### ISSUE THREAD

**Issue by 0xLuca** [citizenfx/fivem#1480]
With this snippet of code, a modder using any lua executor can get control over vehicles that are driven by players:

```lua
function RequestControlOnce(entity)
    if not NetworkIsInSession() or NetworkHasControlOfEntity(entity) then
        return true
    end
    SetNetworkIdCanMigrate(NetworkGetNetworkIdFromEntity(entity), true)
    return NetworkRequestControlOfEntity(entity)
end

RegisterCommand('tpother', function(source, args)
	local id = tonumber(args[1])
	local player = GetPlayerPed(GetPlayerFromServerId(id))
	local vehicle = GetVehiclePedIsIn(player)
	print(vehicle)
	Citizen.CreateThread(function()
		while true do
			local CamRot = GetGameplayCamRot(2)
			local force = 5
			
			local Fx = -(math.sin(math.rad(CamRot.z)) * force * 10)
			local Fy = (math.cos(math.rad(CamRot.z)) * force * 10)
			local Fz = force * (CamRot.x * 0.2)
			RequestControlOnce(vehicle)
			ApplyForceToEntity(vehicle, 1, Fx, Fy, Fz, 0, 0, 0, true, false, true, true, true, true)
			Wait(0)
		end
	end)
end)
```

Here is a video that shows this in action:

https://streamable.com/z2tiy6

At first, the other client does not get the control and the vehicle only moves on the modder's clientside. But after a few seconds pass, the vehicle gets owned by the player that executes the snippet and the vehicle gets thrown away.

Possible solution:
Only allow control over vehicles if the vehicle does not have a driver or add a server-side native that blocks any incoming control change requests for an entity.

**Comment by AvarianKnight** [comment]
You can look at how to fix this issue [here](https://docs.fivem.net/docs/server-manual/server-commands/#sv_filterrequestcontrol-mode)

Note that the doc is currently incorrect and it defaults to 0 (off) not -1
