### ISSUE TITLE
Lua does not support lua modules, require function cannot find any module file

### ISSUE THREAD

**Issue by maicek** [citizenfx/fivem#1506]
Hi, i want to use one of the public lua modules [LuaORM](https://github.com/wesen1/LuaORM/tree/master/src/LuaORM), but theres an issue with using `require` in FiveM lua resource file context, function exists but cannot import any lua module file.

Example repro resource:

fxmanifest.lua
```lua
fx_version 'cerulean'
game 'common'
lua54 'yes'
server_only 'yes'

server_scripts {
    'moduletest.s.lua',
}
```

moduletest.s.lua
```lua
local test = require 'test'

print(test)
```

test.lua
```lua
local pepega = {}

pepega.testing = true

return pepega
```

When executing this code i got this error:
```txt
[       script:LuaORM] Error loading script moduletest.s.lua in resource LuaORM: @LuaORM/moduletest.s.lua:1: module 'test' not found
[       script:LuaORM] stack traceback:
[       script:LuaORM]  [C]: in function 'require'
[       script:LuaORM]  @LuaORM/moduletest.s.lua:1: in main chunk
[    c-scripting-core] Failed to load script moduletest.s.lua.
```

Is there any way (or workaround) to import lua module file, or this feature is not really planned and `require` function exist by mistake?

**Comment by blattersturm** [comment]
GitHub issues aren't for feature requests or non-actionable reports.
