### ISSUE TITLE
FiveM with Wine/Proton

### ISSUE THREAD

**Issue by prinzhoefte** [citizenfx/fivem#1510]
As far as I can see, nothing really stops FiveM from working on Linux with Wine or Proton. But the game automatically starts in insecure mode. 
Would it be possible to disable that?

**Comment by prinzhoefte** [comment]
![932e57bb4ed89b53766ea2bfce603594-png](https://user-images.githubusercontent.com/44341594/175819709-0adcb986-9614-4706-a14f-c9ddf3c0d23f.jpg)
Message when you try to start the game with Wine.

**Comment by blattersturm** [comment]
This has been discussed and explained in *many* other places. 'Disabling' this would just lead to the game not opening. Do you really want that?

Also, this is off-topic for support questions.
