### ISSUE TITLE
`DisableIdleCamera` does not work when you're a passenger in vehicle

### ISSUE THREAD

**Issue by TrAsKiN** [citizenfx/fivem#1511]
To avoid having a loop that regularly calls `InvalidateIdleCam` and `InvalidateVehicleIdleCam`, I decided to use `DisableIdleCamera`.

It works fine on foot and when you are the driver of a vehicle, but does not work when you are the passenger.

**Comment by LWSS** [comment]
https://github.com/citizenfx/fivem/pull/1512

**Comment by Disquse** [comment]
The PR implementing this feature as a separate native has been merged 🎉
