### ISSUE TITLE
DrawMarker rotZ brings no change

### ISSUE THREAD

**Issue by h4eDashboard** [citizenfx/fivem#1516]
Hi all,

i use this native:

DrawMarker(9, pos.x, pos.y, pos.z, 0.0, 0.0, 0.0, 90.0, 90.0, 45.0, 4.0, 4.0, 4.0, 255, 255, 255, 255, false, false, 2, false, "h4e_logo_weiss", "h4e_logo_weiss", false)

But the Value 45.0 -> rotZ has no Ingame Effect?
I try to set a Heading for my Marker and wanna draw them at the Cubes of Legion Square. But no Chance to rotate them?

**Comment by blattersturm** [comment]
This isn't a support forum either.
