### ISSUE TITLE
gta5_b2612

### ISSUE THREAD

**Issue by DARKAOFF** [citizenfx/fivem#1517]
![image](https://user-images.githubusercontent.com/427770/176988234-e21c6202-2ada-494e-a119-389c4f5c488f.png)

**Comment by AvarianKnight** [comment]
This doesn't seem very actionable

**Comment by DARKAOFF** [comment]
do you need a specific file?

**Comment by Lucas7yoshi** [comment]
if you have specific reproduction steps which are very clearly absent here than it would fit here

otherwise this is just asking for support which is not what GitHub issues are for
