### ISSUE TITLE
Consider Adding Support for Dart Language

### ISSUE THREAD

**Issue by KevinCCucumber** [citizenfx/fivem#1519]
Javascipt is a great option for FiveM since its easy to learn and fast to code.
However, its quite easy to make mistakes while coding.

Dart can compile to optimized Javascript while also providing sound nullsafety while being fast and easy to learn.

Imo it would be a good addition

**Comment by maicek** [comment]
I think also you can use typescript and compile it to optimized javascript. With proper setup using esbuild and nodemon you can write your typescript code with nearly no build time waiting.

**Comment by Disquse** [comment]
> Dart can compile to optimized Javascript

So why you can't just compile Dart into JS and use it? Just like it works with TS here.

**Comment by maicek** [comment]
> > Dart can compile to optimized Javascript
> 
> So why you can't just compile Dart into JS and use it? Just like it works with TS here.

I think the same, typescript is also not natively supported by fivem, and to use it you have to compile it by yourself to javascript code. So, if typescript isn't implemented as natively supported language i don't think there might be dart support in future. Especially there is very small requestion.

**Comment by KevinCCucumber** [comment]
Typescript transpiles, Dart compiles. I cannot access the Frameworks classes with Dart. That would need a bit of declaration before it can compile to javascript I guess

**Comment by Disquse** [comment]
> I think the same, typescript is also not natively supported by fivem

There's no such a thing as "native typescript support". Even the thing that claims "native support" (i.e. Deno) actually still does the same TS->JS translation in the end, like we all do. Dart however have it's own VM but there's literally no reason to use it. From what I know it's still kinda slow comparing to V8, safeness is also under a huge question. And IMO adding yet another heavy dependency for such a niche thing simply doesn't worth it.

**Comment by KevinCCucumber** [comment]
This is form 2012 but states that Dart was faster than V8 back then
https://news.ycombinator.com/item?id=4902802

**Comment by blattersturm** [comment]
This isn't the place for feature requests.
