### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#1527]
On weblate, we are asked to translate a word but the trick is : there's no word...
https://translations.cfx.re/translate/citizenfx/cfx-ui/fr/?q=state%3Aempty&offset=12#translations
![image](https://user-images.githubusercontent.com/80094438/178762312-3527587e-e27a-4896-b319-289b75656db0.png)

**Comment by blattersturm** [comment]
Correct, this line is empty:

https://github.com/citizenfx/fivem/blob/61424642f7fabc7952d589de0de86f5356cac289/ext/cfx-ui/src/assets/languages/locale-en.json#L78
