### ISSUE TITLE
network thread hitch warning causing all players to timeout

### ISSUE THREAD

**Issue by Georgie15** [citizenfx/fivem#1529]
Randomly in my server the console is spammed with network thread hitch warning then all players timeout. I have attached a profiler scan during the hitches to see if something could be pointed out.

This is a google drive link of the profiler scan during the mass network thread hitch warning.
https://drive.google.com/file/d/1T6HqDaoKz30LX_LOjZ1bxSdDDlJUOW91/view?usp=sharing

**Comment by MathiAs2Pique** [comment]
Hi, I don't found anything incredibly high in your profiler, could you send your server specs / amount of players ?
Also, did you check your server's metrics ? (CPU, network load, ram, ...)

**Comment by Georgie15** [comment]
Server specs are: 5800x, 64gb of ram, 1GB up and down

Typically around 110+ players we will randomly have a mass server timeout, it never happens under 110 players.

I checked the metrics when it happened and the cpu usage didn't spike at all.

I'm using FXServer artifacts 5659 and it's still happening. I'm honestly lost on how to fix this so any help would be great. Please let me know if I need to provide more information.

**Comment by Ekinoxx0** [comment]
Hi, quick note : GitHub Issues are not for non actionable bugs or investigation, please refer to the forum for this type of demand.

I've had this problem in the past and it was related to bad written scripts, more specifically I did a lot of TriggerClienrEvent with large amount of data in them by accident.
It would be interesting that FiveM implement some warning about scripts that abuse of the available bandwidth, or that send too much event.

Investigating this kind of problem is kinda hard in itself, you could make an ETW of the moment with player timeout, or try disabling recent scripts.

Good luck.

**Comment by Georgie15** [comment]
How did you go about finding those bad scripts?

**Comment by Georgie15** [comment]
> Hi, quick note : GitHub Issues are not for non actionable bugs or investigation, please refer to the forum for this type of demand.
> 
> I've had this problem in the past and it was related to bad written scripts, more specifically I did a lot of TriggerClienrEvent with large amount of data in them by accident. It would be interesting that FiveM implement some warning about scripts that abuse of the available bandwidth, or that send too much event.
> 
> Investigating this kind of problem is kinda hard in itself, you could make an ETW of the moment with player timeout, or try disabling recent scripts.
> 
> Good luck.

How did you go about finding those bad scripts?

**Comment by avilchiis** [comment]
Search this shit TriggerClientEvent('somerandomevent',-1,data) and check what data are you sending to your players, I had this same issue months ago with modfreakz dealership sending a lot of shit to all the clients causing timeouts

**Comment by Georgie15** [comment]
> 

Okay, and how did you find that specific event that was causing this?

**Comment by mickeygeecom** [comment]
> Okay, and how did you find that specific event that was causing this?

Use 'netEventLog' in the client console - also this is not an actionable issue for Cfx. In the future you should use the forum for guidance.

**Comment by SmerfTV** [comment]
Same problem- have you got solution?

**Comment by thorium-cfx** [comment]
As others have noted, this is not an actionable issue to us, you can seek guidance on the forums for these subjects.

`network thread hitch warning` can indeed relate to excessive use of `TriggerClientEvent` and similar, you can follow the advice they gave you here. If it does happen to be an issue on FXServer's side then open a new issue with a minimal repro.
