### ISSUE TITLE
Shutdown param not synchronized

### ISSUE THREAD

**Issue by KevinCCucumber** [citizenfx/fivem#1530]
https://github.com/citizenfx/fivem/blob/edfbbbbdc85f6e8d8ebce286be3e35e7a71c8e17/code/components/citizen-server-main/src/ServerInstance.cpp#L254-L258

This not being synchronized could lead to an where CPU/Compiler could cause the Server being stuck on shutdown or terminate it right after starting it up.

**Comment by blattersturm** [comment]
'synchronized'- what?

Outside of the missing `volatile` in the header file that _may_ be needed if the sleep call isn't interpreted as external, I'm not sure what you're referring to here. On any typical memory model (with the only supported architecture being x86-64), also counting basic causality (it's defaulting to false by default), there is no need for any additional logic here. 

If you can actually show a scenario where what you say may occur occurs, we can reopen this issue, but so far.. huh?
