### ISSUE TITLE
RedM stopped working error when normal exit

### ISSUE THREAD

**Issue by CartierPierre** [citizenfx/fivem#1533]
Hi,
I encounter this crash log after each time I leave my server, using normal game exit
![image](https://user-images.githubusercontent.com/10561315/179419046-41bfe34d-0ac4-49dc-abb8-575b1734c0e8.png)
I'm using the game with Rockstar launcher

**Comment by Disquse** [comment]
This is a known RedM OneSync issue as stated here: https://forum.cfx.re/t/technical-preview-onesync-now-available-for-redm/4413410/30

Going to be fixed soon, hopefully.
