### ISSUE TITLE
Failed to get info from server 

### ISSUE THREAD

**Issue by Havoc47** [citizenfx/fivem#1535]
![Screenshot 2022-07-21 005411](https://user-images.githubusercontent.com/109715297/180132783-b3b8fcad-4ccf-45a2-934a-e1d1c8256456.png)

**Comment by Yum1x** [comment]
![image](https://user-images.githubusercontent.com/46856347/180240286-cb6b5ef6-e625-41ba-9c5e-83685551428c.png)
