### ISSUE TITLE
(ServerGameState): sv_filterRequestControl defaults to NoFilter instead of Default

### ISSUE THREAD

**Issue by 0xLuca** [citizenfx/fivem#1543]
The docs & the code comments say that the current default value for `sv_filterRequestControl` is `-1` (`RequestControlFilterMode::Default`), which is equivalent to `2` (`RequestControlFilterMode::FilterPlayer`).
But in the code, the convar's default value is `RequestControlFilterMode::NoFilter`: https://github.com/citizenfx/fivem/blob/45b879ff140d8055f6b3a190f19299a3df169542/code/components/citizen-server-impl/src/state/ServerGameState.cpp#L5866

**Comment by blattersturm** [comment]
This is intentional and was done while pending feedback on the feature while still being able to bump the 'recommended' server release. 

Since people haven't provided sufficient feedback, this still hasn't changed.

**Comment by 0xLuca** [comment]
> 

What feedback

> This is intentional and was done while pending feedback on the feature, while still being able to bump the 'recommended' server release without inducing a behavior change.
> 
> Since people still haven't provided sufficient feedback, this also still hasn't changed.
> 
> See the commit history for the reasoning as well: [f07c619](https://github.com/citizenfx/fivem/commit/f07c61906f4c14605d3beaec1483f1a9be531d9d)

What feedback do you need? Is there anything we should test? I think this (currently less known) feature would help a few servers regarding "cheaters" using external software to take ownership of foreign vehicles.

**Comment by blattersturm** [comment]
I do not know at this time. It has been a while, so I mostly forgot the specifics.

**Comment by blattersturm** [comment]
In fact, I've taken the initiative and made a forum topic for this: https://forum.cfx.re/t/discussion-on-the-built-in-request-control-filtering-feature/4887321

Please try to remain civil and blameless, however.
