### ISSUE TITLE
False bans?

### ISSUE THREAD

**Issue by Konnapelaaja** [citizenfx/fivem#1553]
What can I do when, I got banned from modding without any valid reason. This is not the first time I get banned without a valid reason. I can't find any kind of mods on my computer, not even gta V. I hope that the matter can be resolved somehow because I would like to go back to playing and I really don't want to wait 12 days when I haven't done anything. Can I contact fivem or something?

**Comment by PappaNiels** [comment]
Issues are not meant for this. For any further info, please see: https://docs.fivem.net/docs/support/ban-faq/
