### ISSUE TITLE
GetLocalTime returns UTC time, when it used to return the proper format depending on OS

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1555]
I've been using it for quite a while, but it seems an update broke the function, which now only returns the UTC time format.
It didn't use to be like that.

**Comment by blattersturm** [comment]
@gottfriedleibniz said:

> ```
> GET_LOCAL_TIME
> NETWORK_GET_FRIEND_NAME
> NETWORK_FORCE_LOCAL_USE_OF_SYNCED_SCENE_CAMERA
> ```
> Have `aliases: ...` [conflicts](https://github.com/citizenfx/natives/blob/master/CLOCK/GetUtcTime.md)

This indeed seems to be the case. As user claim here implies GET_LOCAL_TIME used to be the correct owner for GetLocalTime, I'll indeed assume this one as the canonical variant.

The other two commands seem less relevant so I'll take the same route here.
