### ISSUE TITLE
Access denied for command...

### ISSUE THREAD

**Issue by xrtw** [citizenfx/fivem#1566]
Hey, please add who is trying to type permissioned command 
https://github.com/citizenfx/fivem/blob/a24c8481fa17be9be0986d90186b9a5b6a95fe0b/code/client/citicore/console/Console.Commands.cpp#L116
somebody is spamming commands and flooding console.

**Comment by blattersturm** [comment]
This lacks a lot of context, nor is this a place for feature requests (seeing 'please add ..').
