### ISSUE TITLE
RedM KEEPS POPPING UP ros-patches-rdr3 ugc body CODING AND ITS STUCK

### ISSUE THREAD

**Issue by Muffinmama** [citizenfx/fivem#1567]
Hello i have been trying for several days now to fix my game and this keeps happening and I cant find, the fix online because it doesn't exist please help... this issue is making it to where i cannot load into any game it will jsut keep popping up with no progress 
![image](https://user-images.githubusercontent.com/111020868/184023209-82a71feb-f3e2-4b1c-87ad-269799036aae.png)

**Comment by blattersturm** [comment]
This is not a support platform. Try the forums at https://forum.cfx.re/ instead.

**Comment by yhannaquinn** [comment]
Hi, did you fix it? 
I've been having the same problem also
