### ISSUE TITLE
This is not a support platform. Try the forums at https://forum.cfx.re/ instead.

### ISSUE THREAD

**Issue by Muffinmama** [citizenfx/fivem#1568]
This is not a support platform. Try the forums at https://forum.cfx.re/ instead.

_Originally posted by @blattersturm in https://github.com/citizenfx/fivem/issues/1567#issuecomment-1211329798_ 

Clearly I would’ve tried the forums if anyone gave a shit about it and responded no one has even looked at mine or the other persons who is also having this same issue I NEED HELP THIS IS DAY 5 and I’m FRUSTRATED SO PLEASE DONT CLOSE MY NEXT TICKET WHEN I MAKE A NEW ONE that’s real shitty

**Comment by neptunium-cfx** [comment]
Please just be patient and ask on forum, spamming issues on github won't make someone look at your issue faster, it might only delay it. No need to be hostile/rude too.

**Comment by Muffinmama** [comment]
Fix your game/servers then I wouldn’t have to ☺️ There’s more out there than just gtaV

**Comment by AvarianKnight** [comment]
Didn't know CitizenFX release a game, that's news to me :o

**Comment by titanium-cfx** [comment]
Github issues **are not** support tickets. 
Please use our forums, more specifically over at https://forum.cfx.re/c/redm-discussion/redm-bugreports/56 to report your issue.
