### ISSUE TITLE
Random mass crash "stopped responding"

### ISSUE THREAD

**Issue by Bombelhype** [citizenfx/fivem#1569]
Hi i have a problem on my serwer, for a couple of days huge amount of players get randomly crash “stopped responding”. Sometimes i have this problem twice a day and sometime 10x a day… random time random amount of people on server

I upload some crash dumps

[CfxCrashDump_2022_08_09_16_33_44_1.zip](https://github.com/citizenfx/fivem/files/9308400/CfxCrashDump_2022_08_09_16_33_44_1.zip)

[CfxCrashDump_2022_08_10_19_35_42.zip](https://github.com/citizenfx/fivem/files/9308397/CfxCrashDump_2022_08_10_19_35_42.zip)
.

**Comment by blattersturm** [comment]
> a problem on my serwer

That means this isn't a reproducible issue for us, i.e. not actionable and *doesn't belong on here*.

Also, it's spelled 'server'. Not 'serwer'.

**Comment by blattersturm** [comment]
As a one-off courtesy, here's a hint from dump analysis: something is causing _nested_ physics instances.
