### ISSUE TITLE
Feature request: determine name from resource manifest

### ISSUE THREAD

**Issue by matsn0w** [citizenfx/fivem#1571]
Hello there,

I happened to come across a flaw while developing a server resource and I may have a fix for it right away.

### Background

I am trying to develop a resource which is dependent on another resource. That's totally possible with a [`dependency`](https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/#dependency) key in my resource manifest, but that is assuming that the name of the dependent resource isn't changed by the server owner.

As far as I know, a resource is given a name based on it's folder (containing `fxmanifest.lua`).

Because of this, I am not 100% sure that dependency Y is available to resource X. It might be, but with a different name (read: folder path)!

### Proposal

My idea for fixing the described issue is by simply adding a `name` key to the resource manifest spec, specifiying a unique 'resource id' that can be used for identifying this particular resource. This can be useful for things like dependencies and there may be more applications.

What do you think? Am I missing something? Am I thinking too easy?

Let me know!

Cheers,
matsn0w

**Comment by Mycroft-Studios** [comment]
if the server owner changes resource names and it breaks, surely its on them for changing it?

**Comment by AvarianKnight** [comment]
They can fix the issue themselves by just "providing" for the other resource name, seems like wasted effort to add a `name` field when they will likely just change that too and complain about it being broken

```lua
provides {
	'mysql-async'
}
```

**Comment by matsn0w** [comment]
> if the server owner changes resource names and it breaks, surely its on them for changing it?

Well, you are definately right. I can totally put a warning in the docs, but... People don't read docs. Maybe we can prevent such issues? Make things foolproof so to say ;)

> They can fix the issue themselves by just "providing" for the other resource name, seems like wasted effort to add a `name` field when they will likely just change that too and complain about it being broken

Yeah, good point. However, changing 'code' is a step further IMO.

**Comment by Blumlaut** [comment]
> They can fix the issue themselves by just "providing" for the other resource name

that does imply a certain level of awareness when a resource name is changed/nonstandard, which most amateurish server owners just don't have imho, many just click the "download as zip" button on GitHub and drag&drop the folders, without actually paying attention to the resource name.


On the flip side, it seems to me that using `provide` does work, even if the resource is named the exact same. so as a resource developer this may be a thing you'd want to implement by default, quickly testing it on EasyAdmin shows that it still works as intended, although if this is intentional is another thing altogether..

**Comment by xDope7137** [comment]
> They can fix the issue themselves by just "providing" for the other resource name, seems like wasted effort to add a `name` field when they will likely just change that too and complain about it being broken
> 
> ```lua
> provides {
> 	'mysql-async'
> }
> ```

I wish this "provides" would also work for exports. So if people are renaming their scripts, and have the original script name in "provides", it will directly link the exports to that renamed script.

That would help people renaming the qb-core scripts and other creators needing to create separate configs for custom script names.

**Comment by gottfriedleibniz** [comment]
Closing this issue as stale. If this feature request/RFC needs to be revived the [forums](https://forum.cfx.re/c/general-discussion/feature-requests/33) would be the place to have it.

The discussion here has been productive.
