### ISSUE TITLE
I get a Error

### ISSUE THREAD

**Issue by Nexusbest** [citizenfx/fivem#1575]
I get a Error
C:\Users\Administrator\Desktop\fivem-master\fivem>fxd gen -game five
gen.ps1: Exception calling "Parse" with "1" argument(s): "Value cannot be null. (Parameter 'input')"

**Comment by thorium-cfx** [comment]
Taking a quick look, I would think the `vswhere.exe` input might return null here. If that's so then it would leave me to believe that Visual Studio isn't found/recognized on your system.

To be sure that is/isn't the issue, go into `fivem/code/tools/ci/` with PowerShell and execute `./vswhere.exe -prerelease -latest -property catalog_buildVersion -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` (the same as the script). It should return your VS version.

**Comment by Nexusbest** [comment]
Not working.
