### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Nexusbest** [citizenfx/fivem#1578]
C:\Users\Administrator\Desktop\fivem-master\fivem>fxd gen -game five
...fivem-master/fivem/code/vendor/boost_program_options.lua:6: attempt to concatenate a nil value
stack traceback:
        ...ministrator/Desktop/fivem-master/fivem/code/premake5.lua:554: in metamethod '__concat'
        ...fivem-master/fivem/code/vendor/boost_program_options.lua:6: in field 'run'
        ...sktop/fivem-master/fivem/code/tools/build/components.lua:434: in function 'do_vendor'
        ...ministrator/Desktop/fivem-master/fivem/code/premake5.lua:551: in function <...ministrator/Desktop/fivem-master/fivem/code/premake5.lua:8>
        [C]: in function 'xpcall'
        ...ministrator/Desktop/fivem-master/fivem/code/premake5.lua:8: in main chunk
        [C]: in ?
        [C]: in function 'dofile'
        [string "src/_premake_main.lua"]:109: in field '?'
        [string "src/base/_foundation.lua"]:62: in function 'premake.callArray'
        [string "src/_premake_main.lua"]:225: in function '_premake_main'

**Comment by thorium-cfx** [comment]
I get the high suspicion you are not following the build steps at all (just like #1575), as these reports are also not mentioning these steps. Next time make a proper issue report for actual bugs, for support go to the forums https://forum.cfx.re/.

https://github.com/citizenfx/fivem/blob/master/docs/building.md
