### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nexusbest** [citizenfx/fivem#1579]
2>C:\libraries\boost_1_71_0\libs\locale\src\win32\lcid.hpp(12,10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "boost/locale/config.hpp": No such file or directory
2>C:\libraries\boost_1_71_0\libs\locale\src\util\default_locale.cpp(10,10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "boost/locale/util.hpp": No such file or directory

When i run fxd vs -game five its come the error.
Please help

**Comment by thorium-cfx** [comment]
`No such file or directory`
