### ISSUE TITLE
LibertyM stuff...

### ISSUE THREAD

**Issue by AliceTS1337** [citizenfx/fivem#1582]
Hi.

What are the current status of LibertyM? 
Any off-chance that you'll create some binaries for us to play around with?
I know a pretty big community that would certainly love LibertyM, as would I. I'm just hoping to see any further updates to this project. :)

**Comment by thorium-cfx** [comment]
Sorry this is not the place for feature requests and/or other requests non-bug related.

Though I appreciate the interest in the LibertyM project, feel free to ask on the forums https://forum.cfx.re/

**Comment by AliceTS1337** [comment]
Oh yeah, my bad.
