### ISSUE TITLE
FIVE M ALLOWING 2 OF THE SAME LICENSES JOIN

### ISSUE THREAD

**Issue by Dark3581** [citizenfx/fivem#1585]
As a server owner we have discovered the users may duplicate their five m with their same LICENSE allowing the user to join with the same identifiers except their five m identifier. Allowing the user to be in the server 2 times with the same license allowing the user to be able to dupe or even severely break the server. In some cases the user shows up as nill but was still allowed to load in with the same  LICENSE  and different server id's. 

https://cdn.discordapp.com/attachments/909584306760990830/1010671052516491395/unknown.png
https://i.imgur.com/9S0thRq.png
https://i.imgur.com/j1cjWw1.png

NOTE THIS IS A GAME BREAKING ISSUE.

**Comment by blattersturm** [comment]
> Allowing the user to be in the server 2 times with the same license allowing the user to be able to dupe or even severely break the server. 

'dupe' isn't something handled by game code itself. If this is an issue breaking your scripts, fix your scripts.

**Comment by Dark3581** [comment]
Idk I would think there should be a handler checking if they are already in a server so its not just server specific but I guess could make our own handler for that either way should have been built in.

**Comment by AvarianKnight** [comment]
Why would it be built in when its _intentionally_ like this? What would be the point of being able to launch a second client if you can't even use it to join your test server?

If you want this to not be possible keeping a list of joined identifiers isn't costly and just reject them connecting if their identifier already exists

**Comment by Dark3581** [comment]
Oh okay, if its intentional then that makes a little more sense, thanks.

**Comment by blattersturm** [comment]
Similarly, what if someone has an authentication system that allows selecting, say, multiple characters, and they actually *want* to use them at the same time?

What if someone wants to have a custom set of overlapping identifiers to allow?

Any such thing being 'built in' would ruin the flexibility of the platform, and it rather should have been 'built in' to the system you're using for player data.
