### ISSUE TITLE
Function reference gets type `table` when using type() in lua

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/fivem#1586]
When using `type(var)` in lua (lua 5.4 and/or oal enabled doesn't make a difference) and sending a function ref to the argument of `type`, will return `table` instead of `function`, the following code provided is to reproduce it, I am on FXServer 5802.

Client code
```lua
local test = function() end

CreateThread(function()
    TriggerServerEvent('testEvent', test)
end)
```

Server code
```lua
RegisterNetEvent('testEvent', function(func)
    print(type(func)) -- This prints table
end)
```

**Comment by maicek** [comment]
So, you can check is that a function by checking that table have __cfx_functionReference value

**Comment by BerkieBb** [comment]
You can't index a function reference because it will give you an error that you can't, it's a function

**Comment by maicek** [comment]
It's done this way for cross-resource function calling (and/or some other reasons), and I think it's hard to "fix" and any attempt of fixing this issue would brake backwards compatibility

**Comment by BerkieBb** [comment]
How would it break backwards compatibility if you can't do anything inside the table either way

**Comment by maicek** [comment]
> You can't index a function reference because it will give you an error that you can't, it's a function

I have done this way in one of my scripts and this works, if I get logged into git repo I can se z you an code example

**Comment by BerkieBb** [comment]
I literally just tested it, it's not possible

**Comment by BerkieBb** [comment]
You get the error `Cannot index a funcref`

**Comment by maicek** [comment]
It's souch weird issue, because I'm pretty sure that I have done check for funcref this way.

**Comment by maicek** [comment]
There is one more problem, i didnt ever seen in any fivem code (i have lot of fivem coding exp.) The case and actual usage for passing function as argument in net events, i didnt think that is supported as valid data type for event payload, and I think this won't work when it's only function reference and not actual function bytecode to execute.

**Comment by BerkieBb** [comment]
This is just an example, the original code I used had function references passed through exports, but this is actually supported and it's used for callbacks in the biggest frameworks for example, you'd know that with your fivem conding experiences

**Comment by BerkieBb** [comment]
> It's such weird issue, because I'm pretty sure that I have done check for funcref this way.

I just checked again and you can actually, I messed up by misspelling functionReference in my test code, so `func.__cfx_functionReference` will return a string, so I can check using that if it is a function reference, although I still think it's a bit of a hacky way

**Comment by maicek** [comment]
Exports are intended to use with function types they are not an network events which its listeners does not have the same loaded code that can be executed. I know only that passing functions on same env C <-> C and S <-> S works,  C <-> S imo will never work.

**Comment by BerkieBb** [comment]
> C <-> S imo will never work

That's literally what callbacks do, they've existed for years and work

**Comment by maicek** [comment]
> > C <-> S imo will never work
> 
> That's literally what callbacks do, they've existed for years and work

Nope, for example ESX in callbacks triggers an server event and registers an hander for client callback that executed provided function

**Comment by maicek** [comment]
https://github.com/mitlight/es_extended/blob/master/client/functions.lua#L77-L87 

Some code from one of es_extended fork repo

**Comment by BerkieBb** [comment]
https://github.com/esx-framework/esx-legacy/tree/main/%5Besx%5D/es_extended
Here is the original repo if you didn't know, which is still being updated

**Comment by maicek** [comment]
This have also the same callbacks logic source code

**Comment by BerkieBb** [comment]
I know, I'm just linking the original since you linked a fork

**Comment by BerkieBb** [comment]
But qb-core callbacks do call from client -> server -> client
Server callback registered: https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua#L114
Server callback getting triggered: https://github.com/qbcore-framework/qb-core/blob/main/client/functions.lua#L130
Event triggering it: https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua#L114
Client event calling the function reference for the callback: https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua#L191

**Comment by AvarianKnight** [comment]
This seems intentional/by design, and the "hack" is also the same thing used in the scheduler

https://github.com/citizenfx/fivem/blob/523934ddc9d3a053dc3465a20a9f25e0b88d197b/data/shared/citizen/scripting/lua/scheduler.lua#L459-L469

**Comment by BerkieBb** [comment]
Hmm, alright, I guess we won't see a change in this at all then, thanks for the information though!

**Comment by blattersturm** [comment]
... what are you even trying to do here and how does this lead to 21 comments not saying anything of note at all?!

**Comment by BerkieBb** [comment]
> ... what are you even trying to do here and how does this lead to 21 comments not saying anything of note at all?!

I had a check like this
```lua
local callback = type(someTable[value]) == 'function' and someTable[value] or type(someTable[value]) == 'table' and someTable[value].cb or someTable[value].callback
```
And this would always lead to an error (`Cannot index a funcref`) if a function reference was the value (which it only was because of backwards compatibility for the script that it was in. So I debugged it and found out that function references get the type `table` instead of `function` and found that weird
