### ISSUE TITLE
Error: Assertion failure: instance.GetRef() (C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\shared\Registry.h:164)

### ISSUE THREAD

**Issue by Yum1x** [citizenfx/fivem#1589]
I'm trying compile a custom version of FXServer but this error is showing when I try start the server.

![message error](https://i.imgur.com/AGsqq7s.png)
![message error console](https://i.imgur.com/aUUNBBA.png)

Compiling old versions doesnt throw any error, this should be related with the recent """escrow system break"""?

**Comment by YanQuote** [comment]
Hi, Did you check all prerequisites to build fxserver ? (docs/building.md)
Did you have right version of VS and other tools ?

If yes try launch fxserver without any type of modification.

**Comment by Yum1x** [comment]
> Hi, Did you check all prerequisites to build fxserver ? (docs/building.md) Did you have right version of VS and some other tools ?
> 
> If yes try launch fxserver without any type of modification.

There is my setup
![visual studio setup](https://i.imgur.com/GHaHvLZ.png)

I think it's all correct. I've compiled a version from 2 months ago and didn't got any problem. I keep thinking it's something relationed with the recent "escrow system break" ...
Maybe @blattersturm could say something about this ...

**Comment by blattersturm** [comment]
Using `svadhesive` on an open source build is not supported.

**Comment by biyeicito** [comment]
Explain better
