### ISSUE TITLE
Random Crash In Server - Unknown Cause

### ISSUE THREAD

**Issue by LilMochaZ** [citizenfx/fivem#1594]
![CrashPic](https://user-images.githubusercontent.com/97256967/186790309-7c4b4f02-010d-4a99-85fe-facf200cc28e.png)

[Window Title]
Error GTA5_b2545.exe!sub_140A9F8C8 (0x38)

[Main Instruction]
GTA5_b2545.exe!sub_140A9F8C8 (0x38)

[Content]
An error at GTA5_b2545.exe!sub_140A9F8C8 (0x38) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: oscar-timing-kitten
Stack trace:
  GTA5_b2545.exe!sub_140A9F8C8 (0x38)
  GTA5_b2545.exe!sub_140ACEC28 (0x6c)
  GTA5_b2545.exe!sub_140AC051C (0xa7)
  GTA5_b2545.exe!sub_140AC0688 (0x40)
  GTA5_b2545.exe!sub_140ADFBC4 (0x84)
  GTA5_b2545.exe!sub_14087F17C (0x4d)
  GTA5_b2545.exe!sub_141604E2C (0x195)

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b2545.exe+A9F900
Report ID: si-59b94bc7ef9449c3a91962fb5224c398
You can press Ctrl-C to copy this message and paste it elsewhere
[CfxCrashDump_2022_08_23_03_45_25.zip](https://github.com/citizenfx/fivem/files/9428878/CfxCrashDump_2022_08_23_03_45_25.zip)
.

Server user reports its happened a few times, can be random or when driving along, she claims she isn't doing anything when it happens, so unsure of cause. hopefully all the above can help us figure this out. Thanks in advance for taking your time to look into this.

**Comment by blattersturm** [comment]
This is not a support section.
