### ISSUE TITLE
FXServer-no-version After building

### ISSUE THREAD

**Issue by usershhh** [citizenfx/fivem#1595]
Hello, after building the Windows artifact, there is no nucleus authentication and when I make a request on the following path: 127.0.0.1:30120/ it answers me: "{"version":"FXServer-no -version (didn't run build tools?)"}", here is the command I used to build: "fxd build -game server".

Thanks for you help

**Comment by blattersturm** [comment]
This is not an issue, nor is this a place to receive 'help'.
