### ISSUE TITLE
[Mumble] Same client ip when using a proxy hit the 32 default limit 

### ISSUE THREAD

**Issue by joelwurtz** [citizenfx/fivem#1596]
Since https://github.com/citizenfx/fivem/commit/04af423c8496be1c0e2872a1ee850fd114eda5d5

When using mumble and having a tcp proxy in front of the fivem server, the client ip address is always the one from the tcp proxy (when using a configuration similar to https://docs.fivem.net/docs/server-manual/proxy-setup/)

So after reaching 32 players new players cannot connect to mumble.

I'm not sure if we can get the real ip address (i think nginx create a connection and copy input stream to output stream, it's not a passthrough)

The current work around is to upgrade the max client per ip limit with the convar however i'm not sure if it's a desired behavior ?

It's not really problematic, since there is a work around, but IMO this should be documented (either in the proxy setup or in the patch note) as I consider this to be a BC break

**Comment by blattersturm** [comment]
Thanks, this has been added to the pending changelog entries for the next server 'recommended' bump.

However, this is not an actionable issue for this repo.
