### ISSUE TITLE
sv_purelevel doesn't work with dev mode as it switches to production mode every time

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1600]
When joining a pure level server, it switches to production mode, when in dev mode.

**Comment by blattersturm** [comment]
This doesn't seem very important to fix. Any particular use case here?

**Comment by mcNuggets1** [comment]
Developing on a server with purelevel 1 or 2 enabled?
I can't profile properly, I can't see streaming stats, nor the resource monitor which is crucial to test on my live server

**Comment by blattersturm** [comment]
If you're _actually_ 'developing' you probably can use `beta` or `latest` update channels fine.

**Comment by mcNuggets1** [comment]
Not when the server is in pure mode I believe.
It always kicked me from it. It's mandatory to check performance with more than 1 player...

**Comment by blattersturm** [comment]
> Not when the server is in pure mode I believe.
> It always kicked me from it.

There is nothing in platform code itself that'd do this, so this seems like either a script or other user error.

**Comment by mcNuggets1** [comment]
When i connect it says I have to switch branchs before joining.
Its not by a server script, not at all. Disabling pure mode removes that too.
