### ISSUE TITLE
FXServer crashed. latest version [5845]

### ISSUE THREAD

**Issue by omar-othmann** [citizenfx/fivem#1601]
Hello, i have reinstall my Linux server, and i want to install FXServer on it, but i got FXServer crashed when i start it

Install commands:
1- mk dir server
2- wget https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5848-4f71128ee48b07026d6d7229a60ebc5f40f2b9db/fx.tar.xz
3- tar -xf fx.tar.xz
4- screen ./run.sh

crash file:
[49e389c2-623b-409b-d3fc249d-d108750c.zip](https://github.com/citizenfx/fivem/files/9472003/49e389c2-623b-409b-d3fc249d-d108750c.zip)

crash image:
![image](https://user-images.githubusercontent.com/34454535/187975620-5b2b0c75-e672-4a94-b452-bc0213b21a13.PNG)

Linux version:
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by blattersturm** [comment]
This doesn't seem reproducible and Linux dump files are useless, similarly your distro setup seems screwed as it 'failed to automatically report the crash'.

Closing as not actionable/not enough info.
