### ISSUE TITLE
Clicking image in changelog soft locks UI

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#1604]
# Repro
Open 5848 changelog
Click image
Proceed to be stuck

# Additional notes
You can get out of this by using hardware back buttons like the rear side button on some mice, it seems to just open the image directly with no way out of it without other than that (escape, backspace, etc do not work)

(i suspect the new ui negates this issue, but its so minor it took 30 seconds to write this so doesn't hurt)

**Comment by blattersturm** [comment]
> i suspect the new ui negates this issue

yes

> but its so minor it took 30 seconds to write this

nice

> so doesn't hurt

probably took me more than 30 seconds being puzzled as to why you're even making an issue and not, say, a chat message or something less annoying than yet another frivolous issue
