### ISSUE TITLE
Add linux support for full crash dumps

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1606]
Shouldnt really only be for windows.
Can't figure out a crash and now I'm stuck forever in this hellhole loop.

**Comment by blattersturm** [comment]
This isn't something we can 'just add support for'. The Linux debugging ecosystem is a mess and you're going to have to get *them* to fix this and make anything consistent like how Windows has dbghelp/dbgeng.

**Comment by mcNuggets1** [comment]
Anything to mitigate crashes then at all?
My server keeps crashing with non helpful shitty information like monotone runtime errors relating to A native

**Comment by blattersturm** [comment]
Replicate the issue you're experiencing on Windows, so information can be provided and an actual fix can be implemented.

I'm locking this issue now as this isn't a support forum.
