### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by S1NGer-iwni** [citizenfx/fivem#1608]
I have visual studio 2022 installed, I did everything according to the instructions, what is the problem?
========== Build: 88 succeeded, 4 failed, 92 up-to-date, 0 skipped ==========
one of the problems is related to WinRT, but I do not know how to fix it, the second problem is that there are no Hash and API classes
![unknown_2022 09 05-20 17](https://user-images.githubusercontent.com/52863123/188459041-295fb5b5-308e-4657-897a-3936d4113fd0.png)

**Comment by blattersturm** [comment]
This is still not a support section, and this sounds like you don't have the required OS dependencies installed - without repro this isn't actionable for us.
