### ISSUE TITLE
getUserMedia: Uncaught (in promise) NotAllowedError: Permission denied

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#1609]
On Canary when using `navigator.mediaDevices.getUserMedia({ audio: true })`
I get the following error: 
` CrBrowserMain/ Uncaught (in promise) NotAllowedError: Permission denied`

Before it was asking to allow using F8

**Comment by blattersturm** [comment]
Right, I guess there's an incompatibility/missed-something in the media access patch set port. Queued for investigation.
