### ISSUE TITLE
Crash Console

### ISSUE THREAD

**Issue by Royalstick** [citizenfx/fivem#1610]
Hello, sometimes, for no reason, like 1 time month, i got this crash. That crash all my server. 
![crash novo](https://user-images.githubusercontent.com/93442609/188517490-2316ad5b-e5a4-4820-bcc5-648ef1157d58.png)

**Comment by blattersturm** [comment]
Hello, sometimes, for no reason, like 1 time day, i got this kind of post. That annoy all my mood.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/24576130/188517950-fa1fccc8-65ea-4394-9d06-4247c5a2f5de.png">

---

This is not a support section, and what you posted isn't remotely close to actionable.
