### ISSUE TITLE
Cheat method in `PlaySound` natives

### ISSUE THREAD

**Issue by AmIrReZa386** [citizenfx/fivem#1616]
Hi Cfx.re dev's,

Some cheater's today use this LUA code & play sound on all players very easily :
 ```
PlaySound(-1, 'Bomb_Disarmed', 'GTAO_Speed_Convoy_Soundset', true)
```
**no native** & **no method** for block this cheating !
please add **new native** or **new method** for **get list of sound id's** from player's & we can stop that

**Comment by blattersturm** [comment]
why the **bold**

also this is **not** a **place** for feature **requests**
