### ISSUE TITLE
Anti aliasing of background images changed with new CFX UI Update

### ISSUE THREAD

**Issue by DeForce** [citizenfx/fivem#1619]
Looks like the new CFX UI Update comes with changes to web engine and changes the way aliasing is done for `background-image`

Though it's interesting that I have the same issue just opening the test resource in a browser, so I guess it's not a CFX bug, but mostly an unintended issue of an update.
I can replicate it by setting `.size` element to `image-rendering: pixelated`, but changing background image image-rendering doesn't do anything.
So I'm not sure if CFX can do anything about it.

Unstable release:
![FiveM_b2372_GTAProcess_NHlECPUnK8](https://user-images.githubusercontent.com/7394420/189312519-abb24d0f-87f3-4de5-8dcb-eee664da325b.png)
![FiveM_b2372_GTAProcess_4183y4jN78](https://user-images.githubusercontent.com/7394420/189312612-2ca8caeb-7673-425c-81ad-0fbea060a6db.png)

Stable release:
![FiveM_b2372_GTAProcess_szTSgpsxq0](https://user-images.githubusercontent.com/7394420/189312546-bb1af6e4-fc0e-4ac5-91a0-daec1626e83c.png)
![FiveM_b2372_GTAProcess_cV2M2QEMqU](https://user-images.githubusercontent.com/7394420/189312635-581ebb9b-4071-4ce6-ba99-0a53f2ae4cec.png)

Test resource attached.
[test.zip](https://github.com/citizenfx/fivem/files/9534002/test.zip)

**Comment by blattersturm** [comment]
> that I have the same issue just opening the test resource in a browser

Probably a web platform incompatibility/change, then.

Try looking on https://crbug.com/ if there's anything that looks related.

**Comment by DeForce** [comment]
Yup, that looks like the issue, I had 104 installed. 105 fixed the issue

**Comment by blattersturm** [comment]
Backported the Chromium patch (https://github.com/citizenfx/chromium/commit/d05d08c11961400aecc7eca42d33827d2e9b63d5) and it seems to work fine now.
