### ISSUE TITLE
Features Request/Question: Linux Client

### ISSUE THREAD

**Issue by AroPix** [citizenfx/fivem#1622]
Since shared resources was merged into dxvk, will there be any possibility of a FiveM client for linux?
Here is the pull request, that was merged manually: https://github.com/doitsujin/dxvk/pull/2516

**Comment by AvarianKnight** [comment]
This isn't the place for feature requests or questions, those should be delegated to the [forum](https://forum.cfx.re/)

You can already run the FiveM client on Linux just not in "Secure Mode" (aka adhesive is disabled) as it would require a decent overhaul to the anticheat system which isn't something that is likely to be done any time soon (if ever)

**Comment by AvarianKnight** [comment]
You can also see some previous discussion about this [here](https://forum.cfx.re/t/e-e-engine-update-vulkan-only-shared-resource-less-linux-client/3717234)

**Comment by AroPix** [comment]
> You can also see some previous discussion about this [here](https://forum.cfx.re/t/e-e-engine-update-vulkan-only-shared-resource-less-linux-client/3717234)

Thanks for pointing that out, i didn't know that there already was a discussion. Closing it now.
