### ISSUE TITLE
[Suggestion] Server priority slots

### ISSUE THREAD

**Issue by nzkfc** [citizenfx/fivem#1628]
Apologies if this isn't the right please, but I couldn't figure out where to suggest a feature as part of FiveM as im used to using frameworks and such ontop of FiveM.

I was wondering if it's possible to add a feature of reserved slots for FiveM servers, so you can still get staff right in but also have queue scripts managing anything above the normal slots for general players.

Prob a long shot, but worth a try.

**Comment by nikez** [comment]
Hi,

This is definitely the wrong place for this. Why don't you just reserve a number of slots in your queue manager for staff? We do, and there's zero issue with that. This is something that is up to the servers to manage, not CFX.

Please use the forums.

**Comment by titanium-cfx** [comment]
Hello, 
As mentioned by @nikez, this is a feature that you have to implement directly in your queue resource.
I believe some open-source ones do already support this feature even. :) Take a look at our forums!

(This is also not the place for feature requests, use our forums for that.)
