### ISSUE TITLE
Client crash when drawing emojis

### ISSUE THREAD

**Issue by Ekinoxx0** [citizenfx/fivem#1629]
Hi, it seems there is a return of a crash that was previously fixed in #1572 
Was apparently fixed in a private commit `fivem-private@0e12b5487213ad821d8d70741fee7bbe0abd5a1b`
But is now is present in Release and Unstable today (tested on b2699)

The repro from @rdelian is still valid and you can find it here : https://github.com/rdelian/repro_gfx_err/blob/main/client.lua

Here is also a CrashDump : [CfxCrashDump_2022_09_13_22_24_36.zip](https://github.com/citizenfx/fivem/files/9561217/CfxCrashDump_2022_09_13_22_24_36.zip)
[CfxCrashDump_2022_09_13_22_30_43.zip](https://github.com/citizenfx/fivem/files/9561220/CfxCrashDump_2022_09_13_22_30_43.zip)

My first try of a full memory dump : https://drive.google.com/file/d/1rTi319fdedznHrRBpc6HjnfiVjQI-Rdq/view?usp=sharing

Thanks for the work you do 👍

**Comment by blattersturm** [comment]
Fixed (again) it seems.
