### ISSUE TITLE
Error trying to build fivem

### ISSUE THREAD

**Issue by DaniGP17** [citizenfx/fivem#1630]
Hello, good morning, I have a problem, I am trying to compile fivem from visual studio 2019, but I am encountering several errors, when I look at the code many parts are underlined in red saying that they are not defined, at the beginning of many files appear #include <package-name.h> but many of the include ma are underlined in red.
![image](https://user-images.githubusercontent.com/96537843/190147947-640e0070-857d-4af9-8484-6f8f2daedc9a.png)
I have followed the steps in the documentation of the build.md file but I have run into some problems, I have installed all the requirements that are indicated at the beginning of the file, but when I run the code 'fxd vs -game five' I get an error saying that a file was not found and after a few seconds the project will open in visual studio 2019 and if I open any file I see that many words are underlined in red.
![image](https://user-images.githubusercontent.com/96537843/190149331-d6710a13-3c8e-4d77-b0ad-fa18f96adc97.png)
I don't know if this has anything to do with it but when I run the command 'git submodule update --jobs=16 --init' I get an error, to solve this I have manually installed each submodule one by one.
![image](https://user-images.githubusercontent.com/96537843/190149094-f0d3f818-6a22-44d3-8398-e9f9088087d6.png)

**Comment by PRMerger935** [comment]
I also have a problem using the Five

**Comment by DaniGP17** [comment]
I find, that we've to install sdk of windows 11 in visual studio, but in the build docs, they don't say anything about that.

**Comment by luccasbr** [comment]
Did you manage to build the project? I installed windows 11 sdk but when I go to build the solution in visual studio I get many errors but the first one is:

`>------ Build started: Project: botan, Configuration: Debug x64 ------
3>No C:\Users\lucas\Desktop\fivem\code\tools\build\run_prebuild.ps1:79 caractere:2
3>+     throw "natives failed 2"
3>+     ~~~~~~~~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : OperationStopped: (natives failed 2:String) [], RuntimeException
3>    + FullyQualifiedErrorId : natives failed 2`

In the run_prebuild.ps1 script there is a reference to a file "code\client\clrcore\NativesFive.cs" which does not exist in the project.

**Comment by DaniGP17** [comment]
> Did you manage to build the project? I installed windows 11 sdk but when I go to build the solution in visual studio I get many errors but the first one is:
> 
> `>------ Build started: Project: botan, Configuration: Debug x64 ------ 3>No C:\Users\lucas\Desktop\fivem\code\tools\build\run_prebuild.ps1:79 caractere:2 3>+ throw "natives failed 2" 3>+ ~~~~~~~~~~~~~~~~~~~~~~~~ 3> + CategoryInfo : OperationStopped: (natives failed 2:String) [], RuntimeException 3> + FullyQualifiedErrorId : natives failed 2`
> 
> In the run_prebuild.ps1 script there is a reference to a file "code\client\clrcore\NativesFive.cs" which does not exist in the project.

Same problem, I have not achieved

**Comment by neptunium-cfx** [comment]
Hi, this is not a place for support, please use our discord guild or forums.
