### ISSUE TITLE
NUI's lang config

### ISSUE THREAD

**Issue by teidova21** [citizenfx/fivem#1637]
As said in this topic :
https://forum.cfx.re/t/fivem-nui-cef-browser-language-defaults-to-en-us/2620378

There is no way to change locale of NUI's chromium, restricting some features like date input formats.
Maybe add a resource manifest directive to set nui lang accordingly, or read the html lang arg.

**Comment by blattersturm** [comment]
This *still* isn't a place for feature requests.
