### ISSUE TITLE
GetWeaponDamageModifier broke on canary

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#1638]
Take a bat in your hands then run
SetWeaponDamageModifier("weapon_bat", 0.15)
return GetWeaponDamageModifier("weapon_bat")

On canary
=> result is 39322

On release
=> result is 0.15

most likely related to
https://github.com/citizenfx/fivem/pull/1617

**Comment by 4mmonium** [comment]
Yeah, looks like there's an incorrect cast type (possibly caused by a typo) when being dereferenced right [here](https://github.com/citizenfx/fivem/pull/1617/files#diff-1192340d9d44456793c779143605b5695f47a10c0a8ae54570c2e14112981c8fR332) will try and create a PR to address this.
