### ISSUE TITLE
RedM - Wrong Player receives TriggerEvent's

### ISSUE THREAD

**Issue by R0ckzo0r** [citizenfx/fivem#1642]
Since last Versions, maybe 5848, there are duplicated player objects available or duplicated networkId's/ handles.

Sometimes a fresh connected player already exists or has the same ref/ handle and a player who is connected already receiving its events turning him into the player who connected.

Maybe there is an indexing or ref error or something else

I already debugged the networkId's on each connect and after client scripts etablished, which are not the same. But still a wrong player is receiving events.

this is not always, but sometimes, many times a day.

Framework Serverside and clientside are both C#. Connected Player on Primetime are over 300-350+.

If there are any questions contact me through dc R0ckzo0r#1503 or here. Im willing to help to find this error nor get rid of it.

Greetings.

**Comment by blattersturm** [comment]
This still isn't an actionable work item, so it still doesn't belong here. Ask on the forums instead.

**Comment by R0ckzo0r** [comment]
What do you mean by that. It is an error in the API of FiveM/RedM. 

Who should fix it by asking in the forums.

**Comment by R0ckzo0r** [comment]
Its not a Question its a bugreport. 

How can it be possible if i use TriggerEvent on a fresh connected Player, that another Player will be triggered.

**Comment by titanium-cfx** [comment]
GitHub issues are meant for actionable work items.
In its current state, your post is very vague and doesn't provide any real information to be able to pinpoint the issue you're describing. We need proper reproduction steps or any relevant debugging information to be able to act on such.

Using the bug reports section is your best bet for this situation, and we will make it into an actionable work item once we have everything we need to be able to properly investigate this issue.

**Comment by R0ckzo0r** [comment]
Ok got it, thanks. 

I whish i could reproduce this and provide every information to you. But im also serious that there is no other RedM Server who can have this kind of issue or help me with that, because we are the only populated server with 350+ players using c# and not 200+ lua scripts.

So maybe there is any way of getting some information that i can use to get rid of this problem nor provide detailed information to you.

im using the ref of the Player object provided on an incoming event as source after the client etablished connection and wrap is to an seperate CorePlayer on our Backend. The whole Backend is developed with a service provider.
Im also using a WebSocket to receive and send events after intializing that ManagedPlayer to avoid problems like this. Every Event from Server to Client or Client to Server, sent nor received with our WebSocket is clean and without any error.

So yeah, you guys know your code so maybe i could get some hint.

And sorry if i start a discussion here. but im watching and debugging this kind of issue for the last 10 days now to get any clue of it whats going wrong.

Unless there is nothing you can do or tell me its maybe the best option to not use the TriggerEvent or TriggerServerEvent anymore.

Its not like im doing this for some weeks now. Im developing Servers for the last 7 Years now and on other platform's (RageMP, alt:V) i was always in good contact with the dev's behind it to find bugs and fix this things.

**Comment by blattersturm** [comment]
Adding to this, the .NET scripting runtime is shared across FiveM and RedM, as is the trigger-event logic. There's a lot of servers _on FiveM_ where this works well for C#, so it's likely you either have something odd going on in your code, or your code is hitting some edge case that other people don't.

Either way, the description here is simply not actionable, as 'players get randomly swapped around' isn't something that should remotely be able to happen.

**Comment by Disquse** [comment]
I've been actively monitoring the RedM's ecosystem for the last few years. One of the most popular frameworks out here (VORP) is build mostly in C#. I feel like if there really was any issues related to RedM/.NET scripting people would've already reported this numerous times. There may be some very nasty edge case that breaks some logic, however, as said earlier, it is impossible to find out what exactly happens without your help (reproduction steps, some additional info, pieces of code and  etc).

**Comment by R0ckzo0r** [comment]
Thanks again for your replay. I'm sorry if it came across wrong, but that's more due to my English in words.
