### ISSUE TITLE
Make speed boosting activatable and deactivatable

### ISSUE THREAD

**Issue by Nova-px** [citizenfx/fivem#1643]
Most servers don't like that "feature" and forbid it through their rules.
It would be a good option to enable and disable that feature via a native or server setting. The fix got removed in bd66d73dcec6d632664f1950b5bb94c3a64f48ba

**Comment by KratomDev** [comment]
Can you even "remove" speed boosting?

**Comment by Nova-px** [comment]
> Can you even "remove" speed boosting?

The fix got removed, which you can see here https://forum.cfx.re/t/fix-extra-natives-five-remove-nop/3410133

**Comment by KratomDev** [comment]
That's really nice, Great suggestion.

**Comment by neptunium-cfx** [comment]
Hello,
This is not the place for feature requests. Please use our forums for that, thank you. :)

**Comment by blattersturm** [comment]
Are you maybe looking for https://docs.fivem.net/natives/?_0xA42A3DBF instead?
