### ISSUE TITLE
C#: Inheriting from ServerScript results in no script initialization on Linux

### ISSUE THREAD

**Issue by cm8263** [citizenfx/fivem#1648]
Discovered here: https://github.com/inferno-collection/Ladders-Reborn/issues/6

Inheriting from `ServerScript` instead of `BaseScript` in server resources results in no script initialization on Linux server artifacts. There appears to be no issue with using `ServerScript` in Windows server artifacts.
Interestingly, the resource still "starts" (see below), however, `Instantiated instance of script X.Y.Z` is not outputted.

![image](https://user-images.githubusercontent.com/10535902/193379388-a676746c-6de0-44d1-be12-b46f596d7b5a.png)

Reproduction steps and further discussion can be found in the linked issue.
***
I understand that other than this commit https://github.com/citizenfx/fivem/commit/304f787be3ae9a2a6f0365688318512ea69b1cfe `ServerScript` is not documented anywhere nor recommended to be used, as such I'm creating this issue so others might find it if they come across the same problem as I did.

**Comment by 0rangeFox** [comment]
I can confirm that this error is actually true, I have experienced it. At least on the Linux side, yes. But I never tried windows because I only create servers only on linux.

**Comment by thorium-cfx** [comment]
I wasn't able to replicate this on Linux.

Are you supplying your own `CitizenFX.Core.dll` or referencing any other assembly who's `ServerScript` class you are inheriting?

**Comment by cm8263** [comment]
No and no, you can see the source code in the repo of the linked issue.

Three, possibly four people have been able to repro this on Linux, so something funky is definitely about.

**Comment by thorium-cfx** [comment]
It's not that I don't believe you, just that I'm unable to repro it with the given details/steps.

If you can make a minimal repro, then I can have a better look. The source code you mentioned is a bit too much.

**Comment by thorium-cfx** [comment]
@cm8263 and I managed to narrow the issue down to the NuGet/reference assemblies.

Turns out the reference/forwarding assembly `CitizenFX.Core.Server.dll` doesn't include a type forward for class `ServerScript` on Linux whereas the Windows version does. When overwriting the assembly on Linux with the Windows variant it works as expected.

**Comment by thorium-cfx** [comment]
> ... that's odd, these should be generated as part of the build process. Where does this one come from for Linux?

found the culprit! [`fivem\data\server_linux\citizen\clr2\lib\mono\4.5\CitizenFX.Core.Server.dll`](https://github.com/citizenfx/fivem/blob/master/data/server_linux/citizen/clr2/lib/mono/4.5/CitizenFX.Core.Server.dll)

**Comment by blattersturm** [comment]
Indeed - oddly enough, clrref is enabled to build for Windows, only, and it _appears_ the pre-built reference DLL predates the ServerScript PR.

https://github.com/citizenfx/fivem/blob/ba3b938b4a227d1e6f997d61ea98013ec11d6c79/code/premake5.lua#L477-L478

**Comment by blattersturm** [comment]
Enabling it for Linux build leads to some errors regarding what seems to be missing `-r:` args to the C# compiler, investigating this now:

```
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(88,16): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(91,45): error CS0234: The type or namespace name 'Dynamic' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(94,53): error CS0234: The type or namespace name 'Dynamic' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(94,30): error CS0115: 'ExportSet.TryInvokeMember(Dynamic.InvokeMemberBinder, object[], out object)': no suitable method found to override
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(682,16): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(683,16): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(1079,23): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(1080,23): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(1081,23): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(1154,23): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
/mnt/w/cf/code/fivem-master-pub/code/client/clrref/server/CitizenFX.Core.cs(1163,23): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
```

**Comment by blattersturm** [comment]
... ah! This is actually done by GenAPI which requires a MSBuild project, and premake generates CitiMono as a Makefile.

**Comment by blattersturm** [comment]
Should be resolved now.
