### ISSUE TITLE
Can't set stamina more than 100

### ISSUE THREAD

**Issue by goblinbr** [citizenfx/fivem#1649]
I am trying to use SetPlayerMaxStamina and there's something strange.

If I want to set the stamina to 100 I have to use SetPlayerMaxStamina(playerId, 2147483647)

2147483647 is the max Integer value, if I try to send more than 2147483647 it set the player stamina to 0.000.....

I think it's because SetPlayerMaxStamina is only accepting Integer values and I think SetPlayerMaxStamina should convert the number, like if I want to set the max stamina to 100 I should call SetPlayerMaxStamina(playerId, 100)

PS: I am using lua script.

**Comment by neptunium-cfx** [comment]
Hi, this is not a place for support, please use our discord guild or forums.

**Comment by logan-mcgee** [comment]
except SET_PLAYER_MAX_STAMINA looks to take a float, have you actually tried `SetPlayerMaxStamina(playerId, 100.0)`?
