### ISSUE TITLE
OpenSSL SSL_read: Connection was reset, errno 10054

### ISSUE THREAD

**Issue by JakSar77** [citizenfx/fivem#1652]
Hello the player, when trying to connect, sees no problem, downloads approximately 290 files, some up to 10Mb, some up to 300Mb. However, for example, with 161/290 files it happens that when the file has 255Mb so with 160Mb it will hang for 30sec and the file will start downloading over and over again and maybe like this 5 times. Then for the next file the same thing. And it won't download.
In the user log it says: ResourceCacheDevice reporting failure downloading resource.rpf: OpenSSL SSL_read: Connection was reset, errno 10054 - CURL error code 56 (Failure when receiving data from the peer)

**Comment by JakSar77** [comment]
The firewall is completely down, both here and at the datacenter.

**Comment by blattersturm** [comment]
This is not a support section.
