### ISSUE TITLE
GetVehicleDeformationAtPos

### ISSUE THREAD

**Issue by imsnaily** [citizenfx/fivem#1661]
The native GetVehicleDeformationAtPos only works in a few car models in the last artifacts (5956)

**Comment by blattersturm** [comment]
It's a client native. How are 'artifacts' _possibly_ related to this?

(i.e. seems like you need to provide more info)

**Comment by blattersturm** [comment]
'completed'?

**Comment by imsnaily** [comment]
I found that the deformations it's not the same with all the car classes. For example supercars doesn't have a lot of deformations like sedans, so I think that is gta issue not fivem
