### ISSUE TITLE
First Person Vehicle Hood setting bugged.

### ISSUE THREAD

**Issue by Scullyy** [citizenfx/fivem#1663]
I originally had a PR open but it was closed due to other methods to avoid the mitigation. When the First Person Vehicle Hood setting is enabled other players can't see you aim, shoot or hear your gunshots when shooting from inside a vehicle. This is a major bug to both RP and PvP servers due to people being able to silently kill players. I don't believe the same thing happens in GTA online either as @blattersturm stated, I didn't test it myself but a friend did and he said it works as intended online. 
 
Video from evelyn#1571 in the cfx.re discord: https://drive.google.com/file/d/1tNRpT46-BqIODbEJbaN-OUYbGSQFpeeT/view evelyn#1571 source: https://discord.com/channels/192358910387159041/561197034938564608/979686764262326322

**Comment by blattersturm** [comment]
This still isn't the correct place for stuff that isn't actionable.

**Comment by blattersturm** [comment]
See #1662 and user's followup (originally a DM) at https://forum.cfx.re/t/confused-on-recent-bug-closed/4929799.
