### ISSUE TITLE
Getting error when trying to join server. PLEASE HELP!

### ISSUE THREAD

**Issue by BobaFettTea009** [citizenfx/fivem#1668]
Changing game build failed: Could not patch update/update.rpf. Do you have enough free disk space on all drives? (~2 GB)

I get this error when trying to join a server and I have plenty of space on my PC. Could I please get some help on how to solve this issue?

**Comment by Scxredx** [comment]
i have that too

**Comment by neptunium-cfx** [comment]
Hi, this is not a place for support, please use our discord guild or forums.

**Comment by Scxredx** [comment]
> Hi, this is not a place for support, please use our discord guild or forums.

I have there no permission to write in any channel lmao

**Comment by neptunium-cfx** [comment]
> > Hi, this is not a place for support, please use our discord guild or forums.
> 
> I have there no permission to write in any channel lmao

It's because we have a lot of spam regarding some issues right now.
