### ISSUE TITLE
FiveM 90% Download Fail

### ISSUE THREAD

**Issue by OakleyTesting** [citizenfx/fivem#1669]
FiveM failing download at 90% [after cache clear], and its at 90% every single time. 3 tries and its all been the same result.

**Comment by neptunium-cfx** [comment]
Hi, this is not a place for support, please use our discord guild or forums. We also know about that issue, and are working on it.

**Comment by OakleyTesting** [comment]
> Hi, this is not a place for support, please use our discord guild or forums. We also know about that issue, and are working on it.

brother i cant use the discord so imma use whatever i can

**Comment by ChatDisabled** [comment]
>brother i cant use the discord so imma use whatever i can

Brother, try using a brain next time. https://status.cfx.re/incidents/y1mgvmxr1fgg
