### ISSUE TITLE
When i installing server or updating Fivem is so slow but i have nice internet connection

### ISSUE THREAD

**Issue by AZRAILL13** [citizenfx/fivem#1670]
PLZ HELP

**Comment by Scxredx** [comment]
me too

**Comment by PurchasedGaming** [comment]
There is a current outage which is causing the FiveM updater to become slow and sometimes offline. Please see https://status.cfx.re/incidents/y1mgvmxr1fgg for more info

**Comment by PurchasedGaming** [comment]
f

**Comment by abumslm** [comment]
![لقطة الشاشة 2022-10-28 165329](https://user-images.githubusercontent.com/116895815/198630582-492f991b-ae93-424b-8f62-baa5ff2b01df.png)
I have a problem that I do not know how to solve
I have a nice internet connection?
