### ISSUE TITLE
When going to play a server this pops up. I have no idea how to fix it, does anyone know?

### ISSUE THREAD

**Issue by Trident0101** [citizenfx/fivem#1672]
![image](https://user-images.githubusercontent.com/116850841/198547337-6ed7c3f9-d663-48d9-8758-037e3f8123e2.png)

**Comment by neptunium-cfx** [comment]
Hi, this is not a place for support, please use our discord guild or forums.

**Comment by curiousstitches** [comment]
Clear your cache and try again
