### ISSUE TITLE
Error building fivem server

### ISSUE THREAD

**Issue by roboriba** [citizenfx/fivem#1674]
Hello, I have a problem with building fivem server. I followed the instructions exactly three times in a row but in the end I got stuck on this problem and I don't see a mistake anywhere on my side. Is it possible that there is a bug somewhere in the project?
![mvs_png](https://user-images.githubusercontent.com/76430291/198680037-6a34efa6-7d57-4a28-82c6-dcceeaf07fbb.png)
error MSB8066: Custom build for ... ended with code 1.

**Comment by thorium-cfx** [comment]
You are either missing `curl.exe` in your `PATH` or one of the `xcopy` commands fail. You may want to look into the mentioned `v8-93.vcxproj` file for the `CustomBuild` tag and make sure all commands in there can be executed.

**Comment by roboriba** [comment]
Hi, thanks for your help. Curl was generated incorrectly like this: curl "-zC:...." and not curl -z "C:....". But now I have a problem with the error: "Failed to create environment, hresult 80070002" It's probably my fault, but I don't know where. I am attaching a screenshot.
![mvs_png](https://user-images.githubusercontent.com/76430291/198708946-e1bcf774-fd4c-492a-94ff-35bf3c009967.png)
