### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by adom2020** [citizenfx/fivem#1687]
I followed all the steps in docs/building.md and tried for more than 30 times and it doesn't work

![stGZHrU](https://user-images.githubusercontent.com/59978718/200562222-a90b6a46-e9ef-464a-9d65-05ddea465a60.png)
![image](https://user-images.githubusercontent.com/59978718/200562276-25e85fda-192a-47b4-9144-a1a6db3cd98e.png)

**Comment by gottfriedleibniz** [comment]
Marking as stale. If still an issue, please reopen.
