### ISSUE TITLE
JS: CreateVehicle does not work with onNet

### ISSUE THREAD

**Issue by el8rbawy** [citizenfx/fivem#1696]
I'm using CreateVehicle on the server side but it only works with RegisterCommand and it can't work with onNet

No problem with this:
```js
RegisterCommand('getVeh', (source, arr) => {
  const pedID = GetPlayerPed(source);
  const [x, y, z] = GetEntityCoords(pedID, true);
  
  CreateVehicle(2123327359, x, y, z, GetEntityHeading(pedID), true, true);
}, true);
```

Does not work when used with emitNet on the client side:
```js
onNet('xxxx', async data => {
  const currentID = source;
  // ...await axios...
  // I use the API before executing the following
  const pedID = GetPlayerPed(currentID);
  const [x, y, z] = GetEntityCoords(pedID, true);
  const vehID = CreateVehicle(2123327359, x, y, z, GetEntityHeading(pedID), true, true);
  
  // SetEntityCoords(vehID, x, y, z, false, false, false, false);
  console.log('ID:', vehID);
});
```

This is what I found after creating the vehicle (onNet)
- Get ID
- It is located in an inaccessible place
- SetEntityCoords cannot be used with it

[screenshot](https://f.top4top.io/p_2507ual331.png)

**Comment by blattersturm** [comment]
Do you have a _full_ repro resource, and not some partial snippet that seems to exclude context?

**Comment by el8rbawy** [comment]
> Do you have an actual standalone repro resource, and not some partial snippet that seems to exclude context?

Sorry, but what does that mean?

**Comment by AvarianKnight** [comment]
The code you gave works fine, so he wants the actual context to the code so he can find out what the actual issue is

**Comment by el8rbawy** [comment]
```js
onNet('NewStart_Parking:handleGloble-server', async data => {
   const currentID = source || data.source;
   const license = licenseEncrypt(currentID);  

   if (data.type === 'initial') {
      const vehicles = (await axios.get(`${URL}/vehicles/${license}?insideCode=true&value=false`)).data;

      for (let item of vehicles) {
         const find = dealership.vehicles.find(v => v.hash === item.hash);
         item.vehType = find.vehType;
      }

      emitNet('NewStart_Parking:handleGloble-client', currentID, 'initial', JSON.stringify(vehicles));

   } else if (data.type === 'vehSpawn') {
      // const info = (await axios.get(`${URL}/vehicles/${license}?byID=${data.id}&filter=name,hash,plate.name,fuel,damage&insideCode=true`)).data;
      // const [x, y, z] = GetEntityCoords(GetPlayerPed(currentID), true);
      // const vehID = CreateVehicle(info.hash, x, y, z, data.coord.h, true, true);
      
      // // const speed = dealership.vehicles.find(obj => obj.hash === hash).speed;

      // SetPedIntoVehicle(GetPlayerPed(currentID), vehID, -1);
      // SetVehicleNumberPlateText(vehID, info.plate.name);

      const ped = GetPlayerPed(currentID);
	   const [x, y, z] = GetEntityCoords(ped, true);

		const vehID = CreateVehicle(2123327359, x, y, z, GetEntityHeading(ped), true, true);
      SetEntityCoords(vehID, x, y, z, false, false, false, false);
      console.log('ID:', vehID);
   }
});
```

**Comment by AvarianKnight** [comment]
CreateVehicle won't instantly create vehicles, if you want a native that does you should look at the [CREATE_VEHICLE_SERVER_SETTER](https://github.com/citizenfx/fivem/blob/f14f98f0089b9068916e0fec0180b2ee968d8387/ext/native-decls/server/CreateVehicleServerSetter.md)

`SetPedIntoVehicle` and  `SetVehicleNumberPlateText` are both RPC natives and wont work if [NetworkGetEntityOwner](https://docs.fivem.net/natives/?_0x526FEE31) is -1 as there isn't any player that has the entity

Besides that are you sure info.hash is a valid vehicle hash? If it isn't then the vehicle won't be spawned

**Comment by el8rbawy** [comment]
> CreateVehicle won't instantly create vehicles, if you want a native that does you should look at the [CREATE_VEHICLE_SERVER_SETTER](https://github.com/citizenfx/fivem/blob/f14f98f0089b9068916e0fec0180b2ee968d8387/ext/native-decls/server/CreateVehicleServerSetter.md)
> 
> `SetPedIntoVehicle` and `SetVehicleNumberPlateText` are both RPC natives and wont work if [NetworkGetEntityOwner](https://docs.fivem.net/natives/?_0x526FEE31) is -1 as there isn't any player that has the entity
> 
> Besides that are you sure info.hash is a valid vehicle hash? If it isn't then the vehicle won't be spawned

I used this method because the vehicle ID is not fixed when using routing buckets and back to the original world 0.

**Comment by AvarianKnight** [comment]
What do you mean?

**Comment by el8rbawy** [comment]
> What do you mean?

When I create the vehicle on the client side I save the local ID inside a variable but once I use the following and go back to the original world the ID is no longer valid.

```js
onNet('XXXX_RealEstate:handleBucket-server', ({ type, code }) => {
   const index = realEstate.items.findIndex(i => i.code === code);
   const bucketID = index + 1;
   const ref = realEstate.items[index];

   if (type === 'enter') {
      SetPlayerRoutingBucket(source, bucketID);

   } else { // exit
      SetPlayerRoutingBucket(source, 0);
   }

   if (ref.type === 'garage' || ref.garage) {
      // TODO
   }
});
```

**Comment by AvarianKnight** [comment]
But how does that change using CREATE_VEHICLE_SERVER_SETTER, also of course the entity handle wouldn't be valid anymore, if you're leaving a vehicles scope the entity handle is reused, if you want to save an entitys handle you should [NetworkGetEntityFromNetworkId](https://docs.fivem.net/natives/?_0xCE4E5D9B0A4FF560) to save the vehicles network id

**Comment by el8rbawy** [comment]
> But how does that change using CREATE_VEHICLE_SERVER_SETTER, also of course the entity handle wouldn't be valid anymore, if you're leaving a vehicles scope the entity handle is reused
> 
> If you want to save an entitys handle you should [NetworkGetEntityFromNetworkId](https://docs.fivem.net/natives/?_0xCE4E5D9B0A4FF560) to save the vehicles network id and convert it back

I mean before that I was creating vehicles on the client side instead of on the server side.

```
Error: Unhandled promise failure: ReferenceError: CreateVehicleServerSetter is not defined
```

I'll try with that [NetworkGetEntityFromNetworkId](https://docs.fivem.net/natives/?_0xCE4E5D9B0A4FF560).

**Comment by AvarianKnight** [comment]
Update your server version to fix `CreateVehicleServerSetter` being not defined, you will need a version newer then 5894

**Comment by el8rbawy** [comment]
> Update your server version to fix `CreateVehicleServerSetter` being not defined, you will need a version newer then 5894

I updated the server to version 5894 and it still shows the same error
```Error: Unhandled promise failure: ReferenceError: CreateVehicleServerSetter is not defined```
