### ISSUE TITLE
 RegisterPedheadshotTransparent opacity issue

### ISSUE THREAD

**Issue by cqmpact** [citizenfx/fivem#1697]
This seems like a issue [that was ignored on the forums](https://forum.cfx.re/t/registerpedheadshottransparent-opacity-build-2189) and nobody reported it here.

**Issue:** 
RegisterPedheadshotTransparent returns a headshot on which the ped is transparent too. 
See attached code and images.

```
local function getPlayerHeadshot()
    local playerPed = PlayerPedId()
    local handle = RegisterPedheadshotTransparent(playerPed)
    if handle == nil or handle == 0 then handle = RegisterPedheadshot(playerPed) print(handle, 'normal') end
    while not IsPedheadshotReady(handle) or not IsPedheadshotValid(handle) do
        Wait(0)
    end
    local txd = GetPedheadshotTxdString(handle)
    UnregisterPedheadshot(handle)
    return txd
end
```

![FiveM_b2699_GTAProcess_6B7VELoPSN](https://user-images.githubusercontent.com/35305953/201528195-97ffe85d-f372-405f-be46-b502b6967414.png)
![FiveM_b2699_GTAProcess_brsHTxagwe](https://user-images.githubusercontent.com/35305953/201528297-1293b5d0-5e3e-4541-a5d6-9f3d1ae4e8c4.png)

**Comment by thorium-cfx** [comment]
I've been investigating this one for a bit and it seems GTA is storing them differently now. I do want to understand this a bit more before I work on a proper solution.

My findings until now:
1. Texture compressions are still the same, i.e.: BC3,
2. Alpha channel is scaled to a different range [0..1] to [0.333..0.666] (rough estimates), no clue why,
3. RGBs look premultiplied by the (original?) alpha.

**Comment by gottfriedleibniz** [comment]
Unsure if you've made progress on this, so I took a glance at things.

Comparing the same alpha block of 1604 and 2189 generated textures (everything is scaled off min/max when compressed): 1604 produced `62-255` and 2189 produced `37-153`. Given that nothing has changed in the related `PedHeadshotTextureExporter` code-paths, I suspect there is either some change in a target blend description (I guess? unlikely) or a blit shader used.

Looking through some of the intermediate render targets, there seems to be a discrepancy in `Headshot Color 1L` (background colouring). This target uses `PS_BlitAAAlpha` (0x14064C771) which changed in 2189 (`mad + add` vs `mul + mad + mad`). Maybe this is causing the issue?

**Comment by thorium-cfx** [comment]
Interesting findings, thank you for having a look as well.

I had a look at the shader and the code around `mul + mad + mad` is indeed what's causing it to end up in the [0 .. 0.6] range, this effectively happens: `(color0 * 0.5 + color1 * 0.5 + color2 * 0.5) * 0.4 * GeneralParams0`. Blend state looks fine with all set to `1.0` during run time.

Given the above formula, changing `GeneralParams0` would be fine, though I'm not sure how to set this and if it has any other side effects? Otherwise I'll go with my customizable post-process idea.

**Comment by gottfriedleibniz** [comment]
Actually, I think using `5/3` as the bias *should* give roughly equal results to the texture generated by 1604 (2.f was arbitrary and without thought). The alpha of the texture being sampled ("PedHeadshot ...") at this stage should be binary (all or nothing).

Either the `0x14066B3F9` call (2108; pattern required) can be hooked to replace the value of GeneralParams0 (forwarding a different array); or the `0x14066B3DA` mov can be updated with the address some stub memory. The first probably much easier. There should be no side-effects - these values are reset after the draw call.

**Comment by thorium-cfx** [comment]
The hooking sounds like a good idea, gotta up my reverse engineering.

`5/3` or its equal `1/0.6` is indeed correct, the color space lines up now. Input texture's alpha is indeed binary.

I also solved the background color differences, the color comes from the bottom right pixel; `texture.Sample(sampler, float2(NaN, NaN))` (there are more errors like this). I think the new `mul + mad + mad` changes this value, probably an extra texel fetch or 2, but I'll have to see the previous shader to confirm this.

**Comment by thorium-cfx** [comment]
Thank you for the help @gottfriedleibniz, the addresses were spot on.
