### ISSUE TITLE
B2699 Issue with Vehicles

### ISSUE THREAD

**Issue by Levmann** [citizenfx/fivem#1698]
Since we updated to B2699 we have had the following issues:

-In the handling.meta we always used 
```
"<SubHandlingData>
        <Item type="CCarHandlingData">
            <strAdvancedFlags>10000</strAdvancedFlags>
        </Item>
        <Item type="NULL"/>
        <Item type="NULL"/>
    </SubHandlingData>" 
```
 to Cap the Speed of our Cars to a  certain value.
Since the new Build Version, this feature isn't working anymore, the cars ain't capped.

-We have several Issues with the Mod Menu:
Some cars cant get full tuned or tuning parts cant get attached.
Window Tint is also not working on some parts

-You can only shoot out of the overwatches with the ego-perspective, there's no chance for third person shooting.

**All over we have many issues with FiveM Add-on cars, since  updating to B2699. Before we had B2372, where we had no issues.
We have a server with hundreds of daily players (LatenightV).**

We hope you can help us out!

**Comment by gottfriedleibniz** [comment]
The GTAForums/[GTAMods](https://gtamods.com/wiki/Handling.meta) crew (Wildbrick142? apologies if mistaken!) have documented the behaviour of this flag changing as of 2699. A few other weird cases with the Gen9 changes have been addressed in https://github.com/citizenfx/fivem/issues/1546. Maybe they address your concern as well?

Reverting functionality here, while theoretically possible, is unlikely to happen and would not be worth the time investment. There are a variety of natives available that can simulate the effect you desire.
