### ISSUE TITLE
Support For CSharp

### ISSUE THREAD

**Issue by austinv900** [citizenfx/fivem#17]
Is there plan to add CSharp support here near future?

Not a big fan of lua and C# is a much faster then lua is.

**Comment by impowski** [comment]
I started to use ServerWrapper, Lua is just too retarded.

**Comment by austinv900** [comment]
@impowski Whats ServerWrapper?

**Comment by blattersturm** [comment]
C# is already supported on the client and FXServer (if enabling the component - Windows-only for now) - are you talking about the legacy CitizenMP.Server?

**Comment by austinv900** [comment]
Not actually sure. Any documentation on C# plugin building?
