### ISSUE TITLE
Player State bag does not sync to server anymore?

### ISSUE THREAD

**Issue by renzuzu** [citizenfx/fivem#1700]
last week before statebags update.

this example.

```
      LocalPlayer.state:set('testname', {
		entity = entity, 
		name = value.name, 
		data = value.data
	}, true)
```

will sync to server or the handler will get notified
```
AddStateBagChangeHandler('testname' --[[key filter]], nil --[[bag filter]], function(bagName, key, value, _unused, replicated) 
	Wait(0)
	print('server receive state from player')
end)
```

now the handler does not get anything..

is this a normal behavior now or a issue? 
so i will update my resource logic.

im currently running b2699 BETA

**Comment by mythicalbro** [comment]
Works just fine here with the example that you provided on canary, latest windows server artifact 6020, game build 2699.

**Comment by thorium-cfx** [comment]
I've already received a couple more reports of this issue. And although I can't reproduce it myself, I did find something that might cause this.

**Comment by renzuzu** [comment]
> Works just fine here with the example that you provided on canary, latest windows server artifact 6020, game build 2699.

so its probably the version i am using. im using recommended version of artifact

**Comment by thorium-cfx** [comment]
@renzuzu the above fix #1701 was just applied to resolve an equivalent issue. Could you test if it has been resolved now on the latest build (client, v6021)?

**Comment by renzuzu** [comment]
it seems its replicating well now in server, i get notify by server statebaghandler too.
very good work

**Comment by thorium-cfx** [comment]
Happy to hear, considering this as solved then.
