### ISSUE TITLE
Issue with the CEF?

### ISSUE THREAD

**Issue by PoorLatency** [citizenfx/fivem#1703]
I'm not sure how to reproduce this but numerous people have this error.. Is there anyway to find what's causing it?
```
Process crash captured. 

Crash dialog content:
KERNELBASE.dll!RaiseException (0x69)
An error at KERNELBASE.dll!RaiseException (0x69) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
Stack trace:
  KERNELBASE.dll!RaiseException (0x69)
  libcef.dll!base::internal::OnNoMemoryInternal (0x2a) (memory.cc:42)
  libcef.dll!base::TerminateBecauseOutOfMemory (0x8) (memory.cc:69)
  libcef.dll!partition_alloc::internal::OnNoMemory (0x14) (oom.cc:19)
  libcef.dll!blink::ReportV8OOMError (0x11b) (v8_initializer.cc:690)
  libcef.dll!v8::Utils::ReportOOMFailure (0x22) (api.cc:355)
  libcef.dll!v8::internal::V8::FatalProcessOutOfMemory (0x355) (api.cc:311)
```

**Comment by Doxylamin** [comment]
TerminateBecauseOutOfMemory suggests that there are some tasks running in your CEF browser that are not scheduled or terminated properly. As a first step, you may want to check your servers NUI(s) for code that may be causing the OOM error.

See for example here for more details: https://blog.logrocket.com/escape-memory-leaks-javascript/

**Comment by cjosephdc** [comment]
@PoorLatency have you fixed this? Im facing same issue.
