### ISSUE TITLE
CEF Crash?

### ISSUE THREAD

**Issue by arlofonseca** [citizenfx/fivem#1705]
**Describe the bug:**

Below you will find a couple of videos of what is occuring. In the first video, you can see the player stats in the bottom left, along with devtools opened to the right, when this "bug" occurs, everything refreshes on the users interface; causing devtools to crash, causing all scripts to reload their UI *(which is why you see UI randomly popping up on the players screen)*. The debug tool crashing *repeatedly* when this occured made it damn near *impossible* to actually see what could be triggering this. In the second video, you will see the player stats in the bottom left disappear again, along with some other resources that use a UI just randomly pop up on the players screen, you will then see that the player is frozen & unable to actually do anything within FiveM. This is when they will then need to manually restart the application.

**Steps to reproduce the behavior:**

We were unable to find productive reproduction steps for this. This seems to occur randomly at different times, doing different things, and *only* seems to be happening when the server is at it's full capacity; 140/200. We had the server down for "maintenance" and had 7 people in the server for more than three hours, this "bug" didn't occur once during that time.

**Evidence:**

[Video #1](https://streamable.com/wrn8y9)
[Video #2](https://streamable.com/u7jif0)

**Additional context:**

[Here is another GitHub issue as a reference](https://github.com/citizenfx/fivem/issues/1703), this seems to be happening to a *hefty* amount of people. We originally thought a resource *could* be causing this, come to find out it was also occuring on another very large server. This was also occuring for them when the capacity was full; 140/200.

- Game Version: 6040 (Canary)
- Server Version: 6033
- Build: 2699

**Comment by cjosephdc** [comment]
Im having the same issue. Have you fixed yours?

**Comment by kikreto** [comment]
> good, could you give me your discord name for a consultation ? or some site where I can communicate with you ?

**Comment by cjosephdc** [comment]
> 

We solved ours by removing scripts that are playing youtube thru xsound script.

**Comment by kikreto** [comment]
ok, I have stopped the xsound resource, could you also provide me with a discord for a more fluid communication ?
 I don't want to bother you
