### ISSUE TITLE
NUI crash following FPS drop

### ISSUE THREAD

**Issue by Spykespy** [citizenfx/fivem#1711]
Hello! We're experiencing the following situation on our server:

People get a sudden FPS drop to +-15 FPS around 15 minutes after they join our server, and after that their full screen NUI's stop updating or crash all together. Their game continues to function.

The following error pops up at every event:
![image-1.png](https://user-images.githubusercontent.com/40208312/202911782-1266e807-c154-44b8-b6eb-77df8c4654ed.png)

This is happening for hundreds of people on our server, and we're unsure how to handle this error. We reverted all of our updates, but this didn't resolve anything unfortunately. We're wondering if this might be an issue in the FiveM client, or that someone may be able to give us some insight in the error and how to handle it appropriately.

Please excuse me for my broken English, and thanks in advance! If you'd like a full crash log, I'll happily send one.

**Comment by thorium-cfx** [comment]
We're still looking for reproduction steps on this issue or other info, see https://github.com/citizenfx/fivem/issues/1705#issuecomment-1319733950.

With crash log, do you mean the crash dump? if so then yes please.

**Comment by Spykespy** [comment]
> We solved this by removing scripts that are playing youtube thru xsound script. Check nui dev tools for your errors.

Yup, this fixed our issue indeed. Thanks!
