### ISSUE TITLE
Peds/Cars Flickering, Packet Loss Issue

### ISSUE THREAD

**Issue by Steviol** [citizenfx/fivem#1712]
Packet loss going up when there is a lot players/cars nearby after that peds/cars will flickering
https://user-images.githubusercontent.com/29462114/203154571-41c4778f-ea6f-402d-9136-4811b8440e5c.mp4
But connection from client to server is not giving any packet loss at all 
![image](https://user-images.githubusercontent.com/29462114/203154733-4cb54ac3-0a27-45f2-a396-0b0637be9242.png)

**Comment by blattersturm** [comment]
I'm not seeing any reproduction steps or anything indicating this is actionable.
