### ISSUE TITLE
GTA5_b2699.exe!sub (0x42)

### ISSUE THREAD

**Issue by wTopolino** [citizenfx/fivem#1713]
I've been having problems with fivem for days, after I walk around the city my screen freezes and crashes giving me the GTA5_b2699.exe!sub error, can someone solve this problem, thanks!

![Immagine 2022-11-12 153845](https://user-images.githubusercontent.com/118774487/203161325-06669518-ac1d-41db-a37e-b3fe10d984c0.png)

**Comment by blattersturm** [comment]
This is not a help section.

**Comment by Ziell765** [comment]
I've been having problems with fivem for days, after I walk around the city my screen freezes and crashes giving me the GTA5_b2699.exe!sub error, can someone solve this problem,  #thanks
