### ISSUE TITLE
localGame [name] reloading game

### ISSUE THREAD

**Issue by draobrehtom** [citizenfx/fivem#1714]
I go into `storymode` (continue the game with the last save), I write `localGame helloworld` and the game starts from the beginning, from the prologue.

![image](https://user-images.githubusercontent.com/6503721/203219942-75783793-e1d4-4453-bcf6-185e08c9e0ba.png)

**D:\Games\FiveM\FiveM.app\usermaps\resources\helloworld**
client.lua:
```lua
print("Hello World")
```
fxmanifest.lua:
```lua
fx_version 'cerulean'

game 'gta5'

client_scripts {
    'client.lua'
}
```

**Video:**
https://streamable.com/0095rg
Edition	Windows 11 Home
Version	22H2
Installed on	‎11/‎15/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

GTA V is from Social Club (Rockstar Launcher)

**Comment by thorium-cfx** [comment]
From looking at the code it looks like `localGame <name>` will close any existing open game and start a new single-player environment, so you'll not be able to load story mode with resources from my understanding. This behavior is however not reflected in the docs it seems.

**Comment by draobrehtom** [comment]
This functionality would be great to see in the same form in which it is provided in the multiplayer, as it would allow to develop scripts in singleplayer and play with the existing scripts in singleplayer, not starting every time with the prologue.

**Comment by Local9** [comment]
If you need it you also require this to load the Player, which will enable you to play and shouldn't load the prologue;

https://forum.cfx.re/t/i-want-to-start-scripting-single-player-fimem/1111151/6?u=lacol

Lua version based off the snippet provided by d-bubble
```lua
-- This is the initial launching script
-- You can change the posVector to change the starting position

local firstTick = false;
local posVector = vector3(-2243.810, 264.048, 173.615);

CreateThread(function()
  if IsScreenFadedIn() then
    DoScreenFadeOut(1000);
  end

  while not IsScreenFadedOut() do
    Wait(0);
  end

  while not firstTick do

    Wait(0);
    
    if not IsScreenFadedIn() or GetIsLoadingScreenActive() then
      ShutdownLoadingScreen();
      ShutdownLoadingScreenNui();    
      firstTick = true;
    end
  end

  Wait(1000);

  SetEntityCoords(PlayerPedId(), posVector.x, posVector.y, posVector.z, false, false, true, true);
  DoScreenFadeIn(1000);
end)
```
