### ISSUE TITLE
Entity state bags don't exist out of render distance OR if player is not using/in vehicle/entity (client side)

### ISSUE THREAD

**Issue by damightylamb** [citizenfx/fivem#1717]
I noticed this one the other day when our dispatch for our server had a problem tracking entities for our car boosting script. 

Before we would attempt to pass the network id from the server event to the client event that would create the blip and reference the states after getting the `NetworkGetEntityFromNetworkId`. Example:

Client event getting called ("id" being the network id) :
`TriggerClientEvent('erp-dispatch:carboosting', -1, sentCoords, id, tier, alert)`

Referencing the network id on client script:
`local currentVeh = NetworkGetEntityFromNetworkId(netid) 
Wait(Entity(currentVeh).state.delay)`

This worked well before because the entity would exist to the clients and would have the ability to reference any state bags if the entity just existed. 

But if I recall correctly, there was a recent update to how the entity state bags work. Now if I want to reference an entity state bag, I have to get all the values in the server script then pass it to the client script

New working method:

Server Side
![image](https://user-images.githubusercontent.com/77940542/203608734-3cdf2773-0754-48cd-8603-cc4b9c890328.png)

Client Side
![image](https://user-images.githubusercontent.com/77940542/203609008-2fc3f707-2d7e-4390-9339-4a35d332130d.png)

Personally, it would be a lot better to pass the network id and be able to reference the entity states as long as it exists on the server.

Things to note: 

- The entities were out of render distance when testing.
- Testing consisted of two independent clients. Both on Canary
- When testing with a vehicle, the states were accessible when a client got into the vehicle

**Comment by thorium-cfx** [comment]
I'm not really sure what's being asked/reported here. Could you show examples of what you did before that is no longer working?

As for changes to entity state bags, theoretically they should be the same, i.e.: when an entity is in a player's network scope they'll get updates, outside of it and they won't.

On your personal note; entities are already referenced by their network id, Lua's wrapper does this conversion for you for convenience.

**Comment by damightylamb** [comment]
Absolutely.

**Please note that these screenshots are the old way that was working prior**

The problem comes from our boosting script where a car was created (function below showing that it would be registered network entity):
![image](https://user-images.githubusercontent.com/77940542/203618213-90d8ccdf-9af3-437c-a1cc-16ccf23903df.png)

Code shows the state bag values being set. Ones to note for this problem is "delay"
![image](https://user-images.githubusercontent.com/77940542/203618812-84e0565f-abc3-4067-bd97-fb00190e04bd.png)

After, when Client-A would attempt to break into that vehicle it would trigger a function in our dispatch script that would handle our blips (event "erp-dispatch:carboosting" in SS below):
![image](https://user-images.githubusercontent.com/77940542/203620896-cac6cc89-5086-434f-a40b-5b594b049d31.png)

The server event would then send the data to all clients. There, the client file would create the blips for the police:

(Image 1: Server Event)
![image](https://user-images.githubusercontent.com/77940542/203620988-af9de04d-6dfc-439c-9a53-67b9c9c752e7.png)


(Image 2: Client Event aka our problem)
![image](https://user-images.githubusercontent.com/77940542/203621083-d109a998-a5e3-43e9-bed7-0235b0e4f18b.png)


That last screenshot is where the problem would persist. If Client-A was at the vehicle in the Vinewood hills (where majority of our boosted vehicles spawn) and the police officer (Client-B) was at Vespucci PD, the data (netid, coords, etc) would be sent to the police, but when we attempt to get the delay in the state bad ( `Wait(Entity(currentVeh).state.delay)` ) it would come up as `nil` UNTIL Client-A got into the vehicle. 

![FiveM_b2545_GTAProcess_xX2B1Hb5En](https://user-images.githubusercontent.com/77940542/203621797-1993ed7b-ae67-43ac-b67d-d79c366c07fd.png)

I also tested getting the vehicles coords in the client script which resulted in the blip creating itself at vector3(0,0,0)
![image](https://user-images.githubusercontent.com/77940542/203622441-7081b7f6-2f70-4500-b6c2-f5ed6a817366.png)



That was on my development server. On the live/production server with 350 clients daily, the blips just would not show up UNLESS the officers were in render distance of the vehicle. 

The code blocks from the original post is what I did to combat this.

**Comment by thorium-cfx** [comment]
So to summarize:

1. TriggerClientEvent to all players with network entity id,
2. On all clients you receive the event,
3. Try to get the local entity's id,
3. You read the entity's `delay` value from its state bag,
4. Make it wait for the delay.

From your errors I would assume it already fails at step 3, not even reaching the state bag code.

This whole setup looks a bit wonky to me, but as a suggestion why not just send the delay timer with the event, should solve this problem.

**Comment by damightylamb** [comment]
> I don't see how this is a state bag issue. Looks like the network ID that is received by client B just doesn't exist for them yet thus it shows that log "no object by ID x" and NetworkGetEntityFromNetworkId returns 0 instead of the actual entity ID. That's why the state that you are trying to get is nil, because you are trying to get it from invalid, non-existing entity.

I understand where you are coming from, but the entity does exist. I checked if it did on the client side for Client B. The entity would exist but just cant reference the state bag values

**Comment by damightylamb** [comment]
> Are you sure that it exists at the time when the event is received by the B client? Would not make sense, since the network ID does not exist yet. This probably needs a working repro to understand what you mean, what the issue is.

Yes I am sure. I spent hours testing the state bags and whether or not the entity existed. All the times (before Client-A got into the vehicle) the entity would exist, but would not reference the state bags associated with said entity. 

I already found my solution to fix my problem (in code in original post), but I wanted to bring this issue up because I have had no had this issues until recent.

**Comment by thorium-cfx** [comment]
> My biggest thing is that the entities' state bags were able to be referenced without a problem from client to client without a problem (as long as the entity was a registered network entity).

Previous behavior was actually the same, you might've been lucky not to hit this sooner.

I'm closing this as all given info fits the design and I see no real proof of it being relevant to state bags. You may always supply a minimal repro if something is really incorrect or create a new issue if it's necessary.
