### ISSUE TITLE
DDoS Protection - Solution

### ISSUE THREAD

**Issue by NotYusta** [citizenfx/fivem#1734]
Indirect listing uses the proxy's IP & port to connect, if you are using Cloudflare you are not able to connect the server because it directs to the Cloudflare's IP in exception if you disabled the indirect listing (this can cause ip leak) ~ so, it's better in the FiveM CFX Server to read the header that has been sent by the proxy to direct them to the correct IP.

For example ["Target-IP"] = "10.437.23.6.3"
Cloudflare will forward all headers this will be able to be used and then the CFX Server reads that header to redirect the "player" to the proxy IP.

With indirect listing i can hide the real IP but it is not secure enough for the L7 API. (well an api limit from nginx could do some work i suppose but protecting with cloudflare is much better.)
This could be the ultimate solution to HTTP / HTTPS DDoS attack.

**Comment by blattersturm** [comment]
I'm not sure what you're referring to here, but it sounds like this use case is already supported via either sv_endpoints or sv_proxyIPRanges.

See the documentation: https://docs.fivem.net/docs/server-manual/proxy-setup/

Also, this is not a feature request section either.
