### ISSUE TITLE
entityCreated are not working with CreateVehicleServerSetter 

### ISSUE THREAD

**Issue by renzuzu** [citizenfx/fivem#1737]
if i created a vehicle using this CreateVehicleServerSetter Native.

the entityCreated event handler are not getting feedback / notified  from server.

```
RegisterCommand('carspawn', function(source,args)
    --local vehicle = CreateVehicle(joaat(args[1]), GetEntityCoords(GetPlayerPed(source)), GetEntityHeading(GetPlayerPed(source)), true, true)
    local SpawnedEntity = CreateVehicleServerSetter(joaat(args[1]), 'automobile', GetEntityCoords(GetPlayerPed(source)), GetEntityHeading(GetPlayerPed(source)))
end)

AddEventHandler('entityCreated', function(entity)
    print('test',GetEntityType(entity),GetEntityPopulationType(entity))
end)
```

i dont know if this is a default behavior of this native.
as ESX repo are already using this already on production
so just incase im reporting an issue.

and the CreateVehicle Server rpc works fine.

Artifact version: 6103 ~ 6117

**Comment by blattersturm** [comment]
See https://forum.cfx.re/t/entitycreated-not-triggered-when-creating-objects-peds-on-server-side/4363628/3?u=d-bubble, the same still applies.

The RPC call 'works fine' as it's not actually created from the server.
