### ISSUE TITLE
Issue with Nui

### ISSUE THREAD

**Issue by vkatranas** [citizenfx/fivem#1743]
Good evening, recently there has been a problem that suddenly when a player is playing all the UIs that the server has appear and they are in their default form as if the javascript has been `killed' and you cannot be specific with an action or in a specific interval. 

My Server:
Artifacts: 6129
OS: Ubuntu Server 21.10

Lately I've heard it happening on many servers and I thought I'd mention it.

Thank you in advance.

**Comment by vkatranas** [comment]
Edit: Just now made it to user and become that exact thing.

![Screenshot_1](https://user-images.githubusercontent.com/74133598/206919945-5dc54fd5-fd63-404d-a32e-7e60730b9661.png)

**Comment by blattersturm** [comment]
This is some specific resource leading to the Chromium subprocess crashing and is caused by a bug in said resource.
