### ISSUE TITLE
B2699/B2372 FiveM Crash Error Issue

### ISSUE THREAD

**Issue by Audiatorix20** [citizenfx/fivem#1745]
Several of our players keep getting the below issue after an hour of gameplay. We have rolled back the server build version but got nothing. Any ideas?
![image](https://user-images.githubusercontent.com/86139043/207675790-5407f54d-026a-49a2-81fc-8fee1fa312f0.png)

**Comment by Lucas7yoshi** [comment]
That is b2372, not b2699

**Comment by Audiatorix20** [comment]
> That is b2372, not b2699

It does not matter the game version, it will throw this error for either game version around 1 hour after gameplay.

**Comment by blattersturm** [comment]
Likely some asset - without information on how to cause this oneself, this is not actionable and therefore does not belong here.
