### ISSUE TITLE
GetduiHandle not working Error executing native 0x000000001655d41d at address nui-resources.dll+2CB00

### ISSUE THREAD

**Issue by divide29** [citizenfx/fivem#1747]
So some weeks ago the license plate script doesn't stream the image to the plate. The code is:

`local platesDict = {
    { "plate01", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "plate01_n", "https://i.imgur.com/FNb3UP8.png", 256, 128 },
    { "plate02", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "plate02_n", "https://i.imgur.com/7sKA7M1.png", 300, 160 },
    { "plate03", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "plate03_n", "https://i.imgur.com/7sKA7M1.png", 300, 160 },
    { "plate04_n", "https://i.imgur.com/FNb3UP8.png", 256, 128 },
    { "plate04", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "plate05", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "plate05_n", "https://i.imgur.com/FNb3UP8.png", 256, 128 },
    { "yankton_plate", "https://i.imgur.com/CoxAymd.png", 734, 361 },
    { "yankton_plate_n", "https://i.imgur.com/FNb3UP8.png", 256, 128 },

for _, p in pairs(platesDict) do
    local txd = CreateRuntimeTxd("testing")
    local duiObj = CreateDui(p[2], p[3], p[4])
    local dui = GetDuiHandle(duiObj)
    local tx = CreateRuntimeTextureFromDuiHandle(txd, "test", dui)
    AddReplaceTexture("vehshare", p[1], "testing", "test")
end
}`

it outputs the following error:
![image](https://user-images.githubusercontent.com/92187331/207941240-635ec9e6-66c3-4814-b37a-251f9d5812d8.png)

**Comment by blattersturm** [comment]
This code was ill-formed anyway and can't work anymore since the CEF update. Sadly is unfixable - use different code or properly use DUI calls.
