### ISSUE TITLE
B2802 - SetVehicleHandlingFloat - Error executing native at address handling-loader-five.dll

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#1754]
Repro:
local vehicle = GetVehiclePedIsIn(PlayerPedId(), true)
SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fEngineDamageMult', 1.0)

[    869969] [b2802_GTAProce]             MainThrd/ __Lua_InvokeNative: execution failed: Error executing native 0x00000000488c86d2 at address handling-loader-five.dll+29457.
[    869969] [b2802_GTAProce]             MainThrd/ Execution of native 00000000488c86d2 in script host failed: Error executing native 0x00000000488c86d2 at address handling-loader-five.dll+29457.

**Comment by Disquse** [comment]
I believe this is going to be fixed in #1755

**Comment by Disquse** [comment]
Can you confirm it was fixed on the latest canary?
