### ISSUE TITLE
Server specified an invalid game build enforcement (2802).

### ISSUE THREAD

**Issue by f25a2fc72690b780b2a14e140ef6a9e0** [citizenfx/fivem#1758]
My game won't run on 2802 at all - tried to reinstall and currently game is on canary.

2699 works but 2802 doesn't - tried a few workarounds too such as "path\FiveM.exe -b2802" or launching from 2699

![image](https://user-images.githubusercontent.com/79164319/208741998-eacd7e2d-67a0-4d10-9bec-9acb2f3b3c9e.png)

**Comment by blattersturm** [comment]
We don't have access to 'your game' so that seems a bit not-actionable... so it's a weird place to put something non-actionable as this is for actionable stuff only.
