### ISSUE TITLE
Thread tried to read or write to a virtual adress it does not have access

### ISSUE THREAD

**Issue by PlouffeLuL** [citizenfx/fivem#1764]
(If this is not the right place for this feel free to not answer and close right away)

Lately i have been experiencing random crashes even if the server is more then stable.
I did most of everything i am able to do to try debugging.

Everything is super stable with around 140 players on the server. Profiler does not show anything wrong in any way. So everything you would expect someone to check before opening an issue on git has been checked.

Tabby from txAdmin pointed to this https://docs.fivem.net/docs/support/server-debug/ .

I have been collecting dumps and looking at them since 3-4 days, all of them pretty much give the same information.

Exception code: 0xC0000005
Exception information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

When trying to 'Debug with native only' every dumb throws this error.

`
Unhandled exception at 0x00007FFE3EFCFEF0 (citizen-server-state-rdr3sv.dll) in FXServer.exe_221227_124505.dmp: 0xC0000005: Access violation reading location 0x000000000030303A
`

Server is running on windows and using latest artifact.

I opened a forum post a few days ago but sadly did not get any answer, discord is not really the place to get help and i know here isnt the place to get help but i figured after reading the exception information it might be a good thing to post here where people with alot more knowledge then me could get a look at it.

**Comment by AvarianKnight** [comment]
This isn't the place for help, bubble responded to your forum topic asking for the server dump too.

**Comment by blattersturm** [comment]
Continued [here](https://forum.cfx.re/t/sigsegv-random-crashes-looking-for-external-advices/4975484/5).
