### ISSUE TITLE
BUG: Player state bag not replicated on client

### ISSUE THREAD

**Issue by Derass239** [citizenfx/fivem#1772]
With the last artifact (6183) the Player state create on server is not replicated on client.

**Server**
```lua
RegisterCommande('staffmod', function(src, args, rawCommand)
    local Player = Player(src).state

    local state = player.isStaffmod
    if state == nil or state == true then
        player.isStaffmod = false
    else
        player.isStaffmod = true
    end
end, true)
```

**Client**
```lua
print(LocalPlayer.state.isStaffmod)
```
--> Always output false

With the artifact 5949 i don't have any bug

**Comment by davidxd33** [comment]
Your code repro is setting a state value on an unknown variable `player` when you defined the variable to be `Player`.

**Comment by Derass239** [comment]
I put the default value (false) when loggin with the character. So the state in not unknow in player state on server side but keep unknow on client side.

**Comment by blattersturm** [comment]
Closing this until an actual repro is provided as the code above can't possibly work.
