### ISSUE TITLE
Bug with printing print(...)

### ISSUE THREAD

**Issue by czsquizer** [citizenfx/fivem#1775]
Hello, I have noticed a bug regarding strange printing to server console.

If I use "default" command - the one from docs:

```lua
RegisterCommand("commandName", function(source --[[ this is the player ID (on the server): a number ]], args --[[ this is a table of the arguments provided ]], rawCommand --[[ this is what the user entered ]])
    if source > 0 then
        print("You are not console.")
    else
        print("This is console!")
    end
end, false) -- this true bool means that the user cannot execute the command unless they have the 'command.commandName' ACL object allowed to one of their identifiers.
```

I type it from the server console, I can see the print, but if I invoke it from client, I can not see the print. Running the newest artifact.

Also, this happens if I have an error in script, I restart that script from client side, the error does not print in the server console, but if I restart the script from server side, I see the error.

**Comment by czsquizer** [comment]
It started to happen after artifact 58xx

**Comment by AvarianKnight** [comment]
Isn't this intentional?

See docs [here](https://github.com/citizenfx/fivem-docs/commit/f2306e14f0e7a136423d5d314c196b92ed7d7e7d), linking github as the docs page hasn't been deployed

**Comment by czsquizer** [comment]
Looks understandable now, for those, who want to still see prints (for dev purposes) add this to your server console:

con_removeChannelFilter forward:*/* noprint

**Comment by blattersturm** [comment]
FYI you can still see the prints where the command got invoked i.e. the client console.

**Comment by czsquizer** [comment]
Yeah, but the server side prints were important for me. For debugging.Dne 4. 1. 2023 12:23 napsal uživatel deterministic_bubble ***@***.***>:
FYI you can still see the prints where the command got invoked i.e. the client console.
