### ISSUE TITLE
Im banned for no reason it says 14 days

### ISSUE THREAD

**Issue by Sawke** [citizenfx/fivem#1778]
I got banned for no reason it says cheating but im not i think its false ban cus i was playing normaly and left to go install citizen when i installed it get it in the folder then i started fivem it says
![image](https://user-images.githubusercontent.com/121955241/210578108-f1e365fb-6d4c-4375-98c3-23913dda80d1.png)

**Comment by BARYGA9** [comment]
Fivem Ban 14 days I play fivem, I had to restart it because there is nothing on the server trying to connect to the 14 day ban?
![image](https://user-images.githubusercontent.com/121956225/210582513-0653b231-e61a-4206-89ea-f558b07bc5b1.png)
