### ISSUE TITLE
Missing files and errors

### ISSUE THREAD

**Issue by identifiedasskid** [citizenfx/fivem#1783]
# I tried building my own custom Client Build but i failed at the point where it compiled

### Following Files are missing 

```
Metadata file 'F:\fivem\code\bin\five\release\citizen\clr2\lib\mono\4.5\CitizenFX.Core.dll' could not be found
Source file 'F:\fivem\code\build\five\..\..\client\clrref\five\CitizenFX.Core.cs' could not be found.
Cannot open include file: 'Natives.h': No such file or directory
fatal error C1083: Cannot open include file: 'PASGen.h': No such file or directory
cannot open input file 'F:\fivem\code\build\five\obj\Release\citizen-resources-client\lib\citizen-resources-client.lib'
```

### Following Errors are appearing

```
cannot open input file 'F:\fivem\code\build\five\obj\Release\rage-scripting-five\lib\rage-scripting-five.lib' // many more of these
error MSB8066: Custom build for '..\..\tools\build\run_postbuild.ps1' exited with code 1.
```
![image](https://user-images.githubusercontent.com/112347278/210907959-794e93bf-21f0-4c48-88db-2c457dd886a6.png)
![image](https://user-images.githubusercontent.com/112347278/210908021-8cb07906-02d6-4aca-ae05-52343cbe194a.png)

## I ALREADY TRIED prebuild.cmd / prebuild_natives.cmd but these errors appeared
![image](https://user-images.githubusercontent.com/112347278/210905283-d1377385-7bc5-48a2-bcc1-57f5e3e7c84a.png)
![image](https://user-images.githubusercontent.com/112347278/210905292-c7be4757-2557-4519-9fb3-28f3a27ece59.png)

**Comment by AvarianKnight** [comment]
I have these issues too but just commented out the line that this happened on in the `build.sh`, out of curiosity are you on Windows 11?

**Comment by blattersturm** [comment]
Wrong place to post stuff like this.

Also,

> 'these errors appeared'

Reinstall or properly update your MSYS install.
