### ISSUE TITLE
Not possible to hide default hud for `rdr3`

### ISSUE THREAD

**Issue by Z3rio** [citizenfx/fivem#1790]
It seems like it is pretty much impossible to hide the default hud of RedM.
All ways of hiding it, such as through `DisplayHud`, `_ENABLE_HUD_CONTEXT` / `_DISABLE_HUD_CONTEXT` and all other natives I could find.

I wouldnt say this is an urgent issue, nor am I 100% sure, I could possibly be incorrect.

**Comment by blattersturm** [comment]
This doesn't look like it's something that belongs here.

**Comment by Z3rio** [comment]
> This doesn't look like it's something that belongs here.

Why would it not belong here? This is an issue with the natives in RedM / rdr3, where would it otherwise belong?

**Comment by AvarianKnight** [comment]
Because this is more of a feature request then a bug report.

**Comment by Z3rio** [comment]
> Because this is more of a feature request then a bug report.

Okay sure, that makes sense. I managed to solve it, just that the native is named something completely random & nonsensical, which might want to be changed.

I'm used to feature requests being through Github Issues aswell, what does FiveM use for their feature requests then?
