### ISSUE TITLE
adhesive.dll is crashing the launcher for the last 2 days 

### ISSUE THREAD

**Issue by SirSlyDingo** [citizenfx/fivem#1800]
[CfxCrashDump_2023_01_14_16_03_08.zip](https://github.com/citizenfx/fivem/files/10418184/CfxCrashDump_2023_01_14_16_03_08.zip)

https://gyazo.com/93b7b64f25892848645ddaef227892e9

launcher has been broken for me for the last 2 days .. i tried many fixes and nothing works.. i can launch fivem ONLY when i delete the adhesive.dll ..but then i cant join any server because without adhesive.dll the servers reject you. i even tried pasting in someone elses adhesive.dll and it wouldnt fix the issue. i also did a fresh install.. still broken  .. please help

**Comment by blattersturm** [comment]
> please help

Wrong place.~
