### ISSUE TITLE
Mistake in the docs for RemoveBlip()

### ISSUE THREAD

**Issue by Griiimon** [citizenfx/fivem#1802]
The docs say it has a return value and no parameters but it's supposed to be the other way around.

https://docs.fivem.net/natives/?_0x86A652570E5F25DD

![image](https://user-images.githubusercontent.com/25064539/212503540-4eda1138-13dc-49d4-a80e-0e7def3ddc9b.png)

**Comment by AvarianKnight** [comment]
This isn't the place to report such issues, this should reported on the actual natives documentation, this has been known for a while and happens on any native that takes a reference, such as [DELETE_ENTITY](https://docs.fivem.net/natives/?_0xAE3CBE5BF394C9C9)

**Comment by blattersturm** [comment]
Not related to this repository.
