### ISSUE TITLE
Kernal related crash?

### ISSUE THREAD

**Issue by NB-FiveM** [citizenfx/fivem#1808]
Hello, I have been having some unexplained crashes. I've been trying to trace it down to a resource but have been unable to. Usually the crash will indicate an issue with a resource just before the crash but all that's displayed in the TX log is:

> txaEvent "serverShuttingDown" "{＂delay＂:5000,＂author＂:＂txAdmin＂,＂message＂:＂Server restarting (crash detected).＂}"

No thread hitches, or sync hitches or anything else indicating the cause. So I've been at a loss. I decided to check the kernel log thinking maybe it was something kernel related and notice this message when the crashes happen:

Jan 18 23:14:53 FiveMEast kernel: [274186.785010] luv_svSync[120268]: segfault at 178 ip 00007f67ad345018 sp 00007f6626ffcd00 error 4 in libcitizen-server-state-fivesv.so[7f67ad30d000+151000]
Jan 18 23:14:53 FiveMEast kernel: [274186.785035] Code: 04 fe 0f 85 43 0b 00 00 e9 d6 fe ff ff 45 31 f6 45 31 e4 48 89 df ff 15 a6 17 12 00 48 8b 84 24 f0 00 00 00 8b 80 78 01 00 00 <41> 3b 84 24 78 01 00 00 0f 85 d1 00 00 00 48 8b 44 24 08 4c 8b 68

Currently running FXServer 6198

OS Information:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

Kernel Version:
5.15.0-58-generic

**Comment by blattersturm** [comment]
If there's no report ID anywhere (e.g. whatever setup isn't triggering the crash reporter), Linux crashes sadly are unactionable.

**Comment by gottfriedleibniz** [comment]
Based on the segfault address: `<41> 3b 84 24 78 01 00 00 0f 85`, one potential area for investigation would be unassigned entities owned by some server script.

https://github.com/citizenfx/fivem/blob/5864f0cd30be26ff1a3d616edccdb8580ae44874/code/components/citizen-server-impl/src/state/ServerGameState.cpp#L1663

**Comment by blattersturm** [comment]
... that'd make sense: entityClient isn't being null-checked. I'm unfamiliar with this log syntax but thanks for indicating that indeed is the text around `ip`.
