### ISSUE TITLE
 Fixed-Size NUI issue with html select element

### ISSUE THREAD

**Issue by Moozdzn** [citizenfx/fivem#1812]
1. Client (production/beta/canary) and FXServer version (5848)
2. What you expected to happen
The option tag from the html `select` element should be under said element as the image shows when `Fixed-Size NUI` is enabled and using a resolution under 1920X1080. (Image is with the option disabled to illustrate expected behavior)
![image|690x387](https://forum.cfx.re/uploads/default/original/4X/2/9/4/2946fa828e6898d15d012bd4f4ab8a0f59f58d70.jpeg)
3. What actually happens
 `Fixed-Size NUI`: enabled causes the option tag from the html `select` element to be out of place. Moving the mouse under the select element still allows to select an option even tho they are further to the right (From testing and using absolute position, the further it element is from the top left corner (0,0) the further the options are from the select element)
![image|690x390, 100%](https://forum.cfx.re/uploads/default/original/4X/5/e/4/5e45133b1f6a3ee4e94696e916ac6440f06c776f.jpeg)
4. Category of bug (eg. client, server, weapons, peds, native)
NUI
5. Reproducible steps, preferably with example script(s)
1. Enable Fixed-Size NUI
2. Enter a server and set game to windowed mode with a resolution under 1920X1080, the lower the resolution the greater the distance between the select and the options
3. Create a resource with the following NUI code
4. Start the resource

main.html
```html
<html lang="en">

<head></head>

<body">
    <select style="position: absolute; top:50%; left:50%">
        <option value="1">HEYO</option>
        <option value="2">HEYO2</option>
        <option value="3">HEYO3</option>
        <option value="4">HEYO4</option>
        <option value="5">HEYO5</option>
        <option value="6">HEYO6</option>
        <option value="7">HEYO7</option>
        <option value="8">HEYO8</option>
        <option value="9">HEYO9</option>
    </select>
  
</body>

</html>
```
client.lua
```lua
SetNuiFocus(true, true)
```

**Comment by blattersturm** [comment]
A fun screenshot while fixing it:

![29304](https://user-images.githubusercontent.com/24576130/214970995-c5c9b6d1-a222-46cb-a830-c78b113070a8.png)

... actually did get fixed, though:

![51936](https://user-images.githubusercontent.com/24576130/214971018-9b0ad786-e700-40e8-a226-3480ff057564.png)

**Comment by blattersturm** [comment]
That is likely a different concern (scroll wheel position not being translated or so).
