### ISSUE TITLE
FiveM launching into Windows Painbrush

### ISSUE THREAD

**Issue by AaltoSurfs** [citizenfx/fivem#1813]
As the title describes, when I launched my computer this morning and tried to run the FIVEM exe it just opened windows paintbrush. No idea what's going on. Completely deleted fivem and downloaded it again, same thing.

**Comment by HyperGDD** [comment]
i dont know what happens...

**Comment by AfterNath** [comment]
Yeah its wierd

**Comment by meekz2023** [comment]
Whats happening when it gonna be fixed

**Comment by hardlet** [comment]
New update: My game now launches into the updater, but throws this error code: 
![image](https://user-images.githubusercontent.com/37276406/213871737-9f15cf07-d9cf-48cf-a8ce-cace34dc4181.png)

**Comment by itzalfie01** [comment]
> Whats happening when it gonna be fixed

been hacked, shouldnt take them too long to get ahold of it again

**Comment by Ayymoss** [comment]
> > Whats happening when it gonna be fixed
> 
> been hacked, shouldnt take them too long to get ahold of it again

Provide proof of this hack, please.

**Comment by HyperGDD** [comment]
Idk what happens, but i've drawn this
![image](https://user-images.githubusercontent.com/47295059/213871794-a4e88526-76e7-4feb-a273-4c1d00cba632.png)

**Comment by Ayymoss** [comment]
FiveM seems to be back now. Client is correctly loading.
