### ISSUE TITLE
fivem paintbrush error

### ISSUE THREAD

**Issue by NeickoQ** [citizenfx/fivem#1814]
anytime i click on fivem to load it up it automatically takes me to windows paintbrush. need help

**Comment by ValenciaModifcations** [comment]
Uninstall your FiveM ASAP.

Seen a post here and at least three in the cfx.re discord indicating that it might be installing cryptominers on your machine.

**Comment by bulva2** [comment]
Stop spreading misinformation @ValenciaModifcations
![image](https://user-images.githubusercontent.com/45076998/213880724-a7c575c4-3b72-46b7-819d-b4992c1d774f.png)

**Comment by ValenciaModifcations** [comment]
> Stop spreading misinformation @ValenciaModifcations ![image](https://user-images.githubusercontent.com/45076998/213880724-a7c575c4-3b72-46b7-819d-b4992c1d774f.png)

Not spreading misinformation, advising people of the danager is worth spreading. If you have a problem with it, you can quite frankly get over it. 

you'd be the type of person to have a bomb land next to you and go "its not a bomb" before it blew up, you also cant verify that titanium wasn't hacked prior to that post, so taking action instead is a much better option then sitting here if it is installing something.

**Comment by ValenciaModifcations** [comment]
Reinstalling FiveM does launch it into the main branch
