### ISSUE TITLE
FiveM launching into Windows Paintbrush

### ISSUE THREAD

**Issue by BlotDot** [citizenfx/fivem#1815]
when attempting to launch FIVEM it will open windows paintbrush, please fix this ASAP!!

https://gyazo.com/453de90c92d7c0e59c7fde43ea47dcad

**Comment by 666JAMMY** [comment]
Sane issue here

**Comment by ValenciaModifcations** [comment]
Suggest y'all uninstall your FiveM ASAP

**Comment by ThaaSky** [comment]
why? is there any danger if we launch fivem?

**Comment by 666JAMMY** [comment]
> 

Have done already

**Comment by ValenciaModifcations** [comment]
> why? is there any danger if we launch fivem?

Without any information on whats happenning, I would not be opening FiveM, keeping it open, or anything. If you haven't opened FiveM you should be safe, since FiveM only "updates" when its ran.  

If you have opened FiveM into the new paint brush program, Uninstall FiveM from your machine and wait until you see something from FiveM themselves that can be verfied before you attempt to run FiveM again.

**Comment by BlotDot** [comment]
is this going to be fixed

**Comment by ValenciaModifcations** [comment]
> is this going to be fixed

Most likely.... I don't think any of the FiveM Developers are awake/online now so its just community moderators keeping the discord in check.

**Comment by bulva2** [comment]
![image](https://user-images.githubusercontent.com/45076998/213880706-9e988571-55de-49f2-bc91-12fd3cf91507.png)
Stop spreading misinformation @ValenciaModifcations

**Comment by ValenciaModifcations** [comment]
> ![image](https://user-images.githubusercontent.com/45076998/213880706-9e988571-55de-49f2-bc91-12fd3cf91507.png) Stop spreading misinformation @ValenciaModifcations

misinformation wasn't spread, I noted a problem and advised people to uninstall the game until fivem verifies that its fixed.

**Comment by PepannOS** [comment]
its was turning on now but it says error 429

**Comment by ValenciaModifcations** [comment]
> its was turning on now but it says error 429

typically an error code that indicates to many request. probably alot of people getting into FiveM and overloading their auth servers.

**Comment by ValenciaModifcations** [comment]
Reinstalling FiveM does launch it into the main branch.

**Comment by z3r0Colt** [comment]
> ![image](https://user-images.githubusercontent.com/45076998/213880706-9e988571-55de-49f2-bc91-12fd3cf91507.png) Stop spreading misinformation @ValenciaModifcations

d-bub back at it again lmao
