### ISSUE TITLE
Camera shake after upgrading to DLC 2802

### ISSUE THREAD

**Issue by damightylamb** [citizenfx/fivem#1823]
The server I am currently developing for have been reporting a "camera shake" while in 3rd person. I understand that there is a setting in FiveM that does disable this (see image) but reports from the players have been stating that the "fix" does not change the camera shake. 

![image](https://user-images.githubusercontent.com/77940542/213934083-8a8787ef-2898-40fa-9283-fc52cf7d7cde.png)

Was hoping for clarification on this setting on whether or not this setting was supposed to adjust that camera shake. If not, then what does this fix so I can clarify with the players of the server. 

If this setting was supposed to fix that camera shake, then I suppose its a bug report then.

**Comment by FlawwsX** [comment]
Does not seem related to the DLC version.

It works fine on my end using 2802, **but a user reported:**

> It only started when I reinstalled fivem. I had it disabled when i uninstalled, and then reinstalled. it was automatically checked, but it doesnt work.

**Comment by gottfriedleibniz** [comment]
With the 2802 RTTI changes, this [offset](https://github.com/citizenfx/fivem/blob/master/code/components/rage-nutsnbolts-five/src/FrameHook.cpp#L201) is incorrect (28). `DoAppState` is never called and the `DisableCameraShake` hooks are never invoked. 

Tangentially, with how [DisableCameraShake](https://github.com/citizenfx/fivem/blob/master/code/components/gta-core-five/src/DisableCameraShake.cpp#L25-L33) is implemented, it is likely accidental that this works to begin with. (I think?)

**Comment by blattersturm** [comment]
> it is likely accidental that this works to begin with

I think the main thing missing there would be configuring at runtime. PR author didn't have time to adjust that, but this indeed does need a mild rework.

(similarly, ouch! both those places linked look old and probably based on 2015-era assumptions and understanding about game code as well)

**Comment by thorium-cfx** [comment]
I think this got fixed with f435c5f147cedd868c4975ebb951c81c0ee79663, can this be confirmed so we can close this issue?

**Comment by damightylamb** [comment]
@thorium-cfx yes was fixed! Thank you!
