### ISSUE TITLE
FxDK shortcut path isn't correct.

### ISSUE THREAD

**Issue by JarieTimmer** [citizenfx/fivem#1825]
Hi. 

FxDK won't open when using the shortcut because the path is not correct.

the target path is ..\FiveM\FiveM.app\data\cache\subprocess\FiveM_SteamChild.exe -fxdk

But, FxDK will only run for me when using:  ..\FiveM\FiveM.exe -fxdk

After reinstalling FiveM the shortcut path is identical. So I believe the installer uses the wrong path.

**Comment by blattersturm** [comment]
This doesn't seem to reproduce here - the shortcut gets properly created as `FiveM.exe -fxdk` on this system.

**Comment by VanishedMC** [comment]
I had the same issue some days ago, the FXDK had its path to some executable in cache, rather than the main fivem executable with launch arguments

**Comment by JarieTimmer** [comment]
I did a clean install this morning, and the shortcut now has the correct path for me. 

The issue can be closed as far for me. Thanks.
