### ISSUE TITLE
building.md instructions do not include installation of git

### ISSUE THREAD

**Issue by rebroad** [citizenfx/fivem#1826]
The document https://github.com/citizenfx/fivem/blob/master/docs/building.md currently assumes the "git" command will exist from a Command Prompt, but does not include the installation of git beforehand.

**Comment by jaymo1011** [comment]
I think that it's a safe assumption. `git` should exist in the environment of someone interacting with git repositories. Even if not, the installation of git is trivial and out of scope for project specific documentation. Perhaps at most it could be listed as a prerequisite (open a PR!) but even then, it's a fairly mundane "issue".

**Comment by Disquse** [comment]
According to you logic, we should also provide an instruction about purchasing PC and installing Windows and Visual Studio? We're on **Git**Hub.com, properly installed and working Git is expected as something obvious.

**Comment by rebroad** [comment]
> According to you logic, we should also provide an instruction about purchasing PC and installing Windows and Visual Studio? We're on **Git**Hub.com, properly installed and working Git is expected as something obvious.

All other software prerequisites are mentioned, e.g. python, etc. It's only the software prerequisites I am suggesting are included, and the recommended git software that is supported (in the same way that recommendations are made for python, etc).
