### ISSUE TITLE
Suggestion: Hook DrawSkeleton to hide skeleton part ?

### ISSUE THREAD

**Issue by zircxnium** [citizenfx/fivem#1832]
Implement a custom native to "hide a ped bone this frame" that would rely on this implementation example (https://github.com/CamxxCore/DismembermentASI), would be cool to make RDR-like dismemberment or stuff like this ? I could maybe make a PR on my own when I get time to if bubble is not interested on this stuff 🤷‍♂️

**Comment by blattersturm** [comment]
Per-frame seems weird, storing in an entity extension could work. This is still a feature request though so these should go on the forums and not here.
