### ISSUE TITLE
Sound ID limit

### ISSUE THREAD

**Issue by JLFSL** [citizenfx/fivem#1833]
Hi,

It appears that there's a limit to the amount of sound id's that can be requested. The limit seems to be 100.
This causes issues with large servers making lots of use of them, forcing them to use NUI sounds.

Is there any way this limit can be removed?

**Comment by PappaNiels** [comment]
Do you release the sound id from memory with ReleaseSoundId()? It is like SetModelAsNoLongerNeeded(). And for some sounds you can parse -1 as they don’t need a sound id.

For next time, use the forums or the discord guild for these kind of questions.

**Comment by JLFSL** [comment]
> Do you release the sound id from memory with ReleaseSoundId()? It is like SetModelAsNoLongerNeeded(). And for some sounds you can parse -1 as they don’t need a sound id.
> 
> For next time, use the forums or the discord guild for these kind of questions.

It's not about cleaning up; which I do for all sounds, even range bound.
It's about the fact that there are only 100 available sound id's, which isn't hard to fill up in e.g. minigame servers.

The literal simple question is whether this limit can be increased, whether it's a game or FiveM limit.

**Comment by pedr0fontoura** [comment]
It's not just a literal simple question, there are a lot of other questions involved to narrow down the issue.

Are you talking about networked sounds? Why are you playing 100 sounds on a single client at the same time?

This could be the case of a pool increase or something way more complex depending on the specifics. If you would like this to be actionable, you should at least be able to provide a repro.

**Comment by gottfriedleibniz** [comment]
> way more complex depending on the specifics

Much of `audScriptAudioEntity` is statically allocated and there is not much there in the way of pooling. And the amount of work required to 'increase' (i.e., replace) this limit is probably not worth it.
