### ISSUE TITLE
"populationPedCreating" Event Not Cancelling Entity Creation

### ISSUE THREAD

**Issue by Xilophinum** [citizenfx/fivem#1834]
Hi Bubble!

While working on handling entity spawns in the Altruists Camp, I have come to find that I cannot control their spawning with the referenced event. Based on the docs, its states:

> -- you can also CancelEvent() to skip creating the ped

Based off my research, the event will spam entity creation events, until it gets to the pop it was designed to have in the area that is labeled as CULT in the popcycle. It seems to want to attempt to cancel the entity creation, but it will continue to call the event, allowing entity creation to bleed through, until it reaches its popcycle limit. 

Simple repro steps:
Have a resource with blacklisted ped models found at the cult location, have populationPedCreating event CancelEvent when the model is found to be entering its creation, and then noclip/teleport to Altruist Camp. Wait ~30s to a minute and all peds will have been created around you, even though they were supposed to be cancelled. Test resource simply consisting of the above has been provided. 
[testresource.zip](https://github.com/citizenfx/fivem/files/10514377/testresource.zip)

I tested with an empty onesync server, game build 2699, artifact 5848. Only vMenu installed to noclip to destination. 

If I have mis-interpreted the meaning of CancelEvent, then I am sorry to waste your time!

**Comment by Xilophinum** [comment]
Just to add to this, with more testing, it seems as though this group of entities do not allow their positions to be modified. For example:

> setters.setPosition(-1058.429, 4948.488, 209.996)

Setting the position of all matching models to a random place in the Camp above, but it has no effect or outcome of placement, the entities will still spawn in the scenario locations.

**Comment by gottfriedleibniz** [comment]
It should be possible to just use [SetPedModelIsSuppressed](https://docs.fivem.net/natives/?_0xE163A4BCE4DE6F11). Referencing your reproduction:

```lua
Citizen.CreateThread(function()
    for model,_ in pairs(BlacklistedPedModels) do
        SetPedModelIsSuppressed(model, true)
    end
end)
```

Using `populationPedCreating` to control scenario populations has its issues - some of which you have described.
