### ISSUE TITLE
ERROR with GetConvar

### ISSUE THREAD

**Issue by stgSRP** [citizenfx/fivem#1839]
local str = GetConvar('endpoint_add_tcp', '30120')
print(str)

Why does this always return me port 30120
The port ist changed to 30122

**Comment by Szpachlan** [comment]
use GetConvarInt("netPort") to get port of server

**Comment by stgSRP** [comment]
Thank you very much

**Comment by blattersturm** [comment]
For further information: `endpoint_add_tcp` is a command, not a convar. Getting it as if it were a convar will as such return the default value.
