### ISSUE TITLE
Calling ExecuteCommand("restart " .. GetCurrentResourceName()) makes the server crash instantly

### ISSUE THREAD

**Issue by TsxMax** [citizenfx/fivem#1840]
Hi !
I called the method ExecuteCommand("restart " .. GetCurrentResourceName()) from the resource I'm trying to restart itself, and the server crashed

![image](https://user-images.githubusercontent.com/13369879/215328659-13179334-d135-465e-a4c2-942aa1e290f7.png)

I think this should be fixed
Thanks for your work

**Comment by Szpachlan** [comment]
I think its for security reasons

**Comment by TsxMax** [comment]
Why would it crash then ?

**Comment by blattersturm** [comment]
Where would `ExecuteCommand` return to if the resource that's executing is stopped? Exactly.

If this were 'fixed' it'd just be a no-op, since there is no way to correctly self-restart a resource.
