### ISSUE TITLE
IsPlayerFreeAiming not working as intended

### ISSUE THREAD

**Issue by TraficOfPeras** [citizenfx/fivem#1844]
The native function "IsPlayerFreeAiming()" does not work as intended.
That function does not return the correct value if the PlayerId() we put on the parameter is different from our own PlayerId()
It does work with my own playerid but if I try to get the aim state of another player it is just returning false.
![image](https://user-images.githubusercontent.com/56407925/215906287-3881353f-aff3-4257-a308-b1a467333990.png)

**Comment by blattersturm** [comment]
You really don't have to post the same thing - likely a feature request, since this is probably _base game behavior_ - in two places.

This is already reported on https://forum.cfx.re/t/isplayerfreeaiming-not-working-for-non-local-permanent-ped/4885046.
