### ISSUE TITLE
Character Deletion

### ISSUE THREAD

**Issue by KILLERDICIPLE** [citizenfx/fivem#1846]
Hello admin could you please delete all the characters on my profile, as my screen got stuck on creation and I created like 4 people, please just delete them all so I can create my guy correctly,I have tried to delete them using the ingame delete option but it does nothing.

**Comment by thorium-cfx** [comment]
We don't have access to your characters on whatever server you are playing on, nor do we offer support on here, please get in touch with the actual owners of the server you play on.
