### ISSUE TITLE
Unhelpful error in txadmin console

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1849]
I get this error
https://i.imgur.com/qh9k5iv.png

It's not really helpful, can the error be made more useful, like atleast saying which resource or which line, etc?

**Comment by Szpachlan** [comment]
Its saying that native MUMBLE_SET_PLAYER_MUTED doesn't exists

**Comment by AvarianKnight** [comment]
As Szpachlan said, this is showing an native doesn't exist by its hash 

To provide more explanation, you can find which hash by the error hash, see CC6C2EB1, which is the hash from the error.

![](https://i.imgur.com/5sqHVJC.png)

Searching in the native docs for the hash you get [MUMBLE_SET_PLAYER_MUTED](https://docs.fivem.net/natives/?_0xCC6C2EB1) 



I'm also not sure how you have a version that doesn't have this native as it was added back in [October of 2021 (minimum build 4837)](https://github.com/citizenfx/fivem/commit/d0a2e8659d8ecb8c2356152ae0e102c751ebb022)

**Comment by blattersturm** [comment]
Without additional context this isn't actionable.
