### ISSUE TITLE
False ban 

### ISSUE THREAD

**Issue by lil2tuff** [citizenfx/fivem#1852]
ok so i got my first ever pc yesterday i download five m and im banned for 289 days for no reason i have no idea even knowing how to work cheats I'm not a cheater i just want to enjoy the game please help me. Ban id 2af302a3-2295-4f6a-9f9d-785200291b27_01.

**Comment by AvarianKnight** [comment]
Did you not read the pop up when you get the ban? These bans will not be reversed you HAVE to wait them out

**Comment by lil2tuff** [comment]
Why would I wait it out if I’ve done done nothing wrong your completely retarted.
