### ISSUE TITLE
Document giveWeaponEvent

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1860]
I don't see it anywhere, yet it is talked about in a lot of forum posts by people using it to create anticheat measures for example.
https://forum.cfx.re/t/question-giveweaponevent/1523706

It is designed to be a onesync event, called when a weapon is given.

**Comment by Local9** [comment]
As stated in that post;
> It’s only ‘triggered’ when a weapon is attempted to be placed on a remote-controlled ped.

If I remember correctly its only on the server this is triggered, OneSync is enabled, and only reports if a player is trying to add a weapon to a remote controlled ped that is not in their own clients control. This does not trigger if the player gives themselves a weapon.

As found in another [post](https://forum.cfx.re/t/detect-native-functions/4883194/4);
```lua
AddEventHandler("giveWeaponEvent", function(source, data)
	source = tonumber(source)
	local entity = NetworkGetEntityFromNetworkId(data.pedId)
	if DoesEntityExist(entity) then
		local owner = NetworkGetEntityOwner(entity)
		if owner ~= source then
			-- Your ban trigger
			CancelEvent()
		end
	end
end)
```

**Comment by Keyinator** [comment]
> ```lua
> AddEventHandler("giveWeaponEvent", function(source, data)
> 	source = tonumber(source)
> 	local entity = NetworkGetEntityFromNetworkId(data.pedId)
> 	if DoesEntityExist(entity) then
> 		local owner = NetworkGetEntityOwner(entity)
> 		if owner ~= source then
> 			-- Your ban trigger
> 			CancelEvent()
> 		end
> 	end
> end)
> ```

The owner check is actually not needed to my knowledge since giveWeaponEvent is a network-event which does not need to be triggered when adding weapons to yourself:
```lua
AddEventHandler("giveWeaponEvent", function(source, data)
	CancelEvent()
	-- Your ban trigger
end)
```
(Might want to verify as some scripts MIGHT handle this differently.

**Comment by AvarianKnight** [comment]
Would giving a ped you don't have ownership trigger this? I believe thats why the check is there

**Comment by Keyinator** [comment]
> Would giving a ped you don't have ownership trigger this? I believe thats why the check is there

Probably. Now it makes sense

**Comment by AvarianKnight** [comment]
Just a note [this is already documented](https://docs.fivem.net/docs/scripting-reference/events/server-events/) though isn't searchable (maybe because its embedded)

**Comment by mcNuggets1** [comment]
Its not on the page.
I just looked.
