### ISSUE TITLE
Error in enter server various "No autentication ticket was specificed"

### ISSUE THREAD

**Issue by adailsonm** [citizenfx/fivem#1861]
[     11429] [b2372_GameProc]  UV loop: httpClient/ OnConnectionProgress: Handshaking with server...
[     11430] [b2372_GameProc]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x4f916676 INIT_CORE init (21 out of 22)
[     11434] [b2372_GameProc]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking CCreditsText INIT_CORE init (22 out of 22)
[     11435] [b2372_GameProc]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Done running INIT_CORE init functions!
[     11682] [b2372_GameProc]  UV loop: httpClient/ OnConnectionError: Connection rejected by server: No authentication ticket was specified.
[     98235] [b2372_GameProc]        CrBrowserMain/ OnConnectionProgress: Requesting server variables...
[    102127] [b2372_GameProc]                 2792/ Switching from build 2372 to build 2699...

Not found issue about its

**Comment by blattersturm** [comment]
This is not a support section.

In your case it looks like you either deleted `adhesive.dll` or ignored the warning at launch telling you that you're using Windows on ARM or Wine and as a result connecting to public servers is not supported.
