### ISSUE TITLE
fragInstGta Pool Full, Size == 1600 (you need to raise fragInstGta PoolSize in common/data/gameconfig.xml)

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#1864]
• Is there a way to have this default increased in a FiveM update in the future?

• Alternatively, some way to edit this on the client successfully without it causing a crash upon loading into a server.

`fragInstGta Pool Full, Size == 1600 (you need to raise fragInstGta PoolSize in common/data/gameconfig.xml)`

Client will crash after a time. Whenever any of our players get into a gun fight (sometimes we have Team Deathmatch style events with lots of shooting going on) this error happens to everyone after a few minutes to people randomly. Likely due to all of the projectiles I'd surmise. 

Just want to see if its possible. I know this error has popped up in my searches elsewhere but no support or answer ever given for it. But its happened to about 40 people (not at the same time, but throughout the night during an event) and its making any sort of larger shoot outs rather impossible.

Thank you for your time and hard work.

**Comment by MoskalykA** [comment]
Hello, is there a solution? many of my players have it
