### ISSUE TITLE
FiveM Devs

### ISSUE THREAD

**Issue by Not3nad** [citizenfx/fivem#1866]
when someone actually spends a lot of time in community, and their devs are piece of shit you cant really do much, i provided all information of why i was banned with stream clips and 10+ hours of gameplays still got falsely banned by the system,  also i can name many cheats the are active in FiveM, [redacted] and a lot more!, which never has been detected even in the latest update, and yall are happy with banning innocent just to show its player oh we are actually banning ppl who don't use cheats, Hurraah! look at us banning them. show us that you guys actually care about players and ban ppl who provided the cheats i bet you fucking wont.

**Comment by Disquse** [comment]
Please stop spreading nonsense and face your fault like a decent person. Don't spam issues or you will be blocked.
