### ISSUE TITLE
Server Crashes SigSegv

### ISSUE THREAD

**Issue by AngeloneIL** [citizenfx/fivem#1868]
i noticed there are a bunch of people suffering from this problem

https://forum.cfx.re/t/sigsegv-random-crashes-looking-for-external-advices/4975484

https://forum.cfx.re/t/sigsegv-crashing-server/4801861

https://forum.cfx.re/t/server-crashes/5029201/3 - and my own post as well

also seen a bunch of people complain about this on txadmin's discord via fivem-support

any idea how to fix this problem or wether or not its going to be fixed by fivem themselves, dump file included in my post.

**Comment by blattersturm** [comment]
Can't repro and not enough info has been provided for a fix - a dump doesn't seem to be sufficient.

**Comment by AngeloneIL** [comment]
isn't there anything at all we can provide you with to fix this problem?

**Comment by AngeloneIL** [comment]
https://cdn.discordapp.com/attachments/664871358253105165/1078226677185904691/image.png -- Crash Result Through Dump File

**Comment by AngeloneIL** [comment]
https://dropmefiles.com/ZlMW7
