### ISSUE TITLE
RedM - ```CreatePed``` does not work server-side

### ISSUE THREAD

**Issue by cqmpact** [citizenfx/fivem#1870]
This function works in FiveM, trying to port over my NPC spawner and it does not seem to work in RedM.
Ped does not return 0 but it does not exist after it's "spawned" and its coords are 0.0, 0.0, 0.0 (doesn't exist).

Server Version: ```6247```
Game Build: ```1491```

Expected outcome: The ped spawns with the set model at the coordinates.

```
function spawnNPC(npcData)
    local pedModel = GetHashKey(npcData.model)
    local ped = CreatePed(4, pedModel, npcData.coords.x, npcData.coords.y, npcData.coords.z, npcData.coords.w, true, false) -- same with true for bScriptHostPed
    if not DoesEntityExist(ped) then
        print("Error creating ped")
        return
    else
        print("Ped created")
    end
end

spawnNPC({
    model = "A_M_M_BiVWorker_01",
    coords = {
        x = 2748.78,
        y = -1398.2,
        z = 46.18,
        w = 203.39
    }
})
```

If you try to do ```local pedNet = NetworkGetNetworkIdFromEntity(ped) or PedToNet(ped)```, you will get 
```InvokeNative: execution failed: Tried to access invalid entity: pedIDhere``` in response.

**Comment by Disquse** [comment]
RPC natives aren't available for RedM yet. Some RPC natives may work due to coincidence. Wait for proper implementation of RPC natives in RedM

**Comment by cqmpact** [comment]
> RPC natives aren't available for RedM yet. Some RPC natives may work due to coincidence. Wait for proper implementation of RPC natives in RedM.

Okay, thank  you for this information.
