### ISSUE TITLE
SDK: FxDK build process makes new server artifacts every time

### ISSUE THREAD

**Issue by Whoeza** [citizenfx/fivem#1882]
Hi, building the server artifacts for every single project made with FxDK might waste a lot of CPU and hard disk space, as well as deploying with an outdated FXServer version.
Maybe you could consider allowing the user to specify the location of an existing FXServer in FxDK settings.
It could be an option in the build modal: - build new server artifact Y/N - [if N] server artifact location BROWSE

**Comment by nihonium-cfx** [comment]
You already can disable adding server artifact into build:
![image](https://user-images.githubusercontent.com/77746579/225287992-004cca36-9abc-48ed-9f65-0669a1f2820a.png)
