### ISSUE TITLE
Can we please add a convar option for that line?

### ISSUE THREAD

**Issue by bigamer2** [citizenfx/fivem#1885]
Our console log is filled with messages that looks like this:
[ citizen-server-impl] server thread hitch warning: timer interval of 159 milliseconds
[ citizen-server-impl] server thread hitch warning: timer interval of 157 milliseconds
[ citizen-server-impl] server thread hitch warning: timer interval of 156 milliseconds
[ citizen-server-impl] server thread hitch warning: timer interval of 158 milliseconds

we noticed the limit is coming from here and it's set to a hardcoded 150ms

https://github.com/citizenfx/fivem/blob/9b9823fd1add1f833f8a3e116cb96ef78b0775ee/code/components/citizen-server-impl/src/GameServer.cpp#L213

Can we please work together to add this configuration option?

Any tips?

Ideally we would like to configure this from our server cfg as follows:
![image](https://user-images.githubusercontent.com/124350637/222747202-9ea419b0-b25f-4d20-81e0-bffb99752a9e.png)

**Comment by blattersturm** [comment]
no.

**Comment by bigamer2** [comment]
Hi, thank you for taking the time to help me,
I looked everywhere for print filters yet couldn't find any way to filter those server thread hitch warnings, care to throw a bone?
