### ISSUE TITLE
Ability to pack multiple escrowed assets.

### ISSUE THREAD

**Issue by d22tny** [citizenfx/fivem#1886]
Hello. 
At this time, asset developers [ cars / mlos ] guys, are not even willing to help their customers by packing all the assets i've bought into one resource. So i came here to ask for help.
Would you implement multiple fxaps into one resource, just like all the stream components are loaded.
For example to have 1.fxap, 2.fxap, 3.fxap etc, so instead of 100 resources for escrowed cars, i'd have only one resource.

**Comment by andreiciobanica** [comment]
I believe this is a very good idea and I hope in the future to be able to pack multiple escrowed assets as ONE RESOURCE because it's a little bit frustrating to `ensure` every escrowed resource.

**Comment by FPLAYT** [comment]
Good idea !!!

**Comment by Vladut29** [comment]
Good idea

**Comment by victorTimofte12** [comment]
I support this idea 👌

**Comment by andreiromania12** [comment]
Good Idea!

**Comment by Sebyzz23** [comment]
Very good idea. This thing is gonna help everybody.

**Comment by edinazy** [comment]
that s a nice idea 👌👌👌

**Comment by DanielPitropu** [comment]
Good idea !!!

**Comment by wastedgmt** [comment]
This would be great! Upvote for you!

**Comment by MrFicus** [comment]
Very good idea! 👍

**Comment by medusaa22** [comment]
This would be very useful.

**Comment by Bogdan0333** [comment]
Very good  idea !

**Comment by AMETITU** [comment]
Very good idea! +1 from me.

**Comment by Dazon100** [comment]
Very good idea !

**Comment by TdU12** [comment]
Good idea 👍

**Comment by anggrypanda** [comment]
Thumbs up :)

**Comment by olixdx** [comment]
> I believe this is a very good idea and I hope in the future to be able to pack multiple escrowed assets as ONE RESOURCE because it's a little bit frustrating to `ensure` every escrowed resource.                                                    
this idea comes with a good optimization and stability as well

> I believe this is a very good idea and I hope in the future to be able to pack multiple escrowed assets as ONE RESOURCE because it's a little bit frustrating to `ensure` every escrowed resource.

ciobanica do not forget that ,this idea comes with a good optimization and stability as well

**Comment by rol3x1337** [comment]
a super good idea, in the future it would be interesting to be able to give ENSURE directly to a resource, because it is frustrating to give ENSURE to every escrowed resource. 👍🎮

**Comment by technetium-cfx** [comment]
This should be a feature request that goes in the [forums](https://forum.cfx.re). 

That said, the brigading happening here does not bring positive attention to your request and does not look good on you.
