### ISSUE TITLE
More Train Controls

### ISSUE THREAD

**Issue by maxgestic** [citizenfx/fivem#1889]
Update natives to allow more functionally with trains, Alt:V has a lot more that you are able to do with trains and it be great if FiveM could support as much as that. Especially being able to switching a train between train tracks.

https://docs.altv.mp/js/articles/vehicle/train-api.html

**Comment by AvarianKnight** [comment]
This isn't the place for feature requests, [you should use the forums instead](https://forum.cfx.re/c/general-discussion/feature-requests/33).
