### ISSUE TITLE
sv_filterRequestControl 

### ISSUE THREAD

**Issue by KiLaF** [citizenfx/fivem#1897]
Hello, I was checking on the sv_filterRequestControl command and i noticed when i put it on -1 ( sv_filterRequestControl -1 ), it will print on console only when a player tries to take control of another vehicle. Is their a way to add a event triggred aswell as the print so we can do interactions with it.

**Comment by blattersturm** [comment]
What kind of 'interactions' would you like to 'do with it'?

**Comment by KiLaF** [comment]
> What kind of 'interactions' would you like to 'do with it'?

As for exemple anti-cheat interactions so we can detect cheaters that tries to controls others players vehicles (like delete them, or make them fly etc...)

**Comment by blattersturm** [comment]
That's unsupported by design. The setting already mitigates any abuse by preventing the control request, there's not really anything else you need to do regarding abuse.

**Comment by KiLaF** [comment]
> That's unsupported by design. The setting already mitigates any abuse by preventing the control request, there's not really anything else you need to do regarding abuse.

how can it be abused, their is really much you can do with it. i mean you can added a trigger that is just informing that a player tried to request control, but you can't cancel or refuse the control event.
