### ISSUE TITLE
Removing platform/ and other random files should trigger integrity checking

### ISSUE THREAD

**Issue by xxldudu22** [citizenfx/fivem#19]
[Window Title]
FiveM Fatal Error

[Main Instruction]
FiveM has stopped working

[Content]
An error caused FiveM to stop working. A crash report is being uploaded to the FiveM developers. If you require immediate support, please visit FiveM.net and mention the details below.

[^] Ocultar detalhes  [Close]

[Expanded Information]
Crash ID: b212139d-856f-4a3a-a7f5-28a9e0682d7f (use Ctrl+C to copy)

**Comment by blattersturm** [comment]
Remove `caches.xml` for your error scenario - it seems you'd deleted `citizen/platform/`.
