### ISSUE TITLE
Kernal Error Crash

### ISSUE THREAD

**Issue by NB-FiveM** [citizenfx/fivem#1901]
luv_svSync[2779]: segfault at 40 ip 00007f7bdee420d4 sp 00007f7bd5905500 error 4 in libcitizen-server-state-fivesv.so[7f7bdee2a000+153000]
Code: 80 7f fc 00 74 12 85 d2 74 01 f4 48 63 57 f8 81 fa ff ff 00 00 7f 01 f4 89 d0 c1 e0 04 48 98 48 29 c7 48 8b 47 f0 48 83 ef 10 <48> 39 78 10 74 01 f4 40 8a 78 20 83 e7 1f 39 f7 7d 01 f4 8b 78 18

on build FXServer 6332

**Comment by blattersturm** [comment]
Not enough information to be actionable.
