### ISSUE TITLE
Make a native for f8

### ISSUE THREAD

**Issue by PlantBronze** [citizenfx/fivem#1904]
Would be nice if there is a native that can check if the player opened f8 console.
Like
NetworkIsPlayerInConsole()
So u can make checks for scripts

Thanks
Or if there is a way to get if f8 is opened please let me know

**Comment by pedr0fontoura** [comment]
Use case? I assume you don't want to ban players who open the console, right?

**Comment by blattersturm** [comment]
This is not a place for feature requests. Also, the console should be entirely transparent to scripts - you shouldn't need to check if it is opened.
