### ISSUE TITLE
FiveM cannot be started, an error window appears

### ISSUE THREAD

**Issue by xoxttxox** [citizenfx/fivem#1905]
![Screenshot 2023-03-16 232846](https://user-images.githubusercontent.com/128100889/225767680-54a8bf67-46af-449d-9353-86eebadbd0b1.png)

**Comment by igorsfreitas** [comment]
signed

**Comment by adam-gweleg** [comment]
I have the Same Issue

**Comment by ENJ1** [comment]
Same here

**Comment by RyantheSheriff** [comment]
Okay guys, no need to spam his issue, they're aware we all have the same issue 😭😭 jesus

**Comment by ENJ1** [comment]
> Okay guys, no need to spam his issue, they're aware we all have the same issue 😭😭 jesus

4 other people commented, for most projects this is the bare minimum to make sure its a reproducible issue affecting many, but yeah, I get your point.

**Comment by KetsMiku** [comment]
I have the same problem, and it appeared after the update.

**Comment by Chrissi-de** [comment]
me to idioten no joke

**Comment by AvarianKnight** [comment]
Spamming same when its already been acknowledged in the Cfx.re discord will help no one, they are already aware of the issue and are working on it.

**Comment by Chrissi-de** [comment]
AvarianKnight shut up son of bitch

**Comment by Nathaaan** [comment]
same for me
