### ISSUE TITLE
Five M cfx.re Not Working 

### ISSUE THREAD

**Issue by Apriadi1996** [citizenfx/fivem#1907]
Hallo can help me , currently I am experiencing problems Five M cannot run smoothly can not connenting stuck in preparing to request authentication ticket this after the update of the occurrence of a problem in five M this morning before

![ips](https://user-images.githubusercontent.com/128139338/225873056-774780bf-84a0-4750-bb90-77abe6f68a2f.png)
![image](https://user-images.githubusercontent.com/128139338/225873086-7b16c183-e789-46c6-8355-4127b606123a.png)

**Comment by 4rossi6** [comment]
It doesn't work for me either

**Comment by 4rossi6** [comment]
If someone managed to solve it, please help others

**Comment by 4rossi6** [comment]
So what's going on, I've tried restarting the router and steam and uninstalling fivem

**Comment by BangBangerson** [comment]
Did u ever fix it?

**Comment by roods02** [comment]
eu estou com o mesmo problema 
![HDSA](https://user-images.githubusercontent.com/128187554/226035519-32bfde48-8c8c-4719-84f1-d571cf37f7ae.png)

**Comment by roods02** [comment]
> Você já consertou?

ajuda nois ai ta geral com esse problema

**Comment by 4rossi6** [comment]
No one will help the godfather

**Comment by 1kswavvyy** [comment]
fivem not working for me every since yesterday

**Comment by MOscOW2001** [comment]
![image](https://user-images.githubusercontent.com/128195233/226071954-5c96a5ee-58fe-4666-9780-26e3ce7d1f1e.png)

**Comment by 1kswavvyy** [comment]
Yes mine doing that

**Comment by torresgitan28** [comment]
hola tengo este mismo problema ahi alguien que me pueda ayudar eh reiniciado e borrado fivem lo eh buelto a instalar i sigue el mismo problema
