### ISSUE TITLE
Clothing texture regressions (since #1841?)

### ISSUE THREAD

**Issue by Kc2693** [citizenfx/fivem#1911]
I first saw reports of this bug coming in since 3/16. Server owners & players (across multiple servers) are reporting that skin tone clothing is suddenly appearing completely black, as some sort of graphics issue. 

- This is happening to both native/gta clothing as well as custom addon.
- Seems to be happening to people with "lower" graphics settings
- Forcing 'bugged' users to turn their texture quality to high+ seems to fix issue (but obv this isn't viable long-term)

At first I suspected it was because of #1841 but I have since heard a report of someone experiencing this issue while currently on Release channel of fivem (1841 is only on beta/unstable right now). Not sure what else could have been changed in the meantime aside from that PR. 

All images below are from different people across different servers:
![image](https://user-images.githubusercontent.com/28677397/226096922-6e323d74-4d2f-45c2-9cf0-4c695af89e79.png)
![image](https://user-images.githubusercontent.com/28677397/226096941-bc4fcdec-71f5-4a43-9c14-e0cffb07fbc0.png)
![image](https://user-images.githubusercontent.com/28677397/226096956-0b19e21f-e5b7-4fae-b904-0deeecfa2a60.png)

**Comment by nikez** [comment]
Hi,

Can you have one of the users with this issue do "str_meshBlendTextureRes -1" in F8?

**Comment by blattersturm** [comment]
Is there any known component that is affected here, or does it include 'all'?

Also, is there anything specific GPU-wise here that correlates?

**Comment by Kitteeeee** [comment]
> Hi,
> 
> Can you have one of the users with this issue do "str_meshBlendTextureRes -1" in F8 (and have them restart the client!!)

This worked for us, on unstable

**Comment by Kitteeeee** [comment]
> > > Hi,
> > > Can you have one of the users with this issue do "str_meshBlendTextureRes -1" in F8 (and have them restart the client!!)
> > 
> > 
> > This worked for us, on unstable
> 
> Can you check if str_meshBlendTextureRes 2048 and texture quality high or very high solves the issue too?

Also resolves the issue, yes!

**Comment by flnyla** [comment]
Im also having an issue where pants color are turning to the skin color instead. This also is happening to shoes as well. They seem to take on the texture color of something in a different spot. My guess is that this can happen to any clothing item that shows skin color.

I can replicate this with a friend by having him open his screen share. I can change into an outfit, everything will be fine. 
Then I no clip/fly a heli far away and come back and this issue replicated. He will either see my shoes the same color as the texture for a random clothing item or the pants the color as my skin.

**Comment by blattersturm** [comment]
Is this some case of pooling being weird in some way?

**Comment by YasinY** [comment]
I have the same issue c:(

**Comment by blattersturm** [comment]
I'm suspecting another regression started from #1841: https://forum.cfx.re/t/5050983/5?u=d-bubble has a much increased crash incidence starting March 10th, increasing further when the build containing this changeset hit production.

Here's a representative crash stack from one of the newer/common ones: https://sentry.fivem.net/share/issue/649e31d0bbb3479d8a3ae6b39e703ea5/

**Comment by 4xFloodx4** [comment]
Changing to canary version the problem is solved

![image](https://user-images.githubusercontent.com/90792241/232057095-ae24e034-7707-491f-a4ab-81166de390da.png)
![image](https://user-images.githubusercontent.com/90792241/232057437-1a4a5c2f-c08f-4f5b-8939-fe31f3330e37.png)
![image](https://user-images.githubusercontent.com/90792241/232057675-21f1d0f7-4667-4cae-b50b-78854ed1fc32.png)
![image](https://user-images.githubusercontent.com/90792241/232058015-dbf3d0ea-2034-4132-bfb8-4bf84ddae869.png)
