### ISSUE TITLE
RDR3 Client crashes constantly

### ISSUE THREAD

**Issue by ozdeadmeat** [citizenfx/fivem#1912]
RedM was launching now it no longer launches since the last crash.

[CfxCrashDump_2023_03_18_17_06_31.zip](https://github.com/citizenfx/fivem/files/11009151/CfxCrashDump_2023_03_18_17_06_31.zip)
[CfxCrashDump_2023_03_18_16_41_44.zip](https://github.com/citizenfx/fivem/files/11009150/CfxCrashDump_2023_03_18_16_41_44.zip)
[CfxCrashDump_2023_03_18_16_12_28.zip](https://github.com/citizenfx/fivem/files/11009149/CfxCrashDump_2023_03_18_16_12_28.zip)

**Comment by Disquse** [comment]
Corrupted game files. Try to verify game files or clear RedM cache. Anyway this is not a place for such reports. Use forum instead.
