### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by iusemeteor** [citizenfx/fivem#1914]
[Window Title]
Disconnected

[Main Instruction]
Oшибка (Error)

[Content]
Disconnected.

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b2699.exe+90F2E6
Report ID: si-8e083bddc5e74826bcda6b336fa19637
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by AvarianKnight** [comment]
This isn't the place for support, use the [forums](https://forums.cfx.re), though this doesn't even seem like a proper crash.
