### ISSUE TITLE
CrBrowserMain/ Error with Permissions-Policy header and Unrecognized feature 'web-share' error

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#1916]
```
[   4652125] [b2802_GTAProce]        CrBrowserMain/ Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'. (:0)
[   4652515] [b2802_GTAProce]        CrBrowserMain/ Unrecognized feature: 'web-share'. (https://www.youtube.com/s/player/59acb1f3/www-widgetapi.vflset/www-widgetapi.js:1114)
```

This has been happening recently to everyone and even causing crashes I suspect. I've received about 14 client logs now of someone crashing and this for whatever reason is always near it.  It only started showing up recently but I cannot give an exact date.

Would you happen to know if its something we can fix on the client/server? Thank you.

**Comment by blattersturm** [comment]
I doubt this is 'causing crashes'. This is probably some website you're loading expecting a newer Chrome version and is merely a non-fatal warning.
