### ISSUE TITLE
Black clothing going skin tone

### ISSUE THREAD

**Issue by Shihiro1** [citizenfx/fivem#1920]
I see there was a FiveM fix for skin tone going black, but multiple servers are experiencing black clothing going skin tone.

https://cdn.discordapp.com/attachments/1074591369802293358/1088068066287550564/image.png
https://cdn.discordapp.com/attachments/1074591369802293358/1088212437955780609/image.png
https://cdn.discordapp.com/attachments/1074591369802293358/1088193567060660274/image.png

The /str thing didn't work for us. Thus far, the only thing fixing is logging out of the city and coming back in. I know this sounds client/server-side but many other servers are having the same issue as ours, which came in at the same time as the skin tone being jet-black. I know I'm a new clothing dev (extremely new) but when I'm looking at big servers with a big dev team having the same issues, I can't really say it's me or the city problem.

**Comment by blattersturm** [comment]
Can you actually provide reproduction steps for this?

**Comment by blattersturm** [comment]
Duplicate for #1911 even... sigh.

**Comment by Shihiro1** [comment]
Blattersturm, it's not skin tone turning black... it's black clothing turning skin tone. I can't provide anything in terms of steps because I've no clue what's causing it at all. It happens randomly and fixes randomly. Everyone experiences it at different intervals, everyone has different specs and settings and mods or no mods at all. There's nothing that I can really add other than what I said in terms that it came in at the same time as the skin tone colour going black situation.

**Comment by Shihiro1** [comment]
> 

![image](https://user-images.githubusercontent.com/128648596/227277823-13cfa41f-b2b2-4847-b5bf-623881d728ef.png)

**Comment by blattersturm** [comment]
Sending odd messages by proxy without citing original information is again just... annoying.

There wasn't any other change to clothing textures and even then an issue on this abysmal site being 'open' or not has zero relation to actually solving anything.
