### ISSUE TITLE
ERROR, SEVERAL TIMES

### ISSUE THREAD

**Issue by SoupsGood** [citizenfx/fivem#1926]
I already had the software before by the way, yesterday I played. But today the game refused to open so I restarted my pc and then the game follows with a pop up message:

FiveM need to update the local game data
The Local FiveM game data is outdated, and needs to be updated. 

Then, appears a window with FivM updating and then

Error
Moving of
C:\Users\Utilizador\AppData\Local\FiveM\FiveM.app\data\game-storage\launcher\Launcher.rpf failed (err= 1008). Check your system for any conflicting software.

I tried uninstalling and other many ways and nothing.

**Comment by AvarianKnight** [comment]
This isn't the place for support, you should instead use the [forums](https://forum.cfx.re). Also a hint: probably an antivirus issue.
