### ISSUE TITLE
Peds are not spawnning

### ISSUE THREAD

**Issue by peixotorh** [citizenfx/fivem#1928]
Can someone explain why the peds of my base arent spawnig if i already put a npc control in?

**Comment by Mathu-lmn** [comment]
Hi there,

Please note that GitHub issues are primarily used for reporting bugs, requesting features, and suggesting improvements for the project. They are not meant for support inquiries.

To get support for your issue, we encourage you to visit the [Discord](https://discord.com/invite/fivem) where the community members can help you out with any questions or concerns you may have.

Thank you !
