### ISSUE TITLE
Server hang

### ISSUE THREAD

**Issue by NB-FiveM** [citizenfx/fivem#1929]
My server has been experiencing random crashes so I decided to run procdump on the process and wait until a crash is triggered. I ran the dump file produced from procdump and got the following

Unhandled exception at 0x00007FF9A7FE8B0F (citizen-server-state-fivesv.dll) in FXServer.exe_230405_093105.dmp: 0xC0000005: Access violation reading location 0x00000000000083F4.

After the debug was complete it points to;
>	citizen-server-state-fivesv.dll!fx::ServerGameState::Tick::__l2::<lambda>(const fx::shared_reference<fx::Client,&fx::clientPool> & clientRef) Line 1441	C++

Running FXServer 6374 on Windows Server 2022

**Comment by NB-FiveM** [comment]
https://github.com/citizenfx/fivem/blob/14a69a51c51d12475a116844e9d2a9133bd74921/code/components/citizen-server-impl/src/state/ServerGameState.cpp#L1441

**Comment by blattersturm** [comment]
Instead of trying to analyze the crash yourself, can you upload the crash dump?

**Comment by NB-FiveM** [comment]
Sure.
https://dropmefiles.com/dBnkp

**Comment by NB-FiveM** [comment]
I'm not sure if its anything related but I was reading the entity state bags for each entity in a for loop statement iterating over the vehicle game pool server side. After having remove that section of code the issue seems to have stopped. I'm not sure if its anything related to maybe the entity being removed from the pool as its reading its state bags causing it to hang or not. Again this was being performed server side.

**Comment by gottfriedleibniz** [comment]
Closing this issue. If you do have any more recent dumps, please provide.

Note, these random corruptions of `fx::shared_reference` are duly noted.
