### ISSUE TITLE
GamePrimitives_MapData Crashes with TODO Reference QueueEvent

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#1932]
Lately we have been experiencing some client side crashes that the crash log has some pointers towards the following:

1. https://sourcegraph.com/github.com/citizenfx/fivem/-/blob/code/components/extra-natives-five/src/GamePrimitives_MapData.cpp?L226

Which is:
```
// #TODO: use fast listener elision when we implement it
	fx::ResourceManager::GetCurrent()->GetComponent<fx::ResourceEventManagerComponent>()->QueueEvent2("mapDataLoaded", {}, (int32_t)mapData->name);
```

2. https://sourcegraph.com/github.com/citizenfx/fivem/-/blob/code/components/gta-streaming-five/src/LoadStreamingFile.cpp?L3112

Which is:
```
	return g_origfwMapDataStore__FinishLoading(store, idx, data);
```

When does the crashing occur:
This happens when driving to and from an area or flying, or no clipping from one area to another.

If you know a possible fix or if we should just wait it out until this is completed. Thank you.

**Comment by AvarianKnight** [comment]
This isn't the place for inactionable reports (i.e. no reproduction, no resource, etc) you should use the [forums](https://forums.cfx.re) instead, you should also provide crash reports instead of snippets which have no crash data.

**Comment by Legacy-TacticalGamingInteractive** [comment]
The unfinished TODO reference is actionable - I'm assuming that could be the culprit if its unfinished. Maybe could be looked into being completed. If we are experience crashing that constantly points to this section wouldn't that mean its a possible cause.

**Comment by Legacy-TacticalGamingInteractive** [comment]
What about the **// #TODO: use fast listener elision when we implement it** not yet being completed. This might help?

Apologies about not including a dmp on the initial post.

Here is one similar Crash dmp if it helps. 
[CfxCrashDump_2023_04_08_15_22_39.zip](https://github.com/citizenfx/fivem/files/11183571/CfxCrashDump_2023_04_08_15_22_39.zip)

Its not related to a resource as far as I can see. Its anywhere on the map at any random time when doing those actions mentioned. Reproduction in this case is literally just playing the game driving/walking/flying or noclipping until it happens. Tedious, perhaps yes. Thats why I'm providing any dumps I can as I get them as nobody on the team has time to do that for every single report out there.

**Comment by AvarianKnight** [comment]
This is just an event trigger, the todo is likely just a part of an extremely long backlog.

This *would* be related to resources, most likely a map as thats the only thing that calls this

**Comment by gottfriedleibniz** [comment]
Believe this was also addressed in https://forum.cfx.re/t/lod-slod-texture-issues/5074672. Issues related to bad assets, archetype limits, etc. should be placed there.
