### ISSUE TITLE
SetBigmapActive Not working as intended

### ISSUE THREAD

**Issue by ali-exacute** [citizenfx/fivem#1933]
[SetBigmapActive](https://docs.fivem.net/natives/?_0x231C8F89D0539D8F) Native does not work as intended

Tried on both _The Criminal Enterprises_ and _The Contract_ Game builds, using server builds, _6285_ and  _5799_
With and without the puremode aswell

it just flicker for a nano second whenever you call it like `SetBigmapActive(true, false)` or `SetBigmapActive(true, true)` and nothing else.

Using it in a loop will just make the minimap disappear

**Comment by Disquse** [comment]
This is an incompatibility issue caused by your resources. In one (or more) of your resources this native getting called with a different flags, this is why it getting reset next frame. Also, it's not even a custom native.
