### ISSUE TITLE
No me sale el reshade en FiveM

### ISSUE THREAD

**Issue by K0staaa** [citizenfx/fivem#1937]
Cuando entro a FiveM, le doy a la tecla de inicio y no se me abre el reshade, me he metido a los ajustes de GTA V y me pone que la tecla de inicio esta asociada al menu de social club. como lo puedo solucionar?
![image](https://user-images.githubusercontent.com/130092087/230790708-b6887715-f174-4907-8e7e-c0194edb6370.png)

**Comment by PappaNiels** [comment]
This repo is english only. I doubt the contributors know this certain language. I think this is a support thingy which you can ask support for on the [Forums](forum.cfx.re)  or in the [Discord guild](discord.gg/fivem)
