### ISSUE TITLE
Crash in StreamingFreeTests

### ISSUE THREAD

**Issue by AvarianKnight** [citizenfx/fivem#1952]
We're currently having a weird Heap crash likely due to some invalid asset, but its crashing in `typeName` instead of getting to the end of the statement and printing the error

See: ![](https://i.imgur.com/Q18tR80.png)

Here's a crash minidump [dd30160e-0374-4343-87cf-63b2f4cac18f.zip](https://github.com/citizenfx/fivem/files/11300229/dd30160e-0374-4343-87cf-63b2f4cac18f.zip) 

https://github.com/citizenfx/fivem/blob/907922333a12a96d87083d5df85d3a0de20fbbaa/code/components/gta-streaming-five/src/StreamingFreeTests.cpp#L127

Other places where `typeName` was being used their is error catching in place

https://github.com/citizenfx/fivem/blob/907922333a12a96d87083d5df85d3a0de20fbbaa/code/components/gta-core-five/src/CrashFixes.cpp#L110-L121

**Comment by blattersturm** [comment]
Doesn't seem related to typeName here since it's failing in NT heap functions, likely some memory corruption at an earlier point.

Not actionable without further info.

**Comment by AvarianKnight** [comment]
Not sure if this makes it actionable, heres a full dump https://drive.google.com/file/d/1n2k0CPiX1U0wHT6r2vv_r17Bf7K-XfKk/view?usp=sharing

This "just happens" when leaving noclip and its always this exact crash which is why I originally thought it was typeName

**Comment by gottfriedleibniz** [comment]
Looks like `fwTxdStore` has cycle in `GetDependencies`, causing the `strRequestMgr` request bits to consume all the call stack.

Looking through the dump a bit, one potential cause (I think) would be a custom `vehicles.meta` with a `txdRelationships` element that has `parent` as `vehicles_race_generic` and `child` as `vehicles_race_interior`.
