### ISSUE TITLE
Resource download lagging

### ISSUE THREAD

**Issue by joelwurtz** [citizenfx/fivem#1964]
Since this commit : https://github.com/citizenfx/fivem/commit/907922333a12a96d87083d5df85d3a0de20fbbaa 

Download is fast, but there is a timeout between each downloaded modules, so with a lot of modules the whole process is rather slow.
It also happens in a local dev environnement so i don't think it's network related.

Setting the `cl_rcdFailureBackoff` to 0 before connecting seems to resolve this issue, for what it's worth we use a nginx proxy to cache assets and let him transfer files, i see that other people also have this problem when they have a cloudflare cdn as a proxy.

Maybe nginx / cloudflare doesn't close / handle the connection like fivem do and so for each module we hit the timeout introduced in this commit ?

**Comment by blattersturm** [comment]
This has already been fixed in https://github.com/citizenfx/fivem/commit/5d9c061607ae9b3edcfcee16889c068615569139.

**Comment by joelwurtz** [comment]
didn't see it, my bad sorry for the noise
