### ISSUE TITLE
Resource Monitor Crash

### ISSUE THREAD

**Issue by ProxyPing** [citizenfx/fivem#1965]
[Window Title]
FiveM

[Main Instruction]
GameOverlayRenderer64.dll+A6CC8

[Content]
An error at GameOverlayRenderer64.dll+A6CC8 caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
Stack trace:
  GameOverlayRenderer64.dll+A6CC8
  GameOverlayRenderer64.dll+AD15C
  GameOverlayRenderer64.dll+88F2D
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63

[^] Details ausblenden  [Save information] [Schließen]

[Expanded Information]
Crash signature: gameoverlayrenderer64.dll+A6CC8
Report ID: si-850292c1d05f4f969b4000d2e9fada75

[CfxCrashDump_2023_04_29_21_51_49.zip](https://github.com/citizenfx/fivem/files/11360136/CfxCrashDump_2023_04_29_21_51_49.zip)

**Comment by AvarianKnight** [comment]
Have you tried disabling steam overlay, as this crash isn't FiveM code at all.

1. Click Steam in the top left
2. Go to Settings
3. In-Game
4. Un-tick Enable the Steam Overlay while in-game

**Comment by ProxyPing** [comment]
> Have you tried disabling steam overlay, as this crash isn't FiveM code at all.
> 
> 1. Click Steam in the top left
> 2. Go to Settings
> 3. In-Game
> 4. Un-tick Enable the Steam Overlay while in-game

unfortunately it does not work.

**Comment by blattersturm** [comment]
'unfortunately' you haven't provided the crash message without Steam running either

**Comment by ProxyPing** [comment]
> 'unfortunately' you haven't provided the crash message or dump without Steam running either

unfortunately here it is 

[Window Title]
FiveM

[Main Instruction]
GameOverlayRenderer64.dll+A6CC8

[Content]

An error at GameOverlayRenderer64.dll+A6CC8 caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
Stack trace:
  GameOverlayRenderer64.dll+A6CC8
  GameOverlayRenderer64.dll+AD15C
  GameOverlayRenderer64.dll+88F2D
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63
  GameOverlayRenderer64.dll+88F63


[^] Details ausblenden  [Save information] [Schließen]

[Expanded Information]
Crash signature: gameoverlayrenderer64.dll+A6CC8
Report ID: si-1fceb4e470074cd88d883c4409f7354d
You can press Ctrl-C to copy this message and paste it elsewhere.

[CfxCrashDump_2023_05_02_08_16_57.zip](https://github.com/citizenfx/fivem/files/11371106/CfxCrashDump_2023_05_02_08_16_57.zip)

**Comment by blattersturm** [comment]
That's still got the Steam overlay loaded. Can you actually _close Steam_?

**Comment by ProxyPing** [comment]
> That's still got the Steam overlay loaded. Can you actually _close Steam_?

ohh sorry chief, yeah i closed steam, but i need steam, what can i do?

**Comment by blattersturm** [comment]
If it works fine without Steam, contact Valve for this.
