### ISSUE TITLE
Inheritance not working for Ace Permissions

### ISSUE THREAD

**Issue by thesysadmindev** [citizenfx/fivem#1969]
**Issue:** Users in a child group are not able to use permissions set on the parent group.

**Steps to Reproduce:**
1. Create a new ace permissions group called `group.owner`.
2. Add `add_principal group.owner group.admin` to `server.cfg`.
3. Add a player to the group, e.g. add `add_principal identifier.fivem:1234567 group.admin` to `server.cfg`.
4. Restart FXServer.
5. Connect to the game server.
6. Exec a command such as `/car`.

**Steps to Isolate Issue:**
- I am able to directly grant permissions to the group, e.g. I can run commands at the console such as `add_ace group.owner easyadmin allow` which in turn allows the EasyAdmin menu to be opened by anyone who is only in `group.owner`.

**Server Info:** FXServer v6403 with ESX Legacy 1.9.3 on Windows Server 2022 Standard

**Comment by blattersturm** [comment]
Is this actually the order you're using? With the commands you sent, 'group.owner' is a part of 'group.admin', but if you expect the player (also a part of group.admin) to be able to use a command you assigned to 'group.owner' that obviously will not work.
