### ISSUE TITLE
Exception for URI blacklisted for NUI-Resources

### ISSUE THREAD

**Issue by your-a-nerd** [citizenfx/fivem#1975]
Would it be possible to add an exception to the filter for blacklisted URIS when performing HTTP request in an NUI resource? A lot of cheat menus use custom DUIs and the endpoint "http://localhost:13172/json/list" would be useful to detect the menus. Or even better possibly a native to return the custom textures loaded?

**Comment by Disquse** [comment]
This "solution" makes no sense.
