### ISSUE TITLE
[RDR3 REQUEST] Add support for GET_WORLD_COORD_FROM_SCREEN_COORD

### ISSUE THREAD

**Issue by ESK0** [citizenfx/fivem#1977]
Add support for GetWorldCoordFromScreenCoord that is available on FiveM.

https://github.com/citizenfx/fivem/blob/cf859b338ebe362ebeede242b3bb84a8bc4f2d76/code/components/extra-natives-five/src/GraphicsExtraNatives.cpp#L36

I believe should be an easy job

**Comment by kasuganosoras** [comment]
Currently, you can use [this script](https://gist.github.com/kasuganosoras/006a2441ba35981697ba65914547ca4d) to do the same things as the GET_WORLD_COORD_FROM_SCREEN_COORD native.
