### ISSUE TITLE
Redm GamerTag functions not working

### ISSUE THREAD

**Issue by q8tywolf** [citizenfx/fivem#1984]
These issues are in redm

`SetMpGamerTagVisibility(tag, 0, true)`
this spits out error attempt to call a nil value (global 'SetMpGamerTagVisibility')

`RemoveMpGamerTag(mpGamerTags[i].tag)
`This spits out error RemoveMpGamerTag.lua:5

**Comment by outsider31000** [comment]
invoke the native instead

**Comment by Disquse** [comment]
Invalid native definition. Has nothing to do with this repo as for now.
You should call it using `InvokeNative` like that until we implement proper native decls for RDR3:
`Citizen.InvokeNative(0x839BFD7D7E49FE09, Citizen.PointerValueIntInitialized(id));`
