### ISSUE TITLE
i cant open fivem

### ISSUE THREAD

**Issue by TheSjonnie** [citizenfx/fivem#1988]
if i open my fivem i get this

[Window Title]
Error GTA5_b2699.exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate (0x58)

[Main Instruction]
Could not load dependent module bink2w64.dll. Error code 126 -> Kan opgegeven module niet vinden. 

[Content]
Could not load dependent module bink2w64.dll. Error code 126 -> Kan opgegeven module niet vinden. 

[^] Details verbergen  [Save information] [Sluiten]

[Expanded Information]
Report ID: si-ab63c4071356404f98ce496be32bf70a
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by DaniGP17** [comment]
One possible solution is to find the bink2w64.dll file inside your GTA V folder and delete it. Then go to %localappdata%\\Digital Entitlements and delete this folder. After that, go to steam and validate your GTA files. You can also try reinstalling FiveM completely.

**Comment by blattersturm** [comment]
Not enough information to be actionable.
