### ISSUE TITLE
Character chin dimple

### ISSUE THREAD

**Issue by Meloszn** [citizenfx/fivem#1993]
So I created my character and his chin is dimple for other people's POV. For me it is fine, even the setting that makes it dimple is all the eay to the lowest. Any help?
![C62311C9-44D9-48DD-A1CF-5A61893613FB](https://github.com/citizenfx/fivem/assets/133635278/9b06dd17-7bbd-4cd8-a821-da7d3952ebda)
![605C46FB-1333-45D8-9F64-6FBF05996F1A](https://github.com/citizenfx/fivem/assets/133635278/8939da4e-799e-44e0-8e45-5545db792b1d)

THE PHOTO THAT HAS THE CHIN DIMPLE WAS TOOK BY OTHER PERSON’s POV

**Comment by gottfriedleibniz** [comment]
Only values between 0.0 and 1.0 are technically valid for the final two micro-morph indices in [_SET_PED_FACE_FEATURE](https://docs.fivem.net/natives/?_0x71A5C1DBA060049E).

In addition to gamecode logic of the form `if ( v85 < 18 && v88 < 0.0 )`, these two indices are serialized as (packed) unsigned floats in the sync tree. Meaning negative values will actually be synchronized as 1.0 (what you are experiencing).

As this native does not sanitize invalid values, there are multiple potential solutions here... ranging from doing nothing to doing something.

**Comment by Meloszn** [comment]
> Only 'scale' values between 0.0 and 1.0 are technically valid for the final two micro-morph indices in [_SET_PED_FACE_FEATURE](https://docs.fivem.net/natives/?_0x71A5C1DBA060049E).
> 
> In addition to gamecode logic of the form `if ( v85 < 18 && v88 < 0.0 )`, these two indices are serialized as (packed) unsigned floats in the sync tree. Meaning, negative values will actually be synchronized as 1.0 (what you are experiencing).
> 
> As this native does not sanitize invalid values, there are multiple potential solutions here... ranging from doing nothing to doing something.

 Ok so, what kinda solutions can I do? I had it to the minimum, asked for a reskin to try and fix it and I put it in the middle (default value) and it still didn’t fix. Any suggestions? And by the way thank you for the response

**Comment by jakub-cfx** [comment]
> Ok so, what kinda solutions can I do? I had it to the minimum, asked for a reskin to try and fix it and I put it in the middle (default value) and it still didn’t fix. Any suggestions? And by the way thank you for the response

A fix for this issue has been implemented (https://github.com/citizenfx/fivem/commit/3f5e29533697fd67cd1ce4b3e67dc12b53fb9067)

Please check if this resolves the problem you've been experiencing
