### ISSUE TITLE
NUI browser language 

### ISSUE THREAD

**Issue by Tynopia** [citizenfx/fivem#1995]
Hello,

I have recently encountered an issue with FiveM related to the language settings of the NUI (CEF Browser). The issue is that the language of the CEF Browser does not correspond to the language recognized by the system.

### Description

While the launcher correctly identifies the language and adjusts accordingly, this does not seem to apply to the CEF browser within the NUI. The NUI does not automatically detect the system's language and adjust it accordingly.

### Steps to Reproduce

1. Ensure that the system language is set to German (or any non-English language).
2. Launch FiveM and connect to a server.
3. Check the language setting in the NUI.

### Expected Behavior

The NUI should automatically recognize the system language and adjust accordingly, similar to the FiveM launcher.

### Actual Behavior

The NUI remains set to English, regardless of the system language.

### Screenshots

Attached is a screenshot illustrating the issue. As you can see, the NUI remains in English even though the system language is set to German.

![image](https://github.com/citizenfx/fivem/assets/65678882/16c17f31-d600-4526-9101-e0d8016655b9)
![image](https://github.com/citizenfx/fivem/assets/65678882/903bf7d3-f146-4efe-8a0f-13f5423771a8)

### Additional Remarks

I attempted to manually change the language, but the issue persists. The manually set language is not maintained and reverts back to English after a restart.

> **This issue has a significant impact on the use of services such as Firebase's Remote Config, which relies on the correct setting of the NUI language. As a result, this bug not only affects the user experience but also limits the functionality and potential applications of the NUI within FiveM.**

I hope this issue can be resolved in the near future. Please let me know if you require further information to investigate this issue.

Thank you in advance!

**Comment by blattersturm** [comment]
Not going to happen by default. If you need to read the system language, you can get it using JS from the 'nuiSystemLanguages' array.

I don't know what 'Firebase Remote Config' is or why it relies on language setup but it probably offers an API so you can set it up as such, and if not you might be able to patch it to do so.
