### ISSUE TITLE
ping in server browser

### ISSUE THREAD

**Issue by IZeeXeS** [citizenfx/fivem#1996]
its way easeer for me to use server browser when I see my ping to every server, like its done in mta, samp, all normal server browsers, even rage mp show this

**Comment by Keyinator** [comment]
The github issue section is not the right place for a feature request.
I think the best place for that would be the [forums](https://forum.cfx.re/)

**Comment by blattersturm** [comment]
Due to the design of the server list and the connection process, it's not possible to show 'ping' beforehand at all.

See this reply to an earlier feature request (which *was* in the right place): https://forum.cfx.re/t/ping/4815111/2?u=d-bubble
