### ISSUE TITLE
Mono runtime ignores params keyword for delegates & local functions

### ISSUE THREAD

**Issue by vxlurk** [citizenfx/fivem#2004]
Recently I found out that the mono runtime that is used for scripting (no mater if its v2 or v1) ignores `params` keyword if its applied to a local func or a delegate

The following code gave me the results below
[code](https://gist.github.com/vxlurk/b7e8ffeae8fe0ce5b0b91c6d655ab6ad)

![server results](https://github.com/citizenfx/fivem/assets/105105834/142385ab-0e81-41f2-aba8-54d942073af9)
![client results](https://github.com/citizenfx/fivem/assets/105105834/880d083f-8720-427a-b0e5-541a7d76fc7b)

**Comment by vxlurk** [comment]
oh that has nothing to do with the runtime used for `citizen` scripting
so is there any way to achieve similar behaviour? 
https://gist.github.com/vxlurk/2d40ce2be899deb4b83d3c955428f90b

**Comment by thorium-cfx** [comment]
`params` is a compiler feature and not a runtime feature, they turn all the arguments into an `object[]` and pass those instead. So technically it doesn't ignore it and the results are expected.

As such I'll be closing this as we also don't accept feature requests on here, see the [forums](https://forum.cfx.re/) for that. For your Lua equivalent question I've got no clue as to why one would want to do that.
