### ISSUE TITLE
Allow modifier keys when using the "bind" console command

### ISSUE THREAD

**Issue by roraraptor** [citizenfx/fivem#2005]
I want to use modifier keys to add hotkeys to easily available keys without interfering with normal gameplay.

For example:

`bind keyboard LMENU+C "carry"`

to trigger the command `carry` when I use `ALT+C`, but not trigger it when I'm just trying to look behind me.

However, there doesn't seem to be any way to use this command with modifiers. I've tried using plus signs, quotation, writing it as a JSON list, but it's just interpreted as a single key, and as such it's not recognized.

Please allow using modifier keys, or update documentation to make it obvious how to use them if it's supposed to be possible. I've asked people and searched the internet without finding any good information on this, so here we are.

Thanks!

**Comment by blattersturm** [comment]
We don't accept feature requests on here. Try doing so on the [forums](https://forum.cfx.re), but note that this would be non-trivial to implement since the underlying system for key mappings does not implement key combos _at all_.
