### ISSUE TITLE
Creating Network Object doesn't always network the object

### ISSUE THREAD

**Issue by damightylamb** [citizenfx/fivem#2007]
This one might be a bit weird, but I have noticed that on occasions if I create a network object, with the following native...

`CreateObject(props.model, props.coords.x, props.coords.y, props.coords.z, props.networked or false, true, false)`

...on occasions the object created will show up but not be networked. I attempt to get the Network ID, but it will say in the console log that there is no Network ID for the object. This is all client side by the way because there are just some natives that I need on the client side that the server natives do not have. 

To combat this, I would occasionally run the following code snippet to ensure that the objects are networked...

`while not NetworkGetEntityIsNetworked(obj) do 
    NetworkRegisterEntityAsNetworked(obj)	
    Wait(100) 
end`

This works, but I am not a fan of potentially unneeded loops. 

If there is a step that I am missing, that would be good to know.

**Comment by AvarianKnight** [comment]
Did you create a bunch of objects in a short span of time?

From a duk a little over a year ago:

> Each client gets a set of object ids they can allocate, run out of that, no more object ids, no more objects

[see reference](https://github.com/citizenfx/fivem/blob/master/code/components/gta-net-five/src/ObjectIdManager.cpp#L215)

**Comment by blattersturm** [comment]
Missing repro steps, not actionable.
