### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by MrUmuttt** [citizenfx/fivem#2016]
dün bir sunucuya girmek istediğimde sunucunun yükleme ekranında %0 da kalıp ardında oyundan atıyor ve Fatal Error adında bir hata alıyorum. Bazende sunucuya giriş sağlıyorum fakat 1-2 dakika sonra gene aynı şey oluyor oyundan atıyor ve Fatal Eror adında bir hata alıyorum. YouTube'dan bu sorunun çözümü ile ilgili videolar izledim ve yaptım fakat işe yaramadı yardımcı olabilir misiniz sorunun çözümü nedir?

**Comment by Disquse** [comment]
This is not a place for support questions.
