### ISSUE TITLE
I enter my email on FiveM, but another user's account opens.

### ISSUE THREAD

**Issue by linuxfxdevil** [citizenfx/fivem#2017]
User logged in with his FiveM account on my machine. Every time I log in to FiveM with my email, it accepts the login but when I access a server, it enters the server with the first account of the other user. As I wasn't logging in with my username and password, but with his. I already tried to uninstall GTA5, Five. Could it be a bvug on FiveM?

**Comment by Disquse** [comment]
This is not a place for support questions.
