### ISSUE TITLE
Native SetVehicleTyreFixed does not work with BreakOffVehicleWheel

### ISSUE THREAD

**Issue by damightylamb** [citizenfx/fivem#2022]
I am not sure if it is intentional or not, but we have implemented the new native `BreakOffVehicleWheel` , but when we want to fix the tires, we have to run the native `SetVehicleFixed` which isnt viable if we want to implement it in a basic repair kit. You would assume it would work with `SetVehicleTyreFixed`, but unfortunately it does not. 

More information can be provided if needed.

**Comment by Disquse** [comment]
You can't fix a tyre when a wheel if broken off. Tyre and wheel are not the same thing. Also there's a feature request topic for what you described here: https://forum.cfx.re/t/request-for-is-vehicle-wheel-broken-off-fix-vehicle-wheel/5100826
