### ISSUE TITLE
[Ehancment] Event for when entity leaves the scope

### ISSUE THREAD

**Issue by MatinHQ** [citizenfx/fivem#2040]
I have reviewed the information available at https://docs.fivem.net/docs/scripting-reference/events/client-events/, and it appears that there is no specific event listed for detecting when a networked entity leaves the player's scope on the client.

It would indeed be advantageous to have such an event, which could potentially be named "onScopeLeave," for instance. This event could be equipped with a parameter that represents the entity's handle, allowing developers to conveniently handle the necessary actions.

If such an event were to be implemented, it could greatly enhance the functionality and flexibility of client-side scripting in monitoring and responding to changes in entity scope. This addition would be highly appreciated by developers who rely on precise entity tracking within the client-side environment.

Thank you for considering this suggestion. I hope it receives due attention, as it has the potential to greatly benefit the scripting community.

**Comment by blattersturm** [comment]
Feature requests don't go here but on https://forum.cfx.re/c/general-discussion/feature-requests/33.
