### ISSUE TITLE
Limit of 255 total props per gender

### ISSUE THREAD

**Issue by VolCoM1337** [citizenfx/fivem#2043]
Hello,

There is currently a limit of 255 props (255 drawables, .ydd). In b2802, with 187 base game heads (helmets), there is room for only 68 addon heads. With upcoming DLC, the problem will only get bigger and servers (including us) will start to be obliged to remove some drawables.

After the limit is reached, the majority of heads (including base game) are invisible.

I'm not sure how hard it is to increase this limit but it would be really appreciated. 

Thank you

**Comment by VolCoM1337** [comment]
Hello,

With the new 2944 build (mp2023_1 - Mercenaries), R* added 10 new heads. Meaning there is only room for 58 addons heads.
This limit become increasingly problematic. 

At the rate at R* add helmets, we could keep this limit for a few years (forever?). I think it could be worth to try to increase it.

Would it be possible to increase this limit of 255 props ?

Thank you and sorry to insist, this is a real problem for us.

**Comment by blattersturm** [comment]
Feature requests should go on the forums: https://forum.cfx.re/c/general-discussion/feature-requests/33

**Comment by autfoxx** [comment]
> Hello,
> 
> With the new 2944 build (mp2023_1 - Mercenaries), R* added 10 new heads. Meaning there is only room for 58 addons heads. This limit become increasingly problematic.
> 
> At the rate at which R* add helmets, we could keep this limit for a few years (forever?). I think it could be worth to try to increase it.
> 
> Would it be possible to increase this limit of 255 props ?
> 
> Thank you and sorry to insist, this is a real problem for us.

If your client build is 7669 or higher there should be no more limit, not sure if it works entirley so let me know

**Comment by derBalou** [comment]
On client build 7788 and 7790/beta the prop gets stuck at drawableId 16. Attempting to set a drawableId higher than 16 results in nothing, the ped keeps the last set prop with a drawableId of 16 or below.
