### ISSUE TITLE
NPC Entity Spawn Newtorked

### ISSUE THREAD

**Issue by Kalyptus** [citizenfx/fivem#2051]
Hello, below I am providing you with a code that enables the creation of networked entities, making them appear as ambient NPCs with a population type 5. This is being used by cheaters on servers that have NPCs.

```
RegisterCommand('spawn_ped', function(_, args)
    Citizen.CreateThread(function()
        local model = 'a_c_chimp'
        RequestModel(model)
        while not HasModelLoaded(model) do
            Wait(1)
        end
        local coords = GetEntityCoords(PlayerPedId())
        local ped = CreatePed(29, model, coords.x, coords.y, coords.z, 0.0, true, true)
        SetEntityAsNoLongerNeeded(ped)
        SetPedAsNoLongerNeeded(ped)
    end)
end)

RegisterCommand('spawn_vehicle', function(_, args)
    Citizen.CreateThread(function()
        local model = 'blista'
        RequestModel(model)
        while not HasModelLoaded(model) do
            Wait(1)
        end
        local coords = GetEntityCoords(PlayerPedId())
        local vehicle = CreateVehicle(model, coords.x, coords.y, coords.z, 0.0, true, true)
        SetEntityAsNoLongerNeeded(vehicle)
        SetVehicleAsNoLongerNeeded(vehicle)
    end)
end)
```

**Comment by Keyinator** [comment]
Could you provide more detail?

> on servers that have NPCs.
Do you mean on servers without EntityLockdownMode enabled?

What exactly are the cheaters doing here? Are they spawning peds and vehicles illegally or is there more to it?

Also what measures do you think would be possible since you clearly stated a solution (EntityLockdownMode).

While I know the fight against cheaters is hard and an exhausting process I don't see how fivem could do something specifically against this.

**Comment by Kalyptus** [comment]
EntityLockdownMode is not a solution given that it would cancel the ambient NPCs on the map and that's not the goal. Cheaters use codes to make vehicles appear above people's heads, and NPCs to bother them. 

We have already found certain applicable solutions for this, but if I share the code it's so that FiveM tries to do something to prevent the use of the natives SetEntityAsNoLongerNeeded, SetPedAsNoLongerNeeded, SetVehicleAsNoLongerNeeded to help as many people as possible and so we aren't forced to stick patches everywhere to prevent this.

The problem here is not to prevent the client from creating any entity, but only to prevent them from creating entities pretending to be a vehicle created by the game (NPC).

**Comment by blattersturm** [comment]
Duplicate: https://forum.cfx.re/t/calling-setpedasnolongerneeded-right-after-createped-makes-getentitypopulationtype-in-entitycreating-event-return-5-instead-of-7/5117629/2?u=d-bubble

Not really easy to change either.
