### ISSUE TITLE
RedM crashing on fresh install of Red Dead Online

### ISSUE THREAD

**Issue by lucasschmitz-dev** [citizenfx/fivem#2058]
Redm keeps crashing while installing. Tried multiple times and also a fresh installation of the game.
I have bought Red Dead Online via Steam.

I am using:
Windows 11 Pro 22H2
AMD Ryzen 7 3700X 8-Core Processor
Nvidia RTX 3070

[CfxCrashDump_2023_06_17_20_57_28.zip](https://github.com/citizenfx/fivem/files/11780076/CfxCrashDump_2023_06_17_20_57_28.zip)

**Comment by Disquse** [comment]
For crash reports please use the forum: https://forum.cfx.re/c/redm-client-support/52
