### ISSUE TITLE
Wrong documentation for native 0x2BA40795 (SetVehicleHandlingField)

### ISSUE THREAD

**Issue by JonasDev17** [citizenfx/fivem#2063]
The following native documentation is wrong:

https://docs.fivem.net/natives/?_0x2BA40795

It does not take a vehicle, it takes a model as a string.

**Comment by Disquse** [comment]
This natives takes vehicle handle as first argument: https://github.com/citizenfx/fivem/blob/b197237b2126c5357c91b63d25a904a99a39d40d/code/components/handling-loader-five/src/HandlingLoader.cpp#L565
Are you sure you're not confusing it with the `SET_HANDLING_FIELD` native?

**Comment by JonasDev17** [comment]
My bad, you're right.
