### ISSUE TITLE
Crash Issue on windows 11 insider

### ISSUE THREAD

**Issue by strikersix23** [citizenfx/fivem#2071]
Would crash before login and just after menu start up

[CfxCrashDump_2023_06_26_18_23_15.zip](https://github.com/citizenfx/fivem/files/11872497/CfxCrashDump_2023_06_26_18_23_15.zip)

**Comment by AvarianKnight** [comment]
This crash isn't FiveM related to FiveM so there isn't much that we can do to help you here, try finding whatever `VirtualCamDevice.dll` and `MFDshowReverseBridge.dll` is installed by and uninstall it.

**Comment by strikersix23** [comment]
i cant find it however i only found reference in ms docs

https://learn.microsoft.com/en-us/windows/win32/api/mfvirtualcamera/nf-mfvirtualcamera-mfcreatevirtualcamera

**Comment by RaymonSantoso** [comment]
https://gyazo.com/f358b2d6c278f5d8b2425d48f7893c84

i get this when i start fivem even i uninstalled in and reinstall it and still get this massage
