### ISSUE TITLE
I crash when i join a server

### ISSUE THREAD

**Issue by Incompetenteh** [citizenfx/fivem#2074]
Goodmorning, but not for me. So, sometime ago i was playing a Italian server called "Roma City 2.0", and it was working pretty well. But the problem arrived. Recently, when i was trying to join the server, it was loading all the resources and then, on the loading screen, with the bridge and the mountains behind, it freezed and crashed, giving me the error i attached below... Does someone know how can i fix it?

![Screenshot 2023-05-30 183247](https://github.com/citizenfx/fivem/assets/89078613/1bd3fed3-3c6d-47c9-9265-772208ad37fb)

**Comment by Mycroft-Studios** [comment]
What does this have to do with Fivem....
Go tell the server your trying to join that their stuff is broken....
FiveM/Cfx have no part in that

**Comment by thorium-cfx** [comment]
> Does someone know how can i fix it?

Yes, contact the server owners with these details. Hope you'll be able to resolve this quickly.
