### ISSUE TITLE
error during steam ROS sigin (4000.210)

### ISSUE THREAD

**Issue by guiffar** [citizenfx/fivem#2076]
hello i am unable to connect redm sinds 3day  ive got this error anytime 
![image](https://github.com/citizenfx/fivem/assets/138058663/dd7f2400-27c5-48c8-9a03-edabd042f090)

**Comment by guiffar** [comment]
sorry for my english i am french

**Comment by Disquse** [comment]
https://status.cfx.re/incidents/xdgb17bvhrhc
