### ISSUE TITLE
can't install fivem

### ISSUE THREAD

**Issue by irozzyontop** [citizenfx/fivem#2077]
Hery there i can't install fivem, when i try to do it it just won't let me see the file in my downloads. Can anybody help me?

**Comment by jellyton69** [comment]
This is not the place to ask for help. Please ask on the forums or in the Discord.

**Comment by irozzyontop** [comment]
where can i find the discord?

**Comment by PappaNiels** [comment]
You can join the guild [here!](https://discord.gg/fivem)
