### ISSUE TITLE
the impossible error to solve for end user, FiveM_ROSLauncher+147B6C error

### ISSUE THREAD

**Issue by GHOSTS15** [citizenfx/fivem#2079]
![immagine](https://github.com/citizenfx/fivem/assets/64962832/da8dc8a7-c30d-4185-9b53-fed281e19d70)

IMPOSSIBLE error to fix for end users , the only way is for you developers to open your eyes and fix quersto problem that imepdicates playing or even entering on fivem

the funny thing is that the files that the program has to send you , it doesn't send them because in the logs there is an and error "http 0" (which I think is a problem that it doesn't send the files )

**Comment by AvarianKnight** [comment]
> IMPOSSIBLE error to fix for end users , the only way is for you developers to open your eyes and fix quersto problem that imepdicates playing or even entering on fivem

I implore you to look [at this article](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette) most notably [this section](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette#be_patient_be_timely).

This isn't the way to get developers attentions in any constructive way. You also didn't provide any information on what leads to the crash, or any crash dump.

This issue isn't actionable.

**Comment by thorium-cfx** [comment]
Closing this as we do not offer support on here, please see the [forums](https://forum.cfx.re/).

AvarianKnight's comment above explains it well. For next time; some politeness and professionalism is appreciated.

**Comment by GHOSTS15** [comment]
there are 40+ people who have the same problem , many have sent the dmps ,. the logs, the whole fivem folder and yet you have done nothing to solve the problem in a definitive and official way ...you tell me to go to the forum, I go to the forum to see people asking for help but you developers do nothing to help them so it is useless for you to tell me "go to the forum" ; " look at this article for how to send an error" ; "so the error is not reproducible" , better if you make an examination of conscience and be more humble and help people without making useless excuses.

**Comment by GHOSTS15** [comment]
> > IMPOSSIBLE error to fix for end users , the only way is for you developers to open your eyes and fix quersto problem that imepdicates playing or even entering on fivem
> 
> I implore you to look [at this article](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette) most notably [this section](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette#be_patient_be_timely).
> 
> This isn't the way to get developers attentions in any constructive way. You also didn't provide any information on what leads to the crash, or any crash dump.
> 
> This issue isn't actionable.



> Closing this as we do not offer support on here, please see the [forums](https://forum.cfx.re/).
> 
> AvarianKnight's comment above explains it well. For next time; some politeness and professionalism is appreciated.



there are 40+ people who have the same problem , many have sent the dmps ,. the logs, the whole fivem folder and yet you have done nothing to solve the problem in a definitive and official way ...you tell me to go to the forum, I go to the forum to see people asking for help but you developers do nothing to help them so it is useless for you to tell me "go to the forum" ; " look at this article for how to send an error" ; "so the error is not reproducible" , better if you make an examination of conscience and be more humble and help people without making useless excuses.
