### ISSUE TITLE
Legacy crash hash: yankee-lamp-alanine

### ISSUE THREAD

**Issue by tobybacoon** [citizenfx/fivem#2080]
A lot of players seem to be having this crash across a lot of different servers, usually the crash happens around the legion square area and can happen on fresh servers with no mlos or ymaps

A lot of players seem to be having this crash across a lot of different servers, usually the crash happens around the legion square area and can happen on fresh servers with no mlos or ymaps

[CfxCrashDump_2023_06_28_18_13_09.zip](https://github.com/citizenfx/fivem/files/11909544/CfxCrashDump_2023_06_28_18_13_09.zip)

**Comment by AvarianKnight** [comment]
Maybe related to https://github.com/citizenfx/fivem/commit/a74ee2a27c59ec2480f9a16377b054318ef6a3af?

**Comment by thorium-cfx** [comment]
Logs are filled with map/model related loading errors, 1631 hits for "Physics validation failed" alone. Please fix these assets before reporting an issue.

If this happens on a fresh server "with no mlos or ymaps" then please report an issue with repro steps.

**Comment by gottfriedleibniz** [comment]
See this [response](https://forum.cfx.re/t/game-crashing-setsamplersforpixelshader/5050983/16) on the forums. While the poster there has been incredibly busy, and you seem to be using the same resources, maybe you can continue his work.
