### ISSUE TITLE
Allow setting secondary control

### ISSUE THREAD

**Issue by Dalrae1** [citizenfx/fivem#2084]
Currently ``RegisterKeyMapping`` only supports setting of the primary control, it would be very useful to have 2 extra arguments for setting the secondary control.

Old way of adding controller key mappings:
![image](https://github.com/citizenfx/fivem/assets/52721173/bce95c10-af74-4727-8d55-828b990a9870)
![image](https://github.com/citizenfx/fivem/assets/52721173/633f0099-42c7-4858-a021-d6d559792edc)

Potential new way:
![image](https://github.com/citizenfx/fivem/assets/52721173/1ce0c860-9125-4c4f-94f6-d6bb999f5d30)
![image](https://github.com/citizenfx/fivem/assets/52721173/1f5d5cd3-bf97-43d0-b809-b8122a562984)

**Comment by blattersturm** [comment]
Isn't this already possible?

https://github.com/citizenfx/fivem/assets/24576130/609c77bb-29fa-41f9-89fb-a9522ca588c5

**Comment by blattersturm** [comment]
... or I might've misread, and the following bit of the message meant 'setting the _default_ primary/secondary control':

> it would be very useful to have 2 extra arguments for setting the secondary control.

I think the way secondary controls are implemented, this can already be done by using the internal prefix for secondary controls in a separate registration:

https://github.com/citizenfx/fivem/blob/5d6322b95df25fe508631ee0fbc5ea4682d43618/code/components/gta-core-five/src/GameInput.cpp#L1063

```lua
RegisterCommand('dummy', function() print('hi') end, false)

RegisterKeyMapping('dummy', 'stuff', 'keyboard', 'i')
RegisterKeyMapping('~!dummy', 'stuff', 'pad_digitalbutton', 'rleft')
```

It looks a little awkward though as it gets registered as a 'separate' top-level mapping too in the UI which looks odd:
![image](https://github.com/citizenfx/fivem/assets/24576130/8cee2c90-c960-48b8-ae4f-3920b76a4ae0)

Similarly, it might make sense to have a separate command with arguments for a secondary default or some less 'hacky' way of doing the same, yes, but that'd be more doc/planning work however.

**Comment by blattersturm** [comment]
The issue with the manual method duplicating has been fixed at least and as expected was fairly simple, so at least it's _somewhat_ possible to do this reasonably now:

![image](https://github.com/citizenfx/fivem/assets/24576130/41f7e691-73eb-4a56-9b05-bce6d3f2e313)

**Comment by Dalrae1** [comment]
Awesome! That completely fixes the issue.
