### ISSUE TITLE
Feature request - negative routing buckets

### ISSUE THREAD

**Issue by prdatur** [citizenfx/fivem#2085]
**What:**
Allow using negative routing buckets

**Explaination:**
Currently all players can see player which are within the same bucket id, default is 0
For example, admins or also housing systems, it would be nice to see all the players within the same bucket and all players within the default bucket 0, players within default bucket still only see players within default bucket, nothing else.
This could be archived through negative bucket ids.

**Detailed:**
Player A: Bucket 0
Player B: Bucket 0
Player C: Bucket 1
Player D: Bucket 1
Player E: Bucket -1
Player F: Bucket -1

A: Sees B
B: Sees A
C: Sees D
D: Sees C
E: Sees A,B,F
F: Sees A,B,E

**Comment by blattersturm** [comment]
This is not the place for feature requests, these should go on the [forums](https://forum.cfx.re).

Similarly, this could already be done the traditional way using 'conceal' commands on clients, having routing policy handle this is only going to be causing weird unintended side effects.

(also, you're already proposing a weird solution that doesn't even make _sense_ without specifying the full use case)
