### ISSUE TITLE
Server error on CPU lacking SSSE3 instructions

### ISSUE THREAD

**Issue by mrnoahfink** [citizenfx/fivem#2091]
Hello

Based on the thread I made - https://discord.com/channels/192358910387159041/1127298793818292365

After I update txAdmin to the latest version, it seems didn't fix the issue. Still looping crashing on Linux Pterodactyl

![image](https://github.com/citizenfx/fivem/assets/66857858/6dc52edf-1234-4be0-a7d6-20fcfc5facda)

**Comment by gottfriedleibniz** [comment]
How is your server/VPS configured? With `66 0f 38 00 ..` being SSE3, does `/proc/cpuinfo` contain `sse3` under flags?

**Comment by mrnoahfink** [comment]
This is self-host under public IP address and pterodactyl Linux. I will check on that.

Only I know it is AMD process from 2008, lol.

**Comment by mrnoahfink** [comment]
Just checked, here my cpu info. 

[cpu_info.txt](https://github.com/citizenfx/fivem/files/11992634/cpu_info.txt)

**Comment by gottfriedleibniz** [comment]
Yeah, this is a little gross. My previous message had a typo `SSE3 -> SSSE3`. 

Your CPU is a bit dated and is only showing the `PNI/SSE3` bits. The `server-hosting` FAQ isn't particularly clear and the system requirements section in `client-manual` references `AMD Phenom 9850`, which I think suffers from the same issue (citation needed). Some clarity here is required.

A greater authority will have to speak on this.

**Comment by blattersturm** [comment]
Ah, so there's CPUs that do support POPCNT but not SSSE3, and SSSE3 is _also_ required by some component.

This'd likely need the check on launch to be amended:

https://github.com/citizenfx/fivem/blob/291d43c31e43582432683bc2a32fea24b1286f26/code/server/launcher/src/Main.cpp#L35

Documentation shouldn't need changing, the system requirement of 'x86-64-v2' apparently includes SSE3, SSSE3, SSE4.1 and SSE4.2 as well.

**Comment by gottfriedleibniz** [comment]
It'd may be worth testing if the Linux server can be built without the `SSSE3` [vectorextensions](https://github.com/citizenfx/fivem/blob/master/code/premake5.lua#L104). Botan is quite nice in that it supports function multi-versioning. Although, the openssl bits (and maybe rocksdb?) will maybe take a hit here (or not work).

Although if `x86-64-v2` is a hard-requirement, it may be possible to enable a few other vector extensions by default (e.g., SSE4*).

> Windows build has less painful requirements

If I remember correctly, MSVC is a bit saner w/ features like `popcount` because it uses its own implementation unless you compile w/ `AVX`.

**Comment by RealStonerGamer** [comment]
this broke my test server witch was working fine till today... 
commit b168948

**Comment by gottfriedleibniz** [comment]
@RealStonerGamer you're going to have to provide a bit more information, e.g., the version of Windoze you are running (VPS configuration, etc). If you're running a processor without AVX, then `XCR0` will not be reported. Without `XCR0` then the `cpu_features` will depend on `IsProcessorFeaturePresent` which only recently added SSSE3 through AVX512 support (>= 20H1?)

**Comment by blattersturm** [comment]
> If you're running a processor without AVX, then XCR0 will not be reported. Without XCR0 then the cpu_features will depend on IsProcessorFeaturePresent which only recently added SSSE3 through AVX512 support (>= 20H1?)

... seriously, this is an actual edge case?!

From an email the user sent, by the way:

> I'm looking into the fact that I'm using a VM in further testing my physical Hardware on bear hardware no VM cfx servers load fine so yes it seems to be a VM issue

**Comment by blattersturm** [comment]
Fun check by the way: https://github.com/google/cpu_features/pull/220/files#diff-94a306e42066434db48f55e4330055dbf95059f5cd1157e28a43a8b3487f04aaR48

**Comment by RealStonerGamer** [comment]
> > If you're running a processor without AVX, then XCR0 will not be reported. Without XCR0 then the cpu_features will depend on IsProcessorFeaturePresent which only recently added SSSE3 through AVX512 support (>= 20H1?)
> 
> ... seriously, this is an actual edge case?! It's indeed plausible enough the user here is running RS5 (Server 2019) in the VM which will not handle that state. Great, so detecting SSSE3 presence by running that check is just broken.
> 
> From an email the user sent, by the way:
> 
> > I'm looking into the fact that I'm using a VM in further testing my physical Hardware on bear hardware no VM cfx servers load fine so yes it seems to be a VM issue

i am in deed runing windows server 2019 and i will be also checking out what you posted here 

> Fun check by the way: https://github.com/google/cpu_features/pull/220/files#diff-94a306e42066434db48f55e4330055dbf95059f5cd1157e28a43a8b3487f04aaR49


will just need to do some more research on the issue and the possible fix you have shown i do appreciate it and sorry again for any issue i have been ...

**Comment by gottfriedleibniz** [comment]
> > From an email the user sent, by the way:
> > > I'm looking into the fact that I'm using a VM in further testing my physical Hardware on bear hardware no VM cfx servers load fine so yes it seems to be a VM issue
> 
> i am in deed runing windows server 2019 and i will be also checking out what you posted here

What operating system were you using on bare hardware? Windows Server 2019 as well or something more modern?

> > Fun check by the way: https://github.com/google/cpu_features/pull/220/files#diff-94a306e42066434db48f55e4330055dbf95059f5cd1157e28a43a8b3487f04aaR49

For posterity, this was later updated.

**Comment by RealStonerGamer** [comment]
> > > From an email the user sent, by the way:
> > > > I'm looking into the fact that I'm using a VM in further testing my physical Hardware on bear hardware no VM cfx servers load fine so yes it seems to be a VM issue
> > 
> > i am in deed runing windows server 2019 and i will be also checking out what you posted here
> 
> What operating system were you using on bare hardware? Windows Server 2019 as well or something more modern?
> 
> > > Fun check by the way: https://github.com/google/cpu_features/pull/220/files#diff-94a306e42066434db48f55e4330055dbf95059f5cd1157e28a43a8b3487f04aaR49
> 
> For posterity, this check was later updated (dropping the Westmere hardcode).
> 
> Edit: apologies for edits, I am half asleep at the moment.

I was using Windows 10 as the bare metal

**Comment by RealStonerGamer** [comment]
> is running RS5 (Server 2019) in the VM which will not handle that state. Great, so detecting SSSE3

confirmed  you can no longer use windows 2019 with xeon X5000 series CPUs 
i updated to windows server 2022 fixes all issues and passes flags fully to the Vm used  with these CPUs anyone using windows server 2019 will need to update

**Comment by RealStonerGamer** [comment]
just tested with my old system config that was messing up  with this new check today 
[adcce24](https://github.com/citizenfx/fivem/commit/adcce24b18d82ea4f6a751b38805c3f650a4c420) 
my old windows server 2019 VM i was using now loads cfx server fine with this new check seems to work with window server 2019  using xeon X5000 series cpu in VM now  

i did update to server 2022 and have it al set up so not going to keep using the old config but nice to know its fixed it seems

thanks balattersturm for the hard work

**Comment by mrnoahfink** [comment]
Any update about this?

I just redownload fivem/build_proot_linux/master/ to 6594 and still nothing at this moment. 

Thanks!

**Comment by blattersturm** [comment]
> and still nothing at this moment

What do you mean by 'nothing'? It should properly show an error message stating your CPU is not supported.

**Comment by mrnoahfink** [comment]
I guess it is still not supported. I notice that you guys talking about Windows, This is for Linux, however seems CPU outdated. 

![image](https://github.com/citizenfx/fivem/assets/66857858/66d0f33e-8323-4ea9-95a0-1fa0f3982c25)

**Comment by DaveInchy** [comment]
no flags for server.cfg to run it anyway knowing the dangers?
