### ISSUE TITLE
[Bug] Unable to Join server on build 2944 with pure mode enabled

### ISSUE THREAD

**Issue by ddoucethollett** [citizenfx/fivem#2092]
after updating server to use game build 2944 with pure mode set to level 1 upon attempting to join "Invalid modified game files (update/update2.rpf)" pops up and it doesn't let me join. Using FXServer build 6550 and Beta client. Verified game files as well as re-installed GTA-V with the same issue.

**Comment by ElJoelReis** [comment]
Same problem here

**Comment by blattersturm** [comment]
Already fixed: https://github.com/citizenfx/fivem/commit/7a96d88f03a07a91dcd630a531b7e077e487ca7c
