### ISSUE TITLE
txd poolsize on 2802

### ISSUE THREAD

**Issue by SKITTLE6969** [citizenfx/fivem#2094]
2802 has little space for extra txd Is it possible bump up the txd poolsize to like around 105500 something?

**Comment by Disquse** [comment]
How many texture dictionaries you're trying to stream? I have a resource with more than 4300 dictionaries (map conversion) and it doesn't hit the limit.

**Comment by SKITTLE6969** [comment]
> 

i have no idea how its happening, my server is currently on pure mode 2 and when i change it to pure mode 1 people starts to get txdpool size crashes non stop

**Comment by indonesiafreeroam** [comment]
![image](https://github.com/citizenfx/fivem/assets/139290857/75da283c-b0eb-47d9-b4d4-0db36964663f)

can you please increase txd to game build 2944 thanks

**Comment by normalday123** [comment]
![image](https://github.com/citizenfx/fivem/assets/138086530/bbd624d9-d56d-43b0-b916-0587fb9ad2aa)
![image](https://github.com/citizenfx/fivem/assets/138086530/bad3729b-0a62-455b-bc61-2a156164bde9)

can you please increase txd pool
may server have 33.000 ytd item

thanks

**Comment by normalday123** [comment]
because we add car house and clothess, can you pliss increase, so we can use dlc 2944

**Comment by Moozdzn** [comment]
We are also hitting this limit but I havent seen how many we have

> Why would you need to stream SO MANY #tds?

Assuming only clothing and with every piece having 26 textures (26 ytds)

33.000 ( the number mentioned above ) equals to 1269 pieces of clothing in total with 115 per component, 11 in total.

Doesn't seem to much, nor does it fill an entire clothing dlc

(Unless my math is wrong and this comment is useless)

**Comment by normalday123** [comment]
![image](https://github.com/citizenfx/fivem/assets/138086530/3ecc8674-c95f-4439-8a6c-b4215040ae29)
here ytd car just 4000++++

![image](https://github.com/citizenfx/fivem/assets/138086530/56293c99-e3c8-4e2e-99be-86694c13b533)
and here the ytd clothes 

if i remove clothes, i can use gamebuild 2944, but what point use fivem key stream clothes, if you cant stream all the clothes you liked. i think other server having this problem too, but they dont complain here...

this no include house, custom map, ped, pleasee increasee ytd fragment limit thank you..

**Comment by gottfriedleibniz** [comment]
Unfortunately, due to inflation the Federal Texture Reserve will be lowering TxdStore rates to force deflation within the texture economy. Disquse, please push a commit that lowers the size of `TxdStore`.

**Comment by normalday123** [comment]
@gottfriedleibniz hahaha, so this is about conspiracy fivem theory, we need Revolution from this

**Comment by chrisivey01** [comment]
I think most large servers are back at Txd cap again/or close. +1 to increase if at all possible.

**Comment by normalday123** [comment]
@blattersturm since you are now part of rockstar games, can you fix this problem please, i want to stream all ytd, or maybe can rockstar games developer fork this and fix this issue thanks

**Comment by manuelbpc** [comment]
Streaming some MLOs, clothing and cars and we're close to this limit. Any user with NVE or similar graphics packs will be over this limit and unable to play.
If it's possible to increase this without any consequences, please do!

**Comment by manuelbpc** [comment]
bump

**Comment by manuelbpc** [comment]
Could we expect this limit to be increased in a near future or it's one of those things that is what it is?

**Comment by efearob** [comment]
So you're adding all sorts of features and integrating platforms like Tebex for people to sell and buy add-on content, and yet nobody bothers to respond to a real problem about the latest release not being able to run the majority of said add-on content? Nice.

**Comment by SKITTLE6969** [comment]
> Firstly [there's already an open PR](https://github.com/citizenfx/fivem/pull/2287) for this, there is also better ways to communicate then sounding entitled.

I posted this on July 10th 2023 like almost 5 months ago what are you talking about bruh xD 

https://github.com/citizenfx/fivem/issues/2094#issue-1796030503
