### ISSUE TITLE
adhesive.dll!CreateComponent crash still present

### ISSUE THREAD

**Issue by MrNewb** [citizenfx/fivem#2095]
Server Version: 6551 (Also tried downgrading many different builds as well without success)
Client Verson: Most are on beta/release
Server Core: QBCore

Issue is still happening to all players, using absolute latest artifacts. This was said to be resolved on a previous post. Just trying to help. I have a server impacted by this and have a forum post/discord post with some logs if more crash reports are needed to narrow down the cause.

https://github.com/citizenfx/fivem/issues/2086

**Comment by AvarianKnight** [comment]
Latest server artifacts wouldn't effect anything, the client would need to be on the latest client version (which isn't recommended). You will likely have to wait for a production push.

**Comment by MrNewb** [comment]
today I had a player on the latest that was still impacts by it ```Game crashed: adhesive.dll!CreateComponent (0x2cacb42)``` @11:16 am est today

**Comment by MrNewb** [comment]
Thanks for looking at it though, ill await an update. ( also thanks for the work youve been doing now and prior to being part of the collective) :)

**Comment by AvarianKnight** [comment]
I'm not a part of the collective just try to take some of the burden off of them :)
