### ISSUE TITLE
MSVC 14.37

### ISSUE THREAD

**Issue by gottfriedleibniz** [citizenfx/fivem#2098]
When compiling with v14.37, some [duration](https://github.com/citizenfx/fivem/blob/master/code/components/citizen-devtools/include/ResourceMonitor.h#L55) constructors begin to fail. For reference, [here](https://godbolt.org/z/9Gz8bcssG) is a minified example where at the time of writing MSVC Latest is v14.36.

**Comment by blattersturm** [comment]
Is this a thing that broke since 'preview 3' bits? One development workstation is currently on 'preview 2' and it seemed to build fine.
