### ISSUE TITLE
je narrive pas a lancer fivem ni a jouer au serveur gta rp sur fivem

### ISSUE THREAD

**Issue by EB13K12** [citizenfx/fivem#2102]
voici ce qui saffiche quand je lance fivem et que je vais sur un serveur 
![Capture d’écran 2023-07-12 181447](https://github.com/citizenfx/fivem/assets/139377752/6f83008e-1fe1-4141-95fb-7c362bb3077b)
[Uploading CfxCrashDump_2023_07_12_16_14_04.zip…]()

**Comment by blattersturm** [comment]
This is not a place for support questions *nor* posts in languages other than English.
