### ISSUE TITLE
[Request] Being able to change Steam App Id

### ISSUE THREAD

**Issue by AlexR32** [citizenfx/fivem#2104]
I don't know if this is possible, but please add a option to change the Steam App Id via console command to something other than 218 (Source SDK)

**Comment by matehun00** [comment]
I think if you search hard enough in the files you can change it

**Comment by blattersturm** [comment]
This wouldn't really work at all (servers have to be aware of the app ID too) and what would the use case be and this really isn't for feature requests either so... huh?
