### ISSUE TITLE
Fatal Error: The CPU is not supported for x86-64-v2 instructions

### ISSUE THREAD

**Issue by Jerrys-C** [citizenfx/fivem#2109]
I encountered an issue where I am unable to start FXserver after updating to artifact 6552. 
It gives an error stating that the CPU does not support the instruction set. 
I am using Windows Server 2019 with an Intel XEON X5675 processor. 
According to my research, this CPU should support the mentioned instruction set. I am not using any virtual machines, as this server is a physical machine.
![image](https://github.com/citizenfx/fivem/assets/62429807/fafa9dfe-0378-4451-a323-bbf841f92ccb)

**Comment by blattersturm** [comment]
See the comments in #2091. As a workaround for now, you could upgrade to Server 2022.
