### ISSUE TITLE
The industry rp

### ISSUE THREAD

**Issue by solomocks** [citizenfx/fivem#2112]
The Industry RP

Looking for a unique & streamer-friendly roleplaying experience with a QBCore Base? well, look no further. You've found The Industry RP, but what's the hype of this Serious RP server?

:clipboard: | A Large Variety of Whitelisted Jobs (some are: Limeys Juice Bar, White Widow, Cookies and numerous others!)
:briefcase: |  Variety of Non-Whitelisted Jobs (some are: Delivery, Taxi, Running a Hotdog Stand, Farming, and plenty more!)
:shirt: | Male & Female Clothing to Match YOUR STYLE!
:blue_car: | Large Amount of Custom Cars! (Majority have tuning options!)
:nail_care: | Diverse Nail Salon
:pill: | Many Drugs with realistic system(s) of harvesting/growing, and onwards from that step (we have more simple drugs, but there will be new drugs every month! So don't get bored!)
:hospital: | Realistic Medical Scenes with a custom medbag script! (this bag includes things such as meds, a defib, bandages, a medical kit, and plenty more for your immersion!)
:police_officer: | Unique LEOs! (Law Enforcement Officers) They are well trained and they all have a chance to be brought up to State, or our custom NIA division! (National Intelligence Agency)
:tools: | A Special Mechanic System for YOU! (tune or repair your car for reasonable fees!)
:orange_circle: | A Unique Jailing System & Unique Interactions inside Bolingbroke! (psst... such as breaking out!)
:man_cook: | Paid Jobs inside PRISON! ( yes, you get paid in prison! )
:red_circle: | Different Gangs/Organizations for you to join! (but we need more!)

So what're you waiting for?! Start writing your story!

Trailer:
https://youtu.be/h4PebFo0Qlc

Discord:
https://discord.gg/TESDnde6dB

**Comment by Flambaa** [comment]
So... Whats the issue?
