### ISSUE TITLE
SetVehicleMod Server Side

### ISSUE THREAD

**Issue by KeKs-Root** [citizenfx/fivem#2116]
Hey is it possible to add the native SetVehicleMod to server side so tunings can be set via server

**Comment by CanysLypys** [comment]
https://docs.fivem.net/natives/?_0x5BA35AAF

Works just fine. Spawn the vehicle server side the rest explains itself in the docs of the native.

**Comment by PappaNiels** [comment]
This place is for issues. Not for feature requests. See the forums to submit one.
