### ISSUE TITLE
Clothes missing in 2944 gamebuild

### ISSUE THREAD

**Issue by xCin3kk** [citizenfx/fivem#2119]
I have home hosted server with 2944 gamebuild, but most of clothes are missing, i can select them in vMenu, but clothes not changing.

**Comment by AvarianKnight** [comment]
This isn't the place for in-actionable bug reports, use the [forums](https://forum.cfx.re)

**Comment by Disquse** [comment]
These aren't missed, these are stub assets of gen 9 exclusive content, unfortunately we can't do anything about it. The best thing you can do is filter out these assets in your clothes selector (using `IS_PED_COMPONENT_VARIATION_GEN9_EXCLUSIVE` native).
