### ISSUE TITLE
Server list bug?

### ISSUE THREAD

**Issue by V3SC** [citizenfx/fivem#2126]
Build : Latest (Unstable)
Bug: The filter is not working correctly.

Normally when you click on the players button, it should be sorted from highest to lowest, right?

Video:
https://github.com/citizenfx/fivem/assets/33003717/958ac640-3f05-41d2-a39e-a00cc20c994b

**Comment by PichotM** [comment]
Not a bug, this is how it was asked to be done

@nihonium-cfx do you believe it would be better to only include in the "priority sorting" project name starting with what you're searching? (while keeping the same sorting logic)

**Comment by IllInuz** [comment]
i do believe that'd make more sense as now it just wildcards no?

**Comment by V3SC** [comment]
any news?
