### ISSUE TITLE
Game Server Cheater Causing Crashes in Our Region

### ISSUE THREAD

**Issue by the-big-gs** [citizenfx/fivem#2128]
regarding our game servers for Fivem in our region. Recently, we have been experiencing severe disruptions caused by a malicious cheater who is intentionally crashing our servers, leading to a highly unpleasant gaming experience for our community
https://cdn.discordapp.com/attachments/1077109575523770398/1133576142494904320/CfxCrashDump_2023_07_26_01_47_29.zip

https://cdn.discordapp.com/attachments/779428970336223262/1133574846069092474/CfxCrashDump_2023_07_26_01_45_02.zip

https://cdn.discordapp.com/attachments/1133575462732447764/1133575496240746636/CfxCrashDump_2023_07_26_01_27_16.zip

Looking forward to your prompt response and working together to ensure fair and secure gameplay for all our users.

Thank you for your attention and understanding.

Best regards,

**Comment by blattersturm** [comment]
No repro provided.

**Comment by the-big-gs** [comment]
sorry but what do you mean with repro

**Comment by the-big-gs** [comment]
I seem to have submitted the report wrongly. I will give you more details
I don't know what this cheater really does but he crashes players

We have tried to change the server build to the last version but still the same issue
also the game build we try 1604,2699,2802,2189 
but still he can crash them this all what i have
