### ISSUE TITLE
Extremely wrong implementation of D3D11CreateDeviceHook

### ISSUE THREAD

**Issue by Kaldaien** [citizenfx/fivem#2132]
https://github.com/citizenfx/fivem/blob/7672c8c849165dad70a1e82f89e31059d8fcf20d/code/components/nui-core/src/NUIInitialize.cpp#L1119-L1160

This code is going to fail spectacularly if it ever triggers, because that is NOT the correct function prototype.

You should not be calling that function directly, but if you do, the actual parameters are:

`D3D11CoreCreateDevice (factory, adapter, flags, feature_levels, levels, device)`

Calling it with the wrong function prototype as you currently are will just cause your software to abort.

**Comment by blattersturm** [comment]
Right. I believe this was a hacky attempt to fix bad hooks placing themselves directly on d3d11.dll, confusing some call in I believe some fullscreen handling thread in dxgi.dll.

The function prototype being wrong to this extent *would* explain why that specific stack didn't get fixed - annoying part is that the issue itself didn't have any known reproduction steps and was merely found showing up in crash statistics a lot.

**Comment by blattersturm** [comment]
> You should not be calling that function directly, but if you do, the actual parameters are:
>
>D3D11CoreCreateDevice (factory, adapter, flags, feature_levels, levels, device)

Uh, at least on current Windows "Gallium" (build 25921), this is rather incorrect.

The signature in the code right now _actually matches_:

![image](https://github.com/citizenfx/fivem/assets/24576130/77672344-e42d-49d8-b5cd-d210de7273d2)

**Comment by blattersturm** [comment]
I see that the context here is rather another project ("DXVK") getting it wrong: https://github.com/doitsujin/dxvk/commit/228615b639679267389e23765c5e6de012931031
