### ISSUE TITLE
When creating a blimp, other people see an heli

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#2137]
On canary

Repro:
Server side: CreateVehicle(`blimp`, 1351.69, 3160.82, 39.43, 100.0, true, true)

The person near the spawn point see a blimp, others see an heli

Video:
https://www.youtube.com/watch?v=eNhkt3o_YQE

**Comment by slashkeyvalue** [comment]
seems on purpose, see: https://github.com/citizenfx/fivem/compare/81968d93a04e...44f0289390f0

**Comment by Disquse** [comment]
Just an oversight it seems, definitely not an expected behavior.

**Comment by blattersturm** [comment]
Solved by https://github.com/citizenfx/fivem/commit/c2b33b4c17e05a7e77f744fb7247ba09b4068b99.
