### ISSUE TITLE
Undefined Value When Calling JavaScript Export from Lua

### ISSUE THREAD

**Issue by Tynopia** [citizenfx/fivem#2138]
I am experiencing an unexpected behavior when trying to run a server-side JavaScript script from Lua in FiveM, where I am not able to pass a variable from Lua to JavaScript through an export.

**Environment:**
v6.0.2 atop FXServer 6594
_On Linux_

**Steps to reproduce:**
1. Create a server-side JavaScript script with the following export:

```javascript
global.exports("GetRoles", function (value) {
    console.log(value)
});
```
2. Attempt to call the export from a Lua script:

```lua
exports.tynopia.GetRoles("efwfewfwe")
```

**Expected Results:**
The expected output on the console should be:

```
[script:tynopia] efwfewfwe
```

**Actual Results:**
Instead, the actual output on the console is:

```
[script:tynopia] undefined
```

However, when I call the same export from JavaScript, it works as expected:

```javascript
exports.tynopia.GetRoles("fwewefwe")
```
And the console output is as expected:

```
[script:tynopia] fwewefwe
```

It's odd because exports with variables from Lua to JavaScript seem to work properly, but not vice versa (i.e., from JavaScript to Lua). This behavior is different from what I expected.

**Comment by Ekinoxx0** [comment]
Lua side should call `exports.tynopia:GetRoles("fwewefwe")`
Note the difference is the sign `:`
