### ISSUE TITLE
Vehicle engine multiplier not sync to other players

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#2140]
When using SetVehicleMod(vehicle, 11, 3, false) to set an engine upgrade on a vehicle, the power of the vehicle will not change for other players. 
GetVehicleMod(vehicle, 11) will return the correct value but the power is not effective.

I have attached a repro ressource with an edited carcols to highlight the issue.

Repro:
On player 1:

- Spawn the vehicle using "spawn"
- Set the engine using "setmod"
- Check that this is correct using "getmod"

The vehicle will have the correct multiplied power.

On player 2:

- Enter the vehicle
- Check that this is correct using "getmod"

The vehicle will **NOT** have the correct multiplied power.

Video:
https://youtu.be/izUNEGGfqyw

[cartest.zip](https://github.com/citizenfx/fivem/files/12255077/cartest.zip)

Command "spawnwithmod" of the repro resource can also be used to recreate a similar issue with just one player

**Comment by gottfriedleibniz** [comment]
Would you happen to have a resource that calls `MODIFY_VEHICLE_TOP_SPEED` (previously named `_SET_VEHICLE_ENGINE_POWER_MULTIPLIER`), e.g., vMenu? A lot of its uses are incorrect and causes conflict with `VMT_ENGINE` (fighting over drive force).

**Comment by manzarek123** [comment]
Yes that was the issue. Thank you I have now stopped using this native.
Sorry for the bad report I should have tested without any other resources.

**Comment by gottfriedleibniz** [comment]
The report was fine. These types of weird interactions should be documented anyway (incl. native definitions and their misuse).
