### ISSUE TITLE
StopSound does not effect on this code

### ISSUE THREAD

**Issue by mas7or123** [citizenfx/fivem#2142]
is there a way to stop this sound PlaySound(-1, 'All', 'SHORT_PLAYER_SWITCH_SOUND_SET', true)
i tried to for loop the stopsound native from -1 to 99 but i still play the sound

**Comment by nikez** [comment]
This isn't for support. And if you searched for 10s you would find an answer.

Use GET_SOUND_ID to get an id, provide that as the first parameter in PLAY_SOUND and then use STOP_SOUND to stop it.

**Comment by mas7or123** [comment]
i tried it on this sound but it does not work when the first parameter is -1 but on other sound it work

**Comment by PappaNiels** [comment]
there is no way to stop a sound with -1 as its first parameter, without doing something crazy. again, this is not support. go to the [forums](https://forum.cfx.re) or the [discord guild](https://discord.gg/fivem) for further help.

**Comment by blattersturm** [comment]
You already posted this two weeks ago in #2125. Why _again?_
