### ISSUE TITLE
All servers are not displayed

### ISSUE THREAD

**Issue by HyukMyeongkKwon** [citizenfx/fivem#2149]
The existing server is online, but I can't connect to it, so when I look at it, all servers are displayed as offline.
How should I solve it?
![image](https://github.com/citizenfx/fivem/assets/36390581/4b4a1fc6-1da9-44d7-bdd9-e697799bc3ac)

**Comment by sahtonlvlpasouf** [comment]
FIVEM SE FAIT DDOS

**Comment by PappaNiels** [comment]
This is not the place for support. See the [forums](https://forum.cfx.re) or the [discord guild](https://discord.gg/fivem) for further support. This has probably to do with the current outages.
