### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by niemiecki216** [citizenfx/fivem#2159]
My server has been experiencing random crashes so I decided to run procdump on the process and wait until a crash is triggered. I ran the dump file produced from procdump and got the following

Unhandled exception at 0xc0000005

Running FXServer 6624 on Windows Server 2022

Link to download .dmp: https://drive.google.com/file/d/1j2n2NmNeAL7uzL_xpwOh25z47qw85pTS/view

**Comment by AvarianKnight** [comment]
This is a bit of a weird one, somehow dataLength is overflowing. Think figuring this one out is a bit over my head sadly.

![](https://i.imgur.com/HA6YRrr.png)

https://github.com/citizenfx/fivem/blob/b972aa26e316aee4af84b8acb77d9698ff49c51f/code/components/citizen-resources-core/src/StateBagComponent.cpp#L636-L641

**Comment by gottfriedleibniz** [comment]
How state-bags are serialized is a bit rough, e.g., https://github.com/citizenfx/fivem/issues/1854#issuecomment-1433413761. Even the edgiest of cases, e.g., key value being serialized as a `uint16_t` but not being sanitized is worrisome.

One potential replication here (works on my machine, YMMV):

```lua
    local BufferLimit = 131072
    local Overflow = 13

    local key = string.rep("y", BufferLimit + Overflow)
    local value = string.rep("\0", Overflow - 1)

    SetStateBagValue("global", key, value, #value, true)
```

**Comment by yellowcalvinn** [comment]
Hi, we are having the same problem on Linux Server. Random people crashing our server. Can we change it on linux?

**Comment by moelrobi** [comment]
Question: Is there an ETA when a new linux build will be released?

**Comment by AvarianKnight** [comment]
Add the symbol server `https://runtime.fivem.net/client/symbols` and have the [repo setup on your machine](https://github.com/citizenfx/fivem/blob/master/docs/building.md)

**Comment by AvarianKnight** [comment]
This was fixed in https://github.com/citizenfx/fivem/pull/2161 and cleaned up further in https://github.com/citizenfx/fivem/pull/2185
