### ISSUE TITLE
Keyup Keydown NUI LAlt 

### ISSUE THREAD

**Issue by CeebTV** [citizenfx/fivem#2160]
Can't receive event of keydown / keyup in NUI for the key `LAlt`

My code work on browser

Canary version

**Comment by Z3rio** [comment]
Tested this in-game, this indeed seems to be an issue.
Tried to console log both e.altKey and e.key, whereas neither of them were printed upon using left alt.
Whilst they were printed upon using **right** alt.

Hm...

**Comment by blattersturm** [comment]
_Right_ Alt also does not seem to work (on layouts that have a 'true' right Alt, and not an AltGr). I'm suspecting this might be some trickery regarding Alt being the menu key and it having some specific handling in Win32 stuff- will submit a PR soon.

**Comment by blattersturm** [comment]
Correct: this is fixed by adding `WM_SYSKEYDOWN` and `WM_SYSKEYUP` to the OnWndProc handlers. I've reworked some other code around there too but I'll PR it ~soon - aka when I get my Git set up properly to write commits.

**Comment by Z3rio** [comment]
Great work as usual @blattersturm <3
