### ISSUE TITLE
entity state bags do not replicate after setting the state twice on the same entity

### ISSUE THREAD

**Issue by jellyton69** [citizenfx/fivem#2163]
I've been using entity state bags to reset a vehicle's properties back to default, however, I noticed that after setting the state bag of an entity twice, the state bag is not replicated to the client. I went ahead and made a quick mock resource to test it on a fresh server, and found that this indeed happens with nothing but default resources on the server (build 6623).

Steps to reproduce (using the attached resource):
1. Get in a vehicle
2. Run the preview command
3. Get out of the vehicle
4. Entity state bag is set
5. Repeat steps 1-4 for a second time
6. Repeat steps 1-4 again, and notice that nothing in the entity state bag change handler ran.

[entity-state-repro.zip](https://github.com/citizenfx/fivem/files/12375318/entity-state-repro.zip)

As you can see in the following clip, on the 3rd go, in the console, we should expect to see "attempting to reset properties", just like the previous 2 times, however, it never occurs.

In the server console, we still see the correct set state:
```
[script:entity-state-] resetting vehicle properties
[script:entity-state-] netid: 11
[script:entity-state-] entity: 136253
[script:entity-state-] Setting state on preview vehicle
[script:entity-state-] some data
```

[repro-clip](https://files.jellyton.me/ShareX/2023/08/FiveM_b2699_GTAProcess_-_August17_-_21.26_-_2681.mp4)

**Comment by jellyton69** [comment]
Upon further investigation, it actually looks like the issue occurs when going from client -> server, **_not_** server -> client. As the state is still "some data" before it is set on the server, when run on the 2nd time, resulting in the entity state not "restreaming" when it's set for a third time.

So the actual question is, when the entity state bag is set on the 2nd time, why isn't the state set to **_nil_** like it is on the first time. 

Updated resource with new prints showing the state before it's set on the server side: 
[entity-state-repro.zip](https://github.com/citizenfx/fivem/files/12375389/entity-state-repro.zip)

**Comment by AvarianKnight** [comment]
This isn't a bug, you're setting `Entity(vehicle).state:set('ResetVehicleProperties', nil, true)` in a StateBagChangeHandler, but StateBagChangeHandlers are ran *before* the state gets changed.

Also a note in your example `GetEntityFromStateBagName` shouldn't need a `DoesEntityExist`, of the entity doesn't exist it will return 0.

**Comment by jellyton69** [comment]
> This isn't a bug, you're setting `Entity(vehicle).state:set('ResetVehicleProperties', nil, true)` in a StateBagChangeHandler, but StateBagChangeHandlers are ran _before_ the state gets changed.

Ah, so waiting a frame should result in correct replication back to the server?

**Comment by jellyton69** [comment]
Ah yep I see now: https://github.com/citizenfx/fivem/pull/2108 

Thank you.
