### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by khoerulageng** [citizenfx/fivem#2167]
My server has crashed several times, here I attach the dump file, can you help find out the cause and how to fix it?

Errors that appear like:
0x1c
0x16e
Game crashed: Recursive error: An exception occurred (c0000005 at 0x1412f1c39) during execution of the INIT_SESSION function for CExtraContentWrapper.

Running FXServer on Windows Server 2019

Link to download .dmp: https://drive.google.com/file/d/1ct-1ZkOac0WPEnilLtRxctQ_Yl31YWtP/view?usp=sharing

**Comment by khoerulageng** [comment]
iam using FXServer version 6645

**Comment by the-big-gs** [comment]
use the last fivem update the issue has been fixed there

**Comment by blattersturm** [comment]
> 0x1c
> 0x16e
> Game crashed: Recursive error: An exception occurred (c0000005 at 0x1412f1c39) during execution of the INIT_SESSION function for CExtraContentWrapper.

Are you sure these are _server_ crashes?

**Comment by gottfriedleibniz** [comment]
Server crash. Client dump provided.

If you continue to face similar issues, please reopen.
