### ISSUE TITLE
Issues with the cfx.re website/forums

### ISSUE THREAD

**Issue by KretnGaming** [citizenfx/fivem#2174]
So this will be yet anther attempt at trying to get this issue resolved.
So I'm trying to get my email updated on the cfx.re forums so that I can properly transfer assets from my KeyMaster.
The problem at the moment is, the email in which I created the account was deleted a while back and cannot be accessed anymore.
I've attempted to associate a new email via the site, and never receive the confirmation email. (I have attempted this with several emails)
I have also associated a google account & my patreon account, again no joy. 
All I need is the email change so that I can properly transfer assets that are sitting in my keymaster to a friend.

**Comment by blattersturm** [comment]
The team looking at and maintaining this repository is not the team related to forum accounts, and can not help you with this issue. File a ticket on the [support portal](https://support.cfx.re/hc/en-us/requests/new), or if you've already got one there, wait for a response.
