### ISSUE TITLE
New Search Update is Extremely Inaccurate

### ISSUE THREAD

**Issue by Georgie15** [citizenfx/fivem#2208]
A month ago, the search was updated to this: https://github.com/citizenfx/fivem/pull/2122 and since then, it has provided extremely inaccurate results. For example, my server, "Paradise State Roleplay" is known as "PSRP" by most people yet when you search "PSRP", servers that hold 0 players are able to appear before it. I don't really understand the reason for this change because many servers with longer names are now unable to be found correctly unless the player searches for the server using the entire name.

I have provided a screenshot of how this new search method is worse than before.

![image](https://github.com/citizenfx/fivem/assets/75462145/49283b87-7ab6-43be-9479-5a2a88250395)

**Comment by FlawwsX** [comment]
You could put PSRP somewhere in your server name,

**Comment by outsider31000** [comment]
what you mean is known as PSRP ? known by the search enigne? your serve rname is not PSRP there fore wont show as first.
and probably the player count is not a factor

**Comment by Georgie15** [comment]
> what you mean is known as PSRP ? known by the search enigne?lol Your server rname is not PSRP there fore wont show as first. and probably the player count is not a factor

The player count should be a factor in the search results if the majority of the people searching for "PSRP" are searching for the server with the most players.

**Comment by Georgie15** [comment]
> You could put PSRP somewhere in your server name.

Sure, that's an easy solution. But that isn't the point of my point, the goal is to increase the accuracy of the search so that other servers don't face the same issue.

**Comment by outsider31000** [comment]
> > what you mean is known as PSRP ? known by the search enigne?lol Your server rname is not PSRP there fore wont show as first. and probably the player count is not a factor
> 
> The player count should be a factor in the search results if the majority of the people searching for "PSRP" are searching for the server with the most players.

"should" doesnt mean it is...

**Comment by Georgie15** [comment]
> > > what you mean is known as PSRP ? known by the search enigne?lol Your server rname is not PSRP there fore wont show as first. and probably the player count is not a factor
> > 
> > 
> > The player count should be a factor in the search results if the majority of the people searching for "PSRP" are searching for the server with the most players.
> 
> "should" doesnt mean it is...

Not really sure what you mean. The goal of this post isn't to solve my problem, its to create an accurate search result.

**Comment by outsider31000** [comment]
so wheres the pull request ? 
from what I see here you reporting something you dont know how it works...

**Comment by PichotM** [comment]
> > > > what you mean is known as PSRP ? known by the search enigne?lol Your server rname is not PSRP there fore wont show as first. and probably the player count is not a factor
> > > 
> > > 
> > > The player count should be a factor in the search results if the majority of the people searching for "PSRP" are searching for the server with the most players.
> > 
> > 
> > "should" doesnt mean it is...
> 
> Not really sure what you mean. The goal of this post isn't to solve my problem, its to create an accurate search result.

how is it accurate to prioritize results that do not include what you're searching for?

**Comment by tabarra** [comment]
There are 30k servers out there, most servers have names which words or acronym is not particularly unique, so for most searches there will be many results.  
Putting 100% of the weight just on the server name while ignoring description, boost power, and player counts is an issue.  
  
**Either ways,** the Rockstar team is aware and they are investigating ways to improve this behavior.

**Comment by Georgie15** [comment]
> There are 30k servers out there, most servers have names which words or acronym is not particularly unique, so for most searches there will be many results. Putting 100% of the weight just on the server name while ignoring description, boost power, and player counts is an issue.
> 
> **Either ways,** the Rockstar team is aware and they are investigating ways to improve this behavior.

I agree, thank you!

**Comment by nihonium-cfx** [comment]
Hey there! Just for visibility, we have reverted the previous implementation, so now the server list is back to "filtering" mode as expected. However, we're working on implementing a new approach here, that will satisfy both use-cases here.
