### ISSUE TITLE
Adhesive.dll Crash on Client

### ISSUE THREAD

**Issue by Qishop1** [citizenfx/fivem#2211]
Server Version: 6704
Client Verson: Release/Beta/Canary
Game Build: 2944
Server Core: esx-core
Game Crashed by Adhesive.dll+*******Randomly while playing in the Server.
Recently showed :Adhesive.dll+1239D99; Adhesive.dll+10F5ADE; Adhesive.dll+10F2A80; Adhesive.dll+113115B; Adhesive.dll+10F4260; Adhesive.dll+111BAC1; Adhesive.dll+128041F; Adhesive.dll+1239D99;  Adhesive.dll+10D9494

The Server never Crashed of svadhesive.dll
Most of the players showed  Adhesive.dll+128041F; Adhesive.dll+1239D99 and one player shower the others, due to no further information, we have to send this issue. The server is SAHC.
one of the  .dmp file shows:  INVALID_POINTER_READ_c0000005_adhesive.dll!Unknown
                            FAILURE_ID_HASH:  {beac932c-8bd4-26e8-ec4d-0d33c8be187e}
and it's adhesive.dll+1239D99

**Comment by blattersturm** [comment]
> one of the .dmp file shows:

Can you upload any of these?

**Comment by AstroGirl064** [comment]
https://we.tl/t-IoLH051jSt

I think thats it ?

**Comment by Qishop1** [comment]
> > one of the .dmp file shows:
> 
> Can you upload any of these?

Yeah sure, Here is it:

**Comment by gottfriedleibniz** [comment]
Presumably this has been fixed since 6704. If it still an issue, please reopen.
