### ISSUE TITLE
Call into the Windows API took too long

### ISSUE THREAD

**Issue by daav-dd** [citizenfx/fivem#2212]
This has been an issue for quite a while now but wasn't happening 2 years ago, I am on the latest security patch of Windows 10 and I've got a computer which I wouldn't say is bad at all (32GB RAM 3600, i7 9700k, Radeon 6750xt, z390-e). I've done some googling and I really can't find any solution to the problem. My framerate is very stable and I'm not getting any drop whatsover in performance, however, I am getting huge and infuriating sound distortion throughout my whole system, I would usually keep teamspeak or discord open in the meantime, but even by closing them the problem still stands. A quick glance at task manager shows me how fivem is really power hungry, with power usage levels reaching Very high.
If there is anything you can suggest me doing, please recommend: I'm really looking forward to put an end to this.
![image](https://github.com/citizenfx/fivem/assets/62658015/0774d089-4e0e-47ab-9ceb-0a4359ca9d90)

**Comment by blattersturm** [comment]
This does not look like an actionable project issue. Try checking things like DPC latency on your PC setup.
