### ISSUE TITLE
Adhesive.dll+1239D99  and  Adhesive.dll+ 10D9494

### ISSUE THREAD

**Issue by AstroGirl064** [citizenfx/fivem#2214]
Server Version: v1.0.0.6683
Client Verson: Release/Beta/Canary
Game Build: 2944
Server Core: esx-core
Game Crashed for some players  by Adhesive.dll+ 10D9494 and  Adhesive.dll+1239D99

**Comment by Gogsi** [comment]
Duplicate of #2211

**Comment by AstroGirl064** [comment]
[https://we.tl/t-IoLH051jSt](url)

I think thats it ?
