### ISSUE TITLE
CreatureMetadata not working on b2944

### ISSUE THREAD

**Issue by anotherserver** [citizenfx/fivem#2218]
Addon Clothes Pack, fully working on b2699, no more working on 2944.

ex : heels are not working - shoes are all flat

**Comment by gottfriedleibniz** [comment]
Unfortunately there are some game limits involved that make things incredibly [difficult](https://forum.cfx.re/t/help-build-2372-crash-to-desktop/4123759/13) to fix (also see related posts on forums).
