### ISSUE TITLE
was not safe for net

### ISSUE THREAD

**Issue by imsnaily** [citizenfx/fivem#2220]
So basically you can crash a server spamming TriggerServerEvent of the server events as playerDropped, playerJoining, explosionEvent, etc...

If there's a good amount of resources that handles that events the server will just crash. It could be a nice thing to like "whitelist" this events and prevent from using them on TriggerServerEvent

![image](https://github.com/citizenfx/fivem/assets/75950591/7b176a65-704a-416a-a174-70a72a1059c2)

**Comment by Zydson** [comment]
It won't crash, only will heavily load on CPU, also seems like you are running localhost so you don't get kicked for network event overflow. Normally you could not spam events every 0ms without getting kicked.
