### ISSUE TITLE
Trouble Opening RedM in Steam Version of the Game

### ISSUE THREAD

**Issue by bradistome** [citizenfx/fivem#2221]
I purchased the full version of the game on Steam with the intention of using RedM. However, every time I try to open RedM, the program simply disappears on the 'analyzing game data' screen. I haven't been able to find any solution, and I would greatly appreciate it if someone could assist me.

**Comment by t3chman** [comment]
This isn't the place for client support. Use the RedM support channel in the discord.

**Comment by thorium-cfx** [comment]
This is indeed not the place for support requests. Please use the [forums](https://forum.cfx.re/) or discord.
