### ISSUE TITLE
[NUI] Game camera focus remains in NUI

### ISSUE THREAD

**Issue by zoovdev** [citizenfx/fivem#2226]
Graphics          Geforce RTX 3090 TI
Processor	12th Gen Intel(R) Core(TM) i9-12900K   3.20 GHz
Installed RAM	64.0 GB (63.8 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	22H2
Installed on	‎5/‎03/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Tested server game builds: (Last 3 from 2944) 
Tested fiveM states: Latest, Beta & Canary
Tested servers: Localhost, FiveM test server, Gabz test server + more.

Issue:

Similar to how the native: SetNuiFocusKeepInput works, whenever I open any NUI on any server that is suppose to have Cursor and Keyboard focus, my game camera continues to provide input. 
This occurs even on the F8 console as seen in the attached video. 
When in any NUI my input for voice does not work either.  

I have reinstalled everything (FiveM, CitizenFX in Appdata, GTA V), and cannot replicate this on any other device however I have heard of a few others who have also had this issue. 

[CitizenFX.zip](https://github.com/citizenfx/fivem/files/12790636/CitizenFX.zip)

https://github.com/citizenfx/fivem/assets/84139171/3e17c85e-21c1-44a3-94fd-2c9694abfcd3

**Comment by gottfriedleibniz** [comment]
A potential issue here is that the definition of [OnCtrlInit](https://github.com/citizenfx/fivem/blob/master/code/components/gta-core-five/src/BlockLoadSetters.cpp#L510) is incorrect. 

One of its missing arguments is related to mouse exclusivity that is later used in computing `SetCooperativeLevel` dwFlags. An incorrect exclusivity configuration could explain some issues w/ DirectInput.

**Comment by CaptainAvenger** [comment]
I have also encountered this recently, and I don’t know why this situation has happened. I have tried to reinstall FIVEM, update Window, and update GPU Driver, but still failed to solve.

**Comment by tens0rfl0w** [comment]
@gottfriedleibniz build `7630` still doesn't block camera input when a NUI has focus and the input method is set to 'DirectInput'. (Easily reproducible when opening the F8 console)
