### ISSUE TITLE
GetGameplayCamRelativePitch client native not working as expected

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#2228]
- **Client (production/canary) and FXServer version**
Beta client, 6683 artifacts (windows)

- **What you expected to happen**
When setting the gameplay cam relative pitch to 0.0, using the associated getter would return 0.0 if I'm not moving the camera

- **What actually happens**
There seems to be an offset depending on the ped world coords

- **Category of bug (eg. client, server, weapons, peds, native)**
Camera natives / client side

- **Reproducible steps, preferably with example script(s)**
```lua
-- can be done using basic runcode
SetGameplayCamRelativePitch(0.0, 1.0)
print(GetGameplayCamRelativePitch()) -- this will return a negative value
```

[Video](https://forum.cfx.re/uploads/default/original/4X/c/4/4/c44462d986d4811a498fbd5c171fe448ffd11664.mp4)

**Comment by Mathu-lmn** [comment]
https://github.com/citizenfx/fivem/assets/80094438/162de2b8-c3c0-4743-a555-3d026f141fd4

Reuploading the video to allow preview :)

**Comment by Infinity585** [comment]
While this is still not working I found using GetGameplayCamRot().x worked to get the cam pitch.

**Comment by gottfriedleibniz** [comment]
The sequence does look a bit counter-intuitive w/ `BaseOrbitPitchOffset`, `ExtraOrbitPitchOffset` (controlled via undocumented natives), `LookOverSettings`, and whatever else (the entity) having an effect on the 'relative' pitch after the call to `SetGameplayCamRelativePitch`.

This seems more like a [documentation](https://github.com/citizenfx/natives/pulls) bug. If you truly require absolute-zero, you could, I guess, compensate in the other direction (e.g., +2.046 in your example).

**Comment by Mathu-lmn** [comment]
Hey, the issue here is I have no way to determine the "offset", depending on where I am on the map, it can either be -2.2, -0.9 or anything in between. But I'll try @Infinity585 's suggestion tho.

**Comment by gottfriedleibniz** [comment]
Any updates w/ what was suggested? Otherwise, may I close this issue?

**Comment by Mathu-lmn** [comment]
Hey, I just tested this right now again, but his suggestion didn't work either :/ 
![image](https://github.com/citizenfx/fivem/assets/80094438/0335fc1e-05e0-4c90-8a34-5091abf927d8)

**Comment by Mathu-lmn** [comment]
![image](https://github.com/citizenfx/fivem/assets/80094438/775163fe-44c3-4b8f-ae8d-acc680263693)
After further investigation, it seems that setting the player's heading to 0.0 "fixes" the getter offset

**Comment by Mathu-lmn** [comment]
![image](https://github.com/citizenfx/fivem/assets/80094438/cc708f60-9aec-4c7f-9e23-f202fa67d65f)
Okay it doesn't seems related then.... I don't understand those offsets

**Comment by gottfriedleibniz** [comment]
With third-person cameras it does seem like "relative" here has two different meanings.

1. `SetGameplayCamRelativePitch`, as I mentioned [above](https://github.com/citizenfx/fivem/issues/2228#issuecomment-1749904336), is a calculation relative to its orbit configuration.
1. `GetGameplayCamRelativePitch` returns the relative pitch between the camera and whatever it is attached too (or following; just a subtraction of two angles).

**Comment by Mathu-lmn** [comment]
Hmm so it's more a naming convention issue than a game mechanic issue then. How would I get the GameplayCamRelativePitch correctly then ?

**Comment by gottfriedleibniz** [comment]
Maybe give [ClampGameplayCamPitch](https://docs.fivem.net/natives/?_0xA516C198B7DCA1E1) a shot. See if this helps you achieve the effect you desire.

**Comment by Mathu-lmn** [comment]
Okay so this actually works but there's a twist. While the ClampGameplayCamPitch native is called each frame, the GetGameplayCamRelativePitch native returns 0.0 successfully, but once the loop ends and the native stops being called each frame the getter returns the weird "random" offset again.

The thing is that I found this issue while developing a feature for a menu, when the player's mouse goes on the top or bottom edge of the screen, the camera moves. I managed to do it for the cam heading correctly, but got this issue for the pitch :/

**Comment by gottfriedleibniz** [comment]
> the getter returns the weird "random" offset again.

For these specific cameras, it is not a setter/getter pair in the traditional sense. The orbit camera has its own restricts, effects, and limitations (e.g. clipping) that supercede whatever is desired from scripting commands.
