### ISSUE TITLE
issue while installing five M to my laptop

### ISSUE THREAD

**Issue by ritheesh390** [citizenfx/fivem#2245]
Error updating FiveM
X Downloading
b26004150bb82c03ff69426ccdeb7de6de987803ecf50d96813634b60db21493.xz
failed with CURL code 56 - OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0
neSync
Close

**Comment by PappaNiels** [comment]
The repo is not meant for support. Please see the [forums](https://forum.cfx.re) or the [discord](https://discord.gg/fivem) guild
