### ISSUE TITLE
forced-crash, REPORT_CASH_SPAWN_EVENT exception

### ISSUE THREAD

**Issue by ConradoDev** [citizenfx/fivem#2246]
Some cheaters are using REPORT_CASH_SPAWN_EVENT (CReportCashSpawnEvent) to intentionally crash the game.

Stacktrace from b2372
![image](https://github.com/citizenfx/fivem/assets/72238304/058f5d6f-9dff-4b03-93f8-f92fb92f314a)

![image](https://github.com/citizenfx/fivem/assets/72238304/ffeefc1f-64f2-405c-b00c-f19f0e43150c)
![image](https://github.com/citizenfx/fivem/assets/72238304/c989c766-28af-4782-8524-4801a14f1142)

I couldn't resolve this issue using server resources, so I applied a temporary fix to continue playing using my external application while the problem remains unresolved. If there's a way to prevent that event, it would be appreciated. Thx.

**Comment by gottfriedleibniz** [comment]
Stack trace is what one would expect if `player31` was passed to the event handler (i.e., bad player info). For reference, there are a few other events that will not interact nicely with `player31` (or bad player info) that may also require preemptive fixing.

**Comment by thorium-cfx** [comment]
Closing this as completed; fix was added and since then the crash has no longer popped up in our records.

**Comment by gottfriedleibniz** [comment]
That recent `g_player31` fix is quite messy and could probably be done better. Additionally, there are one or two other edge-cases that should be addressed.
