### ISSUE TITLE
SetEntityDrawOutline crashing for peds

### ISSUE THREAD

**Issue by imsnaily** [citizenfx/fivem#2252]
Basically if I do the drawoutline in objects everything seems fine. But when I do it for a ped/player it crash the client.

![image](https://github.com/citizenfx/fivem/assets/75950591/93f8ad81-d53d-4d6d-89ed-8c4df1667e4b)
![image](https://github.com/citizenfx/fivem/assets/75950591/4fc9d742-9289-42a1-899f-2f9fd071f367)

**Comment by nikez** [comment]
"This function supports SDK infrastructure and is not intended to be used directly from your code."

https://docs.fivem.net/natives/?_0x76180407
