### ISSUE TITLE
StartShapeTestRay & (some) NUI's not functioning on Latest (Unstable) build (Ver 7037)

### ISSUE THREAD

**Issue by Flambaa** [citizenfx/fivem#2258]
**Native found not working so far:** 
| Native | Code Used|
| ----------- | ----------- |
| StartShapeTestRay |![image](https://github.com/citizenfx/fivem/assets/82859879/4bb0d1b8-c0d0-4e52-8c38-22835c74205e)| 

- Some NUI's are also not loading. 

Switching back to the release channel solves these errors. 

Apologies for not having much information, this is really all I could come up with.

**Comment by DemmyDemon** [comment]
You are running an asynchronous shape test as if it was synchronous.
Try [StartExpensiveSynchronousShapeTestLosProbe](https://docs.fivem.net/natives/?_0x377906D8A31E5586) instead, or wait for the result to return before using it.

Not sure why that *used to work* for you, though.

You should probably open a separate issue if you have discovered an issue with NUI.

**Comment by thorium-cfx** [comment]
The return value of `GetShapeTestResult` is not properly checked in your example, see https://docs.fivem.net/natives/?_0x3D87450E15D98694 and read the return value. Keep checking that value (in successive frames) until it is successful, then read the output.
