### ISSUE TITLE
Random crash related to scaleforms

### ISSUE THREAD

**Issue by manups4e** [citizenfx/fivem#2281]
![image](https://github.com/citizenfx/fivem/assets/4005518/0f938dc2-6ada-4aa8-b42a-02d57852ff6d)
[CfxCrashDump_2023_11_22_21_57_08.zip](https://github.com/citizenfx/fivem/files/13444556/CfxCrashDump_2023_11_22_21_57_08.zip)

Sadly i can't give a good repro as this error occurs randomly... could it be related to streamed custom GFX files? even tho i wasn't drawing any scaleform at the time of the crash.

If i'll find more info about the error i'll edit the issue

**Comment by gottfriedleibniz** [comment]
There looks to be a few issues related to `GFxObjectInterface::CreateEmptyMovieClip`.

1. The [hook](https://github.com/citizenfx/fivem/blob/master/code/components/gta-streaming-five/src/ScaleformHacks.cpp#L18) looks to be missing a depth parameter (which gets sanitized and will skip `GFxValue` initialization).
1. `CreateEmptyMovieClip` returning false is not handled.

The crashes being random would support the above being the issue (random stack values being read). Although, that is not guaranteed.

**Comment by manups4e** [comment]
I do create empty movie clips same way as R* does.. the flash way so I think it's nothing I can handle on my side

**Comment by nihonium-cfx** [comment]
Should be fixed by https://github.com/citizenfx/fivem/commit/5031bb7ba9b13823166ad88ee7b4b3a4b329e594
