### ISSUE TITLE
Event to make a ragdolled ped get up again (unragdoll)

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#2290]
There currently does not seem to be any functionality to either ragdoll someone properly without them getting up again automatically after some time (SetPedToRagdoll) or get up from being ragdolled at all!

There is just one variable for time in SetPedToRagdoll THAT can't be reset, even though I was thinking, ResetPedRagdollTimer would do that.
SetPedToRagdoll also twitches the ragdoll, every time, it is applied again.

Calling ClearPedTasks does nothing on a ragdolled player, ClearPedTasksImmediately t-poses the player for a bit and the returns to the base idle animation. (No get up animation whatsoever here)

I would suggest exposing more natives regarding ragdolling or giving some type of way to unragdoll a player atleast.

**Comment by mcNuggets1** [comment]
> I believe you can use `RESET_PED_RAGDOLL_TIMER` to make ped get out of ragdoll state earlier.

That does not work.

**Comment by gottfriedleibniz** [comment]
I think clever use of `RESET_PED_RAGDOLL_TIMER` can still achieve what you are trying to capture: A way to ragdoll indefinitely, or until some condition is met (e.g., no longer knocked out), that allows a proper exiting of the CTaskNMRelax (iirc) task. Hand-waving a bit:

```lua
SetPedToRagdoll(PlayerPedId(), 100, 200, 0, false, false, false)
while SomeCondition do
   Wait(0)
   ResetPedRagdollTimer(PlayerPedId())
end
```

T

**Comment by mcNuggets1** [comment]
ResetPedRagdollTimer does not do anything. It does not stop the last ragdoll timer, the player still gets up after the time configured in SetPedToRagdoll in my tests.

**Comment by gottfriedleibniz** [comment]
Can you provide an example as to how you are running/testing this?

**Comment by mcNuggets1** [comment]
SetPedToRagdoll(ped, 1000, 1000, 0, false, false, false) in a 0 wait loop.
After the loop has ended, I call ResetPedRagdollTimer.

I also found out, that SetPedToRagdoll has instances, in which other players do see the player as standing.

**Comment by tens0rfl0w** [comment]
Using
```lua
local timeToRagdoll = 10000
local ped = PlayerPedId()
local ragdoll = true
SetPedToRagdoll(ped, 10, 10, 0, false, false, false)
CreateThread(function()
    while ragdoll do
        Wait(0)
        ResetPedRagdollTimer(ped)
    end
end)
Wait(timeToRagdoll)
ragdoll = false
```
works perfectly fine for me and achieves exactly what you're asking for.

**Comment by mcNuggets1** [comment]
Ah I totally misunerstood the function, it now makes much more sense. Thanks for clarifying that!

**Comment by mcNuggets1** [comment]
I tried using it.
It did work for the local player, but for other players the ragdoll is twitching, trying to get up, etc.

**Comment by mcNuggets1** [comment]
https://github.com/citizenfx/fivem/assets/18447482/0b9124f8-003d-460b-ae16-1def56831716

**Comment by tens0rfl0w** [comment]
Works perfectly fine for me. However, if you're trying to reset the ragdoll timer on a remotely owned ped this won't work for obv reasons. This only works on the local player ped or peds the client has network ownership of (working around this limitation in code should be easy though, e.g. network events/state bags/...).

https://github.com/citizenfx/fivem/assets/57523343/6d466a34-4bc3-4477-8375-6f33c4e07920

**Comment by mcNuggets1** [comment]
As soon as you hit the ped, it begins twitching and trying to get up, if you dont run EnableBoundAnkles (or whatever).
Even when activated, the player still twitches for others.
I would make a video, but I dont have any software for it, currently.

while isDead do
	if not IsPedRagdoll(ESX.PlayerData.ped) then
		SetPedToRagdoll(ESX.PlayerData.ped, 1000, 1000, 0, false, false, false)
	else
		ResetPedRagdollTimer(ESX.PlayerData.ped)
	end
	Wait(0)
end

**Comment by AvarianKnight** [comment]
That isn't a bug, physics for peds are completely client sided so where they rag-doll will be different for every client.

**Comment by mcNuggets1** [comment]
> That isn't a bug, physics for peds are completely client sided so where they rag-doll will be different for every client.

The position of the ped is still corrected for a certain period of time. It just stops after some time.

**Comment by mcNuggets1** [comment]
NetworkCreateSynchronisedScene needs the player to be not ragdolled to be executed properly.
Here we have a usage for an Unragdoll native now.
