### ISSUE TITLE
Fivem is broken after newest Update

### ISSUE THREAD

**Issue by whyauthentic** [citizenfx/fivem#2301]
### What happened?

Update happened :D After that many Servers loosed players and nobody can join anymore

### Expected result

Normal Join

### Reproduction steps

1. Open FiveM and let it update
2. Try to join a Server

### Importancy

Crash

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM Build 7195

### Additional information

![image](https://github.com/citizenfx/fivem/assets/109388773/276f9da8-4cad-4ef3-b701-5f1095706d4e)

**Comment by hjklwasntavailable** [comment]
should resolve itself in a while
