### ISSUE TITLE
Chat Resource No Longer Includes Built Files

### ISSUE THREAD

**Issue by ghost** [citizenfx/fivem#2302]
### What happened?

The bundled chat resource with the artifacts no longer contains the `dist` folder with the built files not allowing me to use the internal chat resource.

### Expected result

chat resource should include dict dir

### Reproduction steps

Download Latest Artifacts
Go to citizen/system_resources/chat
See no dist folder

### Importancy

Slight inconvenience

### Area(s)

FXServer

### Specific version(s)

Server 7114+ Windows

### Additional information

Seems that it was removed on all artifacts after 7080 on windows.

**Comment by nihonium-cfx** [comment]
Fixed in https://github.com/citizenfx/fivem/commit/084d89c7ecefd9586b594f431052d5c4e3d837ba
