### ISSUE TITLE
Update Building.md

### ISSUE THREAD

**Issue by ook3D** [citizenfx/fivem#2323]
### Segment

Building Cfx.Re

### Importancy

Missing details

### Improvement request

the hyperlink to boost.1.7.1.0 seems to be down or changed since i last compiled the repo, 
![image](https://github.com/citizenfx/fivem/assets/47336113/8cbceb58-8107-4808-ae98-d19822efa67b)
i found an alternative, https://sourceforge.net/projects/boost/files/boost-binaries/1.71.0/

### Area(s)

FiveM

**Comment by AvarianKnight** [comment]
It might be better to test if boost have any upgrades on the newer versions and link to the [boost releases](https://github.com/boostorg/boost/releases) on GitHub instead

**Comment by ook3D** [comment]
Seems to be suddenly fixed now. download is back to working for now.
