### ISSUE TITLE
Execution  of GetPlayerStamina failed

### ISSUE THREAD

**Issue by Raikjo** [citizenfx/fivem#2341]
### What happened?

It is currently not possible to retrieve the Native GetPlayer Stamina.
I noticed this with a gym script, but the Hud also no longer displays the stamina correctly

![Screenshot_62](https://github.com/citizenfx/fivem/assets/49317444/beb9427b-23b5-4ae7-b116-77dd9d8c4eb1)

### Expected result

to get the Stamina of a player

### Reproduction steps

Use the GetPlayerStamina Native in any Function

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

FiveM 3095 / windows Server 7310 and lower

**Comment by ng4software** [comment]
Hi,

The following code works perfectly fine on my end.
Perhaps you can also try running this code, my suspicion is that the argument you are passing in, is nil. 
Thus making the native call fail.

Code used:
```
Citizen.CreateThread(function() 
    while true do
        print(GetPlayerStamina(PlayerId()))
        Citizen.Wait(0)
    end
end)
```

Server was using 7310 and Client used game build 2944.

**Comment by Raikjo** [comment]
The result of this query is "nil"

But my game build is also 3095

**Comment by ng4software** [comment]
Ah yes, on client build 3095 I do also get the error:
```
[     50656] [b3095_GTAProce]             MainThrd/ __Lua_InvokeNative: execution failed: Error executing native 0x00000000e415ec5c at address extra-natives-five.dll+626A6.
[     50656] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: Execution of native 00000000e415ec5c in script host failed: Error executing native 0x00000000e415ec5c at address extra-natives-five.dll+626A6.^7
[     50656] [b3095_GTAProce]             MainThrd/ ^3> GetPlayerStamina^7 (^5GetPlayerStamina.lua^7:6)
[     50656] [b3095_GTAProce]             MainThrd/ ^3> fn^7 (^5@test/client.lua^7:3)
```
Seems like something about it has regressed in this game build.

**Comment by Disquse** [comment]
Can you guys try canary (latest/unstable) update channel? I've fixed this issue in this commit https://github.com/citizenfx/fivem/commit/7a6290774bf721681f685d0fd9bde9e110624caf

**Comment by ng4software** [comment]
> Can you guys try canary (latest/unstable) update channel? I've (hopefully) fixed this issue in this commit [7a62907](https://github.com/citizenfx/fivem/commit/7a6290774bf721681f685d0fd9bde9e110624caf)

Yep, it does work in Canary.

**Comment by Disquse** [comment]
Then, we will have to wait until it's merged into the production 😄

**Comment by gottfriedleibniz** [comment]
I believe we have waited long enough.

**Comment by Disquse** [comment]
@gottfriedleibniz yeah, seems to be working good.
