### ISSUE TITLE
FiveM F8 quit message.

### ISSUE THREAD

**Issue by itsAdminPlus** [citizenfx/fivem#2364]
### What happened?

Players fake crashing their game by clicking F8 & putting a message after quit.

Not sure if there's a possible fix you guys can possibly implement here, but depending the message they insert it is not noticeable to know which ones are fake/real unless they have a typo in the message or what-not, as we sometimes look when people quit mid roleplay scene or actually crash mid roleplay scene.

### Expected result

Possibly just state "disconnected" or just dont display any args after quit

### Reproduction steps

1. click F8 when ingame
2. type "quit"
3. put a message after quit like this: quit "Game crashed: GTA5_b2699.exe!sub_1411E3C8C (0x3f))"
![02f0cc793eb0a1a563f7e7139aa593d7](https://github.com/citizenfx/fivem/assets/89868900/572fa5de-efd4-42d5-9007-c8d8e0f5a3f3)
![2](https://github.com/citizenfx/fivem/assets/89868900/9a9edeb6-3547-4470-a20b-3fb422a450bf)

### Importancy

Security issue

### Area(s)

FiveM, FXServer

### Specific version(s)

7329

**Comment by slashkeyvalue** [comment]
https://github.com/citizenfx/fivem/issues/1424#issuecomment-1108750711

**Comment by aqua3man** [comment]
https://github.com/citizenfx/fivem/issues/1424#issuecomment-1108750711 Answer is sound. Though some convar that would allow to disable user provided quit messages would be nice to have. It would limit the scope of this kind of abuse.

**Comment by Disquse** [comment]
@aqua3man in this scenario you won't be able to see any quit reason at all. As was said, all quit reasons are "user provided", coming from a client and can't be trusted.

**Comment by aqua3man** [comment]
> @aqua3man in this scenario you won't be able to see any quit reason at all. As was said, all quit reasons are "user provided", coming from a client and can't be trusted.

Yes I understand. What I am talking about is limiting the affect. When every user can /quit <reason>, it has same effect as when every user can load client side scripts. Eveyone knows that it can be done, but when it is limited by client, the scope of abuse is also limited. What I am suggesting is limiting parameter <reason>. I understand that scripts can be loaded, cheats can be used, client can be abused. The purpose is not to fight with cheaters. Cheaters is another scope and another topic. If every user couldn't provide the message it could be better "compass" for server admin.

**Comment by blattersturm** [comment]
Quit reasons are barely even 'abuse'. People can quit in any way imaginable (eg intentionally corrupting memory or disconnecting their internet connection), and crash messages are only provided as a courtesy for diagnostics.

If players have an incentive to lie about quitting, you have a people problem, not a technical problem.
