### ISSUE TITLE
Servers show a confusing "sv_disableClientReplays" to end users

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#2367]
### What happened?

Ever since recent server artifacts, server info pages show a confusing variable called 'sv_disableClientReplays'.

Web UI:
![image](https://github.com/citizenfx/fivem/assets/24576130/07b54f77-fb6f-49c4-8d28-bb8dc2ae810c)

In-game UI:
![image](https://github.com/citizenfx/fivem/assets/24576130/4322cfed-2a02-44de-b12c-4134613adaec)

This isn't documented and I don't think this is meant to show to end users. People are also evidently confused about it on the Discord:

![image](https://github.com/citizenfx/fivem/assets/24576130/1391ee2b-5771-4077-9a14-85305bac2883)

### Expected result

This variable to be suppressed from the UI, like other internal variables

### Reproduction steps

1. Launch FiveM.
2. Click on a server in the server list.
3. Note the variable being displayed.

### Importancy

Slight inconvenience

### Area(s)

FiveM, RedM

### Specific version(s)

FiveM Ver.7388/canary

**Comment by LCK-Locke** [comment]
Is there any way to remove it?
Thanks
