### ISSUE TITLE
Could not open resource metadata file - no such file

### ISSUE THREAD

**Issue by ArnoPompio** [citizenfx/fivem#2369]
### What happened?

Hello, I was working on my server on the morning yesterday. Everything was fine. When I got back from work, 8 hours later, I tried to open txadmin but the server apparently crashed. So I tried to restart it, with "screen ./run.sh" (as I am using a VPS and so, putty, I have to do that otherwise It close the server when i close putty). Nothing happened and the server was still off. So I did ./run.sh and it shows me this.

I was in 7290, so I tried to update my apache files, with the 7375 version of fivem, then tried to apt update and upgrade, restarted the vps, but I get the same message. My config.json of txadmin is correct, the paths of serverdata and cfgpath are the right ones.

It's the first time it makes me that in 9 days. Do you have any ideas please ?

(https://github.com/citizenfx/fivem/assets/70692501/9e23072f-0ed6-415e-8052-2e4182b1fae8)
(https://github.com/citizenfx/fivem/assets/70692501/ad5c2ccb-7351-4818-b960-04f6215069e0)
(https://github.com/citizenfx/fivem/assets/70692501/de3e1267-9fde-4bb2-a965-ddc273e92c6f)

### Expected result

Server running

### Reproduction steps

1. Making the server
2. It's working
3. It's suddenly not working anymore
4. Try to restart it
5. Not working
6. Try to update it
7. Still not working

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

FiveM 7375, Ubuntu 22.04 64bit

**Comment by ArnoPompio** [comment]
Wrong run.sh file location, sorry for disturbing.

**Comment by Magnet-js** [comment]
sorry for asking but i got the same problem
how do you fixed this problem ?
