### ISSUE TITLE
Crash during streaming any `sp_manifest.ymt`

### ISSUE THREAD

**Issue by Mycroft-Studios** [citizenfx/fivem#2384]
### What happened?

Updated server to the latest artifacts after 2 weeks of not touching it,
went to load in, and just as the loading screen ends, it crashes with this.
it is not resource specific, i have disabled multiple and each time, it reports a different resource that streams it
![image](https://github.com/citizenfx/fivem/assets/22378232/408560b8-f574-44ae-9850-92e53593854b)

### Expected result

Not crash, and load me into the server

### Reproduction steps

1. find a resource that streams `sp_manifest.ymt`
2. load into server.
3. crash

### Importancy

Crash

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM (prod, beta and canary), FXServer 7436

### Additional information

[CfxCrashDump_2024_02_11_16_59_10.zip](https://github.com/citizenfx/fivem/files/14233240/CfxCrashDump_2024_02_11_16_59_10.zip)

**Comment by Xilophinum** [comment]
This file is normally hard coded to the name of the resource. Meaning you can't change the name of the resource, or it will crash. Im assuming you renamed this mapping resource, which is why this is happening. I recommend renaming the resource back to what it was originally, that should fix your issue.

**Comment by Mycroft-Studios** [comment]
> Im assuming you renamed this mapping resource, which is why this is happening. I recommend renaming the resource back to what it was originally, that should fix your issue.
i didnt rename anything, and it was working perfectly fine 2 weeks ago when i was last on my last :)

**Comment by gottfriedleibniz** [comment]
From this dump, it *seems* like the `CScenarioPointRegionDef` associated with  `compcache:/fiv3devs_bahamamamas/del_perro_shops.ymt` cannot be found. Corrupted scenario override somewhere?

**Comment by Mycroft-Studios** [comment]
It seems that somehow, despite 0 file changes being made and the server not even being online, a single sp_manifest file managed to get currupted, aswell as some of the cache files.
thanks to @gottfriedleibniz managed to find the cause :)
