### ISSUE TITLE
FiveM Client can't load Keymaster Scripts anymore.

### ISSUE THREAD

**Issue by oxince** [citizenfx/fivem#2391]
### What happened?

Keymaster Scripts are not loading anymore. This is a common issue, not only for a single Server (check cfx discord).

Following Error comes:
```
Error parsing script @.../file.lua in resource ...: @.../file.lua: bad binary format (forbidden)
```

### Expected result

/

### Reproduction steps

/

### Importancy

Crash

### Area(s)

FiveM, RedM

### Specific version(s)

Newest Client

**Comment by gottfriedleibniz** [comment]
Things should be fixed!
