### ISSUE TITLE
REDM not comsumable.

### ISSUE THREAD

**Issue by terryterry231** [citizenfx/fivem#2398]
### What happened?

hello i just downloaded a redm server from CFX and also one directly from Vorp and on both of them  i cant consume the food.  i am new to this and have looked for a few days at several files and i can not figure out why  the food is not consumable and how to make it consumable.   Keep in mind this id fresh download from vorp and CFX  and you can not eat the food  you spwan in with or buy form the market.   i have not added anything to it yet because of the food not being consumable.   I am thank ful fo any help.

### Expected result

consumed the food

### Reproduction steps

double click on the food in your inventory to eat it.
nothing happens.

### Importancy

Unknown

### Area(s)

RedM

### Specific version(s)

redm 1491

**Comment by outsider31000** [comment]
you need to go to vorp discord, this isnt the place.

**Comment by Disquse** [comment]
Not a RedM issue.
