### ISSUE TITLE
LocalPlayer.Character.Task.ClearAllImmediately() teleport the player into the ocean and die

### ISSUE THREAD

**Issue by Quandissimo** [citizenfx/fivem#24]
Any call to the LocalPlayer.Character.Task.ClearAllImmediately() or TaskSequence.AddTask.ClearAllImmediately() will teleport the player into the ocean, it happen only from the most recent client patch (June 7th, 2017)

**Comment by blattersturm** [comment]
This was caused by https://github.com/citizenfx/fivem/commit/e3b10ed28e85a6bd579bb65c0f7d3b85e78d92ec (which fixes the bug that made this code not work), and fixed in https://github.com/citizenfx/fivem/commit/cd546d28cef913419d8567bd02cc76b628c588f7 already.
