### ISSUE TITLE
GetIsTaskActive does not recognize CTaskCombatRoll

### ISSUE THREAD

**Issue by ook3D** [citizenfx/fivem#2401]
### What happened?

im trying to make a simple script to check if / when a player has combat rolled, and the GetIsTaskActive native seems to work for other index values, such as aiming on foot (index 4), but doesnt seem to work with index 3.

simple test script i used:

```
Citizen.CreateThread(function()
    while true do
        local LocalPlayerPed = GetPlayerPed(-1)
        local CombatRoll = GetIsTaskActive(LocalPlayerPed, 3)
        
        if CombatRoll then
            print("Player is combat rolling")
        else
            print("Player is not combat rolling")
        end
        
        Citizen.Wait(100)
    end
end)
```

### Expected result

returned true

### Reproduction steps

GetIsTaskActive(LocalPlayerPed, 3)

index 3 returns false even when the player IS combat rolling.

### Importancy

Slight inconvenience

### Area(s)

FiveM, Natives, ScRT: Lua

### Specific version(s)

FiveM/2802/Windows

**Comment by gottfriedleibniz** [comment]
From my understanding much of `CTaskCombatRoll` was deprecated/changed from IV to V and this a remnant of that. Supporting this for V will require something similar to the `CTaskMotionTennis` natives (i.e., checking that specific task-tree)

**Comment by ook3D** [comment]
thanks you guys!
