### ISSUE TITLE
Could not load TLS DLL/CoreRT.dll when debugging/release

### ISSUE THREAD

**Issue by hunga516** [citizenfx/fivem#2402]
### What happened?

i start to rebuild launcher fivem
i have install step by step on Doc code base
when i run debug/release on VS2019 and have bug

### Expected result

i dont think

### Reproduction steps

...

### Importancy

There's a workaround

### Area(s)

FiveM

### Specific version(s)

fivem rebuild

**Comment by tens0rfl0w** [comment]
So you didn't run the `fxd build` command. Explains why it doesn't work then.

**Comment by hunga516** [comment]
> So you didn't run the `fxd build` command. Explains why it doesn't work then.

Where i can run fxd build, is this the last command

**Comment by tens0rfl0w** [comment]
I would recommend actually checking the code of a project before trying to build it.

All available fxd commands are included here:
https://github.com/citizenfx/fivem/tree/master/code/tools/fxd
(and there's also the `fxd help` command).

Also, please use the forum, the Discord guild, or maybe the GH discussions page for questions about building/contributing, this is not a "bug". Maybe, this command can be added to the building docs, but IMO someone who wants to build this on their own should also be able to check for available build tools on their own.

**Comment by hunga516** [comment]
> I would recommend actually checking the code of a project before trying to build it.
> 
> All available fxd commands are included here: https://github.com/citizenfx/fivem/tree/master/code/tools/fxd (and there's also the `fxd help` command).
> 
> Also, please use the forum, the Discord guild, or maybe the GH discussions page for questions about building/contributing, this is not a "bug". Maybe, this command can be added to the building docs, but IMO someone who wants to build this on their own should also be able to check for available build tools on their own.

I have check all step by step agian and again, but after 20 times remove five five and 4 times reset Windows, i have same problem(could not load TLS DLL when debug)

**Comment by FabianTerhorst** [comment]
Fee free to reopen if its still a issue.

**Comment by vovanhau123** [comment]
<img width="428" height="241" alt="Image" src="https://github.com/user-attachments/assets/160713a1-af0a-4449-8496-f3651e9b0c17" />


Let me ask the problem of solving the problem of Could not load corert.dll like I have installed and done the right thing.
