### ISSUE TITLE
Exports Bug

### ISSUE THREAD

**Issue by vkatranas** [citizenfx/fivem#2408]
### What happened?

We notice that there is a problem when we call the export with . and no :

### Expected result

I explained them in detail below.

### Reproduction steps

I have this export:
```
exports("test", function(name1, name2)
    print("OK", name1, name2)
end)
```

If I call it in the following way:
`exports.resource.test('test', 'test1')` result `OK test2 nil`
`exports.resource.test('test', 'test1', 'test3')` result `OK test1 test3`

If I call it in the following way:
`exports['resource']:test('test', 'test1')` result is:  `OK test test1`

### Importancy

Slight inconvenience

### Area(s)

FXServer, ScRT: Lua

### Specific version(s)

Linux/7528

**Comment by tens0rfl0w** [comment]
That's because calling an export function with '.' instead of ':' doesn't work in Lua, as invoking this function with '.' misses the 'self' parameter (object reference), which makes the code treat your first given parameter as the object reference.
