### ISSUE TITLE
It is not possible to get players data in the state bag in worlds

### ISSUE THREAD

**Issue by KAKXER** [citizenfx/fivem#2418]
### What happened?

I wrote a squad system where the players who are in the squad should receive each other's data in the state bag, but the problem starts from the point that if the players are in different worlds, they cannot receive the other state bag with the player id

### Expected result

Please open the access to receive player data all over the world...

### Reproduction steps

![image](https://github.com/citizenfx/fivem/assets/89189991/345f6ec5-f4cd-42e7-a278-503c28db47e2)

![image](https://github.com/citizenfx/fivem/assets/89189991/3df6e029-371c-40c2-9bc7-22bbfdebf6f4)

![image](https://github.com/citizenfx/fivem/assets/89189991/c868ae1f-8cf6-4fd0-8b8c-1fa28e07820b)

### Importancy

Slight inconvenience

### Area(s)

FiveM, Natives

### Specific version(s)

FXServer-master SERVER v1.0.0.7277 win32

### Additional information

Server Info:
```
{
    "enhancedHostSupport": true,
    "requestSteamTicket": "on",
    "resources": [
        "hardcap",
        "WarX",
        "yarn",
        "MongoDB",
        "sessionmanager",
        "webpack"
    ],
    "server": "FXServer-master SERVER v1.0.0.7277 win32",
    "vars": {
        "Developers": "FiveStar Development",
        "Discord": "https://discord.5star.codes",
        "Website": "https://5star.codes",
        "gamename": "gta5",
        "locale": "Fa-IR",
        "onesync_enabled": "true",
        "sv_enforceGameBuild": "2944",
        "sv_enhancedHostSupport": "true",
        "sv_lan": "true",
        "sv_maxClients": "5",
        "sv_projectDesc": "Exclusive by FiveStarâ„¢",
        "sv_projectName": "[SV] WarX",
        "sv_pureLevel": "0",
        "sv_scriptHookAllowed": "false",
        "tags": "default, deployer"
    },
    "version": 1787663103
}

**Comment by V3SC** [comment]
That's one of the purposes of Statebag. It only streams data when you are in render distance. Instead of getting the data you want with statebag, you need to do Client -> Server -> Server to all other squad members. I also have a squad system and this is how I do it.
