### ISSUE TITLE
PlaystatsStuntPerformedEventAllowTrigger Native not working

### ISSUE THREAD

**Issue by ArdentLeKhey** [citizenfx/fivem#2454]
### What happened?

Normally, calling PlaystatsStuntPerformedEventAllowTrigger (0x928DBFB892638EF3) Native will allows CEventNetworkStuntPerformed to be triggered but this event is never triggered.
Other events like CEventEntityDamaged are triggered so my code seems to works.

### Expected result

CEventNetworkStuntPerformed triggered

### Reproduction steps

- Add a stunt jump with AddStuntJumpAngled or AddStuntJump  
    Here a stunt jump :  
    {
        Entry = {
            Start = vector3(2.14, 1720.53, 224.36),
            Ending = vector3(14.62, 1712.37, 230.38),
            Radius = 6.00
        },
        Landing = {
            Start = vector3(98.66, 1846.07, 173.67),
            Ending = vector3(41.46, 1758.40, 213.04),
            Radius = 30.00
        },
        CamCoords = vector3(58.20, 1729.60, 228.10),
    }
- Call the Native PlaystatsStuntPerformedEventAllowTrigger
- Add an event handler for 'gameEventTriggered' that print all args of it (and add one for 'CEventNetworkStuntPerformed' to be sure)
- Do the stunt jump
- Nothing is triggered (only CEventEntityDamaged)

### Importancy

Slight inconvenience

### Area(s)

FiveM, Natives

### Specific version(s)

FiveM 7990 (and other versions)

### Additional information

I thing the Native do nothing or the event is not handled correctly

**Comment by tens0rfl0w** [comment]
IIRC, `CEventNetworkStuntPerformed` does not get send when doing any sort of stunt jump. 

Possible stunts that trigger a stats change are:
- wheelie
- stoppie
- flip
- spin
- roll
- hitting a bowling pin
- hitting a football

**Comment by ArdentLeKhey** [comment]
Oh
I thinked it was stunt jump related ^^
I will change the Native PlaystatsStuntPerformedEventAllowTrigger description to add this

Do you know what event will be triggered if i use SetStuntJumpsCanTrigger(true) ?

TY
