### ISSUE TITLE
Alguns amigos foram bandidos sem nenhum motivo aparente

### ISSUE THREAD

**Issue by DemonDiballa** [citizenfx/fivem#2460]
### What happened?

Estávamos a 1 dia de lançar u nosso servidor e simplesmente os 3 principais adms e CEO foram bandidos sem nem um motivo aparente par ban 

### Expected result

Alguma solução 

### Reproduction steps

1.2.

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

Fivem

### Additional information

Poderiam me responder rapidamente  agradeço!!

**Comment by outsider31000** [comment]
Huh, how about you take the effort to translate it?

**Comment by AvarianKnight** [comment]
This isn't the place for this kind of topic.

*Please note that I do not represent Cfx or Rockstar when I say the following*

Cfx isn't very likely to get involved with any server related politics unless the server is breaking the Terms of Service.
