### ISSUE TITLE
KERNELBASE.dll!RaiseException (0x6c) - NUI Crash (White Flash and NUI Elements Disapper) 

### ISSUE THREAD

**Issue by robert4049** [citizenfx/fivem#2478]
### What happened?

While playing the game, you will sporadically experience moments where you see a white flash and all NUI elements disappear from the screen. I've looked at several other FiveM Servers discords to see if other players are reporting this same issue in other servers, and they are. I checked Next Generation, City Life, and Power RP. Along with those, there are mentions of this same issue in the CFX discord along with various vendor discords of people reporting this same issue. 

### Expected result

Should not flash white and crash

### Reproduction steps

I'm unsure of the root cause and am sadly unable to give repro aside from saying to use NUI items. This also seems to be synced with players where multiple players will loose their NUI at the same time. 

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM Windows 7961

### Additional information

[   4226421] [b3095_GTAProce]        CrBrowserMain/ Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'. (:0)
[   4263593] [b3095_DumpServ]                33352/ Process crash captured. Crash dialog content:
[   4263593] [b3095_DumpServ]                33352/ KERNELBASE.dll!RaiseException (0x6c)
[   4263593] [b3095_DumpServ]                33352/ An error at KERNELBASE.dll!RaiseException (0x6c) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
[   4263593] [b3095_DumpServ]                33352/ Stack trace:
[   4263593] [b3095_DumpServ]                33352/   KERNELBASE.dll!RaiseException (0x6c)
[   4263593] [b3095_DumpServ]                33352/   libcef.dll!base::internal::OnNoMemoryInternal (0x2a) (memory.cc:42)
[   4263593] [b3095_DumpServ]                33352/   libcef.dll!base::TerminateBecauseOutOfMemory (0x8) (memory.cc:69)
[   4263609] [b3095_DumpServ]                33352/   libcef.dll!partition_alloc::internal::OnNoMemory (0x14) (oom.cc:19)
[   4263609] [b3095_DumpServ]                33352/   libcef.dll!blink::ReportV8OOMError (0x11b) (v8_initializer.cc:690)
[   4263609] [b3095_DumpServ]                33352/   libcef.dll!v8::Utils::ReportOOMFailure (0x22) (api.cc:355)
[   4263609] [b3095_DumpServ]                33352/   libcef.dll!v8::internal::V8::FatalProcessOutOfMemory (0x355) (api.cc:311)
[   4263609] [b3095_DumpServ]                33352/

**Comment by Bossman02** [comment]
I also had this problem and in my case it was caused by an excess of memory usage of the NUI, which causes it to crash and reboot (which causes the flash and the whole interface to be buggy), it was not my problem, but the system of captures + ocr of the anticheat and it was something that they solved

**Comment by robert4049** [comment]
I found the issue to be caused by a resource called high3dsound

**Comment by jaybird4357** [comment]
> I found the issue to be caused by a resource called high3dsound

Hi, do you know how to fix it? I can't find it anywhere, and i know that's the same issue I have

**Comment by JustD1rk** [comment]
I have the same problem and I'm still trying to solve it. Can you give me some scripts that might be causing the problem so I can identify which one is causing it?
