### ISSUE TITLE
Nitro exhaust backfire on 3095

### ISSUE THREAD

**Issue by CeebDev** [citizenfx/fivem#2482]
### What happened?

On build 2944, backfire nitro exhaust works fine.
On 3095, flames are not showing up

### Expected result

It should display fire on exhausts

Ex: On build 2944

![g3l7r](https://github.com/citizenfx/fivem/assets/11323987/95163e2e-14b7-4b54-bf8f-fcd653d7cf25)

### Reproduction steps

```lua
local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
SetVehicleNitroEnabled(vehicle, true)
SetVehicleBoostActive(vehicle, true)
SetVehicleRocketBoostActive(vehicle, true)
```

### Importancy

Slight inconvenience

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM build 3095

**Comment by PsychoShock** [comment]
Hello,

You neeed to call

```
RequestNamedPtfxAsset('veh_xs_vehicle_mods')
```

**This is not a issue.** I am currently using boost natives on 3095 without any issue. If you want more support, I don't mind helping you in the [CFX Discord](discord.gg/fivem). Note that this is just my personnal experience and do not represent anyone here :)

Thanks
