### ISSUE TITLE
problem with another hack that is crashing the entire server

### ISSUE THREAD

**Issue by Pedro-Lucas14** [citizenfx/fivem#2497]
### What happened?

hacking I don't know what he's doing with this new badge that is taking down all the players on the server

### Expected result

.

### Reproduction steps

.

### Importancy

Crash

### Area(s)

FXServer, FxDK, ScRT: Lua

### Specific version(s)

Server 8085

### Additional information

![WhatsApp Image 2024-05-04 at 22 59 58](https://github.com/citizenfx/fivem/assets/84646506/2b27647d-d170-4058-bde7-b4ea90876131)
![Uplo
[CfxCrashDump_2024_05_05_01_50_29.zip](https://github.com/citizenfx/fivem/files/15211614/CfxCrashDump_2024_05_05_01_50_29.zip)
ading WhatsApp Image 2024-05-04 at 22.50.01.jpeg…]()

**Comment by Pedro-Lucas14** [comment]
![WhatsApp Image 2024-05-04 at 22 50 01](https://github.com/citizenfx/fivem/assets/84646506/97541ed7-3dde-48d2-8a24-e2da247d69b2)
![WhatsApp Image 2024-05-04 at 22 59 58](https://github.com/citizenfx/fivem/assets/84646506/77337d64-1a7d-4aa
[CfxCrashDump_2024_05_05_01_50_29.zip](https://github.com/citizenfx/fivem/files/15211621/CfxCrashDump_2024_05_05_01_50_29.zip)
b-a8f6-66bd8710bf79)

**Comment by Pedro-Lucas14** [comment]
![WhatsApp Image 2024-05-04 at 22 59 58](https://github.com/citizenfx/fivem/assets/84646506/7e05c299-5fb6-4632-b2c0-af2352408abc)

**Comment by Pedro-Lucas14** [comment]
[CfxCrashDump_2024_05_05_01_50_29.zip](https://github.com/citizenfx/fivem/files/15211624/CfxCrashDump_2024_05_05_01_50_29.zip)

**Comment by ook3D** [comment]
you provided barely any info, there is basically no way to solve this issue

**Comment by Pedro-Lucas14** [comment]
I didn't inform you because I don't know what is making this badge different from the other one. I have already blocked the client's entity spwan in bucket 0. I'm already removing the pickups every time I spwan I don't know what he's using in this case.

**Comment by Pedro-Lucas14** [comment]
What I suspect is that he may be using a state to sync that is some code for the player badge, something that would be interesting to have and know what is being executed in the state bag

**Comment by gottfriedleibniz** [comment]
> some code for the player badge

What do you mean by player badge in this instance? Issues like these are a bit difficult to debug with only a minidump. Any additional information here (incl. full dumps) would be great.

**Comment by Pedro-Lucas14** [comment]
one of the dumps I already sent, I talked about the stade, the hacks only badge the players who are in the region that the state takes.

**Comment by Pedro-Lucas14** [comment]
If you have some code to see what is running in the region, that would help fix it.
