### ISSUE TITLE
CanPayGoon() causes a crash

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#2506]
### What happened?

When trying to use / print the CanPayGoon() native, fivem crashes

### Expected result

Throw an error, or disable the use of this native

### Reproduction steps

```lua
RegisterCommand("test", function()
    print(CanPayGoon())
end)
```
then execute this command once you spawned in

### Importancy

Slight inconvenience

### Area(s)

FiveM, Natives

### Specific version(s)

FiveM b3095

### Additional information

This error is thrown in the console right before crashing : `failed LC - c0000005`

**Comment by JajarGaming** [comment]
The function has 4 parameters. It might be related to those not being filled out

![image](https://github.com/citizenfx/fivem/assets/71441748/2ac3a0c4-a6d8-4109-b5ef-c17fd80094ef)

**Comment by JajarGaming** [comment]
I get a different result when running the native with or without any parameters. The native *might* not exist anymore, but that's unlikely. Do you have a crash dump?

![image](https://github.com/citizenfx/fivem/assets/71441748/7ece11f0-61dd-46ef-9c66-9b1d5f8d055b)

**Comment by Mathu-lmn** [comment]
Hmm I just updated to latest artifacts and indeed this crash seems to be fixed ! That's great new and I'll go ahead and close the issue
