### ISSUE TITLE
GetEntityHealth returns different value between server/client

### ISSUE THREAD

**Issue by nullvariable** [citizenfx/fivem#2558]
### What happened?

GetEntityHealth values between client and server do not match expectations

### Expected result

GetEntityHealth would report the same value on the server as the client

### Reproduction steps

on client
```lua
RegisterCommand('high_health', function()
  local ped = PlayerPedId()
  SetPedMaxHealth(ped, 1100)
  ReviveInjuredPed(ped)
  SetEntityHealth(ped, 1100)
  Wait(100)
  print(GetEntityHealth(ped)) -- result: 1100
  print(GetEntityMaxHealth(ped)) -- result: 1100
```
on server
```lua
RegisterCommand('test', function(src)
  local ped = GetPlayerPed(src)
  print(GetEntityHealth(ped)) -- result: 200
  print(GetEntityMaxHealth(ped)) -- result: 200
  print(GetPedMaxHealth(ped)) -- result: 200
  print(GetPlayerMaxHealth(src)) -- result: 1100
  ```
  
Setting values below 200 returns the same value on both client and server.

### Importancy

There's a workaround

### Area(s)

FiveM, RedM, FXServer

### Specific version(s)

FiveM/b3095 - FXServer 8049 win32

### Additional information

with the `GetPlayerMaxHealth` function I somewhat expected a similar function for getting health if the server was going to differ at all.

In examining the CPedHealthDataNode definition, it looks like if the data for maxhealth is 0 it defaults to 200, but this was the only instance I could track down where that value might be coming from.
https://github.com/citizenfx/fivem/blob/0fc6406b3f3c18243761d0d4dfa0fdfd4d0aeed6/code/components/citizen-server-impl/include/state/SyncTrees_Five.h#L2184

I would like to sample the correct value on the server side either via a new `GetPlayerHealth` function, or preferably via the GetEntityHealth function.

**Comment by AvarianKnight** [comment]
Can you verify that the same thing happens for non-player peds?

**Comment by Pedro-Lucas14** [comment]
you can use this Thread to place MaxHealth

CreateThread(function()
	while true do
		local Ped = PlayerPedId()
		if GetEntityMaxHealth(Ped) ~= 401 then
			SetEntityMaxHealth(Ped,401)
			SetPedMaxHealth(Ped,401)
		end
		Wait(1000)
	end
end)

**Comment by nullvariable** [comment]
adding `SetEntityMaxHealth` doesn't seem to change the outcome. Testing on a server spawned ped appears to return the same results where clientside the value of the ped health reports the desired max and full values, but the server side still only reports 200.

server.lua:
```lua
RegisterCommand('create_test_ped', function(src)
    local coords = GetEntityCoords(GetPlayerPed(src)) + vector3(2, 2, 1)
    local ped = CreatePed(4, `s_m_y_cop_01`, coords.x, coords.y, coords.z, 0.0, true, true)
    while not DoesEntityExist(ped) do Wait(0) end
    print(NetworkGetNetworkIdFromEntity(ped))
    print(GetEntityHealth(ped))
    print(GetEntityMaxHealth(ped))
end)

RegisterCommand('report_ped_health', function(_, args)
    local ped = NetworkGetEntityFromNetworkId(tonumber(args[1]))
    print(GetEntityHealth(ped))
    print(GetEntityMaxHealth(ped))
    print(GetPedMaxHealth(ped))
end)
```
client.lua
```lua

RegisterCommand('set_test_ped_health', function(_, args)
    local ped = NetworkGetEntityFromNetworkId(tonumber(args[1]))
    SetPedMaxHealth(ped, 1100)
    SetEntityMaxHealth(ped, 1100)
    ReviveInjuredPed(ped)
    Wait(0)
    SetEntityHealth(ped, 1100)
    print(GetEntityHealth(ped))
    print(GetEntityMaxHealth(ped))
end)
```

results:
```
> create_test_ped
65534
0
0
> report_ped_health 65534
200
200
200
> set_test_ped_health 65534
1100
1100
> report_ped_health 65534
200
200
200
```

**Comment by nullvariable** [comment]
I tested a couple of other things.
using the test ped above, client A sets the higher values, which read back as expected on Client A. But Client B reports the normal 200/200 values while the ped is owned by Client A, regardless if the values are set while client B is present or arrives after.

Client A leaving the area and Client B setting health, Client A returning reports 200/200

Client A and B both report the expected elevated values for their player peds on the clientside in all scenarios though

**Comment by nullvariable** [comment]
That makes sense, and removing the [SET_PED_MAX_HEALTH](https://docs.fivem.net/natives/?_0xF5F6378C4F3419D3) call from my code as well as the examples outlined above creates the desired result for me.

Thanks!
