### ISSUE TITLE
CreateObject() - Created object immediately disappears again

### ISSUE THREAD

**Issue by KRWerk** [citizenfx/fivem#2566]
### What happened?

By using CreateObject() on client the entity spawns and immediately disappears again.

### Expected result

Created object should be persistent

### Reproduction steps

Use this **client-sided** command on an **Onesync Infinity** server.
```
RegisterCommand("createObject", function(source, args, rawCommand)
    local model = GetHashKey("prop_ld_rub_binbag_01")
    local playerPed = GetPlayerPed(PlayerId())
    local playerPos = GetEntityCoords(playerPed)

    CreateThread(function()
        RequestModel(model)
        while not HasModelLoaded(model) do
            Wait(1)
        end

        local object = CreateObject(model, playerPos.x, playerPos.y, playerPos.z, true, true, true)

        if DoesEntityExist(object) then
            print("Object created successfully")
        else
            print("Failed to create object")
            return
        end
    end)

    SetModelAsNoLongerNeeded(model)
end, false)
```

### Importancy

Slight inconvenience

### Area(s)

FiveM, OneSync

### Specific version(s)

FiveM 8052 and FiveM 8216

**Comment by PsychoShock** [comment]
This is not a native issue. Your code is the issue here. Join the [CFX Discord](discord.gg/fivem) to get more help :)

**Comment by DemmyDemon** [comment]
Turns out it was an [entity lockdown](https://docs.fivem.net/natives/?_0xA0F2201F) issue. Suggest this is closed.

**Comment by KRWerk** [comment]
Yep.
