### ISSUE TITLE
Steam Families Beta - Fivem Won't recognize it's opened

### ISSUE THREAD

**Issue by YeteeDev** [citizenfx/fivem#2567]
### What happened?

I've updated my steam client to the Steam Families Beta build.
Now when I go to connect to my FiveM server, it's denied and says "Steam must be running to connect to this server"

Now when I disable the Steam Families Beta build it works, so I'm thinking it's got to be an issue with the new Steam build.

### Expected result

Fivem will allow me to connect to a server, and recognize that steam is running.

### Reproduction steps

1. Change Steam build ( Steam > Settings > Interface > Client Beta Participation > Steam Families Beta)
2. Attempt to connect to a Fivem server that relies on SteamID for player identification.
3. Connection will fail with "Steam must be running in order to connect to this server"

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

Windows

**Comment by gottfriedleibniz** [comment]
Would it be possible to check the beta/unstable branches?
