### ISSUE TITLE
CitizenFX Logfile wrong time

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#2569]
### What happened?

I noticed that the log files name have a 2 hour delay.
I launched FiveM at 14:20 and the file name shows 12:20

### Expected result

The file name shows the correct time of opening FiveM

### Reproduction steps

1. Open FiveM
2. Open your logs folder and notice the 2hr delay

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

FiveM b3095

**Comment by DerDevHD** [comment]
```c++
#pragma once

struct TickCountData
{
	uint64_t tickCount;
	SYSTEMTIME initTime;

	TickCountData()
	{
		tickCount = GetTickCount64();
		GetSystemTime(&initTime);
	}
};
```
https://github.com/citizenfx/fivem/blob/53fd342c5a0ffabb23e4b89763d4966e1e95def7/code/client/launcher/TickCountData.h

The timestamps of the log files are in UTC-Format. See https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtime. I'm sure that UTC was chosen for specific reasons there.

**Comment by FabianTerhorst** [comment]
Closed, because every timestamp in error logs, artifacts, ... is using utc.
