### ISSUE TITLE
Crashing when Loading mounted data files (fivem.exe+1310754)

### ISSUE THREAD

**Issue by NB-FiveM** [citizenfx/fivem#2573]
### What happened?

Upon loading onto the server the game crashes when it hits the process of loading mounted data files right after "Invoking audNorthAudioEngineDLC INIT_SESSION init (18 out of 18)"

![cc1489270d6f659718e7602439de4d0a](https://github.com/citizenfx/fivem/assets/123033914/0662220d-bbe9-4352-adaf-3193ece13bda)

### Expected result

Loading into the server

### Reproduction steps

Added a resource that contained a ytyp and ydr files containing props.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM (Windows) - b2699 / Server (Linux) b8216

### Additional information

I have tried swapping the ytyp file and ydr's with some others thinking maybe it was an issue with the ones I added only to have the same issue. If I remove some larger map addon's such as Gabz or Roxwood by Ambitioneers  the issue stops happening, which had led me to believe this is some sort of data mounting issue or something else. 

I have attached a crash log below
[CfxCrashDump_2024_06_02_14_47_54.zip](https://github.com/user-attachments/files/15527435/CfxCrashDump_2024_06_02_14_47_54.zip)

**Comment by ook3D** [comment]
i dont know the exact issue, but youre crashing during the main systems initialization, so its likely a certain limit or file being mounted causing it like you thought

**Comment by NB-FiveM** [comment]
I assume its a limit with ytyp's or ydr's. I can remove the added resource and it works fine, if I replace it with another it crashes the same way. I can add it back and remove another unrelated resource such as a Gabz map and an example and it will work fine.

**Comment by NB-FiveM** [comment]
Going to go ahead and close this since it is related to newer and more active thread.
https://github.com/citizenfx/fivem/issues/2602
