### ISSUE TITLE
State Bags/Onesync issues/changes in the last 24 hours?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#2585]
### What happened?

After going from 8450 to 8506 it appears something has changed with state bags? But I cannot find any documentation anywhere. It has broken several of our scripts and we are trying to troubleshoot it.

Would anyone happen to know what was changed in the past 24 hours and is it with state bags/onesync? I've been looking through the commits but cannot seem to find anything.

For example when dragging a player and attempting to then undrag them:
```

[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[script:tugamars-poli] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
[script:tugamars-poli] > [global chunk] (TriggerClientEventInternal.lua:3)
[script:tugamars-poli] > [global chunk] (@tugamars-police_tools/main/server/modules/basic/grab.lua:17)
```

Line 17 points to ````TriggerClientEvent('tgm:police-tools:client:undrag:success',towho)```

### Expected result

State Bag issues

### Reproduction steps

Test a handcuffing, or dragging script.
You may handcuff another player, or drag them. But then you cannot uncuff or undrag.
Onesync Infiniti.

### Importancy

Slight inconvenience

### Area(s)

FiveM, OneSync, Natives

### Specific version(s)

FiveM server artifacts 8509 Windows

### Additional information

Other scripts have been affected as well such as one that talks to the MySQL database for player stats. It is known as x-status. This also occurred in the past 24 hours.

**Comment by gottfriedleibniz** [comment]
Thanks for the report. Fix should be merged in the AM.
