### ISSUE TITLE
[MonoV2] deferrals.presentCard in PlayerConnecting event leads to a crash

### ISSUE THREAD

**Issue by Keyinator** [citizenfx/fivem#2593]
### What happened?

The following code:
```cs
[EventHandler("PlayerConnecting")]
private async Coroutine HandleConnecting([Source] Player player, string playerName, dynamic setKickReason, dynamic deferrals) {
  deferrals.defer();
  deferrals.presentCard(AdaptiveCardText, new Action<dynamic, string>((data, rawData) => {
    //Do nothing
  })
}
```
leads to the crash ``* Assertion at sgen-alloc.c:378, condition `*p == NULL' not met``

(An example adaptive card can be obtained from https://adaptivecards.io/designer/ using the content of the card payload editor)

### Expected result

The card should be shown to the client

### Reproduction steps

```cs
[EventHandler("PlayerConnecting")]
private async Coroutine HandleConnecting([Source] Player player, string playerName, dynamic setKickReason, dynamic deferrals) {
  deferrals.defer();
  deferrals.presentCard(AdaptiveCardText, new Action<dynamic, string>((data, rawData) => {
    //Do nothing
  })
}
```

### Importancy

Crash

### Area(s)

FiveM, FXServer, ScRT: C#

### Specific version(s)

Version: FXServer-master v1.0.0.8552 linux with OneSync enabled

**Comment by FabianTerhorst** [comment]
Try again on latest server build.

**Comment by Keyinator** [comment]
> Try again on latest server build.

Fixed 👍🏻
