### ISSUE TITLE
Node.Js exiting (FXServer)

### ISSUE THREAD

**Issue by ahcenezdh** [citizenfx/fivem#2595]
### What happened?

Sometime when running FXServer.exe, on windows i have the following error message (I don't have other FXServer running)
"Node.js exiting (exit code 5800) See console for details"
![image](https://github.com/citizenfx/fivem/assets/40030799/65aa6b1a-8b35-446f-bc8c-253c79446a46)

I'm on windows 11 pro (Version 10.0.22631 Build 22631)
This problem happens since a long long time ( ~ 5 months) it just happen randomly

NodeJS version: 20.13.1

### Expected result

Starting FXServer

### Reproduction steps

It happen randomly so i don't have reproduction steps

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

FXServer Windows

**Comment by kchaney1508** [comment]
Could be a 'ghost' instance of FXServer ~ check your Task Manager running programs.

**Comment by Ezio121** [comment]
You can also try putting 
`netstat -a -n -p tcp -b`
in an elevated cmd and seeing who's bound to the port 40120

**Comment by nihonium-cfx** [comment]
This happens when there's something in your JS scripts that is invoking `process.exit(code)`, expected behaviour.

**Comment by Noname1235** [comment]
> ![Näyttökuva 2024-07-08 155733](https://private-user-images.githubusercontent.com/175020353/346571989-d4e0f8c4-2ab4-49d1-8465-5cdd5c9d13b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzEwOTAsIm5iZiI6MTcyNzI3MDc5MCwicGF0aCI6Ii8xNzUwMjAzNTMvMzQ2NTcxOTg5LWQ0ZTBmOGM0LTJhYjQtNDlkMS04NDY1LTVjZGQ1YzlkMTNiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzI2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWE1MTBhNzNhNTkwMDhkMjY0NDdlMTJkOTFkOGJmNzA5YzM2YzBhYTQyNGVhYWFkZTU1NWEwNzZjYjliMTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NfaRGEie6ij_2jKx0st0aREethsN-iqyPL5Cy2jQ-aA) how i fix this please help me

stupid

**Comment by DaniGP17** [comment]
> ![Näyttökuva 2024-07-08 155733](https://private-user-images.githubusercontent.com/175020353/346571989-d4e0f8c4-2ab4-49d1-8465-5cdd5c9d13b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTAyMjQsIm5iZiI6MTcyNzI4OTkyNCwicGF0aCI6Ii8xNzUwMjAzNTMvMzQ2NTcxOTg5LWQ0ZTBmOGM0LTJhYjQtNDlkMS04NDY1LTVjZGQ1YzlkMTNiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxODQ1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWE1YmI1NmU5OThhMDZhYmJjYWVkOWJhOGIxY2ZhNWQ3NWZlM2YzNGNiYTU3NzVhOTBiY2ExNjM3ZTQ0MDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7lWEuKq7lhGxU-03CMhIjWIois6yHkhEHTBF-tdJLMA) how i fix this please help me

If you read the console you can notice that your path can't contain non-ASCII characters

**Comment by ming949** [comment]
![image](https://github.com/user-attachments/assets/74168658-857c-4d43-b3e3-246c2f7e4b56)
help

**Comment by DaniGP17** [comment]
> ![image](https://private-user-images.githubusercontent.com/186376212/380374581-74168658-857c-4d43-b3e3-246c2f7e4b56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mzk5NjcsIm5iZiI6MTcyOTkzOTY2NywicGF0aCI6Ii8xODYzNzYyMTIvMzgwMzc0NTgxLTc0MTY4NjU4LTg1N2MtNGQ0My1iM2UzLTI0NmMyZjdlNGI1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMDQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2EyZWI0MmViOGU1YzgxZThlNGE2NGU2ZmVhMzQ1MmIxYzkxYTIxOGE1YzlkYTM5MDVmYjgzZmE3ZjE4NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vxQH_uJb85RxV2lRu3lCs5RPRHD8rQYrD0VNhFPs8q4) help

With that screenshot I'm sure someone will give the exact solution

**Comment by BuddahScripts** [comment]
I deleted the playerdb and the player backupdb in txdata/default/data

And it started right up...
