### ISSUE TITLE
Connection to CNL timed out crash

### ISSUE THREAD

**Issue by ook3D** [citizenfx/fivem#2597]
### What happened?

it seems for no apparent reason i keep getting these Connection to CNL timed out errors and my game closes
![image](https://github.com/citizenfx/fivem/assets/47336113/1b881ce8-17d8-451b-95c4-989c385438a2)

### Expected result

Game runs without issue

### Reproduction steps

1. Run FiveM using canary branch
2. Connect to your localhost server
3. just drive around do whatever, and at random you will get this crash

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM/2802/Windows

### Additional information

[CfxCrashDump_2024_06_18_18_29_23.zip](https://github.com/user-attachments/files/15891010/CfxCrashDump_2024_06_18_18_29_23.zip)

**Comment by neptunium-cfx** [comment]
Hi, thanks for reporting - it's known and fix is about to be deployed.

**Comment by ook3D** [comment]
> Hi, thanks for reporting - it's known and fix is about to be deployed.

Ah one step ahead, perfect 👌

**Comment by internalnightt** [comment]
wheres the update? havent been able to play right in 3 months?

**Comment by Tfc538** [comment]
For me it’s fixed

**Comment by internalnightt** [comment]
> For me it’s fixed

how? did you do something?
i still have the issue

**Comment by Tfc538** [comment]
i’ve literally done nothing. And just today i noticed that its not completely fixed as it happened to me again today twice.

**Comment by Tfc538** [comment]
Update: CNL Issue is there again. This time i got banned after having this issue.

**Comment by bocik1** [comment]
Players on my server have this issue

**Comment by maxifaxipaxi-new** [comment]
> Players on my server have this issue

Same here, any fixes?

**Comment by SrDilach** [comment]
same here

**Comment by fsandov** [comment]
ward

**Comment by KoruCL** [comment]
Pep Guardiola

**Comment by Exyztence** [comment]
issue still occurs

**Comment by emilyssillyscripts** [comment]
has occurred a few times now for me, scared to play in fear of being mistakenly banned :(

**Comment by Tfc538** [comment]
@emilyssillyscripts just so you know:

I've actually been banned twice. The first time I commented on here and about one month later I was banned again after having CNL Timeouts
