### ISSUE TITLE
yet another new problem with a hack that is crashing the entire server.

### ISSUE THREAD

**Issue by Pedro-Lucas14** [citizenfx/fivem#2599]
### What happened?

Cheater is teleporting to a random location
on the map and then return to the old coordinate and cheater jumps before hitting everyone..

![crach1](https://github.com/citizenfx/fivem/assets/84646506/f330a0e4-b895-4184-b177-c73390ed08ec)
[CfxCrashDump_2024_06_21_04_31_02.zip](https://github.com/user-attachments/files/15922768/CfxCrashDump_2024_06_21_04_31_02.zip)

### Expected result

.

### Reproduction steps

.

### Importancy

Crash

### Area(s)

FiveM, FXServer, ScRT: Lua

### Specific version(s)

Fivem 3095

**Comment by AvarianKnight** [comment]
> what were you seeing the hack for some reason the tp hack in a random location on the map and return to the location and skip everyone around him badge.

Can you reword this sentence please.

**Comment by slashkeyvalue** [comment]
> > what were you seeing the hack for some reason the tp hack in a random location on the map and return to the location and skip everyone around him badge.
> 
> Can you reword this sentence please.

Cheater goes out of scope and comes into scope again, crashing everyone around them.

**Comment by Pedro-Lucas14** [comment]
send a text that is easier to understand.

**Comment by Pedro-Lucas14** [comment]
@AvarianKnight send a text that is easier to understand.

**Comment by Pedro-Lucas14** [comment]
@gottfriedleibniz Is there any way to get this badge correct?

a video of how they do it :

https://cdn.discordapp.com/attachments/1203257672116338798/1257169286477250671/crach.mp4?ex=66836da2&is=66821c22&hm=b86194be3c28bd61c8a37567d76009a818ebafcfe1a13dffc145f98e5296cf72&

**Comment by Pedro-Lucas14** [comment]
There must be some padao for him every time he teleports and he's close to the water, some coordinates they use: 

3112.47,2916.86,116.66
4144.16,4335.38,7.19
3639.91, 5667.01, 9.2
3432.11,5174.59,41.57

**Comment by slashkeyvalue** [comment]
Just reported a possible repro to prikolium, hopefully they can fix it faster.
