### ISSUE TITLE
Building FXServer

### ISSUE THREAD

**Issue by ahcenezdh** [citizenfx/fivem#2600]
### What happened?

After building and running the solution i have this error when running FXServer.exe

'D:\Source\Repos\ahcenezdh\fivem\code\bin\server\windows\release\citizen\clr2\lib\mono\4.5\v2' in MONO_PATH doesn't exist or has wrong permissions.
Fatal Error: Could not load CitizenFX.Core.dll.

The v2 folder don't exist i followed every steps

### Expected result

Starting FXServer

### Reproduction steps

1. Build fxserver with the basic steps
2. Generate the solution
3. Run FXServer.exe

### Importancy

Slight inconvenience

### Area(s)

FXServer

### Specific version(s)

FXServer

### Additional information

No

**Comment by FabianTerhorst** [comment]
Closed, because no further info was added and build is working fine.

**Comment by ahcenezdh** [comment]
Hello @FabianTerhorst sorry for the late message, but still not working for me

Here is my steps:
git clone https://github.com/ahcenezdh/fivem.git -c core.symlinks=true
cd fivem
git submodule update --jobs=16 --init
pip install setuptools

fxd gen -game server
fxd vs -game server

After the last command my Visual studio is opening, i'm clicking on generate the solution, i don't have compilation errors, and when launching my FXServer (D:\Github\fivem\code\bin\server\windows\debug)

I have: Fatal Error: Could not load CitizenFX.Core.dll

**Comment by FabianTerhorst** [comment]
try to run with release build. also you need to run the prebuild_natives.cmd as well.

**Comment by ahcenezdh** [comment]
> try to run with release build. also you need to run the prebuild_natives.cmd as well.

I'm going to test thanks

**Comment by ahcenezdh** [comment]
![image](https://github.com/citizenfx/fivem/assets/40030799/275acfc9-489c-498f-a6ef-f82ad5c0ed49)


> try to run with release build. also you need to run the prebuild_natives.cmd as well.

Still the same problem

**Comment by ahcenezdh** [comment]
The problem was i didn't download windows 10 sdk on visual studio (thanks @FabianTerhorst)

**Comment by nthdev1110** [comment]
are you still active can you show me the fx server version suitable to run
