### ISSUE TITLE
Mismatched C++/WinRT headers

### ISSUE THREAD

**Issue by rohybnol** [citizenfx/fivem#2604]
### What happened?

Hello, 
I followed the https://github.com/citizenfx/fivem/blob/master/docs/building.md carefully but yet
everything compiles fine until CitiLaunch which has Mismatched C++/WinRT headers
where could be the issue?

### Expected result

CitiLauncher compile successful

### Reproduction steps

https://github.com/citizenfx/fivem/blob/master/docs/building.md 

### Importancy

Unknown

### Area(s)

FXServer

### Specific version(s)

latest

**Comment by FabianTerhorst** [comment]
Which build tools and windows sdk version you have installed?

**Comment by FabianTerhorst** [comment]
Feel free to comment back when you have further questions.
