### ISSUE TITLE
mono_rt2 expired 

### ISSUE THREAD

**Issue by junredzik** [citizenfx/fivem#2608]
### What happened?

mono_rt2 has expired today, u can extend the version

### Expected result

extend 

### Reproduction steps

![M3O8cNVoezlE3V7e2A2u](https://github.com/citizenfx/fivem/assets/87615205/956753f8-5ad9-413b-946d-8c8368e0d05b)

### Importancy

Slight inconvenience

### Area(s)

FiveM, ScRT: C#

### Specific version(s)

FiveM/8695

**Comment by RickyB505** [comment]
@thorium-cfx

**Comment by FabianTerhorst** [comment]
Fixed in #2609
