### ISSUE TITLE
Game Event CEventNetworkPlayerEnteredVehicle Not Triggered in Latest Build (3258)

### ISSUE THREAD

**Issue by BuddiesTV** [citizenfx/fivem#2629]
### What happened?

In game build 3258, the CEventNetworkPlayerEnteredVehicle event from `gameEventTriggered`, which used to trigger as soon as a player enters a vehicle, no longer fires. This event works correctly in earlier game builds, such as 3095.

### Expected result

Event should be triggered

### Reproduction steps

1. Have a resource with this code:
`AddEventHandler("gameEventTriggered", function(event, _)
    print(event)
end)`
2. Enter a vehicle
3. Event `CEventNetworkPlayerEnteredVehicle` isn't triggered

### Importancy

Slight inconvenience

### Area(s)

FiveM, OneSync

### Specific version(s)

FiveM: 8867/Canary

**Comment by CritteRo** [comment]
event `CEventNetworkPlayerActivatedSpecialAbility` seem to reliably trigger instead of player entered vehicle.

Also related to game events, `CEventNetworkPlayerSpecialAbilityFailedActivation` seem to trigger 2-4 times when the client is loaded on the server.

**Comment by BuddiesTV** [comment]
Seems to got fixed by [this commit](https://github.com/citizenfx/fivem/commit/39e1a834064779263f527b4e2ce4b243fcf5b398), thanks for the quick response.
