### ISSUE TITLE
Server playerJoining event can't work TriggerClientEvent with source  server artifacts 8733 and above

### ISSUE THREAD

**Issue by MisakiVanilla** [citizenfx/fivem#2635]
### What happened?

It seems that from 8733, when using TriggerClientEvent to trigger an event on the source client in the server's playerJoining event, it does not execute.

![image](https://github.com/citizenfx/fivem/assets/95254902/51fbc044-0785-4b0c-8e57-4f44807c376d)

```
8883 X
8859 X
8823 X
8733 X
8695 O
8552 O
8214 O
```
artifacts 8695, 8552, 8214  is work
artifacts 8733 , 8823 , 8859 , 8883 is not work

## Test Code is here
[testcode.zip](https://github.com/user-attachments/files/16178955/testcode.zip)

Registered suggestions not showing up while joining a server player event

### Expected result

Suggestions are displayed in chat

### Reproduction steps

1. download 8733 - 8883
https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

2 remove dir alpine

3 tar --no-same-owner -xvf fx.tar.xz && rm fx.tar.xz

4 ensure testcode
## Test Code is here
[testcode.zip](https://github.com/user-attachments/files/16178955/testcode.zip)

5. restart

### Importancy

There's a workaround

### Area(s)

FiveM, FXServer

### Specific version(s)

Server 8733 - 8883 Linux

## 4 different ways to solve this problem.

1. Use fx: 8695

2. Set playerId to -1 in TriggerClientEvent in playerJoining, which is sent to all users, but for some reason it works even when there is only one player

3. Execute addSuggestion in the client-side script

4. Wait for new updates for FXServer

**Comment by FabianTerhorst** [comment]
Hi, thanks for reporting. This is fixed with the latest build.

**Comment by MisakiVanilla** [comment]
thank you FabianTerhorst :D

**Comment by MisakiVanilla** [comment]
yay it's work 8903

**Comment by FabianTerhorst** [comment]
Thanks for testing.
