### ISSUE TITLE
Vehicles Despawning Even While Driven - NET ID issues/OneSync issues? NETWORK_GET_ENTITY_FROM_NETWORK_ID

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#2654]
### What happened?

We have an issue with networked objects, especially vehicles. NET ID issue perhaps?

A player will spawn a vehicle using the menu (vMenu or other menu via client side), the error in yellow shows, vehicle saves to cache as you see, then randomly despawns after some random amount of time, even when someone is driving it or standing beside it. Then this warning shows yet again when it despawns.

`NETWORK_GET_ENTITY_FROM_NETWORK_ID: no such entity`

![image](https://github.com/user-attachments/assets/ca9390fd-7847-47b6-806c-724b3c9a7806)

We have been turning off all of our scripts trying to figure out of one of them is the culprit with no luck. It has been happening for weeks. I have been searching every old post I can possibly find online about similar problems which have existed for some people some years back but nothing conclusive.

Could this be related to this? https://github.com/citizenfx/fivem/commit/5b62f20d0bc9c278c1f878edade7360e6effc737 

Any ideas? Or easy way to check how many net id's are currently in use and what is creating them if possible? Maybe its an issue suddenly with max NET ID in use? This starts happening whether there are 30 people on the server or 100 it really doesn't seem to make a difference in that regard. However, it does seem to happen more often when there are more networked objects or vehicles around.

Happens on production, beta and canary at this time.

### Expected result

Vehicles should remain persistent? Or at least not despawn when someone is driving them.

### Reproduction steps

1. Running latest artifacts. Windows. tx: v7.2.2 | fx: b8981 | b3905. Onesync Infinity.
2. Spawning add on vehicles with vMenu or other menu on client side such as Badger Vehicle Spawner or other. You can see one of the functions for spawning vehicles here from Badger https://github.com/ChonkyBadger/Vehicle-Spawner/blob/master/Client/Main.cs 
3. Vehicle will spawn, can drive for a while but then will simply despawn on you. Sometimes every single vehicle you spawn will despawn.
4. Attempt to exacerbate this for testing purposes by spawning tons of networked objects perhaps or some other NET ID test.

### Importancy

Unknown

### Area(s)

FiveM, FXServer, OneSync

### Specific version(s)

FXServer Artifacts 8981 | FiveM canary 8981 or production or beta, Game Build 3905, Onesync Infinity. Windows Server 2022.

### Additional information

We are losing our minds trying to figure this out. Please help! It started a few weeks back unfortunately we cannot pinpoint the exact artifacts version when it happens as reports by players were sporadic.

I also noticed someone opened this 2 weeks ago about the same symptom however their spawn method is different than ours is so I'm not certain if its the same thing. https://github.com/citizenfx/fivem/issues/2623

**Comment by UnityRPDevs** [comment]
I can confirm this bug, i've this like for months!

**Comment by Legacy-TacticalGamingInteractive** [comment]
> I can confirm this bug, i've this like for months!

Whats your server artifacts and game build

**Comment by UnityRPDevs** [comment]
> > I can confirm this bug, i've this like for months!
> 
> Whats your server artifacts and game build

Artifacts 7290 - Game Build 3095.

**Comment by Legacy-TacticalGamingInteractive** [comment]
@UnityRPDevs did it fix itself or still happening?

**Comment by Legacy-TacticalGamingInteractive** [comment]
Seems to have fixed itself. Who knows.
