### ISSUE TITLE
Server is loading or failed to load - Cloudflare URL

### ISSUE THREAD

**Issue by bencoletr** [citizenfx/fivem#2655]
### What happened?

We have created an SRV record for our server, which I have confirmed works. I am able to successfully load into the server using connect in the F8 console with the domain but I am being presented with this error [Ref Image]

We are currently using default port [30120].

Endpoints are appropriately defined in the server.cfg with port 30120 for TCP and UDP.

Inbound and outbound ports are defined for 30120 UDP and TCP in Firewall on host.

The connection is established, but something different is displayed.

Server is also showing offline (when it is online) in previously connected server when re-opening Fivem.

Is there anything I could be missing here?

### Expected result

It connects to the server regularly without the "error" or the extra, nor appearing offline in your last played due to the port being added.

### Reproduction steps

We followed many community guides to try and make this work, but kept getting the same results.
connect play.domain.com connects to "https://play.domain.com:30120/"
Server is loading or failed to load is presented when connected, The connection is established, but something different is displayed.

### Importancy

There's a workaround

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM/ Latest Recommended Build: 7290

### Additional information

![image](https://github.com/user-attachments/assets/8ba0169f-c5fb-4642-a5ba-f589ad7f7c77)

connect play.domain.com connects to "https://play.domain.com:30120/"
Server is loading or failed to load is presented when connected, The connection is established, but something different is displayed.

Not entirely sure what we might need to do to change this, or if it's just a bug at the moment.

**Comment by Morji789** [comment]
@bencoletr How Did you fixed this?
