### ISSUE TITLE
come see the truth

### ISSUE THREAD

**Issue by Johnny456654** [citizenfx/fivem#2668]
### Segment

devtools

### Importancy

Unclear or unintuitive

### Improvement request

https://github.com/citizenfx/fivem/issues/2667
the post is right yall are dumb
stop being ignorant
its just dumb that it is an option
that's it. 

### Area(s)

FiveM
RedM
and all your dumbass games

### Additional information

morons

**Comment by kchaney1508** [comment]
i see the truth right here
![image](https://github.com/user-attachments/assets/eea7c0cc-65e1-4cb8-b54d-7763669fc7c3)

**Comment by DemmyDemon** [comment]
Kifflom, brother.

**Comment by matehun00** [comment]
Thank you for enlightening us on the truth

**Comment by matehun00** [comment]
> ### Area(s)
> FiveM

You forgot to add RedM there

**Comment by Johnny456654** [comment]
nah

**Comment by Johnny456654** [comment]
that is lame 
fuck yall thinking you know shit bunch of ignorant idiots
