### ISSUE TITLE
Native Crash When Server Reaches 850 Players

### ISSUE THREAD

**Issue by usershhh** [citizenfx/fivem#2671]
### What happened?

It's been over 3 months since my server crashed around 850 for Native Crash Reporting and displays no Stacktrace.
![Capture d’écran 2024-07-25 234354](https://github.com/user-attachments/assets/33f60fdd-5c1b-40bf-a097-62946a5d7c01)

I've tried changing the artifact several times (7290, 8965, 9073) and nothing changes, I've also tried removing all the statebags from my server, deactivating all the objects, removing the anticheat but nothing does. 

ProcDump : https://gofile.io/d/rLUesU
Crash Dump (Artefact) : https://gofile.io/d/hJpPOy

### Expected result

The server should at least display Stacktrace and not crash.

### Reproduction steps

The crash happens as soon as I reach 850 players or so. 

### Importancy

Crash

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM, Server 9073, Windows

**Comment by Mathu-lmn** [comment]
![image](https://github.com/user-attachments/assets/203dcb15-4d68-4b65-895a-f4c8e551b48e)

Here is the stack trace text in the procdump

**Comment by usershhh** [comment]
New procdump : https://gofile.io/d/8XwUUz

**Comment by ChaiyaZ-Dev** [comment]
I would like to know the specifications of the server you are using. I suspect it might be a server-related issue. Specifically, what RAM bus speed are you using?
