### ISSUE TITLE
Native GetVehiclePedIsIn seems to doesn't work correct on GameBuild 3258

### ISSUE THREAD

**Issue by Zjarany-Ksiezyc** [citizenfx/fivem#2690]
### What happened?

regardless of the situation, GetVehiclePedIsIn on the server side always returns 0

### Expected result

it should return the vehicle ID if it is present in one

### Reproduction steps

just put it in server side lua file

```
RegisterCommand('getvehicle', function(src)
    print('current vehicle',  GetVehiclePedIsIn(GetPlayerPed(src), false))
end, false)
```

### Importancy

Crash

### Area(s)

Natives

### Specific version(s)

Fivem 9164/beta, Server b8780 Windows Server 2022

### Additional information

in "lastVehicle mode" it seems to return always 0 as well

**Comment by ahcenezdh** [comment]
Works fine for me on FXServer-master SERVER v1.0.0.8903 win32

**Comment by ahcenezdh** [comment]
```lua
RegisterCommand("test", function(source, args)
    local playerPed = GetPlayerPed(source)
    if not DoesEntityExist(playerPed) then return end

    local veh = GetVehiclePedIsIn(playerPed, false)
    print(veh, DoesEntityExist(veh))
end, false)
```

**Comment by ahcenezdh** [comment]
And the the lastVehicle argument is working for me too, check if your ped exist

**Comment by Zjarany-Ksiezyc** [comment]
I tested it now on b9235 and everything works, so there was no issue. only the old build had a problem

**Comment by ahcenezdh** [comment]
> I tested it now on b9235 and everything works, so there was no issue. only the old build had a problem

Nice then, you can close the issue
