### ISSUE TITLE
Native issue with Weather?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#2711]
### What happened?

![image](https://github.com/user-attachments/assets/dfe6e30c-d530-4e71-9aee-c8ad3221a3e6)

Entire server crashed when we turned on "Xmas Snow" setting in vMenu. Have to say its the first time we've ever seen the weather cause crashes.

Has this native been changed recently?

tx: v7.2.2 | fx: b9424
vMenu

Oh?
![image](https://github.com/user-attachments/assets/fc42a8cb-56c7-4cab-8fa6-95b6d5fea2a3)

### Expected result

To be able to load "Xmas Snow" weather setting.

### Reproduction steps

1. Set Xmas Snow weather in vMenu v3.6.3

### Importancy

Slight inconvenience

### Area(s)

FiveM, FXServer, OneSync, Natives

### Specific version(s)

FiveM Server Artifacts 9424

**Comment by ook3D** [comment]
> not fix i perm cresh xmas.... whyne what a bulid version my last bulid server test 3407

i have no clue what you are trying to say here

**Comment by CoreBitX** [comment]
> > not fix i perm cresh xmas.... whyne what a bulid version my last bulid server test 3407
> 
> i have no clue what you are trying to say here

man junge halt deine scheiß fresse zich 1000x andere haben es aber!
