### ISSUE TITLE
Adhesive.dll!CreateComponent crash

### ISSUE THREAD

**Issue by AcedaIcon** [citizenfx/fivem#2712]
### What happened?

i keep receiving this same crash code every time i try to connect to a server in FiveM. I have uninstalled and reinstalled the FiveM client twice and still keep receiving the same error. It always goes completely through the process however as soon as it attempts to connect to the server it gives me the 3 failed attempts to connect message and then crashes and this is what appears on screen. 
![Screenshot 2024-08-14 193940](https://github.com/user-attachments/assets/12345f14-c03e-4eb5-bf48-710bedf386b4)

### Expected result

it should have connected to the server 

### Reproduction steps

1. i erased all the caches
2. uninstalled the FiveM client
3. Reinstalled the FiveM client
4. Repeat 

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM canary server: Power

**Comment by neptunium-cfx** [comment]
Closing as non actionable - no crash dump or repro.
