### ISSUE TITLE
Weapon file data mounting does not work in RedM.

### ISSUE THREAD

**Issue by Kianimal** [citizenfx/fivem#2718]
### What happened?

I have exported/extracted weaponcomponents.meta via OpenIV and via CodeX.

I have also extracted pbrweaponsurfaces.ymt via the same methods.

If you in any way try to alter (or not alter) and reintroduce these files back into the game via streaming or data_file import, it will either do nothing or crash to desktop.

Most of the weapon mounting methods fail to do anything with either of these files (presumably this is intended as the filetype is intended for a specific process, not to be jammed in anywhere a weapon data file mounting takes place). Some of them supposedly load the files and then nothing is changed. In particular, though, I would think that `WEAPONCOMPONENTSINFO_FILE`/`CWeaponComponentDataFileMounter` would be used to load weaponcomponents.meta - this will result in a crash to desktop no matter the method of extraction or the content of the file.

### Expected result

The files should load correctly with their new values applied correctly.

### Reproduction steps

1. Extract any weaponcomponents.meta file via any method of your choice.
2. Change nothing in this extracted file.
3. Attempt to load it via data_file loading in an fxmanifest in any resource as a `WEAPONCOMPONENTSINFO_FILE`
4. The game will crash to desktop 100% of the time.

### Importancy

Unknown

### Area(s)

RedM

### Specific version(s)

RedM v.7290

### Additional information

Error code is **RAGE error: 0x9A076438:335**:

```
[    204062] [b1491_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    204062] [b1491_GTAProce]             MainThrd/ loading WEAPONCOMPONENTSINFO_FILE resources:/BGS_Gunsmith/files/weaponcomponents.meta.
[    204062] [b1491_GTAProce]             MainThrd/ Error: RAGE error: 0x9A076438:335
[    207328] [b1491_DumpServ]                16352/ Process crash captured. Crash dialog content:
[    207328] [b1491_DumpServ]                16352/ RAGE error: 0x9A076438:335
[    207328] [b1491_DumpServ]                16352/  
```

I can provide a crash dump if that would be helpful.

**Comment by outsider31000** [comment]
Share the script too including the fxmanifest.lua

**Comment by outsider31000** [comment]
```file 'weaponcomponent_custom.meta'
data_file 'WEAPONCOMPONENTSINFO_FILE' 'weaponcomponent_custom.meta'```
Did you used it this way ?

**Comment by Kianimal** [comment]
I did not add the `file` initially and forgot to document that part - adding the file results in a different error:

![image](https://github.com/user-attachments/assets/5be56a3b-4250-480c-a504-3fcff76e28e9)

fxmanifest.lua:
```
fx_version "cerulean"
lua54 "yes"

games { "rdr3" }

rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'

client_scripts {
  'client/client.lua',
  'client/dataview.lua',
}

server_scripts {
  'server/server.lua'
}

shared_scripts {
  'config.lua',
}

files {
  'stream/pbrweaponsurfaces.ymt',
  'files/weaponcomponents.meta',
}

data_file 'WEAPONINFO_FILE_PATCH' 'stream/pbrweaponsurfaces.ymt'
data_file 'WEAPONCOMPONENTSINFO_FILE' 'files/weaponcomponents.meta'
```

**Comment by outsider31000** [comment]
Remove the .ymt

**Comment by Kianimal** [comment]
That is not the file that is triggering the error, but okay i'll try.

**Comment by outsider31000** [comment]
Don't think you can stream that ymt

**Comment by Kianimal** [comment]
OKAY, so streaming it as the full file always gives the pool size error. However, removing all of the entries but one of them DOES allow the file to load!

![image](https://github.com/user-attachments/assets/7716b67a-43ff-42bb-a60b-4edbfd8a1e88)

Not sure if it has actually done anything, will continue to investigate.

**Comment by Kianimal** [comment]
Also if we can't stream the surfaces file then that means the best that can come of this is modified weapon stats for attachments, which is cool but not exactly what i was going for with this lol

**Comment by Kianimal** [comment]
![image](https://github.com/user-attachments/assets/08a3eb98-d079-4d0a-b481-ca80b246c109)

lol it works!

You're a boss, outsider, much appreciated!

**Comment by outsider31000** [comment]
Np. What did you change?

**Comment by outsider31000** [comment]
Also you can close the issue if you're good.

**Comment by Kianimal** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<CWeaponComponentInfoBlob>
  <Data>
  </Data>
  <Infos>
    <Item type="CWeaponComponentDecorationInfo">
      <Name>COMPONENT_LONGARM_BARREL_MATERIAL_3</Name>
      <Section>Barrel</Section>
      <Type>BaseMaterial</Type>
      <Data type="CWeaponDecorationDataString">
        <Value>Weapon_Enamel_Red</Value>
      </Data>
    </Item>
  </Infos>
  <Engravings>
  </Engravings>
  <InfoBlobName>Core Game</InfoBlobName>
</CWeaponComponentInfoBlob>
```

This is the entire weaponcomponents.meta file that's being streamed.

If I can figure out how to stream that ymt file then I can REALLY do some damage...

Yeah I'll close it up, thanks again.
