### ISSUE TITLE
Ultrawide minimap position is wrong

### ISSUE THREAD

**Issue by Paneedah** [citizenfx/fivem#2719]
### What happened?

Using the default GTAV minimap when using FiveM and an ultrawide monitor results in the map to not go to the bottom-right corner as expected.

For example:

![screenshot-min](https://github.com/user-attachments/assets/601c84f9-8a02-496f-9b8b-dab561e6a088)

As you can see, the minimap is still in the center(ish) of the screen as if it was following a 16:9 aspect ratio.
We have verified that the screen safe-zone is setup correctly and that this does not happen in default GTAV.

This happens with every player who uses an ultra-wide as far as I can see.

### Expected result

The minimap to go to the corner of the screen the same as it does with normal GTAV.

### Reproduction steps

Enable the Minimap, use an ultra-wide monitor, boom.

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

FiveM 9479/beta

**Comment by ahcenezdh** [comment]
Hello did you tried on a empty server?

**Comment by Paneedah** [comment]
Yes I did also try it on an empty server. I just happen to have taken the screenshot on the main server that I'm developing. Seems to happen everywhere.
