### ISSUE TITLE
MainThrd/ tryHostState changing from 5 to 6

### ISSUE THREAD

**Issue by Kevin-key4197** [citizenfx/fivem#2720]
### What happened?

trying to local host a server and it keeps getting stuck on this part 

[     92985] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x5542d14f INIT_SESSION init (9 out of 19)
[     93000] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking CDLCScript INIT_SESSION init (10 out of 19)
[     93000] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking audNorthAudioEngineDLC INIT_SESSION init (11 out of 19)
[     93016] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x44712871 INIT_SESSION init (12 out of 19)
[     93016] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x29122e3b INIT_SESSION init (13 out of 19)
[     93282] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking fwClipSetManager INIT_SESSION init (14 out of 19)
[     93782] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x4d71ca64 INIT_SESSION init (15 out of 19)
[     93782] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0xb45956dd INIT_SESSION init (16 out of 19)
[     93782] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x336e8884 INIT_SESSION init (17 out of 19)
[     93782] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0xe782a671 INIT_SESSION init (18 out of 19)
[     93828] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Invoking 0x914c56a9 INIT_SESSION init (19 out of 19)
[     93828] [b1436_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[     93828] [b1436_GTAProce]             MainThrd/ loading CFX_PSEUDO_ENTRY RELOAD_MAP_STORE.
[     93828] [b1436_GTAProce]             MainThrd/ done loading RELOAD_MAP_STORE in data file mounter 0x7fff449d9b90.
[     93828] [b1436_GTAProce]             MainThrd/ Performing deferred RELOAD_MAP_STORE.
[     94219] [b1436_GTAProce]                12392/ ResourceCache::AddEntry: Saved cache:v1:708d30590560e2e9a9053d5c63d2e7d5c4c49468 to the index cache.
[     94453] [b1436_GTAProce]             MainThrd/ rage::gameSkeleton::RunInitFunctions: Done running INIT_SESSION init functions!
[     94453] [b1436_GTAProce]             MainThrd/ tryHostState changing from 0 to 1
[     94500] [b1436_GTAProce]             MainThrd/ tryHostState changing from 1 to 2
[     94516] [b1436_GTAProce]             MainThrd/ tryHostState changing from 2 to 3
[     94641] [b1436_GTAProce]             MainThrd/ tryHostState changing from 3 to 4
[     95078] [b1436_GTAProce]     RageNetTcpWorker/ ugc body: ticket=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh&contentType=rdr2playlist&queryName=GetContentByCategory&queryParams=%7blang%3a%5b%27en%27%2c%27fr%27%2c%27de%27%2c%27it%27%2c%27es%27%2c%27pt%27%2c%27pl%27%2c%27ru%27%2c%27es-mx%27%5d%2ccategory%3a%22story%22%2csortby%3a%22createddate%22%7d&offset=0&count=500
[     95985] [b1436_GTAProce]     RageNetTcpWorker/ returning title promotions for ticket=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh
[     96766] [b1436_GTAProce]             MainThrd/ tryHostState changing from 4 to 5
[     96797] [b1436_GTAProce]             MainThrd/ tryHostState changing from 5 to 6

### Expected result

the server should have opened 

### Reproduction steps

Followed this link https://www.youtube.com/watch?v=1vLxrbgdV_Y&t=1s and that's it 

### Importancy

Slight inconvenience

### Area(s)

RedM

### Specific version(s)

Redm build

**Comment by outsider31000** [comment]
I still havent figured why this happens as well, many users have it, I once had it too, the only fix was to use another vps.
did you manage to fix yours @Kevin-key4197 ?

**Comment by outsider31000** [comment]
okay actually the fix is to set in txAdmin onsesync infinity in the settings then restart server @Kevin-key4197
