### ISSUE TITLE
data_file 'WEAPON_METADATA_FILE' not working - REDM

### ISSUE THREAD

**Issue by SireVLC** [citizenfx/fivem#2723]
### What happened?

Trying to load weapons.ymts through 'WEAPON_METADATA_FILE' but it's displaying an error everytime in the user's console :
`failed loading resources:/sirevlc_commands/stream/weapons in data file mounter 0x14343dc70 `

When trying others data file like 
```
WEAPONINFO_FILE 
WEAPONINFO_MP_PATCH_FILE 
WEAPONCOMPONENTSINFO_FILE
WEAPON_METADATA_FILE 
WEAPON_ANIMATIONS_FILE 
WEAPONINFO_FILE_PATCH 
WEAPON_HOLDING_ANIMATIONS_FILE 
```

These load properly and don't display any error message but they have no effect for the ymt I'm trying to use. My goal is to slow down reload animations by 
changing the value at `AnimReloadRate`. 

When trying to load that same ymt through a story mode loader like lml it works.

### Expected result

weapons.ymt properly loading using 'WEAPON_METADATA_FILE'

### Reproduction steps

1. Place an edited or not weapons.ymt (can be weapons.ymt itself or any other like weapon_pistol_m1899 etc...)  in a stream folder 

2. Load that stream folder using the following loading method in the manifest : 

```
files {
  'stream/weapons.ymt',
}

data_file 'WEAPON_METADATA_FILE' 'stream/weapons.ymt'
```

3. Restart the resource while in game it will display the error 

### Importancy

Slight inconvenience

### Area(s)

RedM

### Specific version(s)

RedM v.7290

**Comment by draobrehtom** [comment]
Reload animations can be slowed down, take a look on this example:
https://github.com/draobrehtom/redm-custom-mauser

**Comment by SireVLC** [comment]
> Reload animations can be slowed down, take a look on this example: https://github.com/draobrehtom/redm-custom-mauser

Thanks I've been looking for something like this for ages ! I'll take a look. Now the issue I'm facing still should be clarified since is it because it should be another data file used for weapons ymts in general or 'WEAPON_METADATA_FILE' itself can't be used ?

**Comment by draobrehtom** [comment]
> > Reload animations can be slowed down, take a look on this example: https://github.com/draobrehtom/redm-custom-mauser
> 
> Thanks I've been looking for something like this for ages ! I'll take a look. Now the issue I'm facing still should be clarified since is it because it should be another data file used for weapons ymts in general or 'WEAPON_METADATA_FILE' itself can't be used ?

Looks like Rockstar in their updates for RDO don't use WEAPON_METADATA_FILE and use instead WEAPONINFO_FILE_PATCH. For example, weapon_repeater_evans_mp.ymt.

**Comment by SireVLC** [comment]
Oh that explains it then, thanks I'll close that issue

**Comment by Kianimal** [comment]
> > > Reload animations can be slowed down, take a look on this example: https://github.com/draobrehtom/redm-custom-mauser
> > 
> > 
> > Thanks I've been looking for something like this for ages ! I'll take a look. Now the issue I'm facing still should be clarified since is it because it should be another data file used for weapons ymts in general or 'WEAPON_METADATA_FILE' itself can't be used ?
> 
> Looks like Rockstar in their updates for RDO don't use WEAPON_METADATA_FILE and use instead WEAPONINFO_FILE_PATCH. For example, **weapon_repeater_evans_mp.meta**.

@draobrehtom how did you find this info out? Trying to figure out how to restream pbrweaponsurfaces.ymt and I've been unable to get anywhere, so far, but there are two files in the code, one in the update directory, so I think there is some way to update the file.

Don't want you to have to do the work for me but if you could just point me in the right direction I'd appreciate it!

**Comment by draobrehtom** [comment]
@Kianimal 

For example, search in game files for `weapon_revolver_navy` which is strictly RDO weapon, you can see next results (I use CodeX):

![image](https://github.com/user-attachments/assets/7b36973a-e623-41bc-9057-f13b41c66f68)

Also using Tools Binary Search, bunch of files to look into:
<details>
CodeX Search Results for "WEAPON_REVOLVER_NAVY"
[File path], [Byte offset]
update_1.rpf\common\data\damage\default_damage_modifiers.meta, 42431
update_1.rpf\common\data\damage\default_damage_modifiers.meta, 42471
update_1.rpf\common\data\damage\default_damage_modifiers.meta, 43349
update_1.rpf\common\data\damage\default_damage_modifiers.meta, 43389
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 7218
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 7492
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 7766
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 8040
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 8478
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 8758
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 9038
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 9318
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 9599
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 9880
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 10161
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 10442
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 10761
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 11044
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 11327
update_1.rpf\pack_patch\mp006\common\data\ai\weaponcomponents.meta, 11610
update_1.rpf\common\data\progression\compendium_mp.meta, 316253
update_1.rpf\common\data\progression\compendium_mp.meta, 316414
update_1.rpf\common\data\progression\compendium_mp.meta, 316535
update_1.rpf\common\data\progression\compendium_mp.meta, 316848
update_1.rpf\common\data\progression\compendium_mp.meta, 316967
update_1.rpf\common\data\progression\compendium_mp.meta, 317138
update_1.rpf\common\data\progression\compendium_mp.meta, 317269
update_1.rpf\common\data\progression\compendium_mp.meta, 317602
update_1.rpf\common\data\progression\compendium_mp.meta, 353285
update_1.rpf\pack_patch\mp006\content.xml, 1375
update_1.rpf\pack_patch\mp006\content.xml, 1833
update_1.rpf\pack_patch\mp006\content.xml, 39376
update_1.rpf\pack_patch\mp006\content.xml, 39707
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weapon_revolver_navy_mp.meta, 110
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weapon_revolver_navy_mp.meta, 1125
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 2660
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 3647
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 3849
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 4846
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6123
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6171
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6224
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6357
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6415
x64\dlcpacks\mp006\dlc.rpf\common\data\pickups.meta, 6478
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectitems.ymt, 291
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectitems.ymt, 493
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 6881
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 16424
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 17843
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 19984
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 20311
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 20620
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 20932
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 21242
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 21564
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 21887
x64\dlcpacks\mp006\dlc.rpf\common\packs\base\data\ai\weaponanimations.meta, 22206
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 6719
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 6993
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 7267
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 7541
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 7979
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 8259
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 8539
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 8819
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 9100
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 9381
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 9662
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 9943
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 10262
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 10545
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 10828
x64\dlcpacks\mp006\dlc.rpf\common\data\ai\weaponcomponents.meta, 11111
x64\dlcpacks\mp006\dlc.rpf\content.xml, 1375
x64\dlcpacks\mp006\dlc.rpf\content.xml, 1833
x64\dlcpacks\mp006\dlc.rpf\content.xml, 38945
x64\dlcpacks\mp006\dlc.rpf\content.xml, 39276
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 143
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 328
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 526
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 669
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 868
x64\dlcpacks\mp006\dlc.rpf\x64\data\ai\quickselectslots.ymt, 1011
</details>

I also check for content.xml to see what '[data file mounter](https://github.com/draobrehtom/redm-data-file-mounters)' is used, for example:

![image](https://github.com/user-attachments/assets/f5480f1d-55c3-4353-837b-7b0b15228096)

Based on that, there is no WEAPON_METADATA_FILE usage found so far. However WEAPONINFO_FILE is used for weapon_revolver_navy and WEAPONINFO_MP_PATCH_FILE is used for weapon_revolver_navy_mp. I guess, that weapon_revolver_navy can be a base weapon where all main settings are defined, and weapon_revolver_navy_mp use it as base with some 'patched' settings for multiplayer.

**Comment by draobrehtom** [comment]
@Kianimal regarding pbrweaponsurfaces.ymt I failed to stream it in game. The only result I get is to manually place it into RedM folder:

**Comment by Kianimal** [comment]
@draobrehtom I've also been unable to get it to stream, couldn't find it anywhere in any context file either =/

Nice that you can place it in there and do it, though! That's sick. Will test that out and give it a shot.

Thanks for the replies also! I appreciate the hints =)

**Comment by Kianimal** [comment]
![image](https://github.com/user-attachments/assets/0fdc6477-3237-415d-b064-f985b30ee549)

My dream, a reality.

You're a G dude, much appreciated.

**Comment by outsider31000** [comment]
> My dream, a reality.

That only works for your client.

Every player would have to do the same to work for them to.
