### ISSUE TITLE
Animation Sync

### ISSUE THREAD

**Issue by arlofonseca** [citizenfx/fivem#2725]
### What happened?

This issue was initially reported with build `2944`, and it seems to have resurfaced in game build `3258`. The mouth voice sync is no longer functioning properly. You can refer to the previous issue here: https://github.com/citizenfx/fivem/issues/2192. The issue was also previously resolved in this commit: https://github.com/citizenfx/fivem/commit/1a952424cb5d461cbc0e77650e2ce8543589c264.

### Expected result

The mouth movement isn't syncing correctly—you can't see your own mouth moving, though you might see others' mouths move. In some cases, you don't see others' mouth movements at all.

### Reproduction steps

N/A

### Importancy

There's a workaround

### Area(s)

FiveM

### Specific version(s)

N/A

### Additional information

Server Artifacts: 9481 (Windows)
Game Build: 3258 (Bottom Dollar Bounties)
Game Version: 9479 (Beta)

**Comment by Mathu-lmn** [comment]
Hi, can you open a bugreport on the forums please ?

**Comment by prikolium-cfx** [comment]
Hi. Thanks for your report. Fixed in 8d9f38031ba5c96119f5d29bae44f183a9132f11

**Comment by alberttheprince** [comment]
> Hi. Thanks for your report. Fixed in [8d9f380](https://github.com/citizenfx/fivem/commit/8d9f38031ba5c96119f5d29bae44f183a9132f11)

This doesn't seem to be fixed as of the most recent build.
