### ISSUE TITLE
ForceSnowPass native crashes the client

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#2736]
### What happened?

I've tried using the native : `ForceSnowPass(true)` on the client and my game crashed : 
![image](https://github.com/user-attachments/assets/4cd720db-5a69-4846-a01a-78ebbfc1c5d7)

### Expected result

Don't crash

### Reproduction steps

1. `ensure runcode`
2. `ForceSnowPass(true)`
3. Crash

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

Latest client and artifacts

**Comment by ahcenezdh** [comment]
https://forum.cfx.re/t/forcesnowpass-true-crashes-clients/5257135

**Comment by Mathu-lmn** [comment]
Fixed in 0df3d8841ff7c466686f9798454b703cc6987d05
