### ISSUE TITLE
Mumble voip crackling with poor computer hardware

### ISSUE THREAD

**Issue by Identity-labs** [citizenfx/fivem#2742]
### What happened?

RedM players with poor computer having their own voice crackling for other players
This happening when GPU/CPU usage is at 100%.

### Expected result

Clean voice

### Reproduction steps

Just having worst computer ever on earth and other players will not able to understand what you say.

### Importancy

Slight inconvenience

### Area(s)

RedM

### Specific version(s)

Redm latest

### Additional information

All mode have been tested, native, 2d, 3d ect ... 

No solution at all for them expect lowering down all graphics settings, but is not enough.

**May be increasing thread priority of mumble can solve the issue ?**

**Comment by outsider31000** [comment]
I don't think it has to do with PC specs. This happens to all players after a certain time. In a server I am in it happens after 4/6 hours with more than 60/100 people in it.
Some server owners say it helps hosting mumble in another server. But with my tests it didn't.

**Comment by Identity-labs** [comment]
With 250+ players and mumble hosted on external server, we don't have any issue after few hours, only people with low hardware have issue. the only way for them is to lower down graphics settings and kill every programs in background.

**Comment by Ktos93** [comment]
We can try add something like this and check on canary if this fix issue for low end PCs
![image](https://github.com/user-attachments/assets/e6e60b41-cc23-4609-9d74-c4767d00c2eb)
