### ISSUE TITLE
ERR_MEM_MULTIALLOC_FREE Error GTA5_b3095.exe!sub_141306B24 (0x4d)

### ISSUE THREAD

**Issue by xrtw** [citizenfx/fivem#2746]
### What happened?

Please tell me how to know what this could lead to the crash?
![image](https://github.com/user-attachments/assets/6a39a548-283a-4120-9562-325445707849)

### Expected result

I need answers :D

### Reproduction steps

Tried to make full dump (size 2gb) and put in WinDBG but after -v analyze I can tell nothing... Did not see any tutorial how to read crash correctly

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

b9552

**Comment by DurtyFree** [comment]
Hi @xrtw I'll most likely have the answer to your issue here #2760 

Feel free to add any details if it makes sense
