### ISSUE TITLE
ScaleformStore Pool Full - Value Increase?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#2762]
### What happened?

![image](https://github.com/user-attachments/assets/1a16e6fd-cbb2-49bf-a478-800462184c57)

When installing a popular large map mod known as Roxwood. This occurs to every client due to its additional .gfx files used for its minimap.

Would it be possible for an increase of this value to compensate?

### Expected result

To be able to load in with the additional scaleforms from Roxwood.

### Reproduction steps

1. Check amount of .gfx files for example that are streaming on server.
2. Adjust to 80+ files if you have some to test with. Problem will occur for every client.
3. May not just be exclusive to Roxwood.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM tx: v7.2.2 | fx: b9655 | Game Build 3258

**Comment by AvarianKnight** [comment]
This was fixed with the recent pool additions

See: https://github.com/citizenfx/fivem-docs/pull/481
