### ISSUE TITLE
RedM Pool Size Error

### ISSUE THREAD

**Issue by Masterspooni** [citizenfx/fivem#2772]
### What happened?

Hello, right now we get many Information´s People having this Pool Size Error in the F8 Consol.

The error persists the whole time until you restart the game.

[5190985] [b1491_GTAProce]             MainThrd/ Error: 0x6db663ab Pool Full, Size == 400

in the gameconfig.xml
this Pool size.

PoolName: ItemSet
PoolSize value="400"

Can you please set it Higher like 800.

Greats. 

### Expected result

no message in the F8

### Reproduction steps

The Pool Size Happen if you Spawn Objects in a script.

### Importancy

Crash

### Area(s)

RedM

### Specific version(s)

RedM Last Version

### Additional information

Can you please set it Higher like 800.

**Comment by outsider31000** [comment]
yeah, the issue isnt the pool being smaller but how item sets are being handled.
