### ISSUE TITLE
CEventNetworkEntityDamage : Not Triggered or wrong data returned - 3258

### ISSUE THREAD

**Issue by Derass239** [citizenfx/fivem#2779]
### What happened?

In game build **3258** the **CEventNetworkEntityDamage** was not trigger when player take damage from falling before another else damage (like rammed by car)
After that, the "weapon" report by the event is always "**weapon_run_over_by_car**" and not "**weapon_fall**"

On previous build **3095**, the event was directly trigger on fall with the correct "weapon".

### Expected result

Triggered with good data

### Reproduction steps

Artifact : **8851**
Fivem : Ver. **9672/beta** and **9671**

1. Create resource with this code
```LUA
AddEventHandler('gameEventTriggered', function(event, data)
    if event == 'CEventNetworkEntityDamage' then
        local weapon = tonumber(data[7])
        print(weapon)
    end
end)
```
------------
2. On build 3095
3. Take damage from fall 
4. print => -842959696  💹 
------------
5. On Build **3258**
6. Take damage from fall  => Not triggered
7. Take damage from car => Triggered  => print **-1569615261 or -1553120962** 
8. Take damage from fall => Trigger => print **-1553120962** 🟥 

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

Build 3258

### Additional information

I saw a [commit](https://github.com/citizenfx/fivem/commit/39e1a834064779263f527b4e2ce4b243fcf5b398) that should fix the bugs on gameEvent but from my tests there is still a problem

**Comment by Mathu-lmn** [comment]
It works if the fall is fatal. But I can confirm that it won't if the fall is just dealing non fatal damages.
In b2802 the even is triggered multiple times upon player damage after falling

**Comment by Derass239** [comment]
Still bugged on
- Fivem Version 10907
- Artifact : 10573
