### ISSUE TITLE
b9823 : Serialization of the server object id response failed

### ISSUE THREAD

**Issue by serge-golovanow** [citizenfx/fivem#2782]
### What happened?

When some player connects to my server (b9823, onesync legacy), I have an `Serialization of the server object id response failed` error in server log, players crashes with `GTA5_b3258.exe!sub_143E3DE42 (0x9a)` error.

### Expected result

no crash..

### Reproduction steps

Upgrade server to b9823
Let some players connect.. Don't know yet if stable/beta/canary matters
See lot of them crash

### Importancy

Crash

### Area(s)

FiveM, FXServer

### Specific version(s)

server 9823

**Comment by Mathu-lmn** [comment]
Hi, can you send your server.cfg file (remove the license key / db credentials !) ?

**Comment by Mathu-lmn** [comment]
Also would be useful to get a crash dump from one of the players crashing

**Comment by Mathu-lmn** [comment]
[CfxCrashDump_2024_09_10_20_43_17.zip](https://github.com/user-attachments/files/16951344/CfxCrashDump_2024_09_10_20_43_17.zip)
Crashdump from the server

**Comment by GrandpaRex** [comment]
Had the same issue with 9868 here is the server.cfg and a crash dump
[servercfg.txt](https://github.com/user-attachments/files/16972829/servercfg.txt)
[CfxCrashDump_2024_09_12_03_03_44.zip](https://github.com/user-attachments/files/16972830/CfxCrashDump_2024_09_12_03_03_44.zip)

**Comment by FabianTerhorst** [comment]
Your config does not contain any relevant onesync settings. I assume you are setting them at startup in the command line.

**Comment by GrandpaRex** [comment]
Yes I forgot about that but it is through txadmin and it is Legacy not Infinity

**Comment by FabianTerhorst** [comment]
Thanks alot for creating the issue, this seems to be fixed with the latest server build.
