### ISSUE TITLE
Consider reverting 'ui_updateChannel' ScriptAPI restriction

### ISSUE THREAD

**Issue by KillStr3aK** [citizenfx/fivem#2790]
### What happened?

I believe it should be pretty handy to know what version the players enter the server with as many crashes are caused because they are playing on unstable and its not something on our side. A previous issue seems to be fixed by switching to 'unstable' however we are unable to tell how much player is still playing on other versions

we have our own crash statistics with pretty much every info we need, except this one and I don't really understand the decision making this convar unreadable by the script API. I understand that some people misused it, but I believe that's their issue? I know that this is my issue aswell, however I don't really see any reasonable logic behind [this](https://github.com/citizenfx/fivem/blob/master/code/components/glue/src/ConnectToNative.cpp#L999)

Thanks in advance.

### Expected result

`ui_updateChannel` should be readable by script API

### Reproduction steps

GetConvar("ui_updateChannel");

### Importancy

Slight inconvenience

### Area(s)

ScRT: Lua, ScRT: C#, ScRT: JS

### Specific version(s)

FiveM, RedM, FXServer 8733 >=

**Comment by Mathu-lmn** [comment]
Hi, this was removed because of abusive kick for canary users as mentionned [here](https://forum.cfx.re/t/get-clients-update-channel/2366157)

**Comment by KillStr3aK** [comment]
> Hi, this was removed because of abusive kick for canary users as mentionned [here](https://forum.cfx.re/t/get-clients-update-channel/2366157)

I've seen some references about this but I still don't really consider this as a logic decision? If server owners don't want canary users in their server, then let them kick them? Why should it be restricted? If it has to be, then maybe restrict those servers (like blacklist), not the whole API that many others rely on?

**Comment by william-des** [comment]
Alternatively, providing a way to know the version used by a client only when a it's disconnected for a crash (knowing whether they are using mods or not would be very useful as well)

**Comment by AvarianKnight** [comment]
> I've seen some references about this but I still don't really consider this as a logic decision? If server owners don't want canary users in their server, then let them kick them?

Canary is how Cfx is able to tell when regressions happen, servers being able to kick players for using canary could lead to regressions going unnoticed so this isn't a viable solution in my opinion.

> Why should it be restricted?

If something is getting abused in this way its been common place to *not* allow it to be abused, as previously mentioned people running canary are pivotal in finding regressions.

> If it has to be, then maybe restrict those servers (like blacklist), not the whole API that many others rely on?

This isn't a viable solution, there is 28,000 servers, trying to figure out which servers are abusing public apis would be impossible.

**Comment by KillStr3aK** [comment]
> Alternatively, providing a way to know the version used by a client only when a it's disconnected for a crash (knowing whether they are using mods or not would be very useful as well)

This would be enough indeed.

> Canary is how Cfx is able to tell when regressions happen, servers being able to kick players for using canary could lead to regressions going unnoticed so this isn't a viable solution in my opinion.

I agree. I believe there has to be an ideal solution for this

> If something is getting abused in this way its been common place to _not_ allow it to be abused, as previously mentioned people running canary are pivotal in finding regressions.

✅

> This isn't a viable solution, there is 28,000 servers, trying to figure out which servers are abusing public apis would be impossible.

But restricting all of them is also not viable

**Comment by KillStr3aK** [comment]
> There is a good reason why this was blocked: https://forum.cfx.re/t/5025093
> 
> However, you are still able to retrieve the build number of the client with `navigator.userAgent` in a NUI context, which would give you something like:
> 
> > ... CitizenFX/1.0.0.**10048** ...
> 
> Considering that knowing the build number of the client is more productive and not that easy to abuse for weird "anti-cheat" measurements, I don't think this should get reverted.

This is pretty fine for me, thanks for more context.

**Comment by FabianTerhorst** [comment]
> There is a good reason why this was blocked: https://forum.cfx.re/t/5025093
> 
> 
> 
> However, you are still able to retrieve the build number of the client with `navigator.userAgent` in a NUI context, which would give you something like:
> 
> > ... CitizenFX/1.0.0.**10048** ...
> 
> 
> 
> Considering that knowing the build number of the client is more productive and not that easy to abuse for weird "anti-cheat" measurements, I don't think this should get reverted.
> 
> 
> 
> 

Thanks for the info. Might makes sense to hide the version info from the user agent.

**Comment by TickerDev** [comment]
I still see no harm in exposing that to the scripts.
Servers want to more effectively stop cheaters since the cheats usually will not work on canary / beta versions.
If a centralized anti-cheat isn't implemented, let the servers worry about the security of their server.

**Comment by AvarianKnight** [comment]
That's exactly why it's blocked.

Forcing players to play on unstable versions isn't something Cfx wants since these versions are meant to be used to test changes for any breakages, and despite what one might believe, adding a bunch of people who are notoriously bad at providing information on how crashes happen doesn't help.

**Comment by TickerDev** [comment]
Nice to see you still are updated here :)

Well, I can argue that the game is full of cheaters, and that there is no way against them.
Servers can introduce algorithms that will check on the version and other stats and come up with a conclusion.
Canary is still the best way to prevent cheaters on your server, and if CFX or R* or whoever won't come up with a better anti cheat solution then they should at least provide us with the best way to mitigate it, even if it is a bit hacky.

**Comment by ToffyMTA** [comment]
This is (and always was) the worst way to "block" cheaters.. there will be always software which will eventually start supporting canary / latest versions and in fact, many cheats already support this today.

**Comment by V3SC** [comment]
> Nice to see you still are updated here :)
> 
> Well, I can argue that the game is full of cheaters, and that there is no way against them. Servers can introduce algorithms that will check on the version and other stats and come up with a conclusion. Canary is still the best way to prevent cheaters on your server, and if CFX or R* or whoever won't come up with a better anti cheat solution then they should at least provide us with the best way to mitigate it, even if it is a bit hacky.

When many servers start using this method, cheats will also adapt to it and be set up to work in Canary. One reason cheats didn't work in Canary was adhesive updates, and no updates have been made in the last 1 year, meaning there is currently no reason for cheats not to work in Canary. Instead, we should wait for an adhesive update, Unfortunately, this doesn't seem very likely either. Because right now, no one on the team is explaining why there hasn't been an update for Adhesive. Currently, the only way to fight cheaters is to buy all the cheats and fix their features. However, cheats now automatically ban you when you play on 0-player servers or localhost.


#MAKE_FIVEM_BETTER_AGAIN

**Comment by TickerDev** [comment]
> > Nice to see you still are updated here :)
> > 
> > Well, I can argue that the game is full of cheaters, and that there is no way against them. Servers can introduce algorithms that will check on the version and other stats and come up with a conclusion. Canary is still the best way to prevent cheaters on your server, and if CFX or R* or whoever won't come up with a better anti cheat solution then they should at least provide us with the best way to mitigate it, even if it is a bit hacky.
> 
> When many servers start using this method, cheats will also adapt to it and be set up to work in Canary. One reason cheats didn't work in Canary was adhesive updates, and no updates have been made in the last 1 year, meaning there is currently no reason for cheats not to work in Canary. Instead, we should wait for an adhesive update, Unfortunately, this doesn't seem very likely either. Because right now, no one on the team is explaining why there hasn't been an update for Adhesive. Currently, the only way to fight cheaters is to buy all the cheats and fix their features. However, cheats now automatically ban you when you play on 0-player servers or localhost.
> 
> 
> #MAKE_FIVEM_BETTER_AGAIN 

Cheats like spawning objects etc is not the problem those are simple to patch on our side, stuff like aimbot / silent aimbot is the problem and there is nothing we can do about it.

This is the most reliable way to combat the issue.

**Comment by ook3D** [comment]
> 
> This is the most reliable way to combat the issue.

But this isnt actually combating anything, its a temporary "fix" until cheat providers start supporting experimental fivem versions making the problem essentially worse.
