### ISSUE TITLE
Crash with lemon-jig-oxygen when loading some MLO's - 100% of the time.

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [citizenfx/fivem#2805]
### What happened?

![image](https://github.com/user-attachments/assets/25d2f23d-6912-4555-99cd-f4a0f39087e9)

Several MLO's lately, as of around 3-4 weeks ago have been causing this crash soon as players get close to it. 100% of the time they will crash. This is currently happening with at least 3 so far that I've tested.

I've checked for conflicting props. I've checked for flag issues on the props. I've checked LOD distances and recalculated extents. I've been trying to figure it out for several days of dissecting these interiors by these mappers with no luck.

These USED to load just fine. But now no matter what I do they will not load without causing a crash. They actually load on the screen then there is a hang for a second then client crashes.

The only thing I see between them all is that they have over 500 props called from the .ytyp in the MLO interior. These are not all custom props mind you, they are mostly vanilla props. Not to be confused with bbmax bbmin of custom archetypes added to ytyp that are in some of them of course.

This crash log takes me to:

```
static void WrapStreamingLoad(strStreamingModule* strModule, uint32_t index, void* data, void* a4)
{
    uint32_t moduleBase = strModule->baseIdx;
    g_currentStreamingName = streaming::GetStreamingNameForIndex(moduleBase + index);
    g_currentStreamingIndex = moduleBase + index;

    ((decltype(&WrapStreamingLoad))g_currentStreamingModuleCallback)(strModule, index, data, a4);
    g_currentStreamingName = "";
    g_currentStreamingIndex = 0;
}
```

```
        // invoke original thread start
        return meta.origRoutine(meta.originalData);   ---- and here
        
        }, parameter, dwCreationFlags, lpThreadId);
```

I have tried to contact the original mappers to see if they might know more but they have no info to offer. Since this crash is fairly recent. Perhaps someone know if something has changed wtih MLO prop limits maybe or something like that.

### Expected result

To be able to render interiors without crashing.

### Reproduction steps

1. Perhaps try interiors with 800+ MLO props.
2. dip_ pawnshop is one to try by Dipzy
3. ab45's majesty mansion is another

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM build 3258 | tx: v7.2.2 | fx: b9956

### Additional information

At my wits end on this one. If anyone can give any input that would be great. Thank you.

**Comment by ook3D** [comment]
the 2 functions at the top of the stack trace are 
EBStatic::PlaceDrawableIndirectArgs(0x21)
rage::fwDrawableStore::PlaceResource(0xd2)
![image](https://github.com/user-attachments/assets/34bc13b2-43ff-4f2c-a2dc-05df3510a3e5)
it seems you are crashing here.

**Comment by ook3D** [comment]
after checking what those qwords are, it seems something to do with grass batches / instances. 
![image](https://github.com/user-attachments/assets/04ae2852-1b9e-42e6-add7-d1f406031b78)

**Comment by Legacy-TacticalGamingInteractive** [comment]
> after checking what those qwords are, it seems something to do with grass batches / instances. ![image](https://private-user-images.githubusercontent.com/47336113/369669838-04ae2852-1b9e-42e6-add7-d1f406031b78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTQ1MTEsIm5iZiI6MTcyNjk5NDIxMSwicGF0aCI6Ii80NzMzNjExMy8zNjk2Njk4MzgtMDRhZTI4NTItMWI5ZS00MmU2LWFkZDctZDFmNDA2MDMxYjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA4MzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzJmMTZjNDk4ZTRkODExNzhjZjJkNTY3M2RmNzc3YTBjMzBhNmJlMzM1NDZmZDg4N2NmNzZhNWE3MDIxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7TymEFRVT0Kp1LyTHMgTz0i29dadnZ0QlOln4La6GUY)

its strange because there are no grass batches in these or instances and ive even been looking across entire server for duplicate named files conflicting with nothing found

**Comment by Legacy-TacticalGamingInteractive** [comment]
Resolved. I cannot explain why - but for some reason this can be fixed by resizing the bounding box on the MLO and recalculating extents again. Even though they were already calculated by the original mappers and worked fine a few weeks ago. Make it make sense. I never touched these interiors at all. They just suddenly broke and started causing issues. Pure fluke that I figured it out.

**Comment by petike062909** [comment]
Hi, my question is, does any of these files sound familiar: 
rc12b_destroyed.ymap
rc12b_hospitalinterior.ymap
v_40_details2.ydr
v_40_details3.ydr
v_40_doorfr3.ydr
v_40_hospbumpers2.ydr
v_40_hospital.ydr
v_40_hospital_txd.ytd
v_40_hospseating1.ydr
v_40_lights2.ydr
v_40_lights3.ydr
v_40_oldlights.ydr
v_40_roomlights.ydr
v_40_sidedr.ydr
v_40overlay1.ydr
v_hospital.ybn
v_int_40.ytyp

I'm just asking because I had the same problem. And when I removed this folder, the error went away.

**Comment by Legacy-TacticalGamingInteractive** [comment]
For me it was completely different interiors than that one. Which looks to be pillbox or something.
