### ISSUE TITLE
The issue of the number of people in a given area

### ISSUE THREAD

**Issue by R1chter-x** [citizenfx/fivem#2808]
### What happened?

Hello,

In today's FiveM, the number of players on the servers is not 64 - 128. It is much more and much more crowded. Many more scripts, maps, tools, etc. are available. The only problem with this great progress is that we still have problems with more than 128 people in a certain area. There is no way to bring more players together in a certain area. The only way to solve this problem permanently is for the FiveM team to step in.

Thanks for your help in advance.

### Expected result

More than 128 more players in one field

### Reproduction steps

This may not be the only problem with your server.
Crowded servers need to be meticulous and highly optimized.

Simple examples;
Analyze all ytds on your server and apply fixes and mitigations.
Try optimizing products with high polygon and pixel counts.

Despite your efforts, you can support me if you are experiencing situations such as all characters disappearing, textures deteriorating, etc. in a concert event on your roleplay server.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM 9902 | DLC 3258

### Additional information

I hope this request will be granted.
For more crowded and fun days.

**Comment by yannbcf** [comment]
This limitation is due to the game engine, you should be able to render 128 vehicles and 128 peds at once, this 256 limitation is a safety guard so the rendering do not have undefined behaviors such as falling through the ground, which can be experienced above those defined boundaries

**Comment by HuseyinCecen** [comment]
> This limitation is due to the game engine, you should be able to render 128 vehicles and 128 peds (including yourself) at once, this 256 limitation is a safety guard so the rendering do not have undefined behaviors such as falling through the ground, which can be experienced above those defined boundaries

Is there any way to overcome the 128 limits offered by the game engine?

**Comment by ook3D** [comment]
> Is there any way to overcome the 128 limits offered by the game engine?

No, without a memory patch implemented into fivem, such hardcoded limit can't be changed

**Comment by ahcenezdh** [comment]
Even if the limit is bypassed, this is a problem with Rage, those limits are here for a reason

**Comment by d22tny** [comment]
Still, 32 on RedM is very low.

**Comment by R1chter-x** [comment]
Of course, there is a reason for these limits, but systems and computer components have also improved a lot. The old limits are not so necessary nowadays. We need more than 128 now. And I believe those limits can be overcome.

**Comment by ook3D** [comment]
> Of course, there is a reason for these limits, but systems and computer components have also improved a lot. The old limits are not so necessary nowadays. We need more than 128 now. And I believe those limits can be overcome.

That's not how it works, the game engine is not designed to handle higher limits, there's a reason for the limits

**Comment by R1chter-x** [comment]
Okay, I got it. Everything is as I expected, thank you.
