### ISSUE TITLE
Serialization of ID packet failed. Issue to report them

### ISSUE THREAD

**Issue by d22tny** [citizenfx/fivem#2812]
### What happened?

As it was stated in the commit, an issue should be opened to report the packet serialization failure. What else can i provide to help investigating ?

![image](https://github.com/user-attachments/assets/b3efe18b-1e04-4b18-a877-ebb544aedb1c)

### Expected result

-

### Reproduction steps

No idea what triggered the warning initially

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

FiveM b3095

### Additional information

Waiting on further intstructions in order to help with this matter.

**Comment by d22tny** [comment]
![image](https://github.com/user-attachments/assets/e5d1f38a-7fac-426a-b766-55e4ebcd8273)
Just found another one, i went in a crowded area, the police was fighting a gang they were about 100 + people in the zone.

**Comment by d22tny** [comment]
And right after some seconds, another two popped out, with the same packet number:

![image](https://github.com/user-attachments/assets/4a78a1bc-b8de-41fe-9746-7d0ecd52c7d6)

**Comment by d22tny** [comment]
It seems to be spamming that same packet

![image](https://github.com/user-attachments/assets/5e4f9b0c-cdeb-4961-a775-21b2bc6ddb6f)

**Comment by d22tny** [comment]
I can confirm that all the players are getting the same warning, with the same packet number.

**Comment by Thunderwolfx** [comment]
We're getting the same with the same number.

**Comment by tomson701** [comment]
Same

**Comment by FabianTerhorst** [comment]
Could you try it on the latest canary build again and check for more error logs that happen at the same time?

**Comment by d22tny** [comment]
Sure, we'll be monitoring today and come back with a report.

**Comment by d22tny** [comment]
Did some monitoring today and it seems that everything is clean. @FabianTerhorst.

The monitoring was done on a full server ( 1124/1124 players online ) travelling around all the map.

**Comment by FabianTerhorst** [comment]
> Did some monitoring today and it seems that everything is clean. @FabianTerhorst.
> 
> The monitoring was done on a full server ( 1124/1124 players online ) travelling around all the map.

Thanks for reporting the issue and testing the fix. Will close the issue now. Feel free to reopen in case it happens again.
