### ISSUE TITLE
Large events not being executed on canary

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/fivem#2813]
Large events are not received at all

**Comment by Thunderwolfx** [comment]
+1 with client events with large arguments not being executed

**Comment by manzarek123** [comment]
Updating the issue, it was just linked to large events not being executed
Its seems that the limit is now event smaller since last commit

**Comment by BennoArnautovic** [comment]
Same issue here, on Canary, I cannot for example send offline players or vehicles since it sends large amount of data in event. If this was intended, this is really breaking 90% of resources. It is NOT good change!

**Comment by AvarianKnight** [comment]
There was already a push fixed for this, see [here](https://github.com/citizenfx/fivem/commit/1bd895de05f22a543d310ae19b2e02481b51bc78)

**Comment by manzarek123** [comment]
> There was already a push fixed for this, see [here](https://github.com/citizenfx/fivem/commit/1bd895de05f22a543d310ae19b2e02481b51bc78)

As I said, the fix lowered the limit and made it way worst

Repro:

```
RegisterCommand('testevent', function(source, args, raw)
    local data = {}
    for i=1, 50000 do
        data[#data+1] = math.random(999999)
    end
    TriggerClientEvent('first', source, data)
end)

RegisterNetEvent('first')
AddEventHandler('first', function(data)
    print("first")
end)
```

**Comment by outsider31000** [comment]
Seems like changing to release fixes it. So it's canary issue.

**Comment by BennoArnautovic** [comment]
Canary is still with limit, Beta and Production/Release is okay.

**Comment by d22tny** [comment]
I think it's fixed.

**Comment by manzarek123** [comment]
Yep, last commit fixed it
