### ISSUE TITLE
Report calling native hash when failing

### ISSUE THREAD

**Issue by AvarianKnight** [citizenfx/fivem#2817]
### Segment

n/a

### Importancy

Unclear or unintuitive

### Improvement request

Currently calling a native with too large of a value (such as `SetPedComponentVariation(ped, 12, 1, 0, 0)` where 12 isn't a valid component id) will error with `arg[1]: value too large`, but this doesn't report the native used which can make it hard to debug what the error is.

Normal native execution fails would include the native hash of the native that was called to cause the error

https://github.com/citizenfx/fivem/blob/49406c43cf47a0b446f4a9abea44f9856302fdac/code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp#L474-L476

### Area(s)

FiveM, Natives

**Comment by d22tny** [comment]
It normally has a stack trace attached but sometimes it doesn't show the stack trace. I opened a similar issue the first day the change was merged, and they've agreed that it would be okay to have the native hash included.

**Comment by AvarianKnight** [comment]
Haven't had a case of no stack trace being opened, just one that's very uninformative

See:
![uninformative error message](https://github.com/user-attachments/assets/768d79e5-5539-45e0-a506-a3caf75cd5ea)

The line this point to is not useful at all

![image](https://github.com/user-attachments/assets/231d5fe9-6b1e-4a5d-9a2c-2f69c8ca5f37)

**Comment by st860923** [comment]
I encountered the same issue today where debugging lacks sufficient information, and the context is missing. In my case, the situation was even worse within ESX.Menu.Default, as the stack trace did not include any references from other resources.

![image](https://github.com/user-attachments/assets/df9b8141-d8d2-4642-979d-5e0550c00853)

I’m wondering if it would be better to change this to a warning instead? I noticed that throwing an error here directly can cause issues with some resources protected by Asset Escrow hosted by cfx. These resources are not open-sourced, and their authors are no longer providing support.

https://github.com/citizenfx/fivem/blob/aaab4384aeed5873a2353f391a1218d3950d4066/code/components/citizen-scripting-core/src/ScriptInvoker.cpp#L421

**Comment by AvarianKnight** [comment]
> I’m wondering if it would be better to change this to a warning instead? I noticed that throwing an error here directly can cause issues with some resources protected by Asset Escrow hosted by cfx. These resources are not open-sourced, and their authors are no longer providing support.

This wouldn't be desired behavior, this *should* error as it is unexpected input, but it should error in a way can be debugged, which it currently doesn't.

**Comment by d22tny** [comment]
Seems like an improved error handling has been pushed. I'll check it out today.

**Comment by SuricatoX** [comment]
> I encountered the same issue today where debugging lacks sufficient information, and the context is missing. In my case, the situation was even worse within ESX.Menu.Default, as the stack trace did not include any references from other resources.
> 
> ![image](https://private-user-images.githubusercontent.com/68638808/374481683-df9b8141-d8d2-4642-979d-5e0550c00853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzYyOTgsIm5iZiI6MTcyODU3NTk5OCwicGF0aCI6Ii82ODYzODgwOC8zNzQ0ODE2ODMtZGY5YjgxNDEtZDhkMi00NjQyLTk3OWQtNWUwNTUwYzAwODUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE1NTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZmUwZDk3MzcwMTljYWE3YzAxY2VhNjVjYmM4OWY2OTRmOTk2ZTlhMGVkMmRkYzAzMjUzY2Q0NzUwNzBjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jOQ9eJDcpBYfsjKdKMiqV45AUl-MHv5LX9w4yskQC-g)
> 
> I’m wondering if it would be better to change this to a warning instead? I noticed that throwing an error here directly can cause issues with some resources protected by Asset Escrow hosted by cfx. These resources are not open-sourced, and their authors are no longer providing support.
> 
> https://github.com/citizenfx/fivem/blob/aaab4384aeed5873a2353f391a1218d3950d4066/code/components/citizen-scripting-core/src/ScriptInvoker.cpp#L421

As I could see, normally theres no trace when the script is obfuscated (in my case with luraph).

**Comment by SuricatoX** [comment]
> Seems like an improved error handling has been pushed. I'll check it out today.

New build?

**Comment by SuricatoX** [comment]
> Seems like an improved error handling has been pushed. I'll check it out today.

In server side, but client-side still https://cdn.discordapp.com/attachments/469246162239750184/1293966174132113469/image.png?ex=67094b68&is=6707f9e8&hm=17edfb97ec8b768672d72ac5b4b2f0a9448d4d8cee65cbd54373b84e7dac01aa&

**Comment by iridium-cfx** [comment]
The native hash is now included when showing a validation error.

Also, the "value too large" error now silently fails (by not calling the native), to preserve backwards compatibility.
