### ISSUE TITLE
Rcon not working

### ISSUE THREAD

**Issue by aqua3man** [citizenfx/fivem#2831]
### What happened?

Config set:
rcon_password somerconpass

Use IceCon or other client. Rcon passwrod config is loaded though is ignored.
Server responds:
The server must set rcon_password to be able to use this command.

### Expected result

Allow access as previous versions did.

### Reproduction steps

1. Set password in config "rcon_password somerconpass"
2. Try to login through rcon with IceCon
3. Fails with message: The server must set rcon_password to be able to use this command.

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

Server 10072 Linux

**Comment by FabianTerhorst** [comment]
You have to set the rcon password with “set rcon_password somerconpass“. The variable got enforced to be read only for security reasons.

**Comment by Mathu-lmn** [comment]
Yes, I was about to say that aswell. Tho the confusion comes from this tutorial by ZAP Hosting I believe : https://zap-hosting.com/guides/docs/fivem-rcon/
They don't mention that the `set` on the cfg is required now

**Comment by aqua3man** [comment]
Thanks, i was reading fivem docs and there were no mention about this. Thanks for clearing it up.
