### ISSUE TITLE
An error at RDR2_b1491.exe!sub_1422DF278 (0x61) caused RedM to stop working

### ISSUE THREAD

**Issue by Chriss941** [citizenfx/fivem#2857]
### What happened?

Good evening everyone I keep getting this crash in the redm server An error at RDR2_b1491.exe!sub_1422DF278 (0x61) does anyone have an idea how I can fix this like where and what ?
![image](https://github.com/user-attachments/assets/4e633ed2-8684-4266-ab29-c64c3c529860)

### Expected result

help

### Reproduction steps

help

### Importancy

Crash

### Area(s)

RedM

### Specific version(s)

redm windows

**Comment by DaniGP17** [comment]
Can you attach the crash dump?

**Comment by outsider31000** [comment]
[CfxCrashDump_2024_10_11_01_26_48.zip](https://github.com/user-attachments/files/17343546/CfxCrashDump_2024_10_11_01_26_48.zip)

**Comment by outsider31000** [comment]
![image](https://github.com/user-attachments/assets/d1c966c0-48d7-4f21-bbbb-8d9ea281cf6f)
its the latest artifacts. the crash didnt exist before.

i wonder now what servers are going to do that are using Zap-Hosting? since zap dont allow rollback.

**Comment by Chriss941** [comment]
@outsider31000 So there is no solution ? Can it depend on a license or be
???

**Comment by Chriss941** [comment]
this folder crash dumb do I have to insert it somewhere ? where you put it or what do you mean if so where do I have to insert it

**Comment by outsider31000** [comment]
can you try update artifacts to the latest ? 10309

**Comment by bartusek27** [comment]
I can replicate the same error msg and stack trace, version 10309. So far I can't tell what is the trigger, happens randomly to the players.

**Comment by bartusek27** [comment]
It seems that the client is stable until another player gets into their range.

**Comment by outsider31000** [comment]
use this convar on the server.cfg
`set sv_experimentalNetGameEventHandler false`
it seems to fix the issues, although making everyone use this dosen't seem ideal.

**Comment by outsider31000** [comment]
the issue should be fixed try the last artifacts released, if all good colse this issue.
you dont need to use that convar anymore to fix the issue
