### ISSUE TITLE
An error at RDR2_b1491.exe!sub_140185EA0 (0x196) caused RedM to stop working

### ISSUE THREAD

**Issue by Moti90** [citizenfx/fivem#2858]
### What happened?

For around 10 days or so, i have been getting these crashes. An error at RDR2_b1491.exe!sub_140185EA0 (0x196) caused RedM to stop working, it often happens after a while on the server, mostly around cities, or standing still.

I have been getting different kinds of it. 

An error at RDR2_b1491.exe!sub_1432D7FDB (0x719ec5) caused RedM to stop working

An error at RDR2_b1491.exe!sub_140185EA0 (0x196) caused RedM to stop working

An error at RDR2_b1491.exe!sub_142F11874 (0x9e) caused RedM to stop working

An error at RDR2_b1491.exe!sub_14014CDC4 (0xac) caused RedM to stop working

![image](https://github.com/user-attachments/assets/ffbe4f7a-bf89-4028-a627-dc0adfbcb37e)

I tried reinstalling, redm, then reinstalling rdr2. and last night, i clean installed my pc. without it helping.

Is there any one, who might be able to help me ?

### Expected result

help

### Reproduction steps

This often happens, if im cities, or if im standing still too long.

### Importancy

Crash

### Area(s)

RedM

### Specific version(s)

redm version b1491 version 10236 beta

### Additional information

[CfxCrashDump_2024_10_10_13_33_42 (1).zip](https://github.com/user-attachments/files/17342718/CfxCrashDump_2024_10_10_13_33_42.1.zip)
[CfxCrashDump_2024_10_08_16_49_33 (1).zip](https://github.com/user-attachments/files/17342720/CfxCrashDump_2024_10_08_16_49_33.1.zip)
[CfxCrashDump_2024_10_01_18_48_36.zip](https://github.com/user-attachments/files/17342721/CfxCrashDump_2024_10_01_18_48_36.zip)
[CfxCrashDump_2024_10_07_18_30_15 (1).zip](https://github.com/user-attachments/files/17342723/CfxCrashDump_2024_10_07_18_30_15.1.zip)

**Comment by iridium-cfx** [comment]
There seem to be a lot of crashes (20+) happening uniquely to you, so I would most of these are from a computer related issue.

**Comment by Moti90** [comment]
> There seem to be a lot of crashes (20+) happening uniquely to you, so I would most of these are from a computer related issue.

But i tried most things, these crashes started happening out of the blue.

First i tried clearing cache
Then i tried, reinstalling redm.
then i tried reinstalling RDR2
last but not least, i formatted whole pc.
So you would suggest, that it is hardware based?

**Comment by iridium-cfx** [comment]
> > There seem to be a lot of crashes (20+) happening uniquely to you, so I would most of these are from a computer related issue.
> 
> But i tried most things, these crashes started happening out of the blue.
> 
> First i tried clearing cache Then i tried, reinstalling redm. then i tried reinstalling RDR2 last but not least, i formatted whole pc. So you would suggest, that it is hardware based?

Yeah, a hardware issue seems likely.

**Comment by Moti90** [comment]
> > > There seem to be a lot of crashes (20+) happening uniquely to you, so I would most of these are from a computer related issue.
> > 
> > 
> > But i tried most things, these crashes started happening out of the blue.
> > First i tried clearing cache Then i tried, reinstalling redm. then i tried reinstalling RDR2 last but not least, i formatted whole pc. So you would suggest, that it is hardware based?
> 
> Yeah, a hardware issue seems likely.

Shouldnt that affect me in other gametitles then surely?

**Comment by iridium-cfx** [comment]
> > > > There seem to be a lot of crashes (20+) happening uniquely to you, so I would most of these are from a computer related issue.
> > > 
> > > 
> > > But i tried most things, these crashes started happening out of the blue.
> > > First i tried clearing cache Then i tried, reinstalling redm. then i tried reinstalling RDR2 last but not least, i formatted whole pc. So you would suggest, that it is hardware based?
> > 
> > 
> > Yeah, a hardware issue seems likely.
> 
> Shouldnt that affect me in other gametitles then surely?

Not necessarily. I'm going to close this issue as all the crashes you mentioned have only happened once (to you).

**Comment by Jenna-W0lf** [comment]
I am having the exact same crash
