### ISSUE TITLE
RDR2_b1491.exe!sub_142B8E35C Rage error

### ISSUE THREAD

**Issue by farsey87** [citizenfx/fivem#2860]
### What happened?

We have currently a lot of issues with this error RDR2_b1491.exe!sub_142B8E35C and I need help to fix this.

Is there any way to see whats the issue is or how to fix it ? 

I tried several Artifacts the latest or also older but i doesn't change.

### Expected result

solve the issue of RDR2_b1491.exe!sub_142B8E35C

### Reproduction steps

I can't reproduce it - it happens since 3-4 weeks now  - since last REDM updates

[RDR2_b1491.exe!sub_142B8E35C_8.zip](https://github.com/user-attachments/files/17350528/RDR2_b1491.exe.sub_142B8E35C_8.zip)
[RDR2_b1491.exe!sub_142B8E35C_7.zip](https://github.com/user-attachments/files/17350529/RDR2_b1491.exe.sub_142B8E35C_7.zip)
[RDR2_b1491.exe!sub_142B8E35C_6.zip](https://github.com/user-attachments/files/17350530/RDR2_b1491.exe.sub_142B8E35C_6.zip)
[RDR2_b1491.exe!sub_142B8E35C_5.zip](https://github.com/user-attachments/files/17350531/RDR2_b1491.exe.sub_142B8E35C_5.zip)
[RDR2_b1491.exe!sub_142B8E35C.zip](https://github.com/user-attachments/files/17350532/RDR2_b1491.exe.sub_142B8E35C.zip)
[RDR2_b1491.exe!sub_142B8E35C_3.zip](https://github.com/user-attachments/files/17350533/RDR2_b1491.exe.sub_142B8E35C_3.zip)
[RDR2_b1491.exe!sub_142B8E35C_4.zip](https://github.com/user-attachments/files/17350534/RDR2_b1491.exe.sub_142B8E35C_4.zip)

### Importancy

Crash

### Area(s)

RedM, FXServer, OneSync

### Specific version(s)

REDM

**Comment by JackPepper** [comment]
We have the same issue with many users. With up to 200 players during primetime, the crash happened around 2.129 times within the last week. We tried several artefacts with no success. The latest artefact, 10488, made it better than others, but it still crashes a lot of people.

Here are some crash dumps with error RDR2_b1491.exe!sub_142B8E35C

[CfxCrashDump_2024_10_20_06_23_39.zip](https://github.com/user-attachments/files/17449476/CfxCrashDump_2024_10_20_06_23_39.zip)
[CfxCrashDump_2024_10_20_05_36_21.zip](https://github.com/user-attachments/files/17449478/CfxCrashDump_2024_10_20_05_36_21.zip)
[CfxCrashDump_2024_10_19_22_30_10.zip](https://github.com/user-attachments/files/17449481/CfxCrashDump_2024_10_19_22_30_10.zip)
[CfxCrashDump_2024_10_19_21_57_22.zip](https://github.com/user-attachments/files/17449482/CfxCrashDump_2024_10_19_21_57_22.zip)
[CfxCrashDump_2024_10_19_20_21_47.zip](https://github.com/user-attachments/files/17449493/CfxCrashDump_2024_10_19_20_21_47.zip)

**Comment by promiselandrp** [comment]
Also having some issues with this same crash on the latest artifacts

[CfxCrashDump_2024_10_19_00_59_35.zip](https://github.com/user-attachments/files/17450558/CfxCrashDump_2024_10_19_00_59_35.zip)
[CfxCrashDump_2024_10_19_01_29_04.zip](https://github.com/user-attachments/files/17450562/CfxCrashDump_2024_10_19_01_29_04.zip)
[CfxCrashDump_2024_10_20_03_42_29.zip](https://github.com/user-attachments/files/17450566/CfxCrashDump_2024_10_20_03_42_29.zip)

**Comment by JackPepper** [comment]
Based on observations, it would not happen if the cache was cleared before joining the server.

**Comment by iridium-cfx** [comment]
This might be fixed in latest canary (10543), please can you check it and let me know if it's still happening?

**Comment by outsider31000** [comment]
these were not fixed just had someone testing

**Comment by iridium-cfx** [comment]
Thanks, closing this issue as fixed.
