### ISSUE TITLE
GetVehicleModelNumberOfSeats returning incorrect values if model is not loaded

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#2863]
### What happened?

As shown in this image, the [GetVehicleModelNumberOfSeats](<https://docs.fivem.net/natives/?_0x2AD93716F184EDA4=>) native returns the wrong number of vehicle seats when the model is not loaded
![image](https://github.com/user-attachments/assets/c8c5bf10-3e92-4b89-ab14-1591f4404054)
But after that, I tried loading the model in memory and it was working : 
![image](https://github.com/user-attachments/assets/b399939a-377f-461f-98be-7beeb470bb2b)

### Expected result

Returning the correct number of seats

### Reproduction steps

See the code in the screenshots above

### Importancy

Slight inconvenience

### Area(s)

FiveM, Natives

### Specific version(s)

b3095 - canary client

**Comment by AvarianKnight** [comment]
This isn't a bug.

**Comment by Mathu-lmn** [comment]
How is this not a bug ? The native works for the "primo" (returns 4 even when the model is **not** loaded) but not for the "rhinehart" (returns 2 when not loaded)

**Comment by ahcenezdh** [comment]
> How is this not a bug ? The native works for the "primo" (returns 4 even when the model is **not** loaded) but not for the "rhinehart" (returns 2 when not loaded)

Thats how some natives are working, you need to load the model before

**Comment by AvarianKnight** [comment]
https://github.com/citizenfx/natives/issues/986#issuecomment-2266011291

**Comment by Mathu-lmn** [comment]
So the rhinehart's model layout does not have the correct number of seats comparing to the real entity model ? damn...

**Comment by Bossman02** [comment]
> > How is this not a bug ? The native works for the "primo" (returns 4 even when the model is **not** loaded) but not for the "rhinehart" (returns 2 when not loaded)
> 
> Thats how some natives are working, you need to load the model before

If some natives have this “bug/ working mode”, wouldn't it be correct to state it in their documentation entry?
