### ISSUE TITLE
Lastest Game Build Breaks Weapons.meta Files

### ISSUE THREAD

**Issue by LilVegaBoiii** [citizenfx/fivem#2868]
### What happened?

With the lastest game build update weapons.meta files are randomly colliding with each other and causing instant crashes upon login

an Example of the error that shows:

An exception occurred (c0000005 at 0x7ff78bd4cb91) during loading of resources:/grim-colorwave/[GRIMPURP]/meta/weapons.meta in data file mounter 0000000141b500a8. The game will be terminated.

### Expected result

There shouldnt be an error, everything should work fine

### Reproduction steps

Its random but
1. have a weapon in your server
2. add a new one in
3. restart server
4. upon loading into the server your game will crash and pop this error

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM all game builds higher than 2545, windows

### Additional information

Id like to state that this definitely is a bug and not just something wrong with my weapons, there is nothing even remotely the same in the weapons to cause them to collide with each other, they work perfectly fine separate, and upon switching to gamebuild 2545 they work perfectly fine together, only when on higher game builds does this error occur, it is also an error that just started happening this week, so maybe it has to do with the newest update, im unsure.

**Comment by Legacy-TacticalGamingInteractive** [comment]
Please post the file in question

**Comment by LilVegaBoiii** [comment]
[meta.zip](https://github.com/user-attachments/files/17422885/meta.zip)
This is the .meta files from the weapon that is throwing the error, but again this only throws an error when i add my new weapons in

**Comment by LilVegaBoiii** [comment]
EDIT: Think ive hit some sort of limit, i reduced the amount of stream resources i have and the error faded away

**Comment by d22tny** [comment]
You can close the issue yourself.
