### ISSUE TITLE
fivem server crash

### ISSUE THREAD

**Issue by poco8537** [citizenfx/fivem#2879]
### What happened?

Server crash on fxServer 10573.
I think there was a problem with voip-server-mumble.dll.
There were more than 550 
[398d025c-410f-4fd9-ac3a-c99d36bd7ff5.dmp](https://github.com/user-attachments/files/17523100/398d025c-410f-4fd9-ac3a-c99d36bd7ff5.dmp)

### Expected result

normal server operation

### Reproduction steps

1. Open the server.
2. Wait for the crash.

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

10573

**Comment by FabianTerhorst** [comment]
Hi, can you give a bit more information's for reproduction. Which operating system is the server using and what was the player count when the crash happened?

**Comment by poco8537** [comment]
The operating system is Windows Server 2019 Standard, and the server had over 500 players. The server crashed again about 4 hours ago. I'm not sure what caused the shutdown. There have been three crashes in the past two days; should I consider using a lower version of the artifacts?
[0be292e0-297f-4ba1-989c-e9f3123c7c8e.dmp](https://github.com/user-attachments/files/17528770/0be292e0-297f-4ba1-989c-e9f3123c7c8e.dmp)

**Comment by poco8537** [comment]
The recent crash has a very large full dump size (with around 200 players).
![image](https://github.com/user-attachments/assets/2c5ef347-21b4-4c2b-b2a8-d26fbcab9e0c)
