### ISSUE TITLE
increase pool size of DrawableStore

### ISSUE THREAD

**Issue by kamelzarandah** [citizenfx/fivem#2880]
### What happened?

with the increase of streamed files and new maps being added in redm we face an issue of reaching DrawableStore max pool size which results in an instant crash upon loading into the server, we would like to request the ability to increase that pool size so that we can continue to add new maps 
![image](https://github.com/user-attachments/assets/0ef459a5-e63f-4b69-b868-911eecce9d4d)
![image](https://github.com/user-attachments/assets/32d14cb3-1885-4d0e-b390-6744028a8a59)

### Expected result

ability to add more ydr files without crahsing 

### Reproduction steps

i got the crash when i reached approx 1000+ ydrs 

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

redm/ windows 10573

**Comment by Masterspooni** [comment]
I support that.

**Comment by Cleetus777** [comment]
Supported, this needs to happen

**Comment by macabreredm** [comment]
100 percent this needs to happen redm is evolving everyday and something like this would be great

**Comment by AvocadoOutlaw** [comment]
Please do this! We want to fully open the map as much as possible to add new places for players to explore, call home, or own a new business venture! FiveM I know can increase their own Pool Size limits but RedM server owners don't get this advantage. Once we reach this limit we have to be careful on what we pick and choose to add.

All custom items and new mappings we have to miss out on completely or sacrifice something in its place. This is a issue I had no clue about until I reached this limit. I fully support this!

**Comment by VarusXX** [comment]
I support that. We need bigger pools and how to activate this

**Comment by S-H-Development** [comment]
This will become essential at one point or another, I think the time may be now. +1!

**Comment by AvarianKnight** [comment]
While its understandable to want the pool size increase, having a bunch of people spam the issue isn't the way to do it.

**Comment by roancrous** [comment]
I support this too

**Comment by BonnieAmarie** [comment]
I fully support this!

**Comment by Siddwell740** [comment]
Definitely would like to see this happen

**Comment by NOIACAST-br** [comment]
Eu apoio

**Comment by ook3D** [comment]
i love when people spam their useless opinion on issues blocking actual constructive discussion!

**Comment by ook3D** [comment]
> I fully support this!

Oh BonnieAmarie supports this? Quick everyone to work! Thank you for your ever so valuable input.

**Comment by kamelzarandah** [comment]
MaxDoorExtensions value="320"
if possible can we also get this pool size, as of right now, exceeding this one also causes an instant crash 
RDR2_b1491.exe!?Entities_Create@fwMapDataContents@rage@@S?_PPAVfwMapData@rage@@PAVfwMapDataContents@Entities_Create@@H@Z (0x10a) 

Door extensions crash (if you have to many Door extensions in ymap or ytyp Files)

something like this happens when you have many big apartment buildings for example in saint denis where all the big buildings are next to each other

**Comment by Fixitfy** [comment]
> ### What happened?
> with the increase of streamed files and new maps being added in redm we face an issue of reaching DrawableStore max pool size which results in an instant crash upon loading into the server, we would like to request the ability to increase that pool size so that we can continue to add new maps ![image](https://private-user-images.githubusercontent.com/62485293/380310699-0ef459a5-e63f-4b69-b868-911eecce9d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mjg4ODAsIm5iZiI6MTcyOTkyODU4MCwicGF0aCI6Ii82MjQ4NTI5My8zODAzMTA2OTktMGVmNDU5YTUtZTYzZi00YjY5LWI4NjgtOTExZWVjY2U5ZDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA3NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjI2NmM0YjVhY2ExYzk2NjZkYjcyMGM1MjU4YzY4OWRjN2U5M2Q3NmI1OWUzOWUwNDAzZTAyMzdmNDQ2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MpKhxL5-j2m39WrrcJulKpoYAOdSlqxswDXY_eNICDU) ![image](https://private-user-images.githubusercontent.com/62485293/380310739-32d14cb3-1885-4d0e-b390-6744028a8a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mjg4ODAsIm5iZiI6MTcyOTkyODU4MCwicGF0aCI6Ii82MjQ4NTI5My8zODAzMTA3MzktMzJkMTRjYjMtMTg4NS00ZDBlLWIzOTAtNjc0NDAyOGE4YTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA3NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YzMyNDUxMzhmMmJkMzA3NDRkZWM2MmVjMzQ4MTBlMzE4N2Y3MTVmNzc1NDc0YTg3ZWU0OGJlYTM5ZmM4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R7koyJR-I0Z7QvCLNM5SndqxhqdsNOT4Q1HuUzpT8P8)
> 
> ### Expected result
> ability to add more ydr files without crahsing
> 
> ### Reproduction steps
> i got the crash when i reached approx 1000+ ydrs
> 
> ### Importancy
> Crash
> 
> ### Area(s)
> FXServer
> 
> ### Specific version(s)
> redm/ windows 10573
> 
> ### Additional information
> _No response_

I support. this is a big problem

**Comment by NiXyos** [comment]
I support this need, today we need to develop our game boards with more and more content.

**Comment by ook3D** [comment]
> I support, today we need to develop our game boards with more and more content.

What are you even talking about, game boards? No one cares if you support this or not.

**Comment by BlackLegion23** [comment]
Support 100%

**Comment by Quiteck1983** [comment]
Support this, we need it!

**Comment by iSn4x** [comment]
Yes, pls make changing pool sizes possible.

**Comment by prikolium-cfx** [comment]
Thanks for your feedback. We've added DrawableStore to our new system of pool resizing.
You can find more information on how to use it here: https://github.com/citizenfx/fivem-docs/commit/fd7ac6a9ef9041aa05d5f8f2d89f442560947e34#diff-331e99259d1395f290e695c1c52cfb483254b82a1a1534aadcaabc08ad0d8e5dR408
Currently we limited DrawableStore to additional 50k items. Let us know when/if you need more.

**Comment by kamelzarandah** [comment]
> Thanks for your feedback. We've added DrawableStore to our new system of pool resizing. You can find more information on how to use it here: [citizenfx/fivem-docs@fd7ac6a#diff-331e99259d1395f290e695c1c52cfb483254b82a1a1534aadcaabc08ad0d8e5dR408](https://github.com/citizenfx/fivem-docs/commit/fd7ac6a9ef9041aa05d5f8f2d89f442560947e34#diff-331e99259d1395f290e695c1c52cfb483254b82a1a1534aadcaabc08ad0d8e5dR408) Currently we limited DrawableStore to additional 50k items. Let us know when/if you need more.


MaxDoorExtensions value="320"
if possible can we also get this pool size, as of right now, exceeding this one also causes an instant crash
RDR2_b1491.exe!?Entities_Create@fwMapDataContents@rage@@s?_PPAVfwMapData@rage@@PAVfwMapDataContents@Entities_Create@@h@Z (0x10a)

Door extensions crash (if you have to many Door extensions in ymap or ytyp Files)

something like this happens when you have many big apartment buildings for example in saint denis where all the big buildings are next to each other
