### ISSUE TITLE
Can't build the server

### ISSUE THREAD

**Issue by MockbaTheBorg** [citizenfx/fivem#29]
Hi All,

I have tried to build the client and finally managed to.
However I don't see the the server inside.
Is the server a separate repository?

Thanks,
Mockba the Borg

**Comment by izio38** [comment]
Europium's help : premake5 vs2017 --game=server

**Comment by MockbaTheBorg** [comment]
Thanks Izio38, it seemed to work. But it built a server which is different though.
It created a FXServer.exe, not a CitizenMP.Server.exe (which we download from the website).

It this a different server? How can I build the CitizenMP.Server.exe?

Thanks a lot!

**Comment by Povers** [comment]
FXServer.exe is the new incoming server version.

**Comment by izio38** [comment]
I know there is a way to build the old builds, but I don't know how, maybe an elements could tell you that :)

**Comment by MockbaTheBorg** [comment]
Oh ok ... so I guess it can't be used yet?
Is there a way for me to build the current server?

**Comment by blattersturm** [comment]
>Oh ok ... so I guess it can't be used yet?
It can, though? See [Running FXServer](https://wiki.fivem.net/wiki/Running_FXServer) on the wiki, and the build scripts in `code/tools/ci/`.

>Is there a way for me to build the current server?
No. And it's also hard to see why you would want to.

**Comment by MockbaTheBorg** [comment]
Just wanted to be able to build from source the same things I download pre-built.
The server wiki helped though. I will try it tonight, and contribute if I am able to.

Thanks all!!!

**Comment by loursgeeklevrai** [comment]
Yes there is a way and people are just idiots : 
```dos
premake5.exe vs2017 --game=server 
```
will generate you the fxserver project.
