### ISSUE TITLE
players.json missing identifiers

### ISSUE THREAD

**Issue by benzon** [citizenfx/fivem#2901]
### What happened?

players.json is missing identifiers i latest build

### Expected result

identifiers visible

### Reproduction steps

Use latest artifacts

### Importancy

Slight inconvenience

### Area(s)

FiveM, FXServer

### Specific version(s)

10769, Windows Server 2022

**Comment by prikolium-cfx** [comment]
Please take a look into your server console and follow our updates in future.
![image](https://github.com/user-attachments/assets/8df1c58e-969f-48ec-9ca5-4996252fdbdc)

**Comment by Zesty-ZDev** [comment]
Why not require auth only if the connection is not local?
