### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by poco8537** [citizenfx/fivem#2904]
### What happened?

A server crash occurred. There were 455 players connected. Is it possible to analyze the dump?

### Expected result

normal server operation

### Reproduction steps

1. Open the server.
2. Wait for the crash.

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

FXServer-master SERVER v1.0.0.10012 win32

**Comment by poco8537** [comment]
[afd1691f-f335-4149-8371-5408c4655495.dmp](https://github.com/user-attachments/files/17605835/afd1691f-f335-4149-8371-5408c4655495.dmp)
[d43893d8-b778-45c7-9080-fe8b3e8e23a8.dmp](https://github.com/user-attachments/files/17605836/d43893d8-b778-45c7-9080-fe8b3e8e23a8.dmp)

**Comment by FabianTerhorst** [comment]
Please update to the latest server version.

**Comment by poco8537** [comment]
![image](https://github.com/user-attachments/assets/63427f41-4967-43ce-8da5-d1bc65ffed7d)
Are you referring to version 7290? Is there an issue with the server version currently in use?

**Comment by FabianTerhorst** [comment]
With latest version I'm referring to the latest version available at https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/ .

**Comment by poco8537** [comment]
Same crash occurred in builds 7290 and 10778
[e7109599-7748-496e-8d4e-e31a314399a1.dmp](https://github.com/user-attachments/files/17615877/e7109599-7748-496e-8d4e-e31a314399a1.dmp)

**Comment by poco8537** [comment]
The server uptime was 3 hours, and there were over 600 active players. Another crash occurred. Is there a way to analyze this crash?
[7385bbab-6ea4-45c4-83cb-b8072a4e8b4a.dmp](https://github.com/user-attachments/files/17618076/7385bbab-6ea4-45c4-83cb-b8072a4e8b4a.dmp)

**Comment by poco8537** [comment]
using an i9-13900K CPU, 128GB RAM, and Windows Server 2019 as the operating system.

**Comment by prikolium-cfx** [comment]
> i9-13900K

Thanks for your report. That's sad, but most likely your i9-13900K faced with crystal degradation that happens to 13/14 series of Intels. You can read more about it here https://www.theverge.com/2024/7/26/24206529/intel-13th-14th-gen-crashing-instability-cpu-voltage-q-a

**Comment by prikolium-cfx** [comment]
So I would recommend you to swap your CPU to 12 series or AMD. To smoothly run server you don't need such CPU, it's enough to have 8 cores with high frequency.

**Comment by poco8537** [comment]
FXserver is using 117GB of memory, and although I stopped all resources, there is no change in memory usage. This issue didn’t occur on version 7290, but it’s happening on version 10778.![image](https://github.com/user-attachments/assets/ef5230e2-3919-4818-861a-068ddd46c18b)

**Comment by prikolium-cfx** [comment]
> FXserver is using 117GB of memory, and although I stopped all resources, there is no change in memory usage. This issue didn’t occur on version 7290, but it’s happening on version 10778.![image](https://private-user-images.githubusercontent.com/107696090/383407269-ef5230e2-3919-4818-861a-068ddd46c18b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQyODQsIm5iZiI6MTczMDg4Mzk4NCwicGF0aCI6Ii8xMDc2OTYwOTAvMzgzNDA3MjY5LWVmNTIzMGUyLTM5MTktNDgxOC04NjFhLTA2OGRkZDQ2YzE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwOTA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmJmYmJkMGJjN2IwYjZmOTMzMGJjY2Q1MTlkZmFmMGI4NjljNzk5MjlmZDk3ZDc0NmM2YjA2YTA3OWE2Yjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wty8Ph_Gel1fvccrA1E_XwLA-XpiGmAjhCsYv-R9B3A)

I can't give you more advice till you use potentially non properly working CPU.

**Comment by poco8537** [comment]
I upgraded my CPU to the 9950X and RAM to DDR5 192GB today. The active player count is over 700, and while my uplink can handle up to 3Gbps, it's currently using less than 1Gbps. However, players are experiencing long download times for resources. Is this a limitation of FXServer's file server?

**Comment by poco8537** [comment]
![image](https://github.com/user-attachments/assets/a72ae51e-ffba-4e11-927d-d052f53ce80c)

**Comment by prikolium-cfx** [comment]
> I upgraded my CPU to the 9950X and RAM to DDR5 192GB today. The active player count is over 700, and while my uplink can handle up to 3Gbps, it's currently using less than 1Gbps. However, players are experiencing long download times for resources. Is this a limitation of FXServer's file server?

Probably yes. I would recommend you to use something as a reverse proxy for resource downloading, for example nginx

**Comment by poco8537** [comment]
The server uptime is 8 hours, with current RAM usage at 108 GB and CPU usage at 40%. Server and sync thread hitching continues to occur. In FXServer version 7290, RAM usage didn’t increase this much, but in the latest build, memory usage keeps accumulating.

**Comment by FabianTerhorst** [comment]
Ok, make the dump a minute after the server is started.

**Comment by dokkusitdown** [comment]
We are currently shutting down the server following the maintenance notice. We will send the memory dump as soon as possible. Thank you.

**Comment by dokkusitdown** [comment]
![image](https://github.com/user-attachments/assets/d046fe06-1f22-4c73-beef-9544816663bb)

After shutting down the server, disconnecting all users, and stopping all resources, we checked the memory usage, but it still shows 118GB. It doesn’t seem to be an issue with our resources. The server uptime is 8 hours.

**Comment by FabianTerhorst** [comment]
Would a discord id also work?

**Comment by dokkusitdown** [comment]
Yes Thank you
Discord Id : yumipapa
<@267305288544157698>

**Comment by poco8537** [comment]
Could you explain in detail in which cases server/sync/network thread hitching occurs?
