### ISSUE TITLE
B3258 build breaks Fivem Story/Single Player mode missions cinematics

### ISSUE THREAD

**Issue by MrKoddy** [citizenfx/fivem#2909]
### What happened?

B3258 build breaks Fivem Story/Single Player mode missions specially cinematics

### Expected result

Cinematics should run

### Reproduction steps

Transit to B3258
Launch a Single Player game and do a mission with cinematic like the first Simeon's mission or Lester's mission

Transit to B3095, do same mission, it doesn't break

### Importancy

There's a workaround

### Area(s)

FiveM

### Specific version(s)

FiveM B3258

### Additional information

With older FiveM B3095 cinematics don't break

**Comment by Nobelium-cfx** [comment]
Closing the issue. Feel free to reopen if you still experience problems with it.

**Comment by neptunium-cfx** [comment]
> PS: there is still an crash if you loose the mission in SP. E.g. if you start the Prologue mission from mission replay, kill hostages and try to exit the mission. But it is an unrelated issue and should be fixed separately later this week. I'll post an update here as well just in case.

This should get resolved whenever a new canary build is issued.
