### ISSUE TITLE
Request for Increasing Flexibility in Pool Size Adjustments, Specifically the Building Pool

### ISSUE THREAD

**Issue by 0derkek0** [citizenfx/fivem#2933]
### What happened?

Request for Increasing Flexibility in Pool Size Adjustments, Specifically the Building Pool

### Expected result

Request for Increasing Flexibility in Pool Size Adjustments, Specifically the Building Pool

### Reproduction steps

Request for Increasing Flexibility in Pool Size Adjustments, Specifically the Building Pool

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

-/-

**Comment by prikolium-cfx** [comment]
Not enough information. Closing
