### ISSUE TITLE
Severe regression of weapon/gunfire syncing in 3258

### ISSUE THREAD

**Issue by Lucas7yoshi** [citizenfx/fivem#2934]
### What happened?

Actual gunshot events appear to have massively regressed compared to 3095. Tasers sound like they are empty until they fire for remote clients several seconds later. Shotguns have a large delay, muskets do not even shoot at all. Up n atomizer projectile syncs instantly but the actual shoot effect shows up seconds later, laser minigun doesnt seem to work at all.

3095 (Working well): https://youtu.be/7IfqwRMYFzk
3258 (Bad to awful sync): https://youtu.be/KEt_us7j9MU

### Expected result

Gun sync quality should be similar or identical to 3095.

### Reproduction steps

1. Start up a server on 3258
2. Connect with two clients
3. Go to the same area
4. Shoot various firearms, shotguns, up n atomizer, and stungun as well as the musket are best for showing the discrepancy
5. Repeat for 3095
6. Compare

### Importancy

Unknown

### Area(s)

FiveM, FXServer, OneSync

### Specific version(s)

FiveM 3258 (Canary, heard reports across stable/beta), Tested latest FXServer (11012)

### Additional information

There needs to be more importancy options... I would classify this as "severe" for gunplay focused servers, and quite unideal for others.

Environment is identical, only change between is the sv_enforceGameBuild value.

**Comment by Nobelium-cfx** [comment]
A fix should be available on Canary by now (https://github.com/citizenfx/fivem/commit/0991173413bd55a55ceae6ac01ab28041abbfefe). @Lucas7yoshi Can you please confirm that it fixes the issue for you?

**Comment by Lucas7yoshi** [comment]
> A fix should be available on Canary by now ([0991173](https://github.com/citizenfx/fivem/commit/0991173413bd55a55ceae6ac01ab28041abbfefe)). @Lucas7yoshi Can you please confirm that it fixes the issue for you?

Tested and seems to be resolved, thanks!

https://github.com/user-attachments/assets/906cfd45-088d-4f50-99cc-36f5a4de5428
