### ISSUE TITLE
Empty identifiers property for all players

### ISSUE THREAD

**Issue by deluxejamie** [citizenfx/fivem#2994]
### What happened?

When using the API to develop features for FiveM related products, I noticed that the identifiers array prop for player objects is not being populated on https://servers-frontend.fivem.net/api/servers/single/SERVER_CODE .

### Expected result

The identifiers property should be populated with licences & discord (if applicable)

### Reproduction steps

1. Go to https://servers-frontend.fivem.net/api/servers/single/SERVER_CODE replacing SERVER_CODE with a FiveM server code with at least 1 player
2. Observe that the `response.Data.players[i].identifiers` is not populated with identifiers. I have tested this with my friend and his discord identifiers were not populated.
![](https://i.imgur.com/EqHfE0m.png)

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

FiveM Frontend API

**Comment by Mathu-lmn** [comment]
Hi, I believe this is related to this change : 
![image](https://github.com/user-attachments/assets/ab4e5978-14f1-4ee4-aec6-e2a67782185b)
See https://forum.cfx.re/t/celebrating-one-year-with-rockstar-games/5269938#fivem-and-redm-6

**Comment by deluxejamie** [comment]
Extremely grateful for your response thank you!
