### ISSUE TITLE
C# mono (v1, v2) - not working natives

### ISSUE THREAD

**Issue by csskroubledev** [citizenfx/fivem#2996]
### What happened?

Natives like `GetInvokingResource`, `GetCurrentResourceName` or `ExecuteCommand` don't work as intended.
First two return empty strings instead of current resource name, and ExecuteCommand does nothing.

Worth noting, that this doesn't happen in classes inheriting from BaseScript, but not all classes can be inherited from it (for example SignalR Hubs)

### Expected result

Natives should return correct values/do what they're supposed to

### Reproduction steps

1. Create an class inheriting from `BaseScript`, and one not
2. Run one of the three natives (`GetInvokingResource`, `GetCurrentResourceName` or `ExecuteCommand`)
3. In the class inheriting from BaseScript they work correctly, in the one not - they don't.

### Importancy

There's a workaround

### Area(s)

FXServer, Natives, ScRT: C#

### Specific version(s)

Server 10488, Windows Server 2022 (10.0.20348.2762)

### Additional information

Issues above can be annoying, but a workaround is using an EventHandler in one of BaseScript inheriting classes, and then emitting an event executing the native from a non inheritent class.

**Comment by DaniGP17** [comment]
I'm running mono v2 and for me those natives are working in a class that doesn't inherited from BaseScript, code:
```cs
using CitizenFX.Core;
using static CitizenFX.Server.Native.Natives;

namespace server
{
    public class Main : BaseScript
    {
        public Main()
        {
            Second second = new Second();
        }
    }

    public class Second
    {
        public Second()
        {
            Debug.WriteLine("Resource name: " + GetCurrentResourceName());
            ExecuteCommand("refresh");
        }
    }
}
```

Output:
```
[      script:testing] Resource name: testing
[           resources] Scanning resources.
[           resources] Found 0 new resources, and refreshed 0/31 resources.
```

**Comment by manups4e** [comment]
as long as the script is allowed.. you can execute them from all the classes you want 🤔 especially if the API is already included as static.. not a real bug i'd say

**Comment by csskroubledev** [comment]
For me it's not working.
![image](https://github.com/user-attachments/assets/01bd1122-41dc-4ed0-87f8-7f319c3499b9)

```cs
using CitizenFX.Core;
using CitizenFX.Server.Native;
using Microsoft.AspNet.SignalR;
using Pastel;
using Color = System.Drawing.Color;
using static CitizenFX.Server.Native.Natives;

namespace CoCo.Server.SignalR.Hubs;

public class PromptHub : Hub
{
   // Truncated for readability
    public void ExecuteCommand(string command)
    {
        Debug.WriteLine($"Executing command {command.PastelBg(Color.Beige).Pastel(Color.Black)} per SignalR request.");
        Debug.WriteLine($"Current resource: {GetCurrentResourceName()}");
        Events.TriggerEvent("runCommandSv", command);
    }
   // Truncated for readability
}
```

```cs
namespace CoCo.Server;

public class CoCoServer : BaseScript
{
    public CoCoServer()
    {
        StartupSocketServer();
    }
   // Truncated some methods

    public void StartupSocketServer()
    {
        const string url = "http://*:21378";

        WebApp.Start<Startup>(url);
        Debug.WriteLine($"SignalR server running on {url.PastelBg(Color.Beige).Pastel(Color.Black)}");
    }

    [EventHandler("runCommandSv", Binding.Local)]
    private string RunCommandServer(string command)
    {
        Natives.ExecuteCommand(command);
        return "Command executed.";
    }
}
```

```cs
[assembly: OwinStartup(typeof(CoCo.Server.Startup))]

namespace CoCo.Server;

public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        app.UseCors(CorsOptions.AllowAll);
        // Add SignalR to the OWIN pipeline
        app.MapSignalR();

        GlobalHost.HubPipeline.AddModule(new TokenAuthPipeline());
    }
}
```

**Comment by joelwurtz** [comment]
Certainly because when you are handling SignalR request you are not in the context of the game main thread (in a current tick), don't know if there is any helper for that in C# sdk but you need to run native from the game only where you are in the right context (you can push your request to a queue and on the next tick you can pop it from the queue to execute it by example)

**Comment by csskroubledev** [comment]
Okay, thanks for the complex response!

It certainly helped me understand how it works, and I already have an idea how to do this
Thank you very much!

**Comment by csskroubledev** [comment]
I'm reopening the issue, as it's still an issue - and there shouldn't be the requirement to do a work around.

For now, I'm sending my workaround below.
```cs
public class GameScopeExecutor : BaseScript
{
    private readonly ConcurrentDictionary<string, Action> _actionQueue = new();
    private readonly ConcurrentQueue<Action> _continuationQueue = new();
    private readonly ConcurrentDictionary<string, object> _callbackReturns = new();

    public static GameScopeExecutor Instance { get; private set; }

    public GameScopeExecutor()
    {
        Instance = this;
        Tick += ProcessQueue;
    }

    public T EnqueueAction<T>(Func<T> action)
    {
        object result = null;
        var resetEvent = new ManualResetEvent(false);

        _continuationQueue.Enqueue(() =>
        {
            result = action();
            resetEvent.Set();
        });

        resetEvent.WaitOne();
        return (T)result;
    }

    public void EnqueueAction(Action action)
    {
        _continuationQueue.Enqueue(action);
    }

    private async Coroutine ProcessQueue()
    {
        while (_continuationQueue.TryDequeue(out var action))
            try
            {
                action();
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Error executing action in game scope: {ex}");
            }

        await Task.CompletedTask;
    }
}
```

Examples:
```cs
GameScopeExecutor.Instance.EnqueueAction(() => { Natives.ExecuteCommand(command); });

return GameScopeExecutor.Instance.EnqueueAction(GetNumPlayerIndices);
return GameScopeExecutor.Instance.EnqueueAction(() => GetCurrentResourceName().ToString());
```

**Comment by AvarianKnight** [comment]
I'm not entirely sure what you're expecting here, from a quick glance it looks like you're trying to call the native from a different thread (as it looks like SignalR will setup its own thread to run on) which is why calling the natives *will not work* there's no nice way to fix this besides executing back on the main thread (usually calling `await Delay(0)` will get you back on the main thread for certain applications).

**Comment by csskroubledev** [comment]
> I'm not entirely sure what you're expecting here, from a quick glance it looks like you're trying to call the native from a different thread (as it looks like SignalR will setup its own thread to run on) which is why calling the natives _will not work_ there's no nice way to fix this besides executing back on the main thread (usually calling `await Delay(0)` will get you back on the main thread for certain applications).

Okay, that's the reply I expected 😀 

If it's not possible, I'm closing the issue.
I will try the `await Delay(0)` later.
