### ISSUE TITLE
VehicleHash.cs does not contain updated vehicles!

### ISSUE THREAD

**Issue by Synergyst** [citizenfx/fivem#30]
Hello!

I am trying to spawn some of the newer vehicles which have been added to GTA, such as the Phantom Wedge, the APC, and a few others.

I am sure they're in my client files, however they are not spawning even when I spawn by the explicit ID(0x9DAE1398 OR 2645431192 OR -1649536104 (Phantom Wedge))

Below is the link of the current vehicle hash list which I was able to find.
Is there a way to even spawn these, or would the server need to have an updated hashkey list as well as the client to get past the model checks, etc?
https://github.com/citizenfx/fivem/blob/b36c2d66ac9cd91d411dc741e084fa43287f5c4a/code/client/clrcore/External/VehicleHash.cs

Kind regards

**Comment by Kngrektor** [comment]
FiveM runs on a old version of the game, if you want new cars get https://forum.fivem.net/t/release-gunrunning-import-export-special-races-vehicles-in-fivem/25197

**Comment by Synergyst** [comment]
Alright.. I'll have to try that on our server.

Will FiveM ever use a newer version of the game? And if so is there anything that you know of which could delay that?

Kind regards

**Comment by mraes** [comment]
https://forum.fivem.net/t/new-vehicle-functions-support/4524/2

**Comment by Synergyst** [comment]
Alright. That explains a lot.

Thank you both for replying quickly!

Kind regards.
