### ISSUE TITLE
Error affecting FXServer artifacts 12078 and onward: "Failed to open packfile: ReadBulk of header failed:"

### ISSUE THREAD

**Issue by RageOps** [citizenfx/fivem#3011]
### What happened?

After noticing an uptick in user complaints about a specific issue: "Failed to open packfile: ReadBulk of header failed:" when attempting to connect to servers, I investigated whether the issue was related to a certain version of artifacts. On a fresh FXServer creation, Linux (Ubuntu) environment, I was able to reproduce the error on both artifacts 12083 and 12078. When using artifacts 12031, the issue was not present. 

I tested both Release and Canary client versions. The connection error was present for both Release and Canary on 12078, and was not present on Release or Canary on 12031.

The only resources installed on the server were the default cfx-server-data resources.

Error screenshot:
![image](https://github.com/user-attachments/assets/010e933f-11f2-4cc5-af22-64260157a2f3)
> This image shows chat as the resource that couldn't be loaded, but I have also seen sessionmanager and resource monitor as resources that are indicated in the error message. Leading me to believe that the issue does not depend on the resource that is failing to load.

Client log:
[CitizenFX_log_2024-12-17T052541.log](https://github.com/user-attachments/files/18160494/CitizenFX_log_2024-12-17T052541.log)

Server log: (I don't have a brain and couldn't figure out how to network my txAdmin port on my host)
![image](https://github.com/user-attachments/assets/9aa4ac25-954e-49bb-b61a-dd11aa2e0436)

### Expected result

Players are able to connect to servers regardless of artifacts version

### Reproduction steps

Server:
1. Create new Linux FXServer with artifact version 12083 or 12078. In my case I used 12078
2. Install the cfx-server-data resources.
3. Run the server

Client
1. Attempt to connect to the server
2. Be met with the above error message.

### Importancy

There's a workaround

### Area(s)

FiveM, FXServer

### Specific version(s)

Server 12078/12083 linux

### Additional information

This was not tested on a localhost environment.

**Comment by FabianTerhorst** [comment]
Thanks for the report, this issue has been resolved inside the latest artifacts 12092+.
