### ISSUE TITLE
Failed to open packfile: ReadBulk of header failed

### ISSUE THREAD

**Issue by Exyztence** [citizenfx/fivem#3013]
### What happened?

I cannot join any of my servers, even those I created today. Every time I connect, I get disconnected with the error seen below. As far as I know, this issue started yesterday. I've tested all fivem releases and there is no version of the fivem that works.

![image](https://github.com/user-attachments/assets/b737a07c-2b87-4bb8-af3c-032a89ed724f)

### Expected result

Join server

### Reproduction steps

Connect to server

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

b12031

**Comment by FabianTerhorst** [comment]
Please use the latest artifact. This has been fixed since the build you have listed.

**Comment by PixelJuggernaut** [comment]
i have latest artifact, i fixed this problem by installing 1.1.1.1 but now my character is invisible and i cant use any command, my game crashes after some time,....

**Comment by PixelJuggernaut** [comment]
![Uploading 218_2.jpg…]()
