### ISSUE TITLE
Streaming font_lib_efigs_pc.gfx

### ISSUE THREAD

**Issue by FatCatTuxedo** [citizenfx/fivem#3020]
### What happened?

Attempting to stream this in a resource results in nothing happening, the file is not replaced.

### Expected result

font_lib_efigs_pc.gfx should be replaced with the one in the resource

### Reproduction steps

1. Create a resource and attempt to stream a different font_lib_efigs_pc.gfx file
2. the file will remain the original

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

All

**Comment by FatCatTuxedo** [comment]
Kind of a non-issue since you can just add a custom font then use html in scaleform function calls to change them to use said font

**Comment by YasinY** [comment]
it's not a non issue, as e.g. i want to stream an empty gfx file so the text doesn't render at all, so i don't have to call any hidehud native.

**Comment by FatCatTuxedo** [comment]
Its annoying you can't replace but its for a good reason since cfx injects a custom one that supports more fonts
