### ISSUE TITLE
Raiju thrust vector is not synced

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/fivem#3022]
### What happened?

It appears that if a player gets in the `raiju` vehicle and presses G (to toggle the thrust vector state), this change does not gets synced.
![image](https://github.com/user-attachments/assets/8cee5ef9-df36-4a96-a82b-06d948237e9d)
The two screenshots were taken at the same time by the driver and an external player

### Expected result

The thrust vector state gets synced

### Reproduction steps

1. Spawn a `raiju`
2. Get a player to go in the vehicle and toggle the thrust vector state
3. He will see it applied but a second player outside of the vehicle will not see the toggle

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

FiveM 3095, b12031

**Comment by Korioz** [comment]
No sync issue running b3095 with raiju.

Are you sure you're just not misusing `CREATE_VEHICLE_SERVER_SETTER` setting incorrect vehicle type ? 😅

![image](https://github.com/user-attachments/assets/374308b4-7046-4fc6-b68a-6128ddfc2131)

![image](https://github.com/user-attachments/assets/9216aa6a-2638-4029-8052-116970312d18)

**Comment by Mathu-lmn** [comment]
Yup, symptoms of wrong vehicle type in the server setter
