### ISSUE TITLE
Crash Players

### ISSUE THREAD

**Issue by onlyzaxd** [citizenfx/fivem#3035]
### What happened?

Looks like there is a new cheat menu that is crashing people around even on 3095 build

### Expected result

Nothing when they tried to crash players

### Reproduction steps

Unfortunately i can't reproduce it but from the screenshot that i take from that player he is teleporting around the map and crashing everything near him

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM Game Build 3095/Artifact version 12031

### Additional information

[CfxCrashDump_2024_12_23_23_15_10.zip](https://github.com/user-attachments/files/18235533/CfxCrashDump_2024_12_23_23_15_10.zip)

**Comment by PRO4KINGS** [comment]
[CfxCrashDump_2024_12_23_22_40_32.zip](https://github.com/user-attachments/files/18236900/CfxCrashDump_2024_12_23_22_40_32.zip)
[CfxCrashDump_2024_12_23_22_08_47.zip](https://github.com/user-attachments/files/18236901/CfxCrashDump_2024_12_23_22_08_47.zip)

**Comment by andreiciobanica** [comment]
@prikolium-cfx,

[CfxCrashDump_2024_12_24_20_30_56.zip](https://github.com/user-attachments/files/18241830/CfxCrashDump_2024_12_24_20_30_56.zip)

**Comment by prikolium-cfx** [comment]
Should be fixed in f14c44a3cd9d2075db23a59fbd9d3c5617b57369
