### ISSUE TITLE
TriggerLatentServerEvent doesn't work anymore on latest fivem artifacts

### ISSUE THREAD

**Issue by 0x0f234** [citizenfx/fivem#3041]
### What happened?

After the latest FiveM update, the TriggerLatentServerEvent function has ceased to function. This issue is preventing the reliable transfer of large data payloads between client and server, a critical feature for many resources. The server is not receiving any data or triggering the event at all.

### Expected result

The server should receive the event and process the payload as it did in previous builds.

### Reproduction steps

1. Update FiveM to the latest build.
2. Implement or use a script that calls TriggerLatentServerEvent to send a payload from a client to the server.
3. Observe that the event does not trigger or process as expected on the server side.

### Importancy

Unknown

### Area(s)

FiveM, FXServer, ScRT: Lua

### Specific version(s)

FXServer 12160

**Comment by Szpachlan** [comment]
there is an issue with TriggerLatentClientEvent too

**Comment by prikolium-cfx** [comment]
Thanks for your report. Should be fixed in 12164
