### ISSUE TITLE
WARNING: NON-EXISTENT NATIVE 2a488c176d52cca5

### ISSUE THREAD

**Issue by mariusvn** [citizenfx/fivem#31]
When i use Vdist native command, I get this error in my console: 
`WARNING: NON-EXISTENT NATIVE 2a488c176d52cca5`
i found the script who create the error (code/components/citizen-scripting-core/src/ScriptHost.cpp). It's seems like i call a non registered command into fivem

**Comment by blattersturm** [comment]
@mariusvn huh, random people playing with git builds?

**Comment by blattersturm** [comment]
@mariusvn Basically, the master branch isn't meant to be used to play on or directly develop with, random issues such as this may occur.

This issue has been triaged already and should be fixed next push.

**Comment by mariusvn** [comment]
Ok you just need to reinstall FiveM to resolve the bug :)

**Comment by mariusvn** [comment]
i installed fiveM directly via the installer
