### ISSUE TITLE
Huge stuttering 

### ISSUE THREAD

**Issue by matlink** [citizenfx/fivem#33]
While running fivem, I notice huge stuttering spikes that do not happen when running in solo game mode ( even online).
I'm running with a gtx 970, 8Gb RAM and an i5 3350P.
Is there any way for me to optimize fivem? Do you think it's more probably a network connection issue rather than an I/O issue?
Thanks.

**Comment by ejb1123** [comment]
My guess is some loop that does not have a timeout.

**Comment by blattersturm** [comment]
@ejb1123 why the fuck would 'a loop' need to have 'a timeout', and do you even KNOW how game engines work?

**Comment by ejb1123** [comment]
No please inform me.

**Comment by blattersturm** [comment]
No info provided, closed.
