### ISSUE TITLE
Server loaded Handling file crash on load

### ISSUE THREAD

**Issue by RaidedDesign** [citizenfx/fivem#34]
Just to put some context in, I develop a server, I never disconnect before shutting down the server.
Every now and again when I try to rejoin the server the game will crash. Considering the handling file loading via server is new I thought I should mention this. I have also attached the handling file.

[handling.meta](http://www.mediafire.com/file/udmcqvhhmjvjj3b/handling.meta)

> An exception occurred (c0000005 at 0x7ffa91c9dd8c) during loading of resource:/vrp/lib/handling.meta in data file mounter class CVehicleHandlingFileMounter. The game will be terminated.

**Comment by blattersturm** [comment]
No minidump or report ID provided.
