### ISSUE TITLE
Server querying conflicts with the 'direct connect' input box

### ISSUE THREAD

**Issue by neos7** [citizenfx/fivem#4]
Sometimes if you try to direct connect to localhost or 127.0.0.1 it shows a random server as result.

**Comment by ExoKalork** [comment]
Also on local network with 192.168.0.X

**Comment by WeAreFailure** [comment]
Also on whatever the IP is, you have to double check before you join the server.

**Comment by ejb1123** [comment]
I think this is due to the angular app listening for the server info on both the direct connect and the main server list. TLDR the direct connect menu is receiving info that should only be sent to the main server menu.
