### ISSUE TITLE
Missing mscorlib.dll in latest FXServer build for Windows

### ISSUE THREAD

**Issue by ImagicTheCat** [citizenfx/fivem#44]
Unless there is a third-party to install, the FXServer windows build is missing `mscorlib.dll`.

**Comment by blattersturm** [comment]
@ImagicTheCat missing how, what happens if you run it, and what makes you think it's missing❓

**Comment by ImagicTheCat** [comment]
![fxerror](https://user-images.githubusercontent.com/7304870/28032903-76075212-65ac-11e7-844f-d540cc95e546.png)

**Comment by blattersturm** [comment]
@ImagicTheCat mscorlib.dll exists just fine in the 823-79d2ba7484fe83669427556dda934a70af0cb792 artifacts, sure this isn't user error or the path being at fault?

**Comment by ImagicTheCat** [comment]
My bad, too much used to decreasing chronological lists, so I was always taking the oldest version.
