### ISSUE TITLE
game freezes when i click on it

### ISSUE THREAD

**Issue by Swarmington5** [citizenfx/fivem#45]
i have windows 7 and when i start the game up it gives me windows 10 error then it gives me this.

![fivemerror](https://user-images.githubusercontent.com/30139376/28152840-23a05e48-6768-11e7-9ca4-01699b711d18.PNG)

i have reinstalled the game 4 times and it still gives me that.
it has worked before in the past with this error
i have installed the lspdfr mod in my gtaV folder and a mod menu installed also

**Comment by blattersturm** [comment]
@Swarmington5 How is this an issue? This is 100% user error, a) you should use FiveM on a clean game installation, b) you don't have updated enough Win7, if you don't know how to use an old OS, you shouldn't try to use it, c) this isn't a support tracker, this isn't a FiveM bug, so it shouldn't go here. Try the forums.

**Comment by Swarmington5** [comment]
@blattersturm so i should get rid of the mod menu and the lspdfr mod and i should be fine right?

**Comment by ifarbod** [comment]
@Swarmington5 No, update your OS instead.

**Comment by Swarmington5** [comment]
@blattersturm do you know where i can still update for free?

**Comment by blattersturm** [comment]
Not a bug.

**Comment by Swarmington5** [comment]
@blattersturm so i need to update to windows 10 creators edition?

**Comment by Kngrektor** [comment]
Just open windows update and update. Also THIS SHOULD NOT BE ON GITHUB

**Comment by Swarmington5** [comment]
@Kngrektor i can't update for some reason lmao
