### ISSUE TITLE
GetGameplayCamRot not working anymore

### ISSUE THREAD

**Issue by Identity-labs** [citizenfx/fivem#47]
GetGameplayCamRot(0) 
return always 0 before it return Vertor3

It's the same with 
Citizen.InvokeNative(0x837765A25378F0BB, Citizen.PointerValueIntInitialized(0))

**Comment by blattersturm** [comment]
Works fine here:

```
RegisterCommand('getrot', function()
  print(GetGameplayCamRot(0))
end)
```

![example](https://w.wew.wtf/cyfige.png)

Also, InvokeNative in that example won't _ever_ return a vector as you're not even passing ResultAsVector.

Got a repro case?

**Comment by Identity-labs** [comment]
In client not in server

I have put a fix to prevent error 

  local camRot = GetGameplayCamRot(0)
  if type(camRot) == 'number' then
    camRot = {x = 0, y = 0, z = 0}
  end

I use like that

  local camPos = GetGameplayCamCoords()
  local camRot = GetGameplayCamRot(0)
  local camFov = GetGameplayCamFov()
      
  local camOffset = 0.65
  local zoomOffset = 0.6
  local pos = GetOffsetFromEntityInWorldCoords(GetPlayerPed(-1), 0.0, zoomOffset, camOffset)
  local spawnCam = CreateCam("DEFAULT_SCRIPTED_CAMERA", 1)
  
  SetCamActive(spawnCam, true)
  SetCamCoord(spawnCam,  pos.x, pos.y, pos.z+2000)
  SetCamRot(spawnCam, -70.0, camRot.y, camRot.z, true) -- error here camRot is not Vector3
  SetCamFov(spawnCam, camFov)
  RenderScriptCams(1, 0, spawnCam,  true,  true)
  ...

**Comment by blattersturm** [comment]
>In client not in server

This code was tested on the client.

>I have put a fix to prevent error

There is _no_ way GetGameplayCamRot can return a number, unless you somehow redefined it with your (bad) InvokeNative call.

If you can't provide a minimal repro case, we'll have to close this issue as well.

**Comment by Kngrektor** [comment]
Are you using the latest [resource manifest version](https://wiki.fivem.net/wiki/Resource_manifest_versions)?

**Comment by Identity-labs** [comment]
No manifest

**Comment by blattersturm** [comment]
So how does your script get loaded at all without a manifest?

**Comment by Kngrektor** [comment]
Manifest = __resource.lua but I think I know what you mean. Try use the latest version (you may need some minor changes to scripts)

**Comment by Identity-labs** [comment]
__resource.lua
```
client_script {
	"client.lua"
}
```

**Comment by Identity-labs** [comment]
Ok
Now I have the Vector3 with
resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

How to know what is the difference between all manifest version ?

Why yesterday GetGameplayCamRot work fine and not today ?
No change have made in the script

**Comment by Kngrektor** [comment]
If changing manifest version fixed it the old versions are probably broke. And no, the old versions hasn't been changed as that's the only reason manifest versions exist.

Also to figure out differences you can use [the wiki page](https://wiki.fivem.net/wiki/Resource_manifest_versions) and check the mentioned files
