### ISSUE TITLE
Since the client update today....

### ISSUE THREAD

**Issue by CryptoParts** [citizenfx/fivem#48]
Since the client update today I can no longer join my server... I join but as soon as i do i cant move and then it crashes. Here are the errors i get, Everything was working fine before.
http://prntscr.com/fvb28t
https://gyazo.com/2c55d1bf6c27dc591a6e1b2dbe03d615
https://gyazo.com/557dc3640960f0055046cda5850936c8

**Comment by AdrineX** [comment]
I got the same error, first i had problems with custom cars and after i disabled custom cars i got the missisippi error.

**Comment by CryptoParts** [comment]
Yup seems like this is killing a lot of servers out there

**Comment by SuperCoolNinja** [comment]
Hy, we have some problem whit new update I have these Error
http://www.zupimages.net/viewer.php?id=17/28/f1rk.png

**Comment by CryptoParts** [comment]
Welcome to the club brother...

**Comment by SuperCoolNinja** [comment]
Yeah ...
