### ISSUE TITLE
Allow direct servers in the server list

### ISSUE THREAD

**Issue by iTsFILIPOficial** [citizenfx/fivem#5]
- Allow direct connect server to be added as favourites

It would be nice to be able to save some direct connection server, this way you can save these servers.

**Comment by ejb1123** [comment]
It wou;d be nice if they were also added to the history

**Comment by blattersturm** [comment]
Currently, favorites/history are implemented as filter on top of the public server backend - this'll be split in the future to support LAN servers as well.

**Comment by ejb1123** [comment]
Discovering LAN servers may be possible by using the local IP subnet [broadcast address](https://en.wikipedia.org/wiki/Broadcast_address#IP_networking) or with a [multicast address](https://en.wikipedia.org/wiki/Multicast_address#IPv4)
