### ISSUE TITLE
Error 127 Procedure entry point Nui-core.dll

### ISSUE THREAD

**Issue by Kujo67** [citizenfx/fivem#7]
GTA V version? Latest as of (5/6/2017)
Up to date? Yes
Legit or Pirate copy? Legit
Steam/CD/Social Club? Steam
Windows version? Windows 10 (10.0.15063)
Did you try to disable/uninstall your Anti-virus? Yes
Did you try to delete caches.xml and try again? Yes
Error screenshot: http://i.imgur.com/DOGfkIK.png1 , http://i.imgur.com/vJvJIq2.png
GTA V folder screenshot: http://i.imgur.com/Ep0anxb.png1
GTA V/update/x64/dlcpacks screenshot: http://i.imgur.com/eYOTr42.png1
Filepath to FiveM folder: C:\Users\Alexl\Desktop\GTAV-FiveM
FiveM Application Data folder screenshot: http://i.imgur.com/nNbUYHg.png2
System specifications: AMD FX 8320, 32GB DDR3 1800, GTX 670 4GB, GTX 950 2GB(Non-SLI configuration.)
CitizenFX.log file: 
"[ 0] Initialized system mapping!
[ 17813] GlobalError: Could not load component nui-core.dll - Windows error code 127."
.dmp files
https://ufile.io/86uwe1 (494de74b-db0d-4a29-b768-162dfa17341e.dmp)

Also add what you already tried so far.

I've tried deleting the nui-core.dll and allow a new one to be generated, I've completely removed FiveM and installed again. Uninstall, reboot, install of GTAV. Disabled AV and firewalls. reinstalled vcredist 2005 x86 and x64. Closed all non-essential programs in the background (Teamviewer, Twich chat(Curse). I even tried someone elses nui-core.dll same error.

Edit: No there is not a steam_api64.dll in my system32 folder.

**Comment by ejb1123** [comment]
this is related to #6

**Comment by ejb1123** [comment]
@Kujo67 is this still an issue?

**Comment by Kujo67** [comment]
No, The issue was the concrt140.dll and libGLESv2.dll files if i remember correctly. Deleting those files fixed it. (some reason they were added to the folder after a clean install(Including deleting the GTAV folder before reinstall)

**Comment by ejb1123** [comment]
were these files located in the GTA V directory or FiveM directory?

**Comment by Kujo67** [comment]
GTAV Directory

**Comment by ejb1123** [comment]
strange because those file can be found in the `FiveM.app\bin` directory.
This issue can reproduced by deleting the `FiveM.app\bin` directory.

**Comment by Kujo67** [comment]
Perhaps it was having an issue and tried to inject/run both.

**Comment by Kujo67** [comment]
The concrt140.dll is not in my appdata/bin folder for FiveM. Maybe that was the issue.

**Comment by DuiZZZy** [comment]
Ты решил проблему ? просто такая же хрень 
![image](https://user-images.githubusercontent.com/29786092/27713086-99ce95c0-5d32-11e7-8d5c-05d46bff3460.png)

**Comment by DuiZZZy** [comment]
pls help 
![image](https://user-images.githubusercontent.com/29786092/27713205-26a3400e-5d33-11e7-914a-a0ce7e404992.png)
