### ISSUE TITLE
Set up a series of issue forms

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#789]
For transparency, we may want to have public issue reporting for code tasks. I've gone ahead and enabled issues, but without issue forms for each type of issue this may become a bit of a mess.

GitHub supports this feature [as of recently](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), we should investigate what this could look like and make some.

**Comment by gottfriedleibniz** [comment]
I believe this has been solved/superseded by a variety of things.
