### ISSUE TITLE
Stickied servers don't respect filter

### ISSUE THREAD

**Issue by AvarianKnight** [citizenfx/fivem#812]
If you search for a specific term (I used 'Los Santos'), it will ignore any region/tag and always show the stickied server.

**Comment by blattersturm** [comment]
While confusing, this was originally intended. However, since the dedicated pin list exists now and also shows all servers, this _does_ lead to confusion.

When fixing this, one should take note that the pin list does _not_ end up filtering by region - only the main list.

**Comment by blattersturm** [comment]
Seemingly a very trivial fix, since the pin bar only really vanishes when there's a search, and this bypass logic only runs when filtered out.
