### ISSUE TITLE
Monitor mode title says 'FXServer/unknown' as no game is applied

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#821]
![image](https://user-images.githubusercontent.com/24576130/129463631-d0554b91-0065-4a9e-98ac-1f8b496abaaa.png)

Should say 'monitor' or so.

**Comment by donkras** [comment]
![image](https://user-images.githubusercontent.com/62117897/166104184-c5e54387-2da5-424f-a84b-513a1826b1ec.png)
seems resolved by now, no?

**Comment by blattersturm** [comment]
Nope, still had this happen today, even. Is this before the server starts?

**Comment by donkras** [comment]
> Nope, still had this happen today, even. Is this before the server starts?
sorry i didn't see your response until now lol
tried to run FXServer.exe alone ( thats what you do to run 'monitor mode' correct me if im being wrong ) then run the server ( FXServer.exe + exec server.cfg blah blah ) and then do the same, but in the different order, can't replicate it

**Comment by gottfriedleibniz** [comment]
Did https://github.com/citizenfx/fivem/pull/2235 solve this issue?

**Comment by blattersturm** [comment]
Good question - hard to tell as txAdmin overrides the window title now. Might not be relevant anymore as such.

**Comment by gottfriedleibniz** [comment]
https://github.com/citizenfx/fivem/pull/2235 solved my own reproduction of this issue. Will close as completed.
