### ISSUE TITLE
Some serious sudden FPS drop issues & game lags/stuck issue on Latest rec. build.

### ISSUE THREAD

**Issue by abhishekdeshkar** [citizenfx/fivem#823]
Hello,

We were on the latest recommended build (4304) but we were facing sudden FPS and game lag/stuck issue on this build.  Also packet loss goes very high suddenly with Mumble.

Now we rolled back to 3922 and everything is working fine and no FPS drop atm. 

What could be the possible reason for this ?

**Comment by blattersturm** [comment]
Hi,

Our GitHub issues are only for _actionable_ tasks, such as work items, bugs that have clear reproduction steps and crashes/traces with actual information.

Your report provided neither, yet asked for 'a possible reason' i.e. expecting us to have a crystal ball.

Try asking in the technical support section on the forums: https://forum.cfx.re/c/technical-support/27

Thanks!
