### ISSUE TITLE
Game crashes when taking a picture with Snapmatic to fulfill a mission objective in story mode

### ISSUE THREAD

**Issue by Autolyzed-Yeast-Extract** [citizenfx/fivem#832]
This makes it impossible to progress at certain points of the game, specifically the Merryweather Heist scouting mission as the end of the mission requires you to take several pictures of the docked ship

**Comment by blattersturm** [comment]
Do you happen to have the stack trace or dump file for this crash to make it simpler to investigate?

**Comment by Autolyzed-Yeast-Extract** [comment]
> 
> 
> Do you happen to have the stack trace or dump file for this crash to make it simpler to investigate?

Where would these be located?

**Comment by blattersturm** [comment]
Usually, on the window you get on crashing: there's a 'save information' button.

**Comment by Autolyzed-Yeast-Extract** [comment]
> 
> 
> Usually, on the window you get on crashing: there's a 'save information' button.

Okay, well I was able to get through the mission by taking a picture of something else and then quickly moving the camera to the right parts of the ship, which fooled the game into thinking I took the right picture. If I can I will try to replay the mission to try to get the information when I have time

**Comment by blattersturm** [comment]
Was resolved in https://github.com/citizenfx/fivem/commit/a1f66aeed6a27a1225def9a8ec2cfc6f82764c36.
