### ISSUE TITLE
Filtering servers by locale is not working properly

### ISSUE THREAD

**Issue by Trsak** [citizenfx/fivem#863]
Hello,
so using client version 4382, filtering servers by locale does not work for me.

By default, I use czech language in the client and connect only to Czech servers. But on main page, i have server from USA:
![image](https://user-images.githubusercontent.com/5057950/129973786-ca85f143-05a0-4423-a31a-d54157db9efe.png)

When I try to filter servers only to Czech, you can see it still displays many USA servers:
![image](https://user-images.githubusercontent.com/5057950/129973896-601eb65a-ed42-4d1a-b45d-437ae989bc85.png)

**Comment by blattersturm** [comment]
Main page is determined by OS language first and foremost as the in-game language list may not contain all languages. I'm not sure what logic could be better here.

The list itself is odd though, I suspect the cheap fix from #812 is insufficient and this really _does_ need a dedicated left/right list filter bit.

**Comment by Trsak** [comment]
My OS language is also set to Czech. Thanks for quick response on that!

**Comment by blattersturm** [comment]
That's.. odd. Is it maybe using the application languages in the region options in Windows instead?

**Comment by Trsak** [comment]
So I have it like this:
![image](https://user-images.githubusercontent.com/5057950/129975403-29657588-58ed-4dda-97c5-354ad7f37487.png)

I have even English language pack installed, since I use ENG keyboard sometimes. But Czech (Čeština) is my default.

**Comment by blattersturm** [comment]
Aha, so it's _also_ possibly reading languages in the wrong order.

**Comment by blattersturm** [comment]
It appears `cs` is a special language as it's not tied to a region _at all_ when set as a locale in Windows, and it performs a request to find servers for `cs` and not `cs-CZ`.

I wonder if the same goes for any other language in Windows that doesn't have a dedicated country. 😕

**Comment by blattersturm** [comment]
... yeah, that's correct:

```
0: "ja"
1: "cs"
2: "en-US"
3: "qps-ploc"
```

**Comment by blattersturm** [comment]
Backend fix is live:

![image](https://user-images.githubusercontent.com/24576130/130032685-210c7cee-86ba-4599-9298-28478e63514e.png)
