### ISSUE TITLE
Pressing Shift+Home in add panel search bar does a nothing

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#870]
I suspect Home/End on the search list eats the event from the input box too, as Shift-Left etc. work fine.

![image](https://user-images.githubusercontent.com/24576130/130127617-fe33c280-5c0e-4812-8597-f2d7e729d767.png)

![image](https://user-images.githubusercontent.com/24576130/130127638-1a576874-19c1-4973-9d0e-16e1c56f952a.png)

**Comment by nihonium-cfx** [comment]
Yes, Home/End is for jumping to the start or to the end of the list :p
