### ISSUE TITLE
NetworkGetFirstEntityOwner causes server crash

### ISSUE THREAD

**Issue by MatinDark** [citizenfx/fivem#884]
Description: NetworkGetFirstEntityOwner causes server crash

Repro:
Assuming we have a command to create a vehicle via CREATE_AUTMOBILE native
```
RegisterCommand('vehtest2', function(source, args, RawCommand)
	local ped = GetPlayerPed(source)
	Citizen.InvokeNative(GetHashKey('CREATE_AUTOMOBILE'), GetHashKey(args[1]), GetEntityCoords(ped), GetEntityHeading(ped))
end)
```
Afterward, if we try to fetch the first entity owner of the created vehicle, the server will crash and it only happens when you create a vehicle by CREATE_AUTMOBILE (CreateVehicle RPC native is totally fine)
```
RegisterCommand('getowner', function(source, args, RawCommand)
	local ped = GetPlayerPed(source)
	local vehicle = GetVehiclePedIsIn(ped, vehicle)
	
	if not DoesEntityExist(vehicle) then return print("Vehicle does not exist") end
	print(vehicle)
	print(NetworkGetFirstEntityOwner(vehicle))
end)
```

Expected behavior:  NetworkGetFirstEntityOwner should retrieve the first owner or at least -1 as server

Server artifact: 4304
Server OS: Linux ubuntu

**Comment by aiden-z-source** [comment]
You are quite a few server artifacts behind the most recent, 4393. Possibly try the same on that artifacts and see if you can reproduce this?

**Comment by gottfriedleibniz** [comment]
https://github.com/citizenfx/fivem/blob/master/code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp#L145 is returning nullptr and not being sanitized.

**Comment by blattersturm** [comment]
> This also leads into the question of what should firstOwner be for sever-generated entities (and having that documented in the markdown, I suppose).

This rather makes me wonder why people want to know the 'first owner' of an entity, as it is a field that normally only exists in the context of lifetime.

**Comment by AvarianKnight** [comment]
> This rather makes me wonder why people want to know the 'first owner' of an entity, as it is a field that normally only exists in the context of lifetime.

I would assume probably to find people who spawned vehicles/objects instead of just using entity lockdown.

**Comment by blattersturm** [comment]
OK, so #669 was another backdoor PR by people who didn't bother to state their actual use case, as with #550 before.

Time for a blanket ban on community PRs without stating their use case and a risk analysis?

**Comment by gottfriedleibniz** [comment]
Time for `.github/PULL_REQUEST_TEMPLATE.md` ?
