### ISSUE TITLE
After spam clicking, the gizmo turns unresponsive

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#928]
https://user-images.githubusercontent.com/24576130/131152959-9114b96a-67c5-406e-8af5-82be60a1a80d.mp4

**Comment by nihonium-cfx** [comment]
Everything in Im3D state (cpp side) looks perfectly fine, as in mouse pos, current mode, global/local switch, select key. So it looks like something internally in Im3D is locking up.

Easier steps to repro though:
1. Select somthing
2. Click (m/o moving) on plane (doesn't matter if xz or xy or yz) gizmo control
