### ISSUE TITLE
CreateRuntimeTexture crashes game (with incorrect data)

### ISSUE THREAD

**Issue by Vinipux322** [citizenfx/fivem#953]
Incorrectly passed data to `CreateRuntimeTexture` native crashes the game, I think it would be nice to add checks so that it does not crash

repro code:
`
CreateRuntimeTexture(CreateRuntimeTxd("test"), "img", 1.0, 1.0)
`

P.s. I used b2189 build and Canary ver. I don't know if it matters ¯\_(ツ)_/¯

**Comment by blattersturm** [comment]
How would one know anything is 'incorrect data'?

**Comment by Disquse** [comment]
I believe casted floats will be very large as integers, maybe we can add reasonable resolution limit? Same for negative values (i.e. not allow at all).
