### ISSUE TITLE
IsTaskMoveNetworkReadyForTransition doesnt work some times

### ISSUE THREAD

**Issue by forgot9** [citizenfx/fivem#954]
IsTaskMoveNetworkReadyForTransition doesnt work some times. Can you tell me what is causing the problem?

**Comment by blattersturm** [comment]
Hi,

Our GitHub issues are only for actionable tasks, such as work items, bugs that have clear reproduction steps and crashes/traces with actual information.

Your report provided neither, yet asked to 'be told what is causing the problem' i.e. expecting us to have a crystal ball.

Try asking in the technical support section on the forums: https://forum.cfx.re/c/technical-support/27

Thanks!
