### ISSUE TITLE
Ownerschip of vehicles seems to randomly switch when driving with multiple players in a vehicle

### ISSUE THREAD

**Issue by DonTosti** [citizenfx/fivem#969]
When driving in a vehicle with multiple persons, randomly the vehicle goes to another player's control. When opening the netobjectviewer the vehicle under POPTYPE_MISSION changes to another player who is not the driver and the current driver of the vehicle cannot, brake steer or give gas anymore for a couple of seconds until the vehicle goes back to him as 'ownership'.

**Comment by blattersturm** [comment]
I guess this was another issue that was self-induced?

**Comment by DonTosti** [comment]
Yes, I figured out that the passagers where doing the 'Networkrequestcontrolofentity()' in a script, so that broke it. Sorry for the useless issue.
