### ISSUE TITLE
Multiple people can join a server with the same steam account

### ISSUE THREAD

**Issue by MatinDark** [citizenfx/fivem#978]
There is a bypass that you can use to join a server multiple times with the same steam account for example let's say we have 
Matthew, Andrew, and Davis they they logged in to the same steam account

now there are two ways to bypass the system

they just count to three and click on the server at the same time and they are all in without any issue
OR
Considering the steam account name is test1, Matthew join the server with that name then Andrew goes into steam profile setting and changes the account name, it doesn't sync with others but he will be able to join the server with that new name, meanwhile Matthew is still connected to that server!

**Comment by blattersturm** [comment]
Not a bug.

**Comment by blattersturm** [comment]
In fact, how is this 'a bypass' when there's not even any logic checking for dupes to bypass?!

**Comment by MatinDark** [comment]
I checked at my end and I did fix this problem for my own server, but if it's not really a problem at your end why FiveM automatically rejects connection when the account is already connected to that server,  what I described above is what can bypass that check so I don't care if you don't want to fix it but it almost works at 80% of servers and people can duplicate too many stuff

**Comment by blattersturm** [comment]
> why FiveM automatically rejects connection when the account is already connected to that server

It doesn't, though.

**Comment by blattersturm** [comment]
What is the message you're even getting when your connection is 'rejected' for already being connected?
