### ISSUE TITLE
RedM Discord Identity Data support

### ISSUE THREAD

**Issue by looterz** [citizenfx/fivem#994]
RedM is missing support for discord identity data [here](https://github.com/citizenfx/fivem/blob/bd035f29fbd0f1b6c70b0f2ff02c2cc06d57c6db/code/components/discord/src/DiscordIdentityData.cpp#L3). It looks like this may require some support on the backend which is why it's currently disabled, with rich presence now working could this be looked into?

**Comment by Ktos93** [comment]
i can look on this

**Comment by aiden-z-source** [comment]
This should now be done as of https://github.com/citizenfx/fivem/commit/0f19a6d15cda2fc96a20f72355ac7f0135b34df8
